### ISSUE TITLE
wav_head.h: No such file or directory

### ISSUE THREAD

**Issue by Laxiyan** [espressif/esp-adf#1]
编译例程的时候出现这个错误:
/home/esp8266/Desktop/esp/esp-adf/components/audio_stream/./fatfs_stream.c:39:22: fatal error: wav_head.h: No such file or directory
compilation terminated.
make[1]: *** [fatfs_stream.o] Error 1
make: *** [component-audio_stream-build] Error 2

**Comment by tuanpmt** [comment]
Hi @Laxiyan 

You need to fetch all submodules by run this command `git submodule update --init`

**Comment by Laxiyan** [comment]
According to your prompts, the compiler passed.

Thank you！
