### ISSUE TITLE
ESP32-LyraT 4.3 reboots when volume set to 100% (AUD-601)

### ISSUE THREAD

**Issue by deltathoughts** [espressif/esp-adf#100]
Can be reproduced  with play_mp3_control with setting volume to 100%.
Input source is DC 5V with 4A So it look some other problem with ESP32-LyraT 4.3 board.

Pointers?

**Comment by jason-mao** [comment]
@deltathoughts How about this issue?

**Comment by afandian** [comment]
This happens with me when running on battery power at 70% audio volume using the CLI example.
