### ISSUE TITLE
Request a feature detecting DTMF over VoIP (AUD-4657)

### ISSUE THREAD

**Issue by EdwardRyu** [espressif/esp-adf#1019]
## Environment
Audio development kit: ESP32-LyraT
Audio kit version : v4.3
Module or chip used: ESP32-WROVER-E
IDF version: v4.4.4
ADF version: v2.5

## Problem Description
No DTMF detection during VoIP call.

## Requirement
Some of application and use cases require DTMF detection during VoIP call.
Please add the function (callback) during VoIP call.
For example, RTP_EVENT has a field of DTMF event as attached snap shot.
Please expose the callback to get the notification about this event occurence.

![image](https://github.com/espressif/esp-adf/assets/129234308/9345c968-20d6-421a-8c2c-21395ae73cb6)

Thank you,
Edward

**Comment by ahhfzhang** [comment]
Hi Edward

We have added this feature and released within a week.

Thanks.

**Comment by EdwardRyu** [comment]
Hi Michael,

Thanks for your feedback.
I am afraid that I don't see this feature even in the master branch of esp_adf_lib repo.

I am not asking about sending dtmf, but asking about detecting dtmf sent by the peer.

Thanks,
Edward
