### ISSUE TITLE
nvs error (AUD-4779)

### ISSUE THREAD

**Issue by be-inexplicable** [espressif/esp-adf#1045]
i faced an error while building project "unknown type name 'nvs_sec_scheme_t'; did you mean 'nvs_sec_scheme_id_t'?" am facing this error for every project that am trying to build ,how can i solve this

**Comment by jason-mao** [comment]
@be-inexplicable Would you please provide more information for me, such as your IDF version, ADF version, your reproduced code, etc ?

**Comment by be-inexplicable** [comment]
> @be-inexplicable Would you please provide more information for me, such as your IDF version, ADF version, your reproduced code, etc ?

idf4.2  board - lyrat v4.3
thanks for help

**Comment by Miaki-Yang** [comment]
how did u solve the problem？plz

**Comment by be-inexplicable** [comment]
> how did u solve the problem？plz

i just installed lower version idf  and updated the library somehow it got correct
