### ISSUE TITLE
Support of Time Sensitive Networking (AUD-597)

### ISSUE THREAD

**Issue by saeugetier** [espressif/esp-adf#105]
Support of [Time-Sensitive Networking](https://en.wikipedia.org/wiki/Time-Sensitive_Networking) would be useful. It supports realtime [Audio Video Bridging](https://en.wikipedia.org/wiki/Audio_Video_Bridging). I'm not sure if the processing power of the ESP32 is sufficient.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
