### ISSUE TITLE
The green led does not blink anymore (AUD-4796)

### ISSUE THREAD

**Issue by teddykishi** [espressif/esp-adf#1050]
Hi I just bought the ESP32-LyraT V4.3.
I'm using a Mac, I've installed ADF correctly.
When I launch the command `idf.py -p /dev/cu.usbserial-1410 -b 9600 flash monitor` everything works fine until it tries to write on the board. The board is not detected and it fails.
I tried many manipulations but it got worst because I managed to stop the green led from blinking.
I think I've holded the Boot button then RST button. 
I would like to know how to go back to normal and make my Mac detect the board in order to write into it ? 
I've searched and find nothing about that.
The documentation says "the green led should blink" but it does not say what to do if not.

here is the message error : 
```
esptool.py esp32 -p /dev/cu.usbserial-1410 -b 9600 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x1000 bootloader/bootloader.bin 0x10000 main.bin 0x8000 partition_table/partition-table.bin
esptool.py v3.3.3-dev
Serial port /dev/cu.usbserial-1410
Connecting......................................

A fatal error occurred: Failed to connect to ESP32: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
CMake Error at run_serial_tool.cmake:56 (message):
  /Users/teddykishi/.espressif/python_env/idf4.4_py3.11_env/bin/python
  /Users/teddykishi/esp/esp-adf/esp-idf/components/esptool_py/esptool/esptool.py
  --chip esp32 failed
```
Please help me.
Thanks

**Comment by jason-mao** [comment]
Hi @teddykishi, I am not sure about your board status, may the factory firmware is not working. However, you can perform some tests to check if the board is okay, such as build [IDF hello world](https://github.com/espressif/esp-idf/tree/master/examples/get-started/hello_world) and [ADF hello world](https://github.com/espressif/esp-adf/tree/master/examples/get-started/play_mp3_control).

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
