### ISSUE TITLE
Example player bt_source cannot build a2dp iram0_0_seg' overflowed by 1356 bytes (AUD-4850)

### ISSUE THREAD

**Issue by 0x0fe** [espressif/esp-adf#1065]
Target : ESP32D0WDR2 (infernal 2MB PSRAM) 

IDF version : 

 - framework-espidf @ 3.50002.230601 (5.0.2)
 - tool-cmake @ 3.16.4
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - tool-idf @ 1.0.1
 - tool-mconf @ 1.4060000.20190628 (406.0.0)
 - tool-mkfatfs @ 2.0.1
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 2.230.0 (2.30)
 - tool-ninja @ 1.9.0
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
 - toolchain-xtensa-esp32 @ 11.2.0+2022r1

ADF version : latest (2.6)

The example player bt_source cannot build, due to IRAM being overflowed, even though all SPIRAM options are enabled in menuconfig. 
Also i want to point out that most of the menuconfig options shown in the demo project do not exist anymore in menuconfig, 
https://github.com/espressif/esp-adf/blob/49f80aafefc31642ea98db78bf024e18688b8de9/examples/player/pipeline_bt_source/sdkconfig.defaults#L12C1-L14C40
so it would be very useful to update the example project menuconfig files file to match IDF 5, at least. 

The only option i could find which finally allowed me to build and flash is [CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-freertos-place-functions-into-flash)

But i suspect i am very close to full IRAM occupancy, despite the external PSRAM has a lot of free space.

![image](https://github.com/espressif/esp-adf/assets/89607149/d7cfe4a9-1c9c-4b08-8e45-e7132baa6663)

 Also i very much doubt that only setting CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH can free up 90% of the IRAM magically. Clearly the IDF RAM usage report is very wrong.

As a side note, i wonder what is the proper way to change volume in a2dp-source mode, of course we could change the level in the bit stream but that would be pretty bad, due to loss of resolution, and also a2dp has mechanism to propoerly modify the volume on the attached a2dp-sink device. I tried esp_err_t periph_bt_volume_up(esp_periph_handle_t periph) and esp_err_t periph_bt_volume_down(esp_periph_handle_t periph) from a2dp_stream but it did not change the volume at all, i also noticed bt_avrc_volume_set_by_local but its static and cannot be accessed from outside. So i am not sure what we are supposed to use.

**Comment by jason-mao** [comment]
@0x0fe Same as https://github.com/espressif/esp-adf/issues/1070, BTW you should also select the -Os to save IRAM.
