### ISSUE TITLE
ESP BOX LITE does not work with ESP ADF (AUD-4903)

### ISSUE THREAD

**Issue by patrickkeenan** [espressif/esp-adf#1078]
## Environment

- Audio development kit:      [ESP32-S3-BOX-LITE]

- Audio kit version (for ESP32-LyraT/ESP32-LyraT-Mini/ESP32-S3-Korvo-2): [Master branch of ADF]

- [Required] Module or chip used:  [ESP32-S3-BOX-LITE]

- [Required] IDF version (run ``git describe --tags`` in $IDF_PATH folder to find it):
v4.4.5-402-ge9d442d2b7

- [Required] ADF version (run ``git describe --tags`` in $ADF_PATH folder to find it):
v2.6-14-g5cfa0ee

- Build system:  idf.py

- [Required] Running log: 

- Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch5) 8.4.0

- Operating system:     Mac OS 13.5.2

- Using an IDE?: VSCode
- Power supply:        USBC

## Problem Description

Building an example does not work. I have selected the BoxLite as the board in the menuconfig but I get a build error.

### Expected Behavior

Build successfully

### Steps to Reproduce

1. Download ADF
2. Try to compile example for S3 Box Lite

// If possible, attach a picture of your setup/wiring here.

## Debug Logs

`/Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board_pins_config.c:55:33: error: 'GPIO_NUM_47' undeclared (first use in this function); did you mean 'GPIO_NUM_37'?
         i2s_config->ws_io_num = GPIO_NUM_47;
                                 ^~~~~~~~~~~
                                 GPIO_NUM_37
/Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board_pins_config.c:55:33: note: each undeclared identifier is reported only once for each function it appears in
In file included from /Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board.h:29,
                 from /Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board_pins_config.c:28:
/Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board_pins_config.c: In function 'get_pa_enable_gpio':
/Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board_def.h:75:37: error: 'GPIO_NUM_46' undeclared (first use in this function); did you mean 'GPIO_NUM_36'?
 #define PA_ENABLE_GPIO              GPIO_NUM_46
                                     ^~~~~~~~~~~
/Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board_pins_config.c:117:12: note: in expansion of macro 'PA_ENABLE_GPIO'
     return PA_ENABLE_GPIO;
            ^~~~~~~~~~~~~~
/Users/.../esp/esp-adf/components/audio_board/esp32_s3_box_lite/board_pins_config.c:118:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: some warnings being treated as errors`

https://gist.github.com/patrickkeenan/b4795de6663bc2781c214f2eebcf9b25

**Comment by shootao** [comment]
@patrickkeenan 
Based on the log information and toolchain you provided, it seems that the chip model was not selected correctly
Please configure the model of the chip ( `idf.py set-target esp32s3`)  before performing other operations

**Comment by patrickkeenan** [comment]
Thanks @shootao, however that still causes an error. Looks like its expecting >=5.1.0, but I need to use 4.4 to be able to use ADF with this:

`CMake Error at /Users/.../esp/esp-idf/tools/cmake/build.cmake:463 (message):
  ERROR: Because project depends on idf (>=5.1.0) which doesn't match any
  versions, version solving failed.

Call Stack (most recent call first):
  /Users/.../esp/esp-idf/tools/cmake/project.cmake:476 (idf_build_process)
  CMakeLists.txt:16 (project)
`

**Comment by shootao** [comment]
Hi @patrickkeenan 
There is no package manager with restrictions on esp-idf used in ESP-ADF. What project did you compile under?

**Comment by shootao** [comment]
Now `ESP-ADF` supports `ESP-IDF V5.1`, so suggest you upgrade `ESP-IDF` to `V5.1`
