### ISSUE TITLE
pipeline_bt_sink audio example audio quality  (AUD-595)

### ISSUE THREAD

**Issue by MrityunjaiKumar** [espressif/esp-adf#108]
Target platform  -  lyraT 4.3  

Facing a problem where the audio quality is degraded compared to original audio. Here are some screenshots of logs.

![image](https://user-images.githubusercontent.com/6240777/51858785-8b71d500-235b-11e9-92ff-dde9a5049be0.png)

![image](https://user-images.githubusercontent.com/6240777/51858816-9cbae180-235b-11e9-8daa-44185bd52ecc.png)

![image](https://user-images.githubusercontent.com/6240777/51858917-eacfe500-235b-11e9-98af-e0a14a8ce7cf.png)

Any clue?

**Comment by mgsscorr1** [comment]
I am having the same issue with my program. After a recent update of the ADF, the resampling feature was removed and my audio Quality has diminished.

**Comment by theronic** [comment]
The Bluetooth sink audio quality on the ESP32-LYRATD-MSC v2.2 is also bad despite resampling from 44100Hz to 48000Hz in my pipeline (ZL38063 doesn't support 44.1kHz). If I set the volume to 100%, it sounds terrible. Suspect ADC offset issue. At 70% volume Bluetooth sounds soft and tinny at best.

Any advice, @jason-mao? I saw something about having to forcefully flash the ZL38063 firmware on v2.1, but don't know if that's relevant, or how.

**Comment by steenou** [comment]
What is the bad audio quality like? Are you hearing glitching due to zeros in the output like in this issue I posted in the idf repo? https://github.com/espressif/esp-idf/issues/3775
Does it occur when you first start a stream?

**Comment by theronic** [comment]
It's been a while, so I don't recall exactly, but I remember it wasn't glitchy, just low fidelity. It sounded like an undersampled recording - maybe a noisy DAC or quantization error.

Due to lack of support, I have since given up on this hardware and started making my own PCBs.

**Comment by jason-mao** [comment]
@steenou I have note your report issue on IDF.

**Comment by jason-mao** [comment]
@theronic You're right. 44.1kHz music should be resample to 48kHz for The ESP32-LYRATD-MSC board. We will test as your said.  BTW, if you meet this issue again, please let me know.

**Comment by pad52** [comment]
> The Bluetooth sink audio quality on the ESP32-LYRATD-MSC v2.2 is also bad despite resampling from 44100Hz to 48000Hz in my pipeline (ZL38063 doesn't support 44.1kHz). If I set the volume to 100%, it sounds terrible. Suspect ADC offset issue. At 70% volume Bluetooth sounds soft and tinny at best.
> 
> Any advice, @jason-mao? I saw something about having to forcefully flash the ZL38063 firmware on v2.1, but don't know if that's relevant, or how.

Hello @theronic I got the same problem but resolved with just one line change:

FROM:
        .communication_format = I2S_COMM_FORMAT_I2S_MSB,
TO:
        .communication_format = I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB,

Altough I don't understand the real difference, it solved my problems,
check if this could work for you.

**Comment by Tarun-Narain** [comment]
I got clean Audio from LyraTD-MSC board in pipeline_bt_sink, please refer
https://github.com/espressif/esp-adf/pull/279/files

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
