### ISSUE TITLE
Support AW88298 in esp_codec_dev (AUD-4925)

### ISSUE THREAD

**Issue by espzav** [espressif/esp-adf#1085]
Please, is there any plan to add support for AW88298 into `esp_codec_dev`?

It is inside M5Stack CoreS3 https://docs.m5stack.com/en/core/CoreS3 and I would like to add it into BSP.

Thank you.

**Comment by jason-mao** [comment]
@espzav  I think we can plan to support this chip.

**Comment by espzav** [comment]
@jason-mao Thank you, it will be great, if you can add it into plan :-)

**Comment by kristiankielhofner** [comment]
With Willow we've had quite a few users request support for the CoreS3. We've started work on an initial version but support for the AW88298 is definitely necessary to achieve this.

**Comment by espzav** [comment]
Hi @kristiankielhofner, thank you, it is great! I have the first draft od BSP for CoreS3 here: https://github.com/espressif/esp-bsp/tree/bsp/m5stack_s3 I will add audio, when it will be available in `esp_codec_dev`. Thank you very much for your help! 
Please, let me know, when it will be available.
