### ISSUE TITLE
esp-rtc.apk 无法安装 (AUD-4985)

### ISSUE THREAD

**Issue by yolee599** [espressif/esp-adf#1101]
RTC 历程的安卓端应用好像有问题，尝试了 Android 6.0 和 Android 8.1 两部手机均无法安装，提示安装包已损坏。
esp-adf/examples/protocols/esp-rtc/esp-rtc.apk

## Environment

- Audio development kit:  Custom
- Module or chip used:  ESP32-S3
- IDF version: v4.4.5-249-gcc71308e2f
- ADF version: v2.6-23-gef058dac
- Build system:  idf.py
- Running log: None
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch5) 8.4.0
- Operating system: Linux
- Using an IDE?: No
- Power supply:  USB

**Comment by jason-mao** [comment]
@yolee599 我们来检查一下再回复你。

**Comment by ahhfzhang** [comment]
Hi,

我们这里五年前的手机 Android 9.0 安装是正常，建议使用更新版本的手机来安装测试。

Thanks.

**Comment by yolee599** [comment]
换了手机可以安装了，应该是 Android 版本太低了
