### ISSUE TITLE
pipeline_recording_to_sdcard运行报错，且建议我打不存在的补丁 (AUD-4989)

### ISSUE THREAD

**Issue by guochaoa** [espressif/esp-adf#1102]
### 环境：

- ESP32-LyraTD-MSC V2.2
- MacOS
### 报错log
`
I (1689) HTTP_MP3_EXAMPLE: [ 1 ] Start audio codec chip
W (2689) SPI: MCS ret:0,Status:1
I (2689) HTTP_MP3_EXAMPLE: [2.0] Create audio pipeline for playback
I (2689) HTTP_MP3_EXAMPLE: [2.1] Create http stream to read data
I (2699) HTTP_MP3_EXAMPLE: [2.2] Create i2s stream to write data to codec chip
I (2709) HTTP_MP3_EXAMPLE: [2.3] Create mp3 decoder to decode mp3 file
I (2709) HTTP_MP3_EXAMPLE: [2.4] Register all elements to audio pipeline
I (2719) HTTP_MP3_EXAMPLE: [2.5] Link it together http_stream-->mp3_decoder-->i2s_stream-->[codec_chip]
I (2729) HTTP_MP3_EXAMPLE: [2.6] Set up  uri (http as http_stream, mp3 as mp3 decoder, and default output is i2s)
I (2739) HTTP_MP3_EXAMPLE: [ 3 ] Start and wait for Wi-Fi network
W (3759) PERIPH_WIFI: WiFi Event cb, Unhandle event_base:WIFI_EVENT, event_id:4
I (4759) HTTP_MP3_EXAMPLE: [ 4 ] Set up  event listener
I (4759) HTTP_MP3_EXAMPLE: [4.1] Listening event from all elements of pipeline
I (4759) HTTP_MP3_EXAMPLE: [4.2] Listening event from peripherals
I (4769) HTTP_MP3_EXAMPLE: [ 5 ] Start audio_pipeline
E (4769) AUDIO_THREAD: Not found right xTaskCreateRestrictedPinnedToCore.
Please enter IDF-PATH with "cd $IDF_PATH" and apply the IDF patch with "git apply $ADF_PATH/idf_patches/idf_v5.2_freertos.patch" first

E (4789) AUDIO_THREAD: Error creating RestrictedPinnedToCore http
E (4799) AUDIO_ELEMENT: [http] audio_thread_create failed
E (4809) AUDIO_THREAD: Not found right xTaskCreateRestrictedPinnedToCore.
Please enter IDF-PATH with "cd $IDF_PATH" and apply the IDF patch with "git apply $ADF_PATH/idf_patches/idf_v5.2_freertos.patch" first

E (4819) AUDIO_THREAD: Error creating RestrictedPinnedToCore mp3
E (4829) AUDIO_ELEMENT: [mp3] audio_thread_create failed
W (4839) AUDIO_ELEMENT: [http] Element has not create when AUDIO_ELEMENT_RESUME
W (4849) AUDIO_ELEMENT: [mp3] Element has not create when AUDIO_ELEMENT_RESUME
E (4849) AUDIO_PIPELINE: audio_pipeline_resume failed
W (4859) AUDIO_ELEMENT: [http] Element has not create when AUDIO_ELEMENT_TERMINATE
W (4869) AUDIO_ELEMENT: [mp3] Element has not create when AUDIO_ELEMENT_TERMINATE
`
### 问题描述

- 在运行程序是报错，并且建议我打补丁idf_v5.2_freertos.patch，但是$ADF_PATH/idf_patches目录下并不存在该补丁

**Comment by TempoTian** [comment]
可以手动merge下 https://github.com/espressif/esp-adf/blob/master/idf_patches/idf_v5.1_freertos.patch
直接copy对应的函数到tasks.c里面就可以了
