### ISSUE TITLE
components/esp_codec_dev. do not support ac101 anymore ,could you support it again  (AUD-4995)

### ISSUE THREAD

**Issue by luyongfugx** [espressif/esp-adf#1104]
components/esp_codec_dev. do not support ac101 anymore ,could you support it again  

Playback | Record
-- | --
ES8311 | Y | Y
ES8388 | Y | Y
ES8374 | Y | Y
ZL38063 | Y | Y
TAS6805M | Y | N
ES7210 | N | Y
ES7243 | N | Y
ES7243E | N | Y
ES8156 | N | Y

**Comment by jason-mao** [comment]
@luyongfugx  We implemented AC101 with some limitations, such as no hardware testing. I recommend adding not-supported chips to the [ESP component registry](https://components.espressif.com/) individually.

**Comment by luyongfugx** [comment]
> @luyongfugx We implemented AC101 with some limitations, such as no hardware testing. I recommend adding not-supported chips to the [ESP component registry](https://components.espressif.com/) individually.

thanks, i have done
