### ISSUE TITLE
Db level read (AUD-593)

### ISSUE THREAD

**Issue by blacktek** [espressif/esp-adf#111]
Hello,
  I need to write an application that monitors environment noise. It should capture audio and in case the dB is > of a certain threshold it should register the audio and stream it to a server. Of course the level associated to the the captured audio should be calibrated. Could you please advice on how to start a procedure that capture audio every second and outputs the dB/audio level?

Thank you

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
