### ISSUE TITLE
Problem with the return value (AUD-5047)

### ISSUE THREAD

**Issue by Daares1** [espressif/esp-adf#1114]
https://github.com/espressif/esp-adf/blob/ef058dac1fb53d73b354ed8e7b2ae873e09fd937/components/audio_pipeline/audio_element.c#L1293

Function audio_element_multi_input says that return ESP_OK - ESP_ERR_INVALID_ARG, but then uses the function "rb_read," the "ret" value is the number of bytes read, then returns something different, not an esp_err_t value.

**Comment by jason-mao** [comment]
@Daares1 Thank you for your report. You are right, it's incorrect. It will be fixed soon.

**Comment by Daares1** [comment]
OK, You're welcome. Regards.
