### ISSUE TITLE
/dev/ttyUSB0 failed to connect: Failed to connect to Espressif device: No serial data received. (AUD-5079)

### ISSUE THREAD

**Issue by PaulaScharf** [espressif/esp-adf#1122]
## Environment

- Audio development kit:      ESP32-S3-Korvo-2
- Audio kit version: v3
- [Required] Module or chip used:  ESP32-S3-WROOM-1
- [Required] IDF version:
   v5.0.4
- [Required] ADF version:
    v2.6-38-gdbe119de
- Build system:         idf.py
- Compiler version:
    11.2.0
- Operating system:     Linux
- Using an IDE?: VSCode
- Power supply:         USB or Battery

## Problem Description

Hi,
we recently purchased an ESP32S3-Korvo-2 from mouser, but we cant seem to be able to flash it.
We power it with a LiPo or a microusb cable and get the UART from the other microusb interface or the UART breakout pins. We tried flashing the play_mp3_control demo ([https://github.com/espressif/esp-adf/tr ... p3_control](https://github.com/espressif/esp-adf/tree/master/examples/get-started/play_mp3_control)) from ESP-ADF. We also tried flashing other minimal scripts, both with ESP-IDF and Arduino IDE. We can detect the port of the device, but flashing always results with the following error:

`/dev/ttyUSB0 failed to connect: Failed to connect to Espressif device: No serial data received.`

We tried to initialize the manual bootloader before flashing, by tapping the reset button while the boot button is pressed. What is curious here, is that shortly after doing that the board seems to reset and run some sort of build-in test-program (for checking functionality of all the buttons, sd-card and so on). We dont have an issue reading the serial monitor.

What are we doing wrong? Is our board maybe broken?

Sorry to be posting such a hardware question here, but we didnt get any reply in the esp32 forum...

**Comment by jason-mao** [comment]
@PaulaScharf Please check there is any change in the “ls /dev/ttyUSB*” of the USB inserted and unplugged。I think the board is broken if it doesn't change.
