### ISSUE TITLE
Typo: esp_wifi_setting_regitster_notify_handle (AUD-5151)

### ISSUE THREAD

**Issue by Gaai** [espressif/esp-adf#1135]
There is a typo in the following function: 
`esp_wifi_setting_regitster_notify_handle` in /components/wifi_service/src/esp_wifi_setting.c
https://github.com/search?q=repo%3Aespressif%2Fesp-adf%20esp_wifi_setting_regitster_notify_handle&type=code

This function with the typo is used in different examples. 
Probably better to correct this to: `esp_wifi_setting_register_notify_handle`

Let me know if I should do it.

**Comment by jason-mao** [comment]
@Gaai Thanks for your report. It will be fixed soon.
