### ISSUE TITLE
Set stream for I2S only adf version 2.6 (AUD-5188)

### ISSUE THREAD

**Issue by orbitcoms** [espressif/esp-adf#1142]
Hello
I am using latest version of vscode with esp-idf extension 1.7.0
Installed esp-idf 5.1 and then latest adf 2.6 from within vscode.
Next I created a new adf project based on PLAY_MP3_CONTROL_EXAMPLE
I am using esp32-s3 processor (16MB, no psram) on my own custom board (no buttons, lcd etc) and have an I2S amplifier attached.
The code compiles ok but keeps failing with I2C Bus_writerr. 
What do I need to change to prevent the code using any of the other peripherals or I2C and just use the I2C for audio streaming?

I (427) PLAY_FLASH_MP3_CONTROL: [ 1 ] Start audio codec chip
E (437) I2C_BUS: C:/Users/david/.espressif/adf/esp-adf/components/esp_peripherals/driver/i2c_bus/i2c_bus.c:115 (i2c_bus_write_bytes):I2C Bus WriteReg Error
E (977) DRV8311: es8311.c:492 (es8311_codec_init): es8311 initialize failed
E (987) AUDIO_HAL: codec init failed!
E (987) AUDIO_BOARD: board.c:63 (audio_board_codec_init): Got NULL Pointer
W (997) I2C_BUS: I2C bus has been already created, [port:0]
W (1777) ES7210: Enable TDM mode. ES7210_SDP_INTERFACE2_REG12: DB
E (1797) I2C_BUS: C:/Users/david/.espressif/adf/esp-adf/components/esp_peripherals/driver/i2c_bus/i2c_bus.c:170 (i2c_bus_read_bytes):I2C Bus ReadReg Error
E (2107) AUDIO_HAL: audio_hal.c:66 (audio_hal_init): audio_hal_init failed
E (2107) AUDIO_BOARD: board.c:55 (audio_board_adc_init): Got NULL Pointer
E (2117) AUDIO_HAL: audio_hal handle is null
E (2127) AUDIO_HAL: audio_hal handle is null
I (2127) PLAY_FLASH_MP3_CONTROL: [ 2 ] Create audio pipeline, add all elements to pipeline, and subscribe pipeline event
I (2137) PLAY_FLASH_MP3_CONTROL: [2.1] Create mp3 decoder to decode mp3 file and set custom read callback
I (2147) PLAY_FLASH_MP3_CONTROL: [2.2] Create i2s stream to write data to codec chip
I (2157) PLAY_FLASH_MP3_CONTROL: [2.3] Register all elements to audio pipeline
I (2167) PLAY_FLASH_MP3_CONTROL: [2.4] Link it together [mp3_music_read_cb]-->mp3_decoder-->i2s_stream-->[codec_chip]
I (2177) PLAY_FLASH_MP3_CONTROL: [ 3 ] Initialize peripherals
E (2187) gpio: esp_intr_alloc failed (0x105)

**Comment by jason-mao** [comment]
Please create a custom board for your project before proceeding. Please refer to https://github.com/espressif/esp-adf/tree/master/examples/get-started/play_mp3_control/components/my_board.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
