### ISSUE TITLE
在micropython下，esp-adf只能播放sd卡中的mp3，是否支持播放flash中的mp3？应该如何修改代码。 Under micropython, esp-adf can only play mp3 in the sd card. Does it support playing mp3 in flash? How should the code be modified.

### ISSUE THREAD

**Issue by keeqin** [espressif/esp-adf#1143]
esp-adf: master  3999fa5dab3594ced
esp-idf: 5.0.4
micropython: 1.21.0
我使用esp32s3,源码编译用以上版本， 因为mp3文件不大，为了节省成本所以不使用sdcard，但是没有sdcard的情况下，在flash中有文件的情况执行以下代码会导致死机：
```
mPlayer.play('file://boot.mp3')
mPlayer.play('file://sdcard/boot.mp3')
```
死机代码为:
PROBLEM IN THONNY'S BACK-END: Exception while handling 'Run' (ConnectionError: read failed: [Errno 6] Device not configured).

播放例程里http的网络mp3是有声音的。如:mPlayer.play('https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.mp3')
有没有什么办法可以播放flash中的mp3文件？

比如通过修改esp-adf/micropython_adf/mod/vfs_stream.c是否可以播放flash中的mp3。

还请各位指教。

**Comment by cyc36880** [comment]
https://github.com/espressif/esp-adf/issues/1143#issue-2118686001 
你好，请问你是怎么解决的？
