### ISSUE TITLE
No Audio HAL option in "idf.py menuconfig" (AUD-5209)

### ISSUE THREAD

**Issue by n0th1n6** [espressif/esp-adf#1153]
## Environment

- Audio development kit:     ESP32-LyraT
- Audio kit version (for ESP32-LyraT/ESP32-LyraT-Mini/ESP32-S3-Korvo-2): v4
- [Required] Module or chip used:  ESP32-WROVER-E
- [Required] IDF version (run ``git describe --tags`` in $IDF_PATH folder to find it): v4.4.4-278-g3c8bc2213c
    // v4.4-191-g83daa6dabb
- [Required] ADF version (run ``git describe --tags`` in $ADF_PATH folder to find it): v2.6-76-gf1cd5b6a
    // v2.3-171-gaac5912
- Build system:         [Make|CMake|idf.py]
- [Required] Running log:         All logs from power-on to problem recurrence
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` in your project folder to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch5) 8.4.0
    // 1.22.0-80-g6c4433a
- Operating system:     Windows
- (Windows only) Environment type: ESP Command Prompt
- Using an IDE?: No
- Power supply:         USB

## Problem Description

When running ``idf.py menuconfig`` there is no **Audio HAL** option in the menu.

### Expected Behavior

Audio HAL option is present

### Actual Behavior

No Audio HAL option in the menu

### Steps to Reproduce

1. install ESP-ADF's current release
2. run install.bat then export.bat for ADF.
3. Did the same for the IDF using the IDF that comes with ESP-ADF
4. ``idf.py set-target esp32``
5. ``idf.py menuconfig``

// If possible, attach a picture of your setup/wiring here.

<img width="661" alt="Screenshot 2024-02-18 155717" src="https://github.com/espressif/esp-adf/assets/5079634/c190268f-563e-46d5-b4ba-4e7bf97ce7f3">

### Code to Reproduce This Issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{

}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here. It should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plaintext here for us to search the error log. Or attach the complete logs and leave the main part here if the log is *too* long.
```

## Other Items If Possible

- [ ] sdkconfig file (Attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**Note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by TempoTian** [comment]
Please provide your top level CMakeLists.txt, seems that you forget to include ADF in it.
```
include($ENV{ADF_PATH}/CMakeLists.txt)
```

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
