### ISSUE TITLE
ADC Settings for ESP32-LyraT Board (AUD-589)

### ISSUE THREAD

**Issue by srini1948** [espressif/esp-adf#116]
The board specs show a maximum sampling rate of 96 kHz for audio. However, esp-adf seems to have a maximum sampling rate of 96 kHz. Can the driver for ES8388 be modified to get this maximum rate? 

In the case of ESP-IDF there is a nice example i2s_adc_dac that uses the i2s bus for data transfer rather than a "pipeline". Can this be used - if so how does one replace this:

.mode = I2S_MODE_MASTER | I2S_MODE_TX | I2S_MODE_DAC_BUILT_IN | I2S_MODE_RX | I2S_MODE_ADC_BUILT_IN,

so as to use the external codec?

Thanks.

**Comment by srini1948** [comment]
The first sentence should read:

The board specs show a maximum sampling rate of 96 kHz for audio. However, esp-adf seems to have a maximum sampling rate of 48 kHz.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
