### ISSUE TITLE
请问有esp32-lyratd-msc开发板的dueros例程吗 (AUD-588)

### ISSUE THREAD

**Issue by ZKL11G** [espressif/esp-adf#118]

**Comment by jason-mao** [comment]
@ZKL11G Sure, we will released on next version.

**Comment by watson8544** [comment]
> @ZKL11G Sure, we will released on next version.

dueros例程编译有问题，error: too many arguments to function 'raw_stream_read'
     raw_stream_read(audio_pipeline_get_el_by_tag((audio_pipeline_handle_t)handl

**Comment by jason-mao** [comment]
@watson8544 更新一下master代码，raw_stream_read的接口有变动

**Comment by jason-mao** [comment]
Has been supported.
