### ISSUE TITLE
程序加入wwe之后一直报错是怎么回事，求解 (AUD-5307)

### ISSUE THREAD

**Issue by liuliuu-112** [espressif/esp-adf#1181]
![image](https://github.com/espressif/esp-adf/assets/162400299/2c69f42d-c428-477e-97c3-7590067d2271)
加入wwe之后一直报错求解怎么回事呀

**Comment by jason-mao** [comment]
@liuliuu-112  `ch_sort_16bit_4ch`定义在`components/audio_recorder/include/ch_sort.h`，请检查一下这个文件是否参与了编译。

**Comment by jason-mao** [comment]
我将关闭这个长时间不活跃的问题，如果有进一步的更新请重新打开或新建Issue。
