### ISSUE TITLE
Error in build when using custom audio board (AUD-5324)

### ISSUE THREAD

**Issue by Pooria4484** [espressif/esp-adf#1191]
Hi,
when I use cusom audio board in **menuconfig>Audio board>**.

and building example **a2dp_sink_and_hfp_example**, build stopped.

build error:

`
~/.espressif/esp-adf/components/display_service/display_service.c:34:10: fatal error: board.h: No such file or directory
   34 | #include "board.h"
      |          ^~~~~~~~~
compilation terminated.
[1264/1612] Building C object esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src/manager.c.obj
ninja: build stopped: subcommand failed.
`

- Audio Board: Custom Audio Board
- Module used:  ESP32-S3-WROOM-1
-  IDF version v5.2
- ADF version v2.6-86-g1a03fe6a
- Build system: idf.py
- Compiler version: xtensa-esp-elf-gcc (crosstool-NG esp-13.2.0_20230928) 13.2.0
-  Operating system:  macOS
- Using VScode

**Comment by jason-mao** [comment]
@Pooria4484 Did you create a new board folder(like https://github.com/espressif/esp-adf/tree/master/examples/get-started/play_mp3_control/components/my_board/my_board_v1_0) in your project when you select the `custom audio board`?

**Comment by jason-mao** [comment]
我将关闭这个长时间不活跃的问题，如果有进一步的更新请重新打开或新建Issue。
