### ISSUE TITLE
record_wav_sdcard_example.c 这个 demo 录音效果很差

### ISSUE THREAD

**Issue by qq516333132** [espressif/esp-adf#12]
未改程序，使用 LyraT官方开发板，破音, 采样率貌似也不对。

可能是什么问题引起？

**Comment by jason-mao** [comment]
@qq516333132 可否把你录音的文件上传一下？同时请再用example/filterpipeline_resample 进行测试

**Comment by qq516333132** [comment]
录音文件在这里
[https://debugdump.com/files/201805/REC1.wav](url)

晚点我再试一试 example/filterpipeline_resample

**Comment by jason-mao** [comment]
@qq516333132 这个问题现在如何了？
