### ISSUE TITLE
 (932) MPEG_READER: Not find an effective frame, line:857 (AUD-5468)

### ISSUE THREAD

**Issue by nagarajbose** [espressif/esp-adf#1214]
I (442) MP3_PLAY: SD card mounted
I (442) MP3_PLAY: File '/sdcard/music/03.mp3' exists
I (452) MP3_PLAY: Read some bytes from file, file is accessible
I (452) MP3_PLAY: File '/sdcard/music/03.mp3' exists. Size: 55302 bytes
I (452) MP3_DECODER: MP3 init
W (462) I2S: APLL not supported on current chip, use I2S_CLK_D2CLK as default clock source
I (472) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (482) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (482) I2S: I2S0, MCLK output by GPIO16
I (492) AUDIO_PIPELINE: link el->rb, el:0x3fcea6ac, tag:mp3, rb:0x3fced220
W (492) AUDIO_THREAD: Make sure selected the `CONFIG_SPIRAM_BOOT_INIT` and `CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY` by `make menuconfig`
I (512) AUDIO_THREAD: The mp3 task allocate stack on internal memory
I (512) AUDIO_ELEMENT: [mp3-0x3fcea6ac] Element task created
I (522) AUDIO_THREAD: The i2s task allocate stack on internal memory
I (532) AUDIO_ELEMENT: [i2s-0x3fcead68] Element task created
I (532) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:317716 Bytes

I (542) AUDIO_ELEMENT: [mp3] AEL_MSG_CMD_RESUME,state:1
I (552) MP3_DECODER: MP3 opened
I (552) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (562) I2S_STREAM: AUDIO_STREAM_WRITER
I (562) AUDIO_PIPELINE: Pipeline started
I (572) CODEC_ELEMENT_HELPER: The element is 0x3fcea6ac. The reserve data 2 is 0x0.
E (932) MPEG_READER: Not find an effective frame, line:857.
E (932) MPEG_READER: Resync error (line 536)
E (932) MP3_DECODER: Encountered error reading when MP3 init
E (932) AUDIO_ELEMENT: [mp3] AEL_STATUS_ERROR_OPEN,-1
W (942) AUDIO_ELEMENT: [mp3] audio_element_on_cmd_error,7
I (952) MP3_DECODER: Closed
W (952) AUDIO_ELEMENT: IN-[i2s] AEL_IO_ABORT
W (952) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (962) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (962) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (972) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (972) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (982) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT

**Comment by TempoTian** [comment]
Could you please provide the test file: `03.mp3`, so that we can test and find the possible causes?

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
