### ISSUE TITLE
怎么实现通过MQTT流播放WAV和编码WAV (AUD-5500)

### ISSUE THREAD

**Issue by maenkai** [espressif/esp-adf#1222]
**Is your feature request related to a problem? Please describe.**

1.我期望从mqtt服务器上传输wav格式的数据给到esp32,esp32再执行播放
2.esp32语音收集后按照wav格式发布到mqtt服务器

**Describe the solution you'd like**
期望以上结果

**Describe alternatives you've considered**
看了很多例程不知道怎么实现，希望有个example或者库支持

**Additional context**

希望有想关组件和文档

**Comment by hbler99** [comment]
可以参考下述两个链接
https://github.com/espressif/esp-idf/tree/3c8bc2213cd5719d0c61ae9465a188eac83dfd70/examples/protocols/mqtt/tcp，
https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_http_select_decoder，
