### ISSUE TITLE
A lot of "deprecated" in VoIP example (AUD-5517)

### ISSUE THREAD

**Issue by Jon811** [espressif/esp-adf#1226]
## Environment

- Audio development kit:      Waiting for ESP32-LyraT-Mini
- [Required] Module or chip used:  Choose ESP32-LyraT-Mini
- [Required] IDF version v5.2
- [Required] ADF version v2.6-122-g28736657
- Build system:        Visual Studio code
- [Required] Running log:         All logs from power-on to problem recurrence
- Compiler version: not a command in that folder
- Operating system:     [Windows
- (Windows only) Environment type: VSCode
- Using an IDE?:  ESP-IDF addition in VSCode
- Power supply:         [USB

At compilation stage have a lot of "deprecated"

<details><summary>Details</summary>
<p>
[931/1326] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/sip_service.c.obj
In file included from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:23,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream.h:28,
                 from C:/Users/eulitin/YandexDisk/Firmware/VoIP_outside/voip/voip/main/sip_service.h:30,
                 from C:/Users/eulitin/YandexDisk/Firmware/VoIP_outside/voip/voip/main/sip_service.c:28:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
[932/1326] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/voip_app.c.obj
In file included from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:23,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream.h:28,
                 from C:/Users/eulitin/YandexDisk/Firmware/VoIP_outside/voip/voip/main/sip_service.h:30,
                 from C:/Users/eulitin/YandexDisk/Firmware/VoIP_outside/voip/voip/main/voip_app.c:20:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
[997/1326] Building C object esp-idf/esp-adf-libs/CMakeFiles/__idf_esp-adf-libs.dir/esp_codec/audio_forge.c.obj
C:/Users/eulitin/.espressif/esp-adf/components/esp-adf-libs/esp_codec/audio_forge.c: In function 'audio_forge_sonic_set_speed':
C:/Users/eulitin/.espressif/esp-adf/components/esp-adf-libs/esp_codec/audio_forge.c:993:15: warning: using integer absolute value function 'abs' when argument is of floating-point type 'float' [-Wabsolute-value]
  993 |     if ((int)(abs((sonic_speed - audio_forge->sonic_speed) * 100)) <= 5) {
      |               ^~~
C:/Users/eulitin/.espressif/esp-adf/components/esp-adf-libs/esp_codec/audio_forge.c: In function 'audio_forge_sonic_set_pitch':
C:/Users/eulitin/.espressif/esp-adf/components/esp-adf-libs/esp_codec/audio_forge.c:1018:15: warning: using integer absolute value function 'abs' when argument is of floating-point type 'float' [-Wabsolute-value]
 1018 |     if ((int)(abs((sonic_pitch - audio_forge->sonic_pitch) * 100)) <= 5) {
      |               ^~~
[1019/1326] Building C object esp-idf/esp_peripherals/CMakeFiles/__idf_esp_peripherals.dir/periph_adc_button.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/include/periph_adc_button.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_adc_button.c:28:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
[1028/1326] Building C object esp-idf/esp_peripherals/CMakeFiles/__idf_esp_peripherals.dir/periph_wifi.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c:26:
C:/Users/eulitin/esp/v5.2/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:10:9: note: '#pragma message: esp_wpa2.h is deprecated. Use esp_eap_client.h instead.'
   10 | #pragma message("esp_wpa2.h is deprecated. Use esp_eap_client.h instead.")
      |         ^~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c: In function '_wifi_init':
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c:435:9: warning: 'esp_wifi_sta_wpa2_ent_set_ca_cert' is deprecated: Use 'esp_eap_client_set_ca_cert' instead [-Wdeprecated-declarations]
  435 |         ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_ca_cert((const unsigned char *)periph_wifi->wpa2_e_cfg->ca_pem_start, ca_pem_bytes));
      |         ^~~~~~~~~~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:171:11: note: declared here
  171 | esp_err_t esp_wifi_sta_wpa2_ent_set_ca_cert(const unsigned char *ca_cert, int ca_cert_len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c:436:9: warning: 'esp_wifi_sta_wpa2_ent_set_cert_key' is deprecated: Use 'esp_eap_client_set_certificate_and_key' instead  
-Wdeprecated-declarations]
  436 |         ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_cert_key((const unsigned char *)periph_wifi->wpa2_e_cfg->wpa2_e_cert_start, client_crt_bytes, \
      |         ^~~~~~~~~~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:203:11: note: declared here
  203 | esp_err_t esp_wifi_sta_wpa2_ent_set_cert_key(const unsigned char *client_cert, int client_cert_len,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c:438:9: warning: 'esp_wifi_sta_wpa2_ent_set_identity' is deprecated: Use 'esp_eap_client_set_identity' instead [-Wdeprecated-declarations]
  438 |         ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_identity((uint8_t *)periph_wifi->wpa2_e_cfg->eap_id, strlen(periph_wifi->wpa2_e_cfg->eap_id)));
      |         ^~~~~~~~~~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:62:11: note: declared here
   62 | esp_err_t esp_wifi_sta_wpa2_ent_set_identity(const unsigned char *identity, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c:440:13: warning: 'esp_wifi_sta_wpa2_ent_set_username' is deprecated: Use 'esp_eap_client_set_username' instead [-Wdeprecated-declarations]
  440 |             ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_username((uint8_t *)periph_wifi->wpa2_e_cfg->eap_username, strlen(periph_wifi->wpa2_e_cfg->eap_username)));
      |             ^~~~~~~~~~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:89:11: note: declared here
   89 | esp_err_t esp_wifi_sta_wpa2_ent_set_username(const unsigned char *username, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c:441:13: warning: 'esp_wifi_sta_wpa2_ent_set_password' is deprecated: Use 'esp_eap_client_set_password' instead [-Wdeprecated-declarations]
  441 |             ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_set_password((uint8_t *)periph_wifi->wpa2_e_cfg->eap_password, strlen(periph_wifi->wpa2_e_cfg->eap_password)));
      |             ^~~~~~~~~~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:115:11: note: declared here
  115 | esp_err_t esp_wifi_sta_wpa2_ent_set_password(const unsigned char *password, int len);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_wifi.c:445:9: warning: 'esp_wifi_sta_wpa2_ent_enable' is deprecated: Use 'esp_wifi_sta_enterprise_enable' instead [-Wdeprecated-declarations]
  445 |         ESP_ERROR_CHECK(esp_wifi_sta_wpa2_ent_enable());
      |         ^~~~~~~~~~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/wpa_supplicant/esp_supplicant/include/esp_wpa2.h:28:11: note: declared here
   28 | esp_err_t esp_wifi_sta_wpa2_ent_enable(void);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[1030/1326] Building C object esp-idf/esp_peripherals/CMakeFiles/__idf_esp_peripherals.dir/periph_ws2812.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/periph_ws2812.c:29:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/rmt.h:18:2: warning: #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h" [-Wcpp]   
   18 | #warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"
      |  ^~~~~~~
[1033/1326] Building C object esp-idf/esp_peripherals/CMakeFiles/__idf_esp_peripherals.dir/lib/adc_button/adc_button.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/lib/adc_button/adc_button.c:29:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
In file included from C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/lib/adc_button/adc_button.c:32:
C:/Users/eulitin/esp/v5.2/esp-idf/components/esp_adc/deprecated/include/esp_adc_cal.h:17:2: warning: #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h" [-Wcpp]
   17 | #warning "legacy adc calibration driver is deprecated, please migrate to use esp_adc/adc_cali.h and esp_adc/adc_cali_scheme.h"
      |  ^~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/lib/adc_button/adc_button.c: In function 'get_adc_voltage':
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/lib/adc_button/adc_button.c:152:5: warning: 'ADC_ATTEN_DB_11' is deprecated [-Wdeprecated-declarations]
  152 |     esp_adc_cal_characterize(ADC_UNIT_1, ADC_ATTEN_11db, ADC_WIDTH_12Bit, V_REF, &characteristics);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc_types_legacy.h:8,
                 from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:15:
C:/Users/eulitin/esp/v5.2/esp-idf/components/hal/include/hal/adc_types.h:51:5: note: declared here
   51 |     ADC_ATTEN_DB_11 __attribute__((deprecated)) = ADC_ATTEN_DB_12,  ///<This is deprecated, it behaves the same as `ADC_ATTEN_DB_12`
      |     ^~~~~~~~~~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/lib/adc_button/adc_button.c: In function 'button_task':
C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/lib/adc_button/adc_button.c:292:9: warning: 'ADC_ATTEN_DB_11' is deprecated [-Wdeprecated-declarations]
  292 |         adc1_config_channel_atten(info->adc_ch, ADC_ATTEN_11db);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/hal/include/hal/adc_types.h:51:5: note: declared here
   51 |     ADC_ATTEN_DB_11 __attribute__((deprecated)) = ADC_ATTEN_DB_12,  ///<This is deprecated, it behaves the same as `ADC_ATTEN_DB_12`
      |     ^~~~~~~~~~~~~~~
[1046/1326] Building C object esp-idf/esp-adf-libs/CMakeFiles/__idf_esp-adf-libs.dir/media_lib_sal/port/media_lib_os_freertos.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/esp-adf-libs/media_lib_sal/port/media_lib_os_freertos.c:43:
C:/Users/eulitin/esp/v5.2/esp-idf/components/freertos/esp_additions/include/freertos/task_snapshot.h:8:2: warning: #warning freertos/task_snapshot.h header is no longer used, and will be removed in future versions. [-Wcpp]
    8 | #warning freertos/task_snapshot.h header is no longer used, and will be removed in future versions.
      |  ^~~~~~~
[1050/1326] Building C object esp-idf/audio_board/CMakeFiles/__idf_audio_board.dir/lyrat_mini_v1_1/board.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/esp_peripherals/include/periph_adc_button.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/components/audio_board/lyrat_mini_v1_1/board.c:31:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
[1202/1326] Building C object esp-idf/dueros_service/CMakeFiles/__idf_dueros_service.dir/dueros_esp_flash.c.obj
C:/Users/eulitin/.espressif/esp-adf/components/dueros_service/dueros_esp_flash.c: In function 'duer_flash_string_init':
C:/Users/eulitin/.espressif/esp-adf/components/dueros_service/dueros_esp_flash.c:83:22: warning: assignment to 'unsigned int *' from incompatible pointer type 'uint32_t *' {aka 'long unsigned int *'} [-Wincompatible-pointer-types]
   83 |         rt->ele_list = (uint32_t *)audio_malloc(sizeof(uint32_t) * rt->max_ele_count);
      |                      ^
[1205/1326] Building C object esp-idf/dueros_service/CMakeFiles/__idf_dueros_service.dir/duer_wifi_cfg.c.obj
C:/Users/eulitin/.espressif/esp-adf/components/dueros_service/duer_wifi_cfg.c:129:22: warning: initialization of 'int (*)(uint8_t *, size_t,  uint16_t)' {aka 'int (*)(unsigned char *, unsigned int,  
short unsigned int)'} from incompatible pointer type 'int (*)(uint8_t *, uint32_t,  uint16_t)' {aka 'int (*)(unsigned char *, long unsigned int,  short unsigned int)'} [-Wincompatible-pointer-types] 
  129 |     .ble_send_data = duer_ble_send_data,
      |                      ^~~~~~~~~~~~~~~~~~
C:/Users/eulitin/.espressif/esp-adf/components/dueros_service/duer_wifi_cfg.c:129:22: note: (near initialization for 'dipb_cbs.ble_send_data')
[1225/1326] Building C object esp-idf/audio_stream/CMakeFiles/__idf_audio_stream.dir/pwm_stream.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/audio_stream/include/pwm_stream.h:29,
                 from C:/Users/eulitin/.espressif/esp-adf/components/audio_stream/pwm_stream.c:39:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/timer.h:16:2: warning: #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h" [-Wcpp]
   16 | #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h"
      |  ^~~~~~~
[1230/1326] Building C object esp-idf/audio_stream/CMakeFiles/__idf_audio_stream.dir/lib/gzip/gzip_miniz.c.obj
In file included from C:/Users/eulitin/.espressif/esp-adf/components/audio_stream/lib/gzip/miniz_inflate.h:32,
                 from C:/Users/eulitin/.espressif/esp-adf/components/audio_stream/lib/gzip/gzip_miniz.c:30:
C:/Users/eulitin/esp/v5.2/esp-idf/components/esp_rom/include/esp32/rom/miniz.h:7:2: warning: #warning "{target}/rom/miniz.h is deprecated, please use (#include "miniz.h") instead" [-Wcpp]
    7 | #warning "{target}/rom/miniz.h is deprecated, please use (#include "miniz.h") instead"
      |  ^~~~~~~
[1245/1326] Building C object esp-idf/coredump_upload_service/CMakeFiles/__idf_coredump_upload_service.dir/coredump_upload_service.c.obj
C:/Users/eulitin/.espressif/esp-adf/components/coredump_upload_service/coredump_upload_service.c: In function 'coredump_read':
C:/Users/eulitin/.espressif/esp-adf/components/coredump_upload_service/coredump_upload_service.c:84:24: warning: passing argument 2 of 'esp_rom_spiflash_read' from incompatible pointer type [-Wincompatible-pointer-types]
   84 |     if (SPI_READ(addr, *des, *len) != ESP_OK) {
      |                        ^~~~
      |                        |
      |                        uint8_t * {aka unsigned char *}
In file included from C:/Users/eulitin/.espressif/esp-adf/components/coredump_upload_service/coredump_upload_service.c:44:
C:/Users/eulitin/esp/v5.2/esp-idf/components/esp_rom/include/esp_rom_spiflash.h:252:78: note: expected 'uint32_t *' {aka 'long unsigned int *'} but argument is of type 'uint8_t *' {aka 'unsigned char *'}
  252 | esp_rom_spiflash_result_t esp_rom_spiflash_read(uint32_t src_addr, uint32_t *dest, int32_t len);
      |                                                                    ~~~~~~~~~~^~~~
[1303/1326] Building C object esp-idf/av_stream/CMakeFiles/__idf_av_stream.dir/av_stream_hal/av_stream_hal_lcd.c.obj
In file included from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:23,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal_lcd.c:26:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
[1306/1326] Building C object esp-idf/av_stream/CMakeFiles/__idf_av_stream.dir/av_stream_hal/av_stream_hal_camera.c.obj
In file included from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:23,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal_camera.c:27:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
[1307/1326] Building C object esp-idf/av_stream/CMakeFiles/__idf_av_stream.dir/av_stream_hal/av_stream_hal_audio.c.obj
In file included from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:23,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal_audio.c:29:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
[1311/1326] Building C object esp-idf/av_stream/CMakeFiles/__idf_av_stream.dir/av_stream.c.obj
In file included from C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:23,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream_hal/av_stream_hal.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream.h:28,
                 from C:/Users/eulitin/.espressif/esp-adf/examples/protocols/components/av_stream/av_stream.c:46:
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/adc.h:19:2: warning: #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively" [-Wcpp]
   19 | #warning "legacy adc driver is deprecated, please migrate to use esp_adc/adc_oneshot.h and esp_adc/adc_continuous.h for oneshot mode and continuous mode drivers respectively"
      |  ^~~~~~~
C:/Users/eulitin/esp/v5.2/esp-idf/components/driver/deprecated/driver/i2s.h:27:2: warning: #warning "This set of I2S APIs has been deprecated, please include 'driver/i2s_std.h', 'driver/i2s_pdm.h' or 'driver/i2s_tdm.h' instead. if you want to keep using the old APIs and ignore this warning, you can enable 'Suppress leagcy driver deprecated warning' option under 'I2S Configuration' menu in Kconfig" [-Wcpp]
   27 | #warning "This set of I2S APIs has been deprecated, \
      |  ^~~~~~~
[1325/1326] Generating binary image from built executable
esptool.py v4.7.0
Creating esp32 image...
Merged 2 ELF sections
Successfully created esp32 image.
</p>
</details> 

After uploading to ESP32-CAM (for now i have only it, waiting for Lyra) at start i have: 
<details><summary>Details</summary>
<p>
I (844) heap_init: Initializing. RAM available for dynamic allocation:
I (851) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (857) heap_init: At 3FFB5BE8 len 0002A418 (169 KiB): DRAM
I (864) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (870) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (876) heap_init: At 400970E0 len 00008F20 (35 KiB): IRAM
I (883) esp_psram: Adding pool of 2033K of PSRAM memory to heap allocator
I (891) spi_flash: detected chip: generic
I (895) spi_flash: flash io: qio
E (899) i2s(legacy): CONFLICT! The new i2s driver can't work along with the legacy i2s driver
W (908) i2s(legacy): legacy i2s driver is deprecated, please migrate to use driver/i2s_std.h, driver/i2s_pdm.h or driver/i2s_tdm.h
W (920) i2c: This driver is an old driver, please migrate your application code to adapt `driver/i2c_master.h`
W (931) ADC: legacy driver is deprecated, please migrate to `esp_adc/adc_oneshot.h`
I (940) main_task: Started on CPU0
I (944) esp_psram: Reserving pool of 18K of internal memory for DMA/internal allocations
I (952) main_task: Calling app_main()
</p>
</details> 

So even before start the main program we have a conflict. Hope all this can be fixed.

**Comment by Jon811** [comment]
Changing ISP-IDF to 4.4.8 fixed problems, but why can't we use last versions of IDF? I don't understand.

**Comment by mrmonteith** [comment]
> Changing ISP-IDF to 4.4.8 fixed problems, but why can't we use last versions of IDF? I don't understand.

I tried some of the examples on 4.4.8 today and tons are depricated and one final error.  It does make it hard to get very far.
