### ISSUE TITLE
关于AEC信号延迟调整的问题，如果让参考信号更靠前 (AUD-5540)

### ISSUE THREAD

**Issue by laodi-chen** [espressif/esp-adf#1232]
## Environment

- Audio development kit: ESP32-LyraT-Mini
- Audio kit version: v1
- Module or chip used: ESP32-WROVER-E
- IDF version: v4.4.7
- ADF version: v2.6-82-g33ba0c5c
- Build system: idf.py
- Running log:
- Operating system: Windows
- Environment type: ESP Command Prompt
- Using an IDE?: Yes(Visual Studio Code1.87.2)
- Power supply: USB

## Problem Description

使用VOIP过程发现回音消除效果不理想，参阅手册发现需要调整信号延迟
开启`DEBUG_AEC_INPUT`捕获的录制音频发现，右声道落后左声道254ms左右
![image](https://github.com/user-attachments/assets/3495afcf-324f-48d3-a8d0-e8070da22e53)
调整 av_stream.c  algo_stream_set_delay处确实修改了延迟时间，但是意想不到的更靠后了，正好是加上了调整的延迟
```c
if (!_have_hardware_ref(av_stream)) {
ESP_LOGI(TAG,"_have_hardware_ref_have_hardware_ref_have_hardware_ref_have_hardware_ref_have_hardware_ref_have_hardware_ref_have_hardware_ref");
    av_stream->ringbuf_ref = rb_create(8*av_stream->config.hal.audio_framesize, 1);
    AUDIO_NULL_CHECK(TAG, av_stream->ringbuf_ref, return ESP_FAIL);
    algo_stream_set_delay(av_stream->element_algo, av_stream->ringbuf_ref, 245); // 修改信号延迟
}
```
![image](https://github.com/user-attachments/assets/7910d5f1-3da6-4640-9ee5-971db4177eca)

请问如何才能让信号更靠前

**Comment by hbler99** [comment]
请问参考和录制分别是哪个声道？还请您再给出 I2S 的配置信息
