### ISSUE TITLE
ESP-ADF Release/v2.7 (AUD-5577)

### ISSUE THREAD

**Issue by estevaofv** [espressif/esp-adf#1240]
Hello, in README already talking about ESP-ADF
Release/v2.7 compatible with IDF 5.3 when the new ADF version will be releases? or It already have been released and you just forgot to create the tag for v2.7?
Thanks in advance!

**Comment by jason-mao** [comment]
@estevaofv The ADF v2.7 is compatiable the IDF v5.3, it's not released, we are working on it.

**Comment by jason-mao** [comment]
Related https://github.com/espressif/esp-adf/issues/1205

**Comment by kscz** [comment]
Do you happen to have a timeline or just a rough estimate of how soon until the new release? #1205 just has the comment "This won't take long." which is pretty ambiguous.

**Comment by jason-mao** [comment]
The ADF v2.7 was released in https://github.com/espressif/esp-adf/releases/tag/v2.7
