### ISSUE TITLE
When the ESP-ADF can  support Continuous speech recognition for continuous dialogue when wakeup by wakenet (AUD-5610)

### ISSUE THREAD

**Issue by iot-lorawan** [espressif/esp-adf#1247]
Hi,
     When the ESP-ADF can support Continuous speech recognition for continuous dialogue when wakeup by wakenet

Thanks,

**Comment by hbler99** [comment]
Currently, we have no plans to support continuous speech recognition.

**Comment by iot-lorawan** [comment]
Hi @hbler99 ,
      Is there good solution for this.

Thanks,

**Comment by hbler99** [comment]
You can try to comment out the line
```
208            detect_flag = 0;
```
https://github.com/espressif/esp-adf/blob/dac74d81c85b5bc4e9da008031f31394943fa2c7/components/audio_recorder/recorder_sr.c#L208C1-L208C29

**Comment by iot-lorawan** [comment]
Hi @hbler99 ,
     Thanks for your response.
     I modify as your suggestion, but it seem dont work well. 
     I change use esp-idf with esp-sr， it work fine.

Best Regard.

**Comment by hbler99** [comment]
Congrats!
