### ISSUE TITLE
Configuring I2S Peripheral to Support PT8211 with LSB Justified Format (AUD-5618)

### ISSUE THREAD

**Issue by masm31** [espressif/esp-adf#1250]
Hi,

I am working with the PT8211 DAC, which only supports the Least Significant Bit (LSB) Justified format. I need help configuring the I2S peripheral to work with this format. Could you please guide me on how to achieve this? Any specific registers or settings that I should look into?

Thank you!

**Comment by TempoTian** [comment]
You can check headfile `https://github.com/espressif/esp-idf/blob/master/components/esp_driver_i2s/include/driver/i2s_std.h` for help.
Take care of `msb_right` and `bit_shift` field.

**Comment by jason-mao** [comment]
This topic has become inactive, so I'm closing the issue. Please reopen it if you have any questions or need any further assistance.
