### ISSUE TITLE
VoIP in ESP32 LyraT 4.3 No Audio after hang up (AUD-5632)

### ISSUE THREAD

**Issue by strdvxt** [espressif/esp-adf#1254]
Board : ESP32 LyraT v4.3
IDF ver 4.4.8
ADF-master

Currently, I try to run VoIP Example from ADF. it successful to register, call in, dial in, and hang up but the problem is audio didnt come up. 
the bug eror is : 

E (3307) TONE_PARTITION: Not flash tone partition
I (3315) MP3_DECODER: MP3 opened
I (3315) ESP_AUDIO_TASK: Blocking play until received AEL_MSG_CMD_REPORT_MUSIC_INFO
E (3324) AUDIO_ELEMENT: [IN_flash] AEL_STATUS_ERROR_OPEN,-1
E (3338) TONE_PARTITION: tone_partition.c:205 (tone_partition_deinit): Got NULL Pointer
I (3339) ESP_AUDIO_TASK: Recv Element[IN_flash-0x3f806b0c] MSG,type:20000,cmd:8,len:4,status:ESP_ERR_AUDIO_OPEN
E (3347) MP3_DECODER: Failed to read audio data (line 129)
E (3358) ESP_AUDIO_TASK: Got element[IN_flash] error:ESP_ERR_AUDIO_OPEN, stop pipeline[0]

i dont have any idea bcs there is no similar problem on the forum. Did anyone here has solved this? Thank youuuu <3

**Comment by jason-mao** [comment]
@strdvxt I think you do not download the tone to Flash, please refer to https://github.com/espressif/esp-adf/tree/master/examples/protocols/voip#download-flash-tone

**Comment by jason-mao** [comment]
This topic has become inactive, so I'm closing the issue. Please reopen it if you have any questions or need any further assistance.
