### ISSUE TITLE
如何将 esp-adf 的 dueros 例程加入到 esp-box 的 factory_demo 中？ (AUD-5648)

### ISSUE THREAD

**Issue by AaronPMM** [espressif/esp-adf#1258]
我希望在 esp-box 的 factory_demo 例程中添加 dueros ，将 ESP32-S3-BOX-3 接入百度平台，根据文档介绍，dueros 使用了 ADF 的接口，在 esp-box 中并没有，也看不到接口的实现，请问如何将 dueros 功能在 esp-box 中实现？

**Comment by shootao** [comment]
same as [issues/1264](https://github.com/espressif/esp-adf/issues/1264), plaese close this Issue
