### ISSUE TITLE
Question about using audio flash tone in Dueros routine (AUD-5664)

### ISSUE THREAD

**Issue by AaronPMM** [espressif/esp-adf#1264]
The hardware I have is ESP32-S3-BOX-3. Although ESP-ADF indicates that it supports this hardware, the dueros example does not support it. The example uses sdcard, but ESP32-S3-BOX-3 does not support sdcard. I hope to replace sdcard with aduio flash tone. Since this is my first time using ESP chips, I have a problem with how to put the generated bin file into flash.
I searched for some online articles, which pointed out that the partition table needs to be modified to add a flash_tone partition. There are 2 ".csv" files in this example, partitions_dueros_examples.csv and partitions_dueros_examples_esp32s3.csv. Which one should I modify? Or should I modify both? In addition, what should I modify for the offset and size options?

**Comment by hbler99** [comment]
In the future, we will support it. Please be patient.

**Comment by AaronPMM** [comment]
> In the future, we will support it. Please be patient.

Can you give me a reply or suggestion on my question? Our company is currently evaluating this project and plans to quickly build a sample based on this hardware. We may not be able to wait for you to complete the routine.

**Comment by AaronPMM** [comment]
I made the following changes according to the routine 

1. Add audio_tone_uri.c and audio_tone_uir.h in the main directory 

2. 2. Modify the CMakeList.txt file in the dueros directory

 ```
      # This is a cmake function, which is used to flash the bin file to the specified partition
      function(esptool_py_flash_customize_image target_name image_name offset image)
          idf_build_get_property(build_dir BUILD_DIR)
          file(RELATIVE_PATH image ${build_dir} ${image})
      
          set_property(TARGET ${target_name} APPEND PROPERTY FLASH_FILE
                      "\"${offset}\" : \"${image}\"")
          set_property(TARGET ${target_name} APPEND PROPERTY FLASH_ENTRY
                      "\"${image_name}\" : { \"offset\" : \"${offset}\", \"file\" : \"${image}\" }")
          set_property(TARGET ${target_name} APPEND PROPERTY IMAGES "${offset} ${image}")
      
          if(CONFIG_SECURE_FLASH_ENCRYPTION_MODE_DEVELOPMENT)
              set_property(TARGET encrypted-${target_name} APPEND PROPERTY FLASH_FILE
                          "\"${offset}\" : \"${image}\"")
              set_property(TARGET encrypted-${target_name} APPEND PROPERTY FLASH_ENTRY
                          "\"${image_name}\" : { \"offset\" : \"${offset}\", \"file\" : \"${image}\" }")
              set_property(TARGET encrypted-${target_name} APPEND PROPERTY IMAGES "${offset} ${image}")
          endif()
      endfunction()
      
      # Flash the custom partition named `flash_tone`.
      set(partition flash_tone)
      idf_build_get_property(project_dir PROJECT_DIR)
      message(STATUS "project_dir = >>>>>>>>>>>>>>>>>>>>>>>>>>>> %s", ${project_dir})
      set(image_file ${project_dir}/tone/audio_tone.bin)
      partition_table_get_partition_info(offset "--partition-name ${partition}" "offset")
      esptool_py_flash_customize_image(flash "${partition}" "${offset}" "${image_file}")
```

   3. Modify the void *duer_audio_start_recorder(rec_event_cb_tcb) function

```
      void *duer_audio_start_recorder(rec_event_cb_t cb)
      {
          if (recorder) {
              return recorder;
          }
      
          audio_element_handle_t i2s_stream_reader;
          audio_pipeline_handle_t pipeline;
          audio_pipeline_cfg_t pipeline_cfg = DEFAULT_AUDIO_PIPELINE_CONFIG();
          pipeline = audio_pipeline_init(&pipeline_cfg);
          if (NULL == pipeline) {
              return NULL;
          }
      
          i2s_stream_cfg_t i2s_cfg = I2S_STREAM_CFG_DEFAULT_WITH_PARA(CODEC_ADC_I2S_PORT, 48000, CODEC_ADC_BITS_PER_SAMPLE, AUDIO_STREAM_READER);
          i2s_cfg.task_core = 1;
          i2s_stream_reader = i2s_stream_init(&i2s_cfg);
      
          raw_stream_cfg_t raw_cfg = RAW_STREAM_CFG_DEFAULT();
          raw_cfg.type = AUDIO_STREAM_READER;
          raw_read = raw_stream_init(&raw_cfg);
      
          audio_pipeline_register(pipeline, i2s_stream_reader, "i2s");
          audio_pipeline_register(pipeline, raw_read, "raw");
      #if 0   
          const char *link_tag[3] = {"i2s", "raw"};
          uint8_t linked_num = 2;
      
          rsp_filter_cfg_t rsp_cfg = DEFAULT_RESAMPLE_FILTER_CONFIG();
          rsp_cfg.src_rate = 48000;
          rsp_cfg.dest_rate = 16000;
          rsp_cfg.task_core = 1;
      #ifdef CONFIG_ESP32_S3_KORVO2_V3_BOARD
          rsp_cfg.mode = RESAMPLE_UNCROSS_MODE;
          rsp_cfg.src_ch = 4;
          rsp_cfg.dest_ch = 4;
          rsp_cfg.max_indata_bytes = 1024;
      #endif
          audio_element_handle_t filter = rsp_filter_init(&rsp_cfg);
          audio_pipeline_register(pipeline, filter, "filter");
          link_tag[1] = "filter";
          link_tag[2] = "raw";
          linked_num = 3;
      #endif
      //aaron change
      #if 1
      /*
          const char *link_tag[4] = {"i2s", "raw"};
          uint8_t linked_num = 2;
      
          rsp_filter_cfg_t rsp_cfg = DEFAULT_RESAMPLE_FILTER_CONFIG();
          rsp_cfg.src_rate = 48000;
          rsp_cfg.dest_rate = 16000;
          rsp_cfg.task_core = 1;
      #ifdef CONFIG_ESP32_S3_KORVO2_V3_BOARD
          rsp_cfg.mode = RESAMPLE_UNCROSS_MODE;
          rsp_cfg.src_ch = 4;
          rsp_cfg.dest_ch = 4;
          rsp_cfg.max_indata_bytes = 1024;
      #endif
          audio_element_handle_t filter = rsp_filter_init(&rsp_cfg);
          audio_pipeline_register(pipeline, filter, "filter");
      */
      
          audio_element_handle_t tone_stream_reader;
          tone_stream_cfg_t tone_cfg = TONE_STREAM_CFG_DEFAULT();
          tone_cfg.type = AUDIO_STREAM_READER;
          tone_stream_reader = tone_stream_init(&tone_cfg);
          AUDIO_NULL_CHECK(TAG, tone_stream_reader, return);
          audio_pipeline_register(pipeline, tone_stream_reader, "tone");
          link_tag[1] = "tone";
          link_tag[2] = "raw";
          linked_num = 3;
      #endif
      
          audio_pipeline_link(pipeline, &link_tag[0], linked_num);
          audio_pipeline_run(pipeline);
          ESP_LOGI(TAG, "Recorder has been created");
      
          recorder_sr_cfg_t recorder_sr_cfg = DEFAULT_RECORDER_SR_CFG();
          recorder_sr_cfg.afe_cfg.aec_init = RECORD_HARDWARE_AEC;
          recorder_sr_cfg.multinet_init = false;
          recorder_sr_cfg.afe_cfg.memory_alloc_mode = AFE_MEMORY_ALLOC_MORE_PSRAM;
          recorder_sr_cfg.afe_cfg.agc_mode = AFE_MN_PEAK_NO_AGC;
      
          audio_rec_cfg_t cfg = AUDIO_RECORDER_DEFAULT_CFG();
          cfg.read = (recorder_data_read_t)&input_cb_for_afe;
          cfg.sr_handle = recorder_sr_create(&recorder_sr_cfg, &cfg.sr_iface);
          cfg.event_cb = cb;
          cfg.vad_off = 1000;
          recorder = audio_recorder_create(&cfg);
      
          return recorder;
      }
```

4. Modify the static esp_err_t rec_engine_cb(audio_rec_evt_t *event, void *user_data) function

```
   static esp_err_t rec_engine_cb(audio_rec_evt_t *event, void *user_data)
   {
       if (AUDIO_REC_WAKEUP_START == event->type) {
           ESP_LOGI(TAG, "rec_engine_cb - AUDIO_REC_WAKEUP_START");
           if (dueros_service_state_get() == SERVICE_STATE_RUNNING) {
               dueros_voice_cancel(duer_serv_handle);
           }
           if (duer_audio_wrapper_get_state() == AUDIO_STATUS_RUNNING) {
               duer_audio_wrapper_pause();
           }
           display_service_set_pattern(disp_serv, DISPLAY_PATTERN_TURN_ON, 0);
           ESP_LOGI(TAG, "rec_engine_cb - Play tone");
           //aaron change
           //duer_dcs_audio_sync_play_tone("file://sdcard/dingding.wav");
           duer_dcs_audio_sync_play_tone(tone_uri[TONE_TYPE_DINGDING]);
           
       } else if (AUDIO_REC_VAD_START == event->type) {
           ESP_LOGI(TAG, "rec_engine_cb - AUDIO_REC_VAD_START");
           audio_service_start(duer_serv_handle);
           xEventGroupSetBits(duer_evt, DUER_REC_READING);
       } else if (AUDIO_REC_VAD_END == event->type) {
           xEventGroupClearBits(duer_evt, DUER_REC_READING);
           if (dueros_service_state_get() == SERVICE_STATE_RUNNING) {
               audio_service_stop(duer_serv_handle);
           }
           ESP_LOGI(TAG, "rec_engine_cb - AUDIO_REC_VAD_STOP, state:%d", dueros_service_state_get());
       } else if (AUDIO_REC_WAKEUP_END == event->type) {
           if (dueros_service_state_get() == SERVICE_STATE_RUNNING) {
               audio_service_stop(duer_serv_handle);
           }
           display_service_set_pattern(disp_serv, DISPLAY_PATTERN_TURN_OFF, 0);
           ESP_LOGI(TAG, "rec_engine_cb - AUDIO_REC_WAKEUP_END");
       } else {
   
       }
   
       return ESP_OK;
   }
   
 ```
   

5. Modified partitions_dueros_example_esp32s3.csv and added flash_tone data 0x04  （Blank space）   0xc800
6. Compile and download

The program keeps rebooting. The print is as follows

----------------------------- ESP Audio Platform -----------------------------
|                                                                            |
|                       ESP_AUDIO-v1.8.0-017893b-9815982                     |
|                     Compile date: Aug 15 2024-04:10:00                     |
------------------------------------------------------------------------------
I (11344) ESP_AUDIO_CTRL: Func:media_ctrl_create, Line:355, MEM Total:16865715 Bytes, Inter:183051 Bytes, Dram:183051 Bytes, Dram largest free:172032Bytes

I (11354) AUDIO_HAL: Codec mode is 3, Ctrl:1
I (11364) AUDIO_THREAD: The player_task task allocate stack on external memory
W (11374) I2S: APLL not supported on current chip, use I2S_CLK_D2CLK as default clock source
I (11374) I2S: DMA Malloc info, datalen=blocksize=2400, dma_buf_count=3
I (11384) I2S: DMA Malloc info, datalen=blocksize=2400, dma_buf_count=3
I (11394) I2S: I2S0, MCLK output by GPIO2
I (11394) MP3_DECODER: MP3 init
I (11404) AUDIO_WRAPPER: Func:duer_audio_setup_player, Line:198, MEM Total:16838455 Bytes, Inter:162879 Bytes, Dram:162879 Bytes, Dram largest free:151552Bytes

I (11414) AUDIO_WRAPPER: esp_audio instance is:0x3d015ed0
E (11424) I2S: register I2S object to platform failed
I (11424) I2S: I2S0, MCLK output by GPIO2
I (11434) AUDIO_PIPELINE: link el->rb, el:0x3d018db4, tag:i2s, rb:0x3d0191c8
I (11444) AUDIO_PIPELINE: link el->rb, el:0x3d019080, tag:tone, rb:0x3d01b210
I (11444) AUDIO_THREAD: The i2s task allocate stack on internal memory
I (11454) AUDIO_ELEMENT: [i2s-0x3d018db4] Element task created
I (11464) AUDIO_ELEMENT: [raw-0x3d018ee4] Element task created
I (11464) AUDIO_THREAD: The tone task allocate stack on internal memory
I (11474) AUDIO_ELEMENT: [tone-0x3d019080] Element task created
I (11484) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:16809395 Bytes, Inter:153107 Bytes, Dram:153107 Bytes, Dram largest free:143360Bytes

I (11494) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (11504) AUDIO_ELEMENT: [tone] AEL_MSG_CMD_RESUME,state:1
I (11514) TONE_PARTITION: tone partition format 1, total 1
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x40057143  PS      : 0x00060b30  A0      : 0x82014964  A1      : 0x3fcc5b90  
A2      : 0x0000000d  A3      : 0x0000005f  A4      : 0x0000dfac  A5      : 0x00060523  
A6      : 0x00060523  A7      : 0x00000001  A8      : 0x8200b050  A9      : 0x3fcc5b70  
A10     : 0x00000001  A11     : 0xffffffff  A12     : 0x3c12a4e4  A13     : 0x00002cfa  
A14     : 0x3c12a31c  A15     : 0x3fcc5af0  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x0000000d  LBEG    : 0x400556d5  LEND    : 0x400556e5  LCOUNT  : 0xfffffffc  


Backtrace: 0x40057140:0x3fcc5b90 |<-CORRUPTED




ELF file SHA256: 8992d4d0bcebfc19

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x2a (SPI_FAST_FLASH_BOOT)
Saved PC:0x40379b74
0x40379b74: esp_restart_noos at /home/aaron/esp/esp-adf/esp-idf/components/esp_system/port/soc/esp32s3/system_internal.c:151 (discriminator 1)

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x179c
load:0x403c9700,len:0xe78
load:0x403cc700,len:0x317c
entry 0x403c9980
I (19) boot: ESP-IDF v4.4.4-278-g3c8bc2213c-dirty 2nd stage bootloader
I (19) boot: compile time 10:31:17
I (19) boot: chip revision: v0.2
I (23) qio_mode: Enabling QIO for flash chip GD
I (28) boot.esp32s3: Boot SPI Speed : 80MHz
I (33) boot.esp32s3: SPI Mode       : QIO
I (37) boot.esp32s3: SPI Flash Size : 8MB
I (42) boot: Enabling RNG early entropy source...
I (48) boot: Partition Table:
I (51) boot: ## Label            Usage          Type ST Offset   Length
I (59) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (66) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (73) boot:  2 factory          factory app      00 00 00010000 00310000
I (81) boot:  3 model            Unknown data     01 82 00320000 0040e000
I (88) boot:  4 flash_tone       NVS keys         01 04 0072e000 0000c800
I (96) boot: End of partition table
I (100) esp_image: segment 0: paddr=00010020 vaddr=3c120020 size=4d420h (316448) map
I (156) esp_image: segment 1: paddr=0005d448 vaddr=3fc9ad30 size=02bd0h ( 11216) load
I (159) esp_image: segment 2: paddr=00060020 vaddr=42000020 size=11ed5ch (1174876) map
I (340) esp_image: segment 3: paddr=0017ed84 vaddr=3fc9d900 size=03a90h ( 14992) load
I (343) esp_image: segment 4: paddr=0018281c vaddr=40378000 size=12d28h ( 77096) load
I (369) boot: Loaded app from partition at offset 0x10000
I (369) boot: Disabling RNG early entropy source...
I (381) opi psram: vendor id : 0x0d (AP)
I (381) opi psram: dev id    : 0x03 (generation 4)
I (381) opi psram: density   : 0x05 (128 Mbit)
I (385) opi psram: good-die  : 0x01 (Pass)
I (389) opi psram: Latency   : 0x01 (Fixed)
I (394) opi psram: VCC       : 0x00 (1.8V)
I (399) opi psram: SRF       : 0x01 (Fast Refresh)
I (404) opi psram: BurstType : 0x01 (Hybrid Wrap)
I (410) opi psram: BurstLen  : 0x01 (32 Byte)
I (415) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (421) opi psram: DriveStrength: 0x00 (1/1)
I (426) spiram: Found 128MBit SPI RAM device
I (431) spiram: SPI RAM mode: sram 80m
I (435) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (442) cpu_start: Pro cpu up.
I (446) cpu_start: Starting app cpu, entry point is 0x40379428
0x40379428: call_start_cpu1 at /home/aaron/esp/esp-adf/esp-idf/components/esp_system/port/cpu_start.c:148

I (438) cpu_start: App cpu up.
I (1016) spiram: SPI SRAM memory test OK
I (1025) cpu_start: Pro cpu start user code
I (1025) cpu_start: cpu freq: 240000000
I (1025) cpu_start: Application information:
I (1028) cpu_start: Project name:     esp_dueros
I (1033) cpu_start: App version:      970300b-dirty
I (1039) cpu_start: Compile time:     Sep  3 2024 14:21:09
I (1045) cpu_start: ELF file SHA256:  8992d4d0bcebfc19...
I (1051) cpu_start: ESP-IDF:          v4.4.4-278-g3c8bc2213c-dirty
I (1058) cpu_start: Min chip rev:     v0.0
I (1063) cpu_start: Max chip rev:     v0.99 
I (1068) cpu_start: Chip rev:         v0.2
I (1072) heap_init: Initializing. RAM available for dynamic allocation:
I (1080) heap_init: At 3FCA6108 len 00043608 (269 KiB): D/IRAM
I (1086) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DIRAM
I (1093) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (1099) spiram: Adding pool of 16384K of external SPI memory to heap allocator
I (1108) spi_flash: detected chip: gd
I (1112) spi_flash: flash io: qio
W (1116) spi_flash: Detected size(16384k) larger than the size in the binary image header(8192k). Using the size in the binary image header.
I (1129) sleep: Configure to isolate all GPIO pins in sleep state
I (1136) sleep: Enable automatic switching of GPIO sleep configuration
I (1143) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (1154) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (1174) DUEROS: ADF version is v2.6-167-ge27cd526-dirty
E (1174) DISPATCHER: exe first list: 0x0
I (1174) AUDIO_THREAD: The esp_dispatcher task allocate stack on internal memory
I (1174) DISPATCHER: dispatcher_event_task is running...
I (1194) DRV8311: ES8311 in Slave mode
I (1204) gpio: GPIO[46]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
W (1214) I2C_BUS: I2C bus has been already created, [port:0]
I (1214) ES7210: ES7210 in Slave mode
I (1224) ES7210: Enable ES7210_INPUT_MIC1
I (1234) ES7210: Enable ES7210_INPUT_MIC2
I (1234) ES7210: Enable ES7210_INPUT_MIC3
W (1234) ES7210: Enable TDM mode. ES7210_SDP_INTERFACE2_REG12: 2
I (1244) ES7210: config fmt 60
I (1244) AUDIO_THREAD: The esp_periph task allocate stack on external memory
I (1254) gpio: GPIO[0]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 
I (1264) gpio: GPIO[1]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 
I (1274) AUDIO_THREAD: The wifi_serv task allocate stack on external memory
I (1274) pp: pp rom version: e7ae62f
I (1284) net80211: net80211 rom version: e7ae62f
I (1294) wifi:wifi driver task: 3fcaf168, prio:23, stack:6656, core=0
I (1294) system_api: Base MAC address is not set
I (1294) system_api: read default base MAC address from EFUSE
I (1304) wifi:wifi firmware version: bd1de02
I (1304) wifi:wifi certification version: v7.0
I (1314) wifi:config NVS flash: enabled
I (1314) wifi:config nano formating: disabled
I (1324) wifi:Init data frame dynamic rx buffer num: 32
I (1324) wifi:Init management frame dynamic rx buffer num: 32
I (1334) wifi:Init management short buffer num: 32
I (1334) wifi:Init static tx buffer num: 16
I (1334) wifi:Init tx cache buffer num: 32
I (1344) wifi:Init static tx FG buffer num: 2
I (1344) wifi:Init static rx buffer size: 1600
I (1354) wifi:Init static rx buffer num: 16
I (1354) wifi:Init dynamic rx buffer num: 32
I (1354) wifi_init: rx ba win: 16
I (1364) wifi_init: tcpip mbox: 32
I (1364) wifi_init: udp mbox: 6
I (1374) wifi_init: tcp mbox: 6
I (1374) wifi_init: tcp tx win: 5744
I (1374) wifi_init: tcp rx win: 5744
I (1384) wifi_init: tcp mss: 1440
I (1384) wifi_init: WiFi/LWIP prefer SPIRAM
I (1394) phy_init: phy_version 540,a5d905b,Oct 20 2022,19:36:11
I (1434) wifi:mode : sta (74:4d:bd:2e:86:bc)
I (1434) wifi:enable tsf
I (1110,tid:3fcbdb70) lightduer_session.c(  44): random = 75933
W (11274) AUDIO_BOARD: The board has already been initialized!
W (11274) WIFI_SSID_MANAGER: There is no ssid stored in flash, please save ssids to flash first
W (11274) WIFI_SERV: No ssid stored in flash, try to connect to wifi set by wifi_service_set_sta_info()
I (11284) WIFI_SERV: Connect to wifi ssid: TWGJ-Wireless-XNY, pwd: XnY!5716
I (11294) AUDIO_THREAD: The media_task task allocate stack on external memory
I (11304) ESP_AUDIO_TASK: media_ctrl_task running...,0x3d015ed0


Is my modification correct? Is there anything missing? Why do they keep rebooting?

**Comment by shootao** [comment]
@AaronPMM 
Please apply the attached patch:
1. Support ESP-Box wake-up.
2. Support playing prompt sounds without an SD card.
[dueros_support_box_without_sdcard.zip](https://github.com/user-attachments/files/16862764/dueros_support_box_without_sdcard.zip)
