### ISSUE TITLE
如何更新 esp-adf 中的 ESP-IDF (AUD-5673)

### ISSUE THREAD

**Issue by AaronPMM** [espressif/esp-adf#1268]
我这边移植 esp-box 的部分功能，但是提示 ESP-IDF 本版过低，打算更新 esp-idf ，请问如何更新 esp-idf？直接从github 上下载 esp-idf 然后替换吗？

**Comment by shootao** [comment]
@AaronPMM 
直接在 esp-adf/esp-idf ,执行 git checkout <your commit/branch> 就可以了
