### ISSUE TITLE
Crash in callback function when mp3decoder's stack is allocated in PSRAM (AUD-5688)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-adf#1273]
A callback function is defined for mp3decoder.  if stack_in_ext is set to true, then crash will happen in the callback function when "fread" is called. Setting stack_in_ext to false solves the problem. Is this expected? why?

ESP32S3
IDF 5.2.2
ADF (not found a version number, but it is pretty updated)

![image](https://github.com/user-attachments/assets/b9ba0752-4d86-4dc8-b004-077b49b29a57)

**Comment by jason-mao** [comment]
@mike-2020 Please provide the crashed log

**Comment by shootao** [comment]
@mike-2020 
I think your `mp3DecoderReacCb` must get data from flash.
For ESP32/ESP32S3, we cannot read or write flash data in a task running on the PSRAM stack.

**Comment by jason-mao** [comment]
This topic has become inactive, so I'm closing the issue. Please reopen it if you have any questions or need any further assistance.
