### ISSUE TITLE
刷入编译play_mp3刷入开发机提示错误，怎么回事

### ISSUE THREAD

**Issue by xzg1983** [espressif/esp-adf#128]
I (5236) BAIDU_SPEECH_EXAMPLE: [ 1 ] Start audio codec chip
I (5236) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 
E (5246) gpio: gpio_install_isr_service(394): GPIO isr service already installed
E (5256) ES8388_DRIVER: es_write_reg error
E (5256) ES8388_DRIVER: es_write_reg error
E (5266) ES8388_DRIVER: es_write_reg error
E (5266) ES8388_DRIVER: es_write_reg error
E (5276) ES8388_DRIVER: es_write_reg error
E (5276) ES8388_DRIVER: es_write_reg error
E (5286) ES8388_DRIVER: es_write_reg error
E (5286) ES8388_DRIVER: es_write_reg error
E (5296) ES8388_DRIVER: es_write_reg error
E (5296) ES8388_DRIVER: es_write_reg error
E (5306) ES8388_DRIVER: es_write_reg error
E (5306) ES8388_DRIVER: es_write_reg error
E (5316) ES8388_DRIVER: es_write_reg error
E (5316) ES8388_DRIVER: es_write_reg error
E (5326) ES8388_DRIVER: es_write_reg error
E (5326) ES8388_DRIVER: es_write_reg error
E (5326) ES8388_DRIVER: es_write_reg error
E (5336) ES8388_DRIVER: es_write_reg error
E (5336) ES8388_DRIVER: es_write_reg error
E (5346) ES8388_DRIVER: es_write_reg error
E (5346) ES8388_DRIVER: es_write_reg error
E (5356) ES8388_DRIVER: es_write_reg error
E (5356) ES8388_DRIVER: es_write_reg error
E (5366) ES8388_DRIVER: es_write_reg error
E (5366) ES8388_DRIVER: es_write_reg error
I (5376) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (5386) ES8388_DRIVER: init,out:02, in:00
E (5386) AUDIO_HAL: codec init failed!

这是怎么回事，是GPIO配置错了吗？

**Comment by jason-mao** [comment]
@xzg1983 看你的log信息`E (5366) ES8388_DRIVER: es_write_reg error`, 这个是Lyrat-V4.3 板子的打印， 你用的是什么开发板？
