### ISSUE TITLE
demo中使用的mp3文件是使用专用的软件合成的吗？

### ISSUE THREAD

**Issue by Hynsn** [espressif/esp-adf#130]
你好，我有在学习adf，不是很清楚这部分为什么需要这样做。
```
extern const uint8_t adf_music_mp3_start[] asm("_binary_adf_music_mp3_start");
extern const uint8_t adf_music_mp3_end[]   asm("_binary_adf_music_mp3_end");
```
我猜测是demo中附带mp3文件是你们自己合成的，但我用文本分析mp3文件格式看不到相应的ASC字符串。我尝试替换了mp3文件(filename不变)，编译烧写进去之后播放是旧的mp3。请问该如何理解上面这部分。谢谢。

**Comment by jason-mao** [comment]
@Hynsn 在component.mk 的`COMPONENT_EMBED_TXTFILES` 会把对应文件在编译的时候生成二进制，然后asm("_binary_adf_music_mp3_start");可以获取到文件的起始地址。你的情况可能是替换文件后没有make clean导致的。

**Comment by Hynsn** [comment]
的确是这样，谢谢！
