### ISSUE TITLE
Play audio on two channels (AUD-5816)

### ISSUE THREAD

**Issue by GCTechnology** [espressif/esp-adf#1305]
Hi, I am using an ESP32S3 module to develop a project with dual channel audio output. What I mean is using the two I2S interfaces to connect two codecs separately and output audio independently.
So I'd like to know if it is possible to use the current ADF library's 'audio_pipeline' audio player to implement the feature? It would be even better if there were corresponding examples.
![图片](https://github.com/user-attachments/assets/6ac215a2-f20f-4805-8c39-f4522d21daee)

**Comment by jason-mao** [comment]
@GCTechnology Is your audio in stereo? If yes, I think you should implement an element to change the interleave audio to un-interleave audio， then put the un-interleave audio into two I2S streams.

**Comment by GCTechnology** [comment]
> @GCTechnology Is your audio in stereo? If yes, I think you should implement an element to change the interleave audio to un-interleave audio， then put the un-interleave audio into two I2S streams.

Ah, I almost forget this issue I pushed. I have successfully implemented this feature by modifying example 'play_mp3_control'.
Thanks for your reply.
