### ISSUE TITLE
Based on ESP-C5 series, ADF scheme（ESP - C5 -Devkitc-1） (AUD-5835)

### ISSUE THREAD

**Issue by Lin-Mu-Mu2000** [espressif/esp-adf#1307]
There is currently no C5-related audio development board on the market. Is there any way to configure Devkitc-1

**Comment by TempoTian** [comment]
You can use following script to fast generate one for you after change json config.
https://github.com/espressif/esp-adf/issues/997#issuecomment-2418345704

**Comment by Lin-Mu-Mu2000** [comment]
Thank you for sharing, the script can be used, thank you very much
