### ISSUE TITLE
udp stream (AUD-5860)

### ISSUE THREAD

**Issue by davidHuW** [espressif/esp-adf#1316]
hi，
do you have any plan for udp stream just like tcp_stream or http_stream？
thanks

**Comment by TempoTian** [comment]
http stream have standard so can just follow the standard and do the realization. UDP is suitable to transfer customized data, and there is no standard to define how the data orgnized. So I prefer user to realize it by himself.

**Comment by davidHuW** [comment]
close as not planned

**Comment by davidHuW** [comment]
close as not planned
