### ISSUE TITLE
PAUSE WORK BUT RESUME ERROR (AUD-5872)

### ISSUE THREAD

**Issue by hoanganh1911** [espressif/esp-adf#1318]
I am currently having the following error, when I press the button, my circuit will pause, but when I press it again, the following error message appears, I think it will resume, I developed from the original example play_sdcard_mp3_control. Thank you for your help.![IMG_20241116_005453.jpg](https://github.com/user-attachments/assets/315e2b83-3038-4a7f-a9dc-d4da9f8335e3)

**Comment by hoanganh1911** [comment]
I am currently having the following error, when I press the button, my circuit will pause, but when I press it again, the following error message appears, I think it will resume, I developed from the original example play_sdcard_mp3_control. Thank you for your help.![IMG_20241116_005453.jpg](https://github.com/user-attachments/assets/93862049-c72b-4360-b4ee-e75d781e5c5e)

**Comment by JokerChow** [comment]
having same issue. keep watching.

**Comment by ShaoMingya** [comment]
应该是版本问题，之前可以。我最近更新了一下，发现这个问题了。

**Comment by jason-mao** [comment]
Thanks for your report, let's check and fix it.

**Comment by ShaoMingya** [comment]
好像是 adf 此次提交后的问题：6d9c46cccd884df478db3a6e15b85e91359c76b7
切换到d16b0401cc805e184b132aa6c821eccd26163f61后正常。
`git checkout d16b0401cc805e184b132aa6c821eccd26163f61`
`git submodule update --init --recursive`

**Comment by JokerChow** [comment]
[ShaoMingya](https://github.com/ShaoMingya), 

Thank you, it works now.

**Comment by majingjing123** [comment]
Already fix this bug. You can checkout ADF to commit id: 93a56fcddcabe3be856df547fbc2db566ee2f740.
