### ISSUE TITLE
DLNA不支持手机端的酷狗音乐/QQ音乐 (AUD-584)

### ISSUE THREAD

**Issue by 84506232** [espressif/esp-adf#132]
如题，官方有更新计划吗？

**Comment by jason-mao** [comment]
问题已知悉，后续会修复。

**Comment by ahhfzhang** [comment]
QQ音乐新版去掉DLNA功能了，变为私有化的Qplay，酷狗音乐也把DLNA私有化为酷狗play，都为非开源协议，目前只有QQ音乐或者酷狗音乐认证的设备才支持的协议，抱歉目前暂无法支持到，您可以尝试使用网易云音乐的DLNA功能来测试。
