### ISSUE TITLE
请问是否有支持 ESP32-S3-Korvo-1 开发板的计划？ (AUD-5939)

### ISSUE THREAD

**Issue by iysheng** [espressif/esp-adf#1331]
我想开发音频相关的应用，选择的时 ESP32-S3-Korvo-1 开发板，请问 esp-adf 是否有支持 ESP32-S3-Korvo-1 的计划？

**Comment by jason-mao** [comment]
这个目前没有， ESP32-S3-Korvo-1 和 ESP32-S3-Korvo-2 差别不大，您可以参考components/audio_board/esp32_s3_korvo2_v3添加ESP32-S3-Korvo-1。
