### ISSUE TITLE
关于挂载SPIFFS失败后导致的系统崩溃 (AUD-5940)

### ISSUE THREAD

**Issue by PoohWoah** [espressif/esp-adf#1332]
我用的是ADF的例子（WWE语音唤醒），因为我没有SD卡，所以我准备使用Spiffs去挂载一个文件系统方便去使用，目前挂载文件系统后会报错
assert failed: spi_flash_disable_interrupts_caches_and_other_cpu cache_utils.c:159 (esp_task_stack_is_sane_cache_disabled())

上网查了后发现于PSRAM有关，但是资源珍贵，我无法关闭PSRAM去进行操作。

idf版本：5.3.1
硬件：BOX_3
希望得到有效的回答，谢谢。

**Comment by jason-mao** [comment]
@PoohWoah WWE 的sdcard 是未开启的（VOICE2FILE=false），应该可以直接使用的。

**Comment by PoohWoah** [comment]
> @PoohWoah WWE 的sdcard 是未开启的（VOICE2FILE=false），应该可以直接使用的。

感谢回复，我想你理解错我的意思了，我实际并不想去使用sd卡，我是挂载虚拟的文件系统，目前我找到了原因，我的一个初始化在了外部psram，关闭掉就解决了问题。
