### ISSUE TITLE
切换音频输入的问题 (AUD-583)

### ISSUE THREAD

**Issue by ChiShaoJun** [espressif/esp-adf#136]
更新后，切换音频得到在esp-adf/components/audio_hal/board/include/board.h中更改。比如pipeline_passthru例程，想要它生效得把AUDIO_HAL_ADC_INPUT_LINE1更改成AUDIO_HAL_ADC_INPUT_LINE2。我觉得这种写死的做法不是很好。

**Comment by jason-mao** [comment]
谢谢你提出的意见。`audio_board_init`后续会完全由用户来定制化。
