### ISSUE TITLE
pipeline_amr_sdcard example not working

### ISSUE THREAD

**Issue by scruffynerf** [espressif/esp-adf#139]
latest revs of code... fresh git checkout, and other examples are working fine.

monitor shows:
I (180) REC_AMR_SDCARD: [1.0] Mount sdcard
and it just hangs there.

Running pipeline_wav_sdcard works perfectly, same SD card, same board (Lyra-T v4.3), same compiler/laptop/etc.

**Comment by jason-mao** [comment]
@scruffynerf Thanks for report this issue, we are fixing.
