### ISSUE TITLE
Typo? DEFAULT_ESP_PHERIPH_SET_CONFIG

### ISSUE THREAD

**Issue by sethcohn** [espressif/esp-adf#146]
This should be DEFAULT_ESP_PERIPH_SET_CONFIG()
Not PHERIPH

Found here (and in a number of examples):

https://docs.espressif.com/projects/esp-adf/en/latest/api-reference/peripherals/esp_peripherals.html

It's spelled differently from the other macros:

Macros
DEFAULT_ESP_PERIPH_STACK_SIZE
DEFAULT_ESP_PERIPH_TASK_PRIO
DEFAULT_ESP_PERIPH_TASK_CORE
DEFAULT_ESP_PHERIPH_SET_CONFIG()
periph_tick_get

intentional?  Or just a typo that's not been fixed?

**Comment by jason-mao** [comment]
@sethcohn It's a typo.Thanks for your report.
