### ISSUE TITLE
蓝牙PERIPH_BLUETOOTH_AUDIO_SUSPENDED事件触发的不及时

### ISSUE THREAD

**Issue by ChiShaoJun** [espressif/esp-adf#149]
请教下，当我手机播放音乐时，按下暂停键，esp32要超过几秒钟才触发蓝牙外设PERIPH_BLUETOOTH_AUDIO_SUSPENDED事件。是手机音乐处理的机制还是esp32蓝牙音频的处理问题？

**Comment by esp-xiaodong** [comment]
hi @ChiShaoJun ：
一般手机在手机ui上按暂停后，还会送2s左右的a2dp音频包，之后才会送suspend上来，esp32也是收到该suspend之后才会cb通知。

**Comment by ChiShaoJun** [comment]
@esp-xiaodong 感谢解答
