### ISSUE TITLE
Old IDF

### ISSUE THREAD

**Issue by glennhuber** [espressif/esp-adf#150]
When are you going to update the associated/embedded IDF. I need the latest MDF stuff along with ADF.
Thanks.

**Comment by jason-mao** [comment]
@glennhuber  Which IDF version did you used ? we have plan to update IDF to 3.2.

**Comment by couperyork** [comment]
+1 Be great to have the recently released v3.2 esp-idf version @jason-mao. What would be your projected estimated delivery time for that?

**Comment by glennhuber** [comment]
3.2 would be great!!! Do you have an ETA on that?

**Comment by HumamHelfawi** [comment]
3.2-rc has a great fix to the mbedtls memory problem (spiram). It would be great if we moved to 3.2-rc or later. The current submodule version of esp-idf is buggy if you are https client & mqtt in the same time.

**Comment by jason-mao** [comment]
Hi guys

We are working on this.  Most of the features and examples should be supported on this week.

**Comment by glennhuber** [comment]
Any status updates? ETA (Estimated Time of Arrival)?

**Comment by jason-mao** [comment]
@glennhuber @couperyork @HumamHelfawi IDF 3.2 has been supported on 4164305c718fcd7225a86dd3665858305239f4fa.
