### ISSUE TITLE
整个ADF框架依然不可用，这个问题不打算解决了？

### ISSUE THREAD

**Issue by coollofty** [espressif/esp-adf#151]
我现在用的是以前clone下来的框架，整个项目开发已经基本结束了，但是看到新版ADF解决了一些Bug，于是做了git pull和git submodule update，然后就不能再编译了，错误如下：

E:/esp32/esp-adf/esp-idf/make/project.mk:405: *** 多个目标匹配。 停止。

请注意这个前提：现在用的是好好的，只需要git pull一下，就会出上面的错误，不要拿出IDF/ADF配置教程来说事，我发的不是新手问题。上一次发出这个问题是至少一个星期前了，有一些人也碰到和我完全相同的情况。只要不更新，就可以继续用，一更新就再也编译不了任何工程。请看我上一个发的同样的issue，也有几个人遇到了相同的情况，是否应该解决一下了？

**Comment by jason-mao** [comment]
It's same with #143 .
