### ISSUE TITLE
es8374_set_voice_volume and es8374_config_i2s compilation error

### ISSUE THREAD

**Issue by maxgerhardt** [espressif/esp-adf#158]
When attempting to compile `es8374.c`, it fails because the function `es8374_set_voice_volume()` does not exist and is never declared. 

https://github.com/espressif/esp-adf/blob/316f6f77b1ee249004e09d1d6506abf0ba59aa85/components/audio_hal/driver/es8374/es8374.c#L731

However, `es8374_codec_set_voice_volume` exists:

https://github.com/espressif/esp-adf/blob/316f6f77b1ee249004e09d1d6506abf0ba59aa85/components/audio_hal/driver/es8374/es8374.c#L591-L606

The same for the call 

https://github.com/espressif/esp-adf/blob/316f6f77b1ee249004e09d1d6506abf0ba59aa85/components/audio_hal/driver/es8374/es8374.c#L758

But the function `es8374_codec_config_i2s` exists

https://github.com/espressif/esp-adf/blob/316f6f77b1ee249004e09d1d6506abf0ba59aa85/components/audio_hal/driver/es8374/es8374.c#L769-L783

If this is a bug, please fix it. Otherwise ESP-ADF is not compilable.

```
lib\audio_hal\driver\es8374\es8374.c: In function 'es8374_init_reg':
lib\audio_hal\driver\es8374\es8374.c:731:12: error: implicit declaration of function 'es8374_set_voice_volume' [-Werror=implicit-function-declaration]
res |= es8374_set_voice_volume(0);
^
lib\audio_hal\driver\es8374\es8374.c: In function 'es8374_codec_init':
lib\audio_hal\driver\es8374\es8374.c:758:12: error: implicit declaration of function 'es8374_config_i2s' [-Werror=implicit-function-declaration]
res |= es8374_config_i2s(cfg->codec_mode, &(cfg->i2s_iface));
^
```

**Comment by ichenxing** [comment]
@maxgerhardt have a try such as:
```
res |= es8374_set_voice_volume(0);  → res |= es8374_codec_set_voice_volume(0);

res |= es8374_config_i2s(cfg->codec_mode, &(cfg->i2s_iface));  → res |= es8374_codec_config_i2s(cfg->codec_mode, &(cfg->i2s_iface)); 
```

**Comment by maxgerhardt** [comment]
Yeah, that's the exact fix that I proposed which works.

**Comment by withdra** [comment]
@maxgerhardt 
This is a mistake we introduced when we updated the version. Because the new version did not use 8374, its compilation was omitted. If you need to use 8374, you first need to include 8374 related files in component.mk file, and there are compilation errors in the current version, which can be used normally after modification according to the prompt. We have fixed this problem and will release it in a new version.
