### ISSUE TITLE
New board/codec (AC101) support

### ISSUE THREAD

**Issue by glennhuber** [espressif/esp-adf#162]
There is a module with an integrated AC101 codec, A.I. Thinker ESP32-A1S. Do you have plans to add support for this board/codec? If not, can you offer some guidance. Maybe interfaces  that need to be implemented, block diagrams and file layout? I'm sure I can figure it out but any assistance you can provide would be greatly appreciated.  

Keep up the good work!!!

**Comment by vikramdattu** [comment]
Related PR: https://github.com/espressif/esp-adf/pull/11
