### ISSUE TITLE
Support signal messenger protocol (AUD-620)

### ISSUE THREAD

**Issue by renne** [espressif/esp-adf#17]
The [Signal Protocol C Library](https://github.com/signalapp/libsignal-protocol-c) is a C-implementation of the [Signal protocol](https://en.wikipedia.org/wiki/Signal_(software)) used by the [Signal messenger](https://signal.org/) from Whisper Systems. Adding this with WebRTC/Opus as sink/source to the ESP-ADF would allow to stream audio/video securely and in high quality between the ESP32 and the Signal messenger on Smartphones and Desktops (e.g. ESP32 as door station, ...).

**Comment by tuanpmt** [comment]
Thank you for the suggestion about this useful protocol, We will note as a new feature request and find out the capabilities of ESP32 and ADF for this protocol.

**Comment by rdehuyss** [comment]
+1! Would buy one right now if there would be webrtc support.

**Comment by sosaucily** [comment]
Would be a nice replacement for the SIP systems, which are very complex and difficult to support widely.

**Comment by sosaucily** [comment]
Seems Amazon has a tech that is working with it's [Kenesis](https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/what-is-kvswebrtc.html) tech.

https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-c.html

If anyone gets this working on espressif hardware that would be interesting. Would love to see that.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
