### ISSUE TITLE
请问在使用dueros上，在dueros云端服务器添加了数据点后，在example上需要如何添加自己创建的数据点信息和注册回调函数？

### ISSUE THREAD

**Issue by xiaoyeYear** [espressif/esp-adf#178]
请问在使用dueros上，在dueros云端服务器添加了数据点后，在example上需要如何添加自己创建的数据点信息和注册回调函数？
研究了好久没发现有相关API，望指教

**Comment by jason-mao** [comment]
@xiaoyeYear 参考https://github.com/espressif/esp-adf/issues/145

**Comment by xiaoyeYear** [comment]
收到，谢谢
