### ISSUE TITLE
/esp-adf/components/audio_service/bluetooth_service.c:435 (bluetooth_service_start): enable controller failed

### ISSUE THREAD

**Issue by ChiShaoJun** [espressif/esp-adf#179]
use esp-adf/examples/player/pipeline_bt_sink demo error.
error log:
```
E (249) BLUETOOTH_SERVICE: /home/kyle/esp/esp-adf/components/audio_service/bluetooth_service.c:435 (bluetooth_service_start): enable controller failed
```
esp_bt_controller_enable failed.How to solve this problem?

**Comment by esp-xiaodong** [comment]
You should check esp_bt_controller_enable() function in bluetooth_service_start(). Its parameter should be same with the menuconfig.(bluetooth->bluetooth controller->bluetooth controller mode). You can use br/edr only.

**Comment by ChiShaoJun** [comment]
It's OK.Thank you for your help.
