### ISSUE TITLE
esp32接miot平台，小爱鉴权问题 (AUD-573)

### ISSUE THREAD

**Issue by fuhongyu321** [espressif/esp-adf#182]
我现在遇到的问题是：
   模块要用到小爱鉴权，在miot的sdk里有miot鉴权，需要米家的token和session ID，我想问下连接上miot后，怎么拿到token和session ID呢？

   模块是：ESP-WROOM-32D Wi-Fi蓝牙双模模组
   系统是：freertos

**Comment by xuhongv** [comment]
- 小米文档不是提到了吗

**Comment by fuhongyu321** [comment]
能告诉我是哪个文档吗？还有关于米家接入esp32的api的文档是哪个呀，我只能看到关于蓝牙的API的接口文档mijia_ble_api，看不到关于WiFi连接的

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
