### ISSUE TITLE
fatal error: Periph_adc_button.h: No such file or directory

### ISSUE THREAD

**Issue by ineedsomehelp** [espressif/esp-adf#185]
When I compile ESP-ADF example ‘play_mp3’，i met this issue。
fatal error: Periph_adc_button.h: No such file or directory
compilation terminated.
~/make/component_wrapper.mk:285: recipe for target 'lyratd_msc_v2_2/board.o' failed
make[1]: *** [lyratd_msc_v2_2/board.o] Error 1
~/make/project.mk:530: recipe for target 'component-audio_board-build' failed

**Comment by Yuvaraj4041** [comment]
You need to fetch all submodules by run this command **git submodule update --init**

**Comment by jason-mao** [comment]
@ineedsomehelp There is a bug, should be "periph_adc_button.h" at components/audio_board/lyratd_msc_v2_2/board.c and components/audio_board/lyratd_msc_v2_1/board.c.

**Comment by jason-mao** [comment]
Has been fixed on ff29502c4b8c6c9dbdc95bb57acf3715aab6a8bb
