### ISSUE TITLE
Using ESP-ADF with Arduino

### ISSUE THREAD

**Issue by HumamHelfawi** [espressif/esp-adf#19]
Hi,
Is it possible to use ESP-ADF from Arudino IDE with other Arduino libraries? I used to use ESP-IDF from Arduino IDE. However, I could not find any documentation about using ESP-ADF from Arduino.

**Comment by tuanpmt** [comment]
I think the better way to use ADF with Arduino is using Arduino for ESP32 as IDF component: https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md

It means that you can compile examples of the current ADF, and add Arduino features, libraries to ADF application.

**Comment by HumamHelfawi** [comment]
@tuanpmt Thanks for your reply! Yes this the only way it worked with me.

**Comment by unltdsoul** [comment]
I am trying to use Arduino as component of ADF - but only get errors - I have successfully used Arduino as component of IDF.  
Errors I get:  
execvp: xtensa-esp32-elf-gcc: Argument list too long
make[1]: *** [/home/ameyatma/esp/esp-adf/esp-idf/make/component_wrapper.mk:274: cores/esp32/libb64/cencode.o] Error 127
make: *** [c:/msys32/home/ameyatma/esp/esp-adf/esp-idf/make/project.mk:450: component-arduino-build] Error 2

I have reloaded in ADF - i can build without Arduino, or can use Arduino as component of IDF, but, not with ADF -  any idea?

**Comment by mgsscorr1** [comment]
From what ive seen on another forum is that ESP has no plan to make ADF compatibly with Arduino, but seems like the guys above^^^ have found a slight work around

**Comment by HumamHelfawi** [comment]
> I am trying to use Arduino as component of ADF - but only get errors - I have successfully used Arduino as component of IDF.
> Errors I get:
> execvp: xtensa-esp32-elf-gcc: Argument list too long
> make[1]: *** [/home/ameyatma/esp/esp-adf/esp-idf/make/component_wrapper.mk:274: cores/esp32/libb64/cencode.o] Error 127
> make: *** [c:/msys32/home/ameyatma/esp/esp-adf/esp-idf/make/project.mk:450: component-arduino-build] Error 2
> 
> I have reloaded in ADF - i can build without Arduino, or can use Arduino as component of IDF, but, not with ADF - any idea?

I have faced the same issue at some point while I was updating the version of AFD and Arduino. As far as I remember (I am note sure actually), the problem was that the Arduino version (commit actually) was compatible. So, you have to make sure that ADF, IDF and Arduni-esp32 commits you are using are the same the repos suggest in their sub-modules.

If you clone the last commit of each repo, it won't work.

**Comment by unltdsoul** [comment]
Thank, HumanHelfawi, I'll look into that when i get time, and will post here if successful letting others know how, or if, i got it to work.

**Comment by maharshi114** [comment]
Hey, @tuanpmt page not found in this comment, link: https://github.com/espressif/esp-adf/issues/19#issuecomment-395490888

Thank you.

**Comment by Droxx** [comment]
It's moved here: https://github.com/espressif/arduino-esp32/blob/master/docs/en/esp-idf_component.rst

**Comment by sheetaljain01** [comment]
Hi, have u completed successfully?
