### ISSUE TITLE
adf最新程序编译找不到头文件怎么解决(之前可以)？

### ISSUE THREAD

**Issue by ichenxing** [espressif/esp-adf#192]
![image](https://user-images.githubusercontent.com/9410660/59732525-389ea880-927d-11e9-9b6e-6af204292027.png)

![image](https://user-images.githubusercontent.com/9410660/59732582-78659000-927d-11e9-8b47-642db1024fb7.png)

头文件位于LibRel/include

**Comment by ichenxing** [comment]
好像和win10 ubuntu开发环境配置有关，在虚拟机上的ubunutu则可以编译通过

**Comment by jason-mao** [comment]
在有问题的环境上，IDF的example可以编译过吗？

**Comment by ichenxing** [comment]
编译了一下adf的example文件夹下的esp_dispatcher_dueros例程可以
