### ISSUE TITLE
node ‘’adc6ac1’’ compiles 'dueros' error

### ISSUE THREAD

**Issue by yqj2012** [espressif/esp-adf#195]
Hello, I am compiling the error when updating the code to the latest node ‘’adc6ac1’’. The log is as follows: 
/mnt/g/esp/esp-adf/components/esp-adf-libs/esp_sr/lib/libesp_wakenet.a(wakenet5_quantized.o):(.literal.model_init+0x0): undefined reference to `get_coeff_wakeNet5_model_quant'
collect2: error: ld returned 1 exit status
/mnt/g/esp/esp-adf/esp-idf/make/project.mk:460: recipe for target '/mnt/g/esp/esp-adf/dueros/build/esp_dueros.elf' failed
make: *** [/mnt/g/esp/esp-adf/dueros/build/esp_dueros.elf] Error 1

**Comment by yqj2012** [comment]
Just tried because the configuration is "Speech Recognition Configuration --->Wakeup word is Alexa" will be wrong, and configured as "Wakeup word is Hi Lexin" will not

**Comment by jason-mao** [comment]
@yqj2012 Alexa only support WakeNet3.

**Comment by yqj2012** [comment]
You can do this in the Kconfig file, and avoid the same mistakes that others will download and compile. Thank you.

**Comment by jason-mao** [comment]
Thank you mentioned that.
