### ISSUE TITLE
为什么在新版本中移除了对speex的计划支持？

### ISSUE THREAD

**Issue by flyoo** [espressif/esp-adf#198]
是speex移植后不能达到很好的效果？我现在在使用speex录音中出现采集效果很差的情况，是否跟移植有关系？

**Comment by jason-mao** [comment]
@flyoo 不是的。首先，DuerOS里面就已经提供和使用了Speex的接口，参见：components/clouds/dueros/lightduer/include/lightduer_speex.h
。这里把speex移除除了已经存在这个库之外，目前没有收到太多的需求，所以调低了优先级。如果您这边对这个有较高的依赖吗？

**Comment by flyoo** [comment]
是的，我这边主要在使用speex进行语音压缩处理，我会参考下duous里面的接口，谢谢回复
