### ISSUE TITLE
pipeline_http_mp3

### ISSUE THREAD

**Issue by Laxiyan** [espressif/esp-adf#2]
我使用pipeline_http_mp3这个例程可以正常播放【http://dl.espressif.com/dl/audio/adf_music.mp3】这个链接的MP3，当我把链接修改成：

audio_element_set_uri(http_stream_reader, "http://zhangmenshiting.qianqian.com/data2/music/bf160d8f4fb3bb924659f20a3b00f8b6/559184460/559184460.mp3?xcode=f4c51f4e425f5db748ae5c20176c0886");

出现以下错误:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5604
load:0x40078000,len:0
load:0x40078000,len:13724
entry 0x40078fb4
\0x1b[0;32mI (28) boot: ESP-IDF v3.0-rc1-243-gf851568 2nd stage bootloader\0x1b[0m
\0x1b[0;32mI (28) boot: compile time 15:56:25\0x1b[0m
\0x1b[0;32mI (30) boot: Enabling RNG early entropy source...\0x1b[0m
\0x1b[0;32mI (34) boot: SPI Speed      : 40MHz\0x1b[0m
\0x1b[0;32mI (38) boot: SPI Mode       : DIO\0x1b[0m
\0x1b[0;32mI (42) boot: SPI Flash Size : 4MB\0x1b[0m
\0x1b[0;32mI (46) boot: Partition Table:\0x1b[0m
\0x1b[0;32mI (49) boot: ## Label            Usage          Type ST Offset   Length\0x1b[0m
\0x1b[0;32mI (57) boot:  0 nvs              WiFi data        01 02 00009000 00006000\0x1b[0m
\0x1b[0;32mI (64) boot:  1 phy_init         RF data          01 01 0000f000 00001000\0x1b[0m
\0x1b[0;32mI (72) boot:  2 factory          factory app      00 00 00010000 00100000\0x1b[0m
\0x1b[0;32mI (79) boot: End of partition table\0x1b[0m
\0x1b[0;32mI (83) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x21754 (137044) map\0x1b[0m
\0x1b[0;32mI (140) esp_image: segment 1: paddr=0x0003177c vaddr=0x3ffb0000 size=0x03428 ( 13352) load\0x1b[0m
\0x1b[0;32mI (145) esp_image: segment 2: paddr=0x00034bac vaddr=0x40080000 size=0x00400 (  1024) load\0x1b[0m
\0x1b[0;32mI (147) esp_image: segment 3: paddr=0x00034fb4 vaddr=0x40080400 size=0x0b05c ( 45148) load\0x1b[0m
\0x1b[0;32mI (174) esp_image: segment 4: paddr=0x00040018 vaddr=0x400d0018 size=0x9a8b8 (633016) map\0x1b[0m
\0x1b[0;32mI (394) esp_image: segment 5: paddr=0x000da8d8 vaddr=0x4008b45c size=0x0f4d0 ( 62672) load\0x1b[0m
\0x1b[0;32mI (420) esp_image: segment 6: paddr=0x000e9db0 vaddr=0x400c0000 size=0x00000 (     0) load\0x1b[0m
\0x1b[0;32mI (435) boot: Loaded app from partition at offset 0x10000\0x1b[0m
\0x1b[0;32mI (436) boot: Disabling RNG early entropy source...\0x1b[0m
\0x1b[0;32mI (438) spiram: SPI RAM mode: flash 40m sram 40m\0x1b[0m
\0x1b[0;32mI (441) spiram: PSRAM initialized, cache is in low/high (2-core) mode.\0x1b[0m
\0x1b[0;32mI (448) cpu_start: Pro cpu up.\0x1b[0m
\0x1b[0;32mI (452) cpu_start: Starting app cpu, entry point is 0x400812e4\0x1b[0m
\0x1b[0;32mI (0) cpu_start: App cpu up.\0x1b[0m
\0x1b[0;32mI (1353) spiram: SPI SRAM memory test OK\0x1b[0m
\0x1b[0;32mI (1354) heap_init: Initializing. RAM available for dynamic allocation:\0x1b[0m
\0x1b[0;32mI (1354) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM\0x1b[0m
\0x1b[0;32mI (1360) heap_init: At 3FFB93B0 len 00026C50 (155 KiB): DRAM\0x1b[0m
\0x1b[0;32mI (1367) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM\0x1b[0m
\0x1b[0;32mI (1373) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM\0x1b[0m
\0x1b[0;32mI (1379) heap_init: At 4009A92C len 000056D4 (21 KiB): IRAM\0x1b[0m
\0x1b[0;32mI (1386) cpu_start: Pro cpu start user code\0x1b[0m
\0x1b[0;32mI (1391) spiram: Adding pool of 4096K of external SPI memory to heap allocator\0x1b[0m
\0x1b[0;32mI (1399) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations\0x1b[0m
\0x1b[0;32mI (79) cpu_start: Starting scheduler on PRO CPU.\0x1b[0m
\0x1b[0;32mI (0) cpu_start: Starting scheduler on APP CPU.\0x1b[0m
\0x1b[0;32mI (169) HTTP_MP3_EXAMPLE: [ 1 ] Start audio codec chip\0x1b[0m
\0x1b[0;32mI (199) HTTP_MP3_EXAMPLE: [2.0] Create audio pipeline for playback\0x1b[0m
\0x1b[0;32mI (199) HTTP_MP3_EXAMPLE: [2.1] Create http stream to read data\0x1b[0m
\0x1b[0;32mI (199) HTTP_MP3_EXAMPLE: [2.2] Create i2s stream to write data to codec chip\0x1b[0m
\0x1b[0;32mI (209) HTTP_MP3_EXAMPLE: [2.3] Create mp3 decoder to decode mp3 file\0x1b[0m
\0x1b[0;32mI (219) HTTP_MP3_EXAMPLE: [2.4] Register all elements to audio pipeline\0x1b[0m
\0x1b[0;32mI (219) HTTP_MP3_EXAMPLE: [2.5] Link it together http_stream-->mp3_decoder-->i2s_stream-->[codec_chip]\0x1b[0m
\0x1b[0;32mI (229) HTTP_MP3_EXAMPLE: [2.6] Setup uri (http as http_stream, mp3 as mp3 decoder, and default output is i2s)\0x1b[0m
\0x1b[0;32mI (239) HTTP_MP3_EXAMPLE: [ 3 ] Start and wait for Wi-Fi network\0x1b[0m
\0x1b[0;32mI (329) phy: phy_version: 366.0, ba9923d, Dec 29 2017, 14:25:06, 0, 0\0x1b[0m
\0x1b[0;32mI (3629) HTTP_MP3_EXAMPLE: [ 4 ] Setup event listener\0x1b[0m
\0x1b[0;32mI (3629) HTTP_MP3_EXAMPLE: [4.1] Listening event from all elements of pipeline\0x1b[0m
\0x1b[0;32mI (3629) HTTP_MP3_EXAMPLE: [4.2] Listening event from peripherals\0x1b[0m
\0x1b[0;32mI (3639) HTTP_MP3_EXAMPLE: [ 5 ] Start audio_pipeline\0x1b[0m
\0x1b[0;33mW (3639) AUDIO_ELEMENT: [http] RESUME:Element has not running,state:3,task_run:1\0x1b[0m
\0x1b[0;33mW (3659) AUDIO_ELEMENT: [mp3] RESUME:Element has not running,state:3,task_run:1\0x1b[0m
\0x1b[0;33mW (3659) AUDIO_ELEMENT: [i2s] RESUME:Element has not running,state:3,task_run:1\0x1b[0m
\0x1b[0;32mI (3669) HTTP_MP3_EXAMPLE: [ * ] Event received: src_type:131072, source:0x3f800130 cmd:8, data:0xd, data_len:4\0x1b[0m
\0x1b[0;32mI (3679) HTTP_MP3_EXAMPLE: [ * ] Event received: src_type:131072, source:0x3f800348 cmd:8, data:0xd, data_len:4\0x1b[0m
\0x1b[0;32mI (3689) HTTP_MP3_EXAMPLE: [ * ] Event received: src_type:131072, source:0x3f800224 cmd:8, data:0xd, data_len:4\0x1b[0m
\0x1b[0;32mI (3699) HTTP_MP3_EXAMPLE: [ * ] Event received: src_type:131072, source:0x3f800224 cmd:8, data:0xc, data_len:4\0x1b[0m
Guru Meditation Error: Core  0 panic'ed (LoadProhibited)
. Exception was unhandled.
Register dump:
PC      : 0x4009a0b8  PS      : 0x00060530  A0      : 0x801323e9  A1      : 0x3ffd1d70  
A2      : 0x00000000  A3      : 0x3f4126f0  A4      : 0x00000007  A5      : 0x00000200  
A6      : 0xe6af6218  A7      : 0x3ffd1de0  A8      : 0x3ffb3320  A9      : 0x3ffd1d70  
A10     : 0x3ffd4bf4  A11     : 0x3ffb3324  A12     : 0x00000007  A13     : 0x3ffd4bfa  
A14     : 0x00000001  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x40099e98  LEND    : 0x40099ec6  LCOUNT  : 0xffffffff  

Backtrace: 0x4009a0b8:0x3ffd1d70 0x401323e6:0x3ffd1d90 0x4013f10d:0x3ffd1dd0 0x4013f3ba:0x3ffd1e00 0x40165ae7:0x3ffd1e30 0x4013f9d1:0x3ffd1ea0 0x40132740:0x3ffd1ed0 0x4012fbf1:0x3ffd1f90 0x40130146:0x3ffd1fc0

**Comment by tuanpmt** [comment]
Hi @Laxiyan 

This issues resolved by https://github.com/espressif/esp-adf/commit/83444ce94d72a08ed603096d50044bd38dbf0af6

Please update master branch and re-check

Thanks
