### ISSUE TITLE
A fatal error occurred when make flash

### ISSUE THREAD

**Issue by jictannu** [espressif/esp-adf#20]
I download firmware to ESP32-LyraTD-MSC with make flash in Ubuntu, It prompts error:
A fatal error occurred: Failed to connect to ESP32: Invalid head of packet ('\x08')
Please give me some suggestion

**Comment by tuanpmt** [comment]
Hi @jictannu 

Could you please try another lower baud rates?

And I think whether you can flash it, but this board still not supported in the ADF

**Comment by tuanpmt** [comment]
Yes @jictannu 

We had planned to support it, but I'm not sure about the time

**Comment by jason-mao** [comment]
@jictannu ZL38063 driver has been supported. Refer to `e5cdb191815d686eaa68e794e2faf1e641174fa6`
