### ISSUE TITLE
I ask esp-adf to replay any connection after wifi disconnects successfully, and then play any network music that cannot be played again. How to solve this problem. (AUD-564)

### ISSUE THREAD

**Issue by jimeixuehua** [espressif/esp-adf#204]

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by jason-mao** [comment]
This issue same as #205 .
