### ISSUE TITLE
Using original ESP32

### ISSUE THREAD

**Issue by HumamHelfawi** [espressif/esp-adf#21]
Hi,
The answer seems obvious but I just want to double check. Does esp-adf basic features such as decoding Mp3 from an external SD card and playing it using the internal DAC (GPIO 25,26) available with the original ESP32 (I do not have Lyrat board ).

**Comment by tuanpmt** [comment]
Hi @HumamHelfawi 

Yes, you can use external SD card and internal DAC without LyraT board, but you need:
- Initialize SD Card and mount it before running the pipeline 
- Amplifier for DAC 

PS: LyraT board doesn't support DAC output

**Comment by HumamHelfawi** [comment]
@tuanpmt Thank you very much for the confirmation!
