### ISSUE TITLE
VOIP/SIP Info method (AUD-558)

### ISSUE THREAD

**Issue by nandibrenna** [espressif/esp-adf#212]
Hi,
it would be nice if you could implement an SIP_EVENT_ for the SIP Info method to receive DTMF signals.

**Comment by ahhfzhang** [comment]
@nandibrenna Thanks for your report. 
VoIP have 3 methods for DTMF: **in-band**, **RFC2833** and **SIP INFO**
RFC2833 has the best compatibility,we will support it In the last few days.
