### ISSUE TITLE
JTAG cannot be used after burning play_mp3_control  (AUD-555)

### ISSUE THREAD

**Issue by Lyubiao** [espressif/esp-adf#217]
hi，hear
I use the LTrat4.3 version of hardware and can use JTAG normally after burning play_music. However, JTAG cannot be used after burning play_music_control. JTAG is recognized but not linked to esp32 

![image](https://user-images.githubusercontent.com/39191633/61166829-14c24000-a567-11e9-9ab3-050683d4d5e6.png)

I found that JTAG had a pin multiplexed to touch button vol -, and neither I burned other programs nor erase flash could use JTAG to link to esp32.

**Comment by jason-mao** [comment]
@Lyubiao   Did you check your hardware with IDF_PATH/examples/get-started/hello_world?

**Comment by jason-mao** [comment]
Closed by no more informations.
