### ISSUE TITLE
examples/advanced_examples/downmix_pipeline doesn't work on lyrat_v4_3 properly (AUD-554)

### ISSUE THREAD

**Issue by easyvolts** [espressif/esp-adf#218]
Tested version adc6ac1165f08ad6096768264068a99babd6534c.
For test used https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.mp3 sound renamed as test1.mp3 and test2.mp3. Mixing doesn't work as expected, there are some noises and sound is "scattered" into pieces. Other note - when "base" file ends, the second file won't start (mixing works ONLY if base file is playing). Which is not expected in my opinion, i expected that i can play each sound independent or together in any combination.

**Comment by jason-mao** [comment]
@easyvolts Thanks for your report.

**Comment by houhaiyan** [comment]
@easyvolts  Hello, The down-mix branch has update. Please check you test.

**Comment by houhaiyan** [comment]
@easyvolts  If all  channels for down-mix are stopping, my down-mix wound stop.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
