### ISSUE TITLE
Detect packet boundaries when encoding for transmit over RTP (AUD-553)

### ISSUE THREAD

**Issue by epaterlini** [espressif/esp-adf#219]
Hello, I'm trying to implement RTP over UDP (mainly AUDIO_STREAM_WRITER interface) for streaming live audio from ESP-32 to the web.
I'm using OPUS encoder for this purpose.
The problem is that RTP only allows for complete OPUS packets to be sent as a single RTP payload, as specified [here](https://tools.ietf.org/html/rfc7587#section-4.2).
If the OPUS encoder is the previous AudioElement in the pipeline, how can I know the packet boundaries from the encoder?
My thought is that the encoder AudioElement writes its output to the ring buffer, when the ring buffer is full the next AudioElement "process" callback is called and the packet boundary is lost.
Am I missing something?

Thank you very much for this great project,
Emiliano

**Comment by jason-mao** [comment]
@epaterlini I am not sure I got your means. what's means of ''If the OPUS encoder is the previous AudioElement in the pipeline, how can I know the packet boundaries from the encoder?''?  Could you add more explanation？

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
