### ISSUE TITLE
[i2s_writer] AEL_IO_TIMEOUT when use I2S ADC DAC [AUD-551]

### ISSUE THREAD

**Issue by minhhieuec** [espressif/esp-adf#220]
Hi,
I'm trying play sine wave with I2S0 use ADC1_CHANNEL_6 to read ADC. But AEL_IO_TIMEOUT make esp memset and send zero value to DAC unit. I tried increase time out with function audio_element_set_input_timeout, esp no longer send zero value but the time out make the signal like phase reversal.

> #define I2S_STREAM_CFG_DEFAULT()                                            \
>   {                                                                         \
>     .type = AUDIO_STREAM_WRITER, .task_prio = I2S_STREAM_TASK_PRIO,         \
>     .task_core = I2S_STREAM_TASK_CORE, .task_stack = I2S_STREAM_TASK_STACK, \
>     .out_rb_size = I2S_STREAM_RINGBUFFER_SIZE,                              \
>     .i2s_config =                                                           \
>         {                                                                   \
>             .mode = I2S_MODE_MASTER | I2S_MODE_TX | I2S_MODE_RX |           \
>                     I2S_MODE_ADC_BUILT_IN | I2S_MODE_DAC_BUILT_IN,          \
>             .sample_rate = 44100,                                           \
>             .bits_per_sample = 16,                                          \
>             .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,                   \
>             .communication_format = I2S_COMM_FORMAT_I2S_MSB,                \
>             .dma_buf_count = 2,                                             \
>             .dma_buf_len = 1024,                                             \
>             .use_apll = 0,                                                  \
>             .intr_alloc_flags = ESP_INTR_FLAG_LEVEL2,                       \
>         },                                                                  \
>     .i2s_port = 0, .use_alc = false, .volume = 0,                           \
>   }

I think this problem occur because:
 ```
if (rb_block(rb->can_read, ticks_to_wait) != pdTRUE) {
                ret_val = RB_TIMEOUT;
                ESP_LOGE(TAG, "rb_block(rb->can_read, ticks_to_wait) != pdTRUE");
                goto read_err;
            }
```

if use `.use_apll = 1` then no longer AEL_IO_TIMEOUT issuse but the signal is disgusting not is sine wave the same input (adc)

How to fix this problem?

Thanks!

**Comment by jason-mao** [comment]
@minhhieuec How can I reproduced this issue?

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
