### ISSUE TITLE
About “vTaskDelay(1000 / portTICK_PERIOD_MS)” in func "dueros_task" (AUD-624)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-adf#224]
Hi, below‘s maybe a better solution:

Changed in function "audio_service_handle_t dueros_service_create(void)"
{

    dueros_service_t *serv =  audio_calloc(1, sizeof(dueros_service_t));
    serv->duer_que = xQueueCreate(3, sizeof(duer_task_msg_t));
    serv->duer_state = SERVICE_STATE_UNKNOWN;
    audio_service_config_t duer_cfg = {
        .task_stack = DUEROS_TASK_STACK_SIZE,
        .task_prio  = DUEROS_TASK_PRIORITY,
        .task_core  = 1,
        .task_func  = dueros_task,
        .service_start = dueros_start,
        .service_stop = dueros_stop,
        .service_connect = dueros_connect,
        .service_disconnect = dueros_disconnect,
        .service_destroy = dueros_destroy,
        .service_name = "duer_serv",
        .user_data = serv,
    };
    audio_service_handle_t duer = audio_service_create(&duer_cfg);
    duer_serv_handle = duer;
    return duer;
}

**Comment by jason-mao** [comment]
@xiruilin Thanks for your report.
