### ISSUE TITLE
Get song metadata in bt_sink example? (AUD-639)

### ISSUE THREAD

**Issue by HimbeersaftLP** [espressif/esp-adf#227]
Is it possible to get metadata like song name when using the bt_sink pipeline?

I heard there are some Android or iOS specific methods of doing that?

https://github.com/espressif/esp-adf/blob/master/examples/player/pipeline_bt_sink/main/play_bt_music_example.c

**Comment by esp-xiaodong** [comment]
use this file to replace of the old one.
[bluetooth_service.txt](https://github.com/espressif/esp-adf/files/3499681/bluetooth_service.txt)

**Comment by HimbeersaftLP** [comment]
Thank you so much ❤
