### ISSUE TITLE
"audio_element_finish_state()" function error (AUD-642)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-adf#229]
Hi, 
    “audio_element_finish_state()” in commit [dbebaf3](https://github.com/espressif/esp-adf/commit/dbebaf34785c80ad94ba59afb917301b2acd62ee) failure to achieve functionality.
The following changes should be made:
```
-    if (el->task_stack < 0) {
+    if (el->task_stack <= 0) {
+        audio_element_set_ringbuf_done(el);

```

**Comment by jason-mao** [comment]
@xiruilin Thanks for your report.
