### ISSUE TITLE
SIP, why isn't there any source files (AUD-726)

### ISSUE THREAD

**Issue by versamodule** [espressif/esp-adf#241]
Should we wish to tweak it to suit our needs, why isn't there any sources ?

**Comment by jason-mao** [comment]
Hi versamodule,
Sorry we can't open source directly now. If you need some customization, you can send the requirement for me or contact our sales with sales@espressif.com.

**Comment by sosaucily** [comment]
I am interested in this as well. Could be useful to extend functionality, and to deliver products based on this great feature set with confidence.
