### ISSUE TITLE
pipline_passthru doesn't work - volume not set (AUD-746)

### ISSUE THREAD

**Issue by jponko** [espressif/esp-adf#244]
Although technically the program is working as given, the most likely result for most people will be that the sound output is too low to hear and they may feed a high enough signal into the AUX input to damage the codec chip in an attempt to hear something. Please add the following line before the start audio pipeline to fix the audio level problem:

audio_hal_set_volume(board_handle-> audio_hal, 100);

**Comment by espressif-zhanghu** [comment]
Your finding is great, but I personally verified your problem and found that the output is ok.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
