### ISSUE TITLE
some files are missing (AUD-767)

### ISSUE THREAD

**Issue by pilnikov** [espressif/esp-adf#247]
When adding new features, you forgot to add 3 .h files and 3 (?) .c files with code
For the project to compile, I had to make stubs. (file func.c)

https://github.com/pilnikov/adf/commit/75a35f28dc5a9f2aaaf47ee1cfa035172c2fe99

I also corrected a syntax error - replaced "headphone_det**ce**t" with "headphone_det**eс**t"

**Comment by jason-mao** [comment]
@pilnikov Thank you for your report.
