### ISSUE TITLE
How to link the "raw_read" to "http_stream_writer" in a pipeline ? (AUD-837)

### ISSUE THREAD

**Issue by ninghuiy** [espressif/esp-adf#250]
I already made "record_raw_http" example work, and I am trying to build a new pipeline 
i2S-> filter->  raw-> http. This new pipeline does not work, but after I remove the "raw_read", everything works fine. 

I need to add "raw_read" because this help me do the VAD (voice activity detection), and if there is no speech detected,  stop the pipeline and stop upload to the server. 

I do not know if there is any other solutions to help me accomplish my goal. My system requires when there is no voice detected, it will automatically stop uploading voice streams to the server. 

Thanks for your suggestions

**Comment by jason-mao** [comment]
@ninghuiy I think you can create a new element instance for VAD detection. Then linked into pipeline  like i2S-> filter-> new_vad_element-> http.
