### ISSUE TITLE
ESP32-A1s  ac101怎麼 沒有被放進audio_hal/driver/呢 (AUD-1020)

### ISSUE THREAD

**Issue by kimouser64** [espressif/esp-adf#258]
請問為什麼不放在一起而獨立另外
是要放生了嗎

**Comment by kimouser64** [comment]
https://github.com/donny681/esp-adf

**Comment by timotoots** [comment]
Could it be possible to add support in the main branch?

**Comment by pilnikov** [comment]
https://github.com/pilnikov/adf 
Support is partially implemented, there are not enough functions for processing an analog keyboard, headphone detect and amp control. But the main functionality works. He plays music. Complies with the new management rules through HAL. Can an espressif add this board to the repository?

**Comment by Flos** [comment]
Im also missing the support for the AC101 ("Audio Kit")

**Comment by pilnikov** [comment]
try my bin files from https://github.com/pilnikov/adf/tree/master/esp-adf/examples/Ka_mod/bin
Several users have already successfully launched their aithinker a1s based boards. 
For myself, I use a very heavily modified version of ADF, which supports the new (4.1.xx) version of IDF with Cmake, ninja && e.t.c.
You can simply replace the components folder with mine and delete the idf folder (inside adf)

**Comment by jason-mao** [comment]
Closed, please refer to https://github.com/espressif/esp-adf/issues/341
