### ISSUE TITLE
support esp_app_desc_t in ESP-ADF

### ISSUE THREAD

**Issue by MichaelDu9226** [espressif/esp-adf#259]
I need tag my application image with a name and version string, like esp_app_desc_t based on ESP-IDF V3.3. 
But ESP-ADF based on ESP-IDF V3.2.
So how can I solve this problem? Thank you.

**Comment by jason-mao** [comment]
Hi @MichaelDu9226，

I have test ADF example `play_mp3` with the IDF v3.3 on 46b12a560a29fa6ade07800a4abe12a026183988, it's works fine. You can used IDF V3.3 directly, if you got any problems, please let me know.
