### ISSUE TITLE
How to use the recorder engine

### ISSUE THREAD

**Issue by yun-zero** [espressif/esp-adf#260]
I only need a single dialog box to get in touch with the framework soon. Can be used to give a process code using the recorder

**Comment by jason-mao** [comment]
Hi yun-zero,
`recorder engine` integrate with wake word engine, AMR encoding and VAD. After wakeup or trigger, recoding active voice data  and fill the internal buffer, user call the` rec_engine_data_read` or `rec_engine_enc_data_read` to get the voice data.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
