### ISSUE TITLE
esp-idf 4.0 compatibilty (AUD-1189)

### ISSUE THREAD

**Issue by DeltaEvo** [espressif/esp-adf#261]
Make esp-adf compatible with esp-idf release 4.0

I'm interested in using nimble stack instead of bluedroid

**Comment by jason-mao** [comment]
Sure, we will support IDF v4.0 on December.

**Comment by PleasantD** [comment]
Is there an update on the timeline for this?

**Comment by jason-mao** [comment]
@DeltaEvo v4.0 have a lot of break changes, we are working on this, I think need more 2-3 weeks for release. Thanks.

**Comment by joncmaloney** [comment]
Hi @jason-mao is there anything I can do to help out to get the esp-adf framework compatible with v4.0?

**Comment by jason-mao** [comment]
Hi guys
Sorry for late. ADF can be work with IDF v4.x start 2a95e1f2c603d07f98735518295243cbdb2958ed.
Thank you.
