### ISSUE TITLE
很多DEMO选择 MINI 语音板会显示 No board.h file

### ISSUE THREAD

**Issue by flfq** [espressif/esp-adf#262]
esp-adf/components/esp_peripherals/periph_button.c:38:19: fatal error: board.h: No such file or directory
compilation terminated.

**Comment by flfq** [comment]
```
if (CONFIG_ESP_LYRATD_MINI_V1_1_BOARD)
message(STATUS "Current board name is " CONFIG_ESP_LYRATD_MINI_V1_1_BOARD)
list(APPEND COMPONENT_ADD_INCLUDEDIRS ./lyratd_mini_v1_1)
set(COMPONENT_SRCS
./lyratd_mini_v1_1/board.c
./lyratd_mini_v1_1/board_pins_config.c
)
endif()
```
lyratd_mini_v1_1 应是 lyrat_mini_v1_1

**Comment by jason-mao** [comment]
@flfq Thank you for your report.

**Comment by jalakamkiranadspl** [comment]
Hey I am getting this issue for the esp32 audio kit(from ai-thinker) too. 
![image](https://user-images.githubusercontent.com/73413933/112314592-3168c200-8ccf-11eb-9ba3-e032a86b3616.png)
Can you please tell how you resolved it? Or how can it be resolved?
