### ISSUE TITLE
ES8388 Register 40/41 (AUD-1034)

### ISSUE THREAD

**Issue by szucsi23** [espressif/esp-adf#263]
Hi!
There are two registers for the ES8388 (reg 40 and 41) which have values assigned to them (0x38 in the user guide, 0x28 on the data sheet), but it's not specified, what these registers are for.
Could you tell the Bit Name and Description?
Thanks in advance!

**Comment by jason-mao** [comment]
@szucsi23 The confirmed message from  Everest company, which reg40 and reg41 are not used, no more make sense.
