### ISSUE TITLE
"esp_audio_time_get()" can't get correct playback time (AUD-944)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-adf#265]
Hi, 
In "esp_audio_time_get()" function, playback time is always start with zero,
whether "esp_audio_play()" function parameter "pos" is equal to zero or not.

**Comment by jason-mao** [comment]
@xiruilin 
Does the music playing? could you provide your log ?

**Comment by xiruilin** [comment]
@jason-mao

**Comment by jason-mao** [comment]
@xiruilin Got that, will be fixed later.

**Comment by xiruilin** [comment]
@jason-mao 

Thanks for update, the playing time is more accurate.
