### ISSUE TITLE
建议在esp-adf增加FFT的API，可以处理raw_read。 (AUD-991)

### ISSUE THREAD

**Issue by zxl777** [espressif/esp-adf#269]
raw_read 可以做语音识别，有vad_process这样的API。

请增加一个FFT的API吧。

能从 https://github.com/espressif/esp-dsp 中把FFT移植到esp-adf也好，谢谢。

**Comment by jason-mao** [comment]
@zxl777 FFT 是一个较为通用的算法，`esp-dsp`的API 能满足您的需求吗？

**Comment by drewandre** [comment]
I'm also having issues using an FFT on raw audio streams: https://github.com/espressif/esp-adf/issues/365

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
