### ISSUE TITLE
Bugs after adding SR (AUD-1008)

### ISSUE THREAD

**Issue by pilnikov** [espressif/esp-adf#274]
![1](https://user-images.githubusercontent.com/25922873/69404673-a87af880-0d1f-11ea-94cc-6dd196f64c7b.JPG)

**Comment by jason-mao** [comment]
@pilnikov Thanks for your report.

**Comment by pilnikov** [comment]
[log.txt](https://github.com/espressif/esp-adf/files/3878409/log.txt)

![2](https://user-images.githubusercontent.com/25922873/69406964-2ab9eb80-0d25-11ea-99ed-ef73b0a4e730.JPG)

file - esp-adf-libs/Cmakelists.txt

**Comment by pilnikov** [comment]
![log](https://user-images.githubusercontent.com/25922873/69916299-420e7c80-147b-11ea-8e35-6fac9d1c6146.PNG)
![1](https://user-images.githubusercontent.com/25922873/69916302-476bc700-147b-11ea-9d1a-3e2df35ddc38.PNG)
in file /components/esp-sr/Kconfig.projbuild

**Comment by jason-mao** [comment]
@pilnikov Thanks for your report.

**Comment by pilnikov** [comment]
One more little remark: I am using cmake version 3.13.4
![ver](https://user-images.githubusercontent.com/25922873/69963870-f3bcb480-1532-11ea-8065-a360aed3713e.PNG)

And every time I have to replace $ {COMPONENT_NAME) with $ {COMPONENT_LIB)
![orig](https://user-images.githubusercontent.com/25922873/69963910-1222b000-1533-11ea-90f9-8823a30ee668.PNG)

![my](https://user-images.githubusercontent.com/25922873/69963962-2e265180-1533-11ea-9460-8a5a90ec26aa.PNG)

**Comment by feizi** [comment]
When we use cmake version 3.5.1 and idfv3.2， $ {COMPONENT_NAME) can not be replaced with $ {COMPONENT_LIB).   We will try to find a way to be compatible with more versions.    
Thanks for your report.

**Comment by pilnikov** [comment]
still not correct in file /components/esp-sr/Kconfig.projbuild

![image](https://user-images.githubusercontent.com/25922873/75314680-4bdd2b80-5882-11ea-8072-0e9cb84601af.png)
