### ISSUE TITLE
Can do something before recording after wake up？ (AUD-1021)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-adf#278]
Hi,
When waked up with the wake-up word "nihaoxiaoxin", rec_engine_cb() is called directly.
Can configure a custom callback function, call this function after wake-up to do something, 
and then call the function rec_engine_trigger_start() to start recording?
Thanks

**Comment by jason-mao** [comment]
@xiruilin Could you  give more information for what want to do in the `custom callback function`?

**Comment by xiruilin** [comment]
@jason-mao 

Maybe to control other devices, such as toy cars, cameras,
or play the voice prompt, or judge whether it is in microphone mute mode.
Anyway, I don't want to put these extra sounds into the microphone.
It will add a wake-up callback function.
After some extra processing is done in this callback function,
it is decided whether to call "rec_engine_trigger_start()" to turn on the microphone.
Thanks.

**Comment by jason-mao** [comment]
@xiruilin
I think the current implementation meets your needs. 
The REC_EVENT_WAKEUP_START event posted after wake-up, then you can do what you want to do at the callback function, after that the ` rec_engine` detecting the voice by VAD, REC_EVENT_VAD_START means got active voice, silence a while (`vad_off_delay_ms`)  post REC_EVENT_VAD_STOP event. Out of the `wakeup_time_ms`post REC_EVENT_WAKEUP_END  event.

**Comment by xiruilin** [comment]
Oh, thanks
