### ISSUE TITLE
ESP32-LyraT Connection to PC

### ISSUE THREAD

**Issue by jeremylua** [espressif/esp-adf#28]
Hello, so I just received my ESP32-LyraT v4.3 today, and I tried going through the Getting Started with the LyraT and noticed my board wasn't behaving as expected.

When I plug in both MicroUSB ports to two USB ports on my Mac, I don't see the Standby green LED light up (neither the battery LED). I do see the red Power LED light up when I turn the power on though.  Additionally, I don't see the computer recognizing the serial port that the LyraT is connected to, however when I connect to my ESP-WROVER-KIT board I see the port just fine. Is my LyraT board defective?

**Comment by krzychb** [comment]
Hi @jeremylua,

This indeed looks like an issues with the board. To be sure I would double check the power supply to the ESP32-LyraT. Use an external power supply and a USB cable that works with another board. Connect just this cable to USB port labelled  "Power" on the ESP32-LyraT and check if this changes anything in LED light pattern.
