### ISSUE TITLE
esp-adf/examples/recoder/wav_sdcard改成自动录音 (AUD-1079)

### ISSUE THREAD

**Issue by woody5418** [espressif/esp-adf#283]
除了按键按下录音 松开结束 或者等待10s以后结束外，有可以检测录音的函数么？

**Comment by jason-mao** [comment]
回答见#280. 后续会提供这样一个example。

**Comment by woody5418** [comment]
最好是独立于dureos的 单纯的自动录音，录音以后播放或者存储的例子

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
