### ISSUE TITLE
dueros总是：Play activity timeout (AUD-1085)

### ISSUE THREAD

**Issue by DemoKK** [espressif/esp-adf#285]
[0;32mI (480908) ESP_AUDIO_TASK: 2.1 Update all pipelines[0m
[0;32mI (480914) ESP_AUDIO_TASK: 3. Previous starting...[0m
[0;32mI (480920) AUDIO_ELEMENT: [iis] AEL_MSG_CMD_RESUME,state:1[0m
[0;32mI (480926) I2S_STREAM: AUDIO_STREAM_WRITER[0m
[0;33mW (488872) ESP_AUDIO_CTRL: Play activity timeout[0m
W (488859,tid:3ffc6bb8) lightduer_events.c(  80):[lightduer_ca] <== event end = 400F29B4, timespent = 8132

**Comment by jason-mao** [comment]
@DemoKK 整个log帮提供一下

**Comment by jason-mao** [comment]
Closed by no more informations.
