### ISSUE TITLE
Cannot specify link libraries for target "esp-sr" which is not built by this project. (AUD-1134)

### ISSUE THREAD

**Issue by didiaozy** [espressif/esp-adf#293]
pull的最新ADF工程，使用IDF V3.3.1编译play_mp3这个例子，出现下述关于SR的错误：

`-- Current board name is CONFIG_ESP_LYRAT_V4_3_BOARD
CMake Error at D:/workspace/gitee/esp-adf/components/esp-sr/CMakeLists.txt:15 (t
arget_link_libraries):
  Cannot specify link libraries for target "esp-sr" which is not built by
  this project.

-- Configuring incomplete, errors occurred!
See also "D:/workspace/gitee/esp-adf/examples/get-started/play_mp3/build/CMakeFi
les/CMakeOutput.log".
See also "D:/workspace/gitee/esp-adf/examples/get-started/play_mp3/build/CMakeFi
les/CMakeError.log".
cmake failed with exit code 1`

难道是https://github.com/espressif/esp-sr中的库文件不是用同版本的编译器生成的么？

**Comment by jason-mao** [comment]
@didiaozy   谢谢你的反馈。你可以先到esp-sr目录下，拉最新的master，暂时修复这个问题。
