### ISSUE TITLE
.h C++ compatibility -> extern "C" (AUD-1171)

### ISSUE THREAD

**Issue by stasartcode** [espressif/esp-adf#301]
// FIXED bug like this -> undefined reference sdcard_list_create ->  
esp-adf/components/playlist/include/sdcard_list.h
esp-adf/components/playlist/include/dram_list.h
esp-adf/components/playlist/include/flash_list.h
esp-adf/components/playlist/include/partition_list.h
esp-adf/components/playlist/include/playlist.h
esp-adf/components/playlist/include/sdcard_scan.h

and other ...

esp-adf/components/input_key_service/include/input_key_com_user_id.h
esp-adf/components/input_key_service/include/input_key_service.h

esp-adf-libs/esp_codec/include/processing/esp_alc.h
... more

**Comment by jason-mao** [comment]
@stasartcode Thanks for your report.
