### ISSUE TITLE
ESP32 wroom32D no sound call VOIP example (AUD-1177)

### ISSUE THREAD

**Issue by Arto1994** [espressif/esp-adf#303]
Hello everyone !

I'm testing the new adf , to make  a VOIP call. But I could not hear anything from a external client , I already debug and the callbacks of audio coding/decoding , trasmition and reception works , The sip was able to register to the server and handle the call the only error from SIP is  this one 

> **E (284027) SIP_RTP: receive task, server addr=192.168.0.114:4000**

For now I only  using the  received data and doing the echo to trasmit again ,But I can hear anything. It seems like  an access error .

Also I used wireshark to view the sip protocol and I could see ICMP (unreachable port) error:

![ICMP VOIP error](https://user-images.githubusercontent.com/32774451/71590895-2b9a2600-2af8-11ea-8d0f-f3d1bb968aba.JPG)

I tried with three servers  ,uSipServer Android app  and I install  Asterisk in raspeberry and  last using a Virutal machine with linux in amazon,  But in all of these there is no audio from esp32.

Also Wireshar have a tool to do a telephony (sip) diagram and this is what It captured:

192.168.0.124 is my PC calling the esp 192.168.0.122 trough server 192.1680.114 (android uSipServer )

![SIP diagram esp32](https://user-images.githubusercontent.com/32774451/71591070-ddd1ed80-2af8-11ea-9ac8-95abc159ce8d.JPG)

As you see there is no audio data coming from esp32  :( , only there is audio from PC to esp32.

Other blocker for my using the adf , is that there is no source code to modify and this error is not clear printed from terminal or  at least I don't know it. 

Thanks for help!

PD: Here is the terminal verbose:

W (282407) SIP: [1970-01-01/00:04:21]=======================>>
I (283237) VOIP_EXAMPLE: Contestar
I (283317) VOIP_EXAMPLE: SIP_EVENT_REQUEST_NETWORK_IP
W (283317) SIP: [1970-01-01/00:04:21]=======WRITE 0768 bytes>>
I (283317) SIP:

SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.114:5060;branch=z9hG4bK-597af8b6f97c3ff4525ed77dfd0ee95c
Via: SIP/2.0/UDP 192.168.0.124:63014;rport;branch=z9hG4bKPjc733b9f8cd234a11bc055324cd7ad9b6
Record-Route: <sip:192.168.0.114;ftag=5a8908fe3b964d00ab0b54a703ffbae3;lr=on>
Contact: <sip:100@192.168.0.122:5060>
From: <sip:200@192.168.0.114>;tag=5a8908fe3b964d00ab0b54a703ffbae3
To: <sip:100@192.168.0.114>;tag=-1149976290
Call-ID: 174567c39bd849f2be0a87354b0fdec4
CSeq: 4273 INVITE
Server: ESP32 SIP/2.0
Allow: ACK, INVITE, BYE, CANCEL, OPTIONS, INFO
Content-Length: 156
Content-Type: application/sdp

v=0
o=Z 0 3 IN IP4 192.168.0.122
s=Z
c=IN IP4 192.168.0.122
t=0 0
m=audio 9999 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000

W (283387) SIP: [1970-01-01/00:04:21]=======================>>
I (283497) VOIP_EXAMPLE: ringing... RemotePhoneNum 200
W (283937) SIP: [1970-01-01/00:04:21]<<=====READ 0501 bytes==
I (283937) SIP:

ACK sip:100@192.168.0.122 SIP/2.0
Record-Route: <sip:192.168.0.114;ftag=5a8908fe3b964d00ab0b54a703ffbae3;lr=on>
Via: SIP/2.0/UDP 192.168.0.114:5060;branch=z9hG4bK-597af8b6f97c3ff4525ed77dfd0ee95c
Via: SIP/2.0/UDP 192.168.0.124:63014;rport;branch=z9hG4bKPj45769b563d7e428bb55e4c3c670251aa
Max-Forwards: 69
From: <sip:200@192.168.0.114>;tag=5a8908fe3b964d00ab0b54a703ffbae3
To: <sip:100@192.168.0.114>;tag=699323670
Call-ID: 174567c39bd849f2be0a87354b0fdec4
CSeq: 4273 ACK
Content-Length: 0

W (283987) SIP: [1970-01-01/00:04:21]<<======================
I (283987) SIP_RTP: rtp local addr=192.168.0.122, port=9999
W (283997) SIP: CHANGE STATE FROM 16, TO 32, :func: sip_uas_process_req:774
W (284007) SIP: [1970-01-01/00:04:21]<<=====READ 0503 bytes==
I (284007) SIP:

BYE sip:100@192.168.0.122 SIP/2.0
Record-Route: <sip:192.168.0.114;ftag=5a8908fe3b964d00ab0b54a703ffbae3;lr=on>
Via: SIP/2.0/UDP 192.168.0.114:5060;branch=z9hG4bK-617a2296236f13c492a323b0fa457bcd
Via: SIP/2.0/UDP 192.168.0.124:63014;rport;branch=z9hG4bKPj13e1f99952d14935b6400d74e33ac97b
Max-Forwards: 69
From: <sip:200@192.168.0.114>;tag=5a8908fe3b964d00ab0b54a703ffbae3
To: <sip:100@192.168.0.114>;tag=-1149976290
Call-ID: 174567c39bd849f2be0a87354b0fdec4
CSeq: 4274 BYE
Content-Length: 0

E (284027) SIP_RTP: receive task, server addr=192.168.0.114:4000
W (284057) SIP: [1970-01-01/00:04:21]<<======================
I (284077) VOIP_EXAMPLE: SIP_EVENT_AUDIO_SESSION_BEGIN
I (284077) VOIP_EXAMPLE: SIP_EVENT_AUDIO_SESSION_END
I (284077) SIP_RTP: send task stopped
I (284087) SIP_RTP: receive task stopped
I (284087) SIP_RTP: RTP stopped
I (284097) VOIP_EXAMPLE: SIP_EVENT_HANGUP
W (284097) SIP: CHANGE STATE FROM 32, TO 2, :func: sip_uas_process_req:759
W (284107) SIP: [1970-01-01/00:04:21]=======WRITE 0590 bytes>>
I (284117) SIP:

SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.0.114:5060;branch=z9hG4bK-617a2296236f13c492a323b0fa457bcd
Via: SIP/2.0/UDP 192.168.0.124:63014;rport;branch=z9hG4bKPj13e1f99952d14935b6400d74e33ac97b
Record-Route: <sip:192.168.0.114;ftag=5a8908fe3b964d00ab0b54a703ffbae3;lr=on>
Contact: <sip:100@192.168.0.122:5060>
From: <sip:200@192.168.0.114>;tag=5a8908fe3b964d00ab0b54a703ffbae3
To: <sip:100@192.168.0.114>;tag=-1149976290;tag=470519648
Call-ID: 174567c39bd849f2be0a87354b0fdec4
CSeq: 4274 BYE
Server: ESP32 SIP/2.0
Allow: ACK, INVITE, BYE, CANCEL, OPTIONS, INFO
Content-Length: 0

W (284167) SIP: [1970-01-01/00:04:21]=======================>>
W (284177) SIP: [1970-01-01/00:04:21]<<=====READ 0503 bytes==
I (284187) SIP:

ACK sip:100@192.168.0.122 SIP/2.0
Record-Route: <sip:192.168.0.114;ftag=5a8908fe3b964d00ab0b54a703ffbae3;lr=on>
Via: SIP/2.0/UDP 192.168.0.114:5060;branch=z9hG4bK-597af8b6f97c3ff4525ed77dfd0ee95c
Via: SIP/2.0/UDP 192.168.0.124:63014;rport;branch=z9hG4bKPjfca07115dd974f528d0537c0fc6ac7b0
Max-Forwards: 69
From: <sip:200@192.168.0.114>;tag=5a8908fe3b964d00ab0b54a703ffbae3
To: <sip:100@192.168.0.114>;tag=-1149976290
Call-ID: 174567c39bd849f2be0a87354b0fdec4
CSeq: 4273 ACK
Content-Length: 0

W (284227) SIP: [1970-01-01/00:04:22]<<======================
W (300037) SIP: [1970-01-01/00:04:29]=======WRITE 0572 bytes>>
I (300037) SIP:

OPTIONS sip:100@192.168.0.114:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.122:5060;branch=z9hG4bK--478255208;rport
From: <sip:100@192.168.0.114:5060>;tag=-413503598
To: <sip:100@192.168.0.114:5060>
Contact: <sip:100@192.168.0.122:5060>
Max-Forwards: 70
Call-ID: EF67AB6DC726D3764DF218459BCCD4629169186903E7
CSeq: 10 OPTIONS
Expires: 3600
User-Agent: ESP32 SIP/2.0
Content-Length: 0
Allow: INVITE, ACK, CANCEL, BYE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE
Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri
Allow-Events: presence, kpml

W (300087) SIP: [1970-01-01/00:04:29]=======================>>
W (300567) SIP: [1970-01-01/00:05:00]<<=====READ 0694 bytes==
I (300567) SIP:

OPTIONS sip:100@192.168.0.122 SIP/2.0
Record-Route: <sip:192.168.0.114;ftag=-413503598;lr=on>
Via: SIP/2.0/UDP 192.168.0.114:5060;branch=z9hG4bK-eb136eeb56f9624303612889d4f3afad
Via: SIP/2.0/UDP 192.168.0.122:5060;branch=z9hG4bK--478255208;rport
From: <sip:100@192.168.0.114>;tag=-413503598
To: <sip:100@192.168.0.114>
Contact: <sip:100@192.168.0.122>
Max-Forwards: 69
Call-ID: EF67AB6DC726D3764DF218459BCCD4629169186903E7
CSeq: 10 OPTIONS
Expires: 3600
User-Agent: ESP32 SIP/2.0
Content-Length: 0
Allow: INVITE, ACK, CANCEL, BYE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE
Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri
Allow-Events: presence, kpml

**Comment by ahhfzhang** [comment]
@Arto1994 Thanks for your report.
This seems to be a bug in the sip interaction, can you help provide the full log? 
and can you try Yate or Freeswitch server?

**Comment by Arto1994** [comment]
Hello Espressif/Esp-Adf

For now I have the log that I put in the bottom of the page , Im using
asterisk and also I tried with uSipServer (app server) and happens the same
no sound , and I received the same error.

Tomorrow I can share the entire log , but meanwhile can you provide me more
error information , since you don't have released the source code  for me
I've been hard debug this  problem .

Other thing that I tried is running this asterisk server in a raspberry pi
as I said ,skipping the possible firewalls issues , but still the same :(

**Comment by MrZANE42** [comment]
Any news on this? About to start a project possibly using this code

**Comment by ahhfzhang** [comment]
Hi,
We've been testing a lot on the FreePBX recently, bugfix commit: https://github.com/espressif/esp-adf/commit/20b0827
hope you can try again.

many thanks.
