### ISSUE TITLE
3D CAD files for ADF boards (AUD-1178)

### ISSUE THREAD

**Issue by evanbreakout** [espressif/esp-adf#304]
Could you please share the 3d files for the esp32 adf boards? It would make it so much easier to use these boards in the future.

**Comment by jason-mao** [comment]
@evanbreakout Sorry, we don't have the 3D CAD files of LyraT board.

**Comment by lucastcox** [comment]
@jason-mao , do you at least have drawings with dimensions? Kind of odd to put out dev boards without any dimensional information.
