### ISSUE TITLE
ES8388 PA 使能异常 (AUD-1181)

### ISSUE THREAD

**Issue by newstarqu** [espressif/esp-adf#306]
es8388.c文件，void es8388_pa_power(bool enable)函数使能PA，如果gpio超过31则不能正常使能。
原代码 io_conf.pin_bit_mask = BIT(get_pa_enable_gpio())处应改为io_conf.pin_bit_mask = BIT64(get_pa_enable_gpio())

**Comment by jason-mao** [comment]
@newstarqu Thanks for your report.
