### ISSUE TITLE
when I use PCM5102,have noise (AUD-1186)

### ISSUE THREAD

**Issue by Tianxiaomo** [espressif/esp-adf#307]

**Comment by jason-mao** [comment]
How is the noise? Did you given  a right sample rate and channels?

**Comment by Tianxiaomo** [comment]
Sample rate and channels is right.The noise is a crash.

**Comment by vacovnik** [comment]
If you didn't do that yet, you should add a pull-down to SCK pin on PCM5102 board.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
