### ISSUE TITLE
Long URLs won't play (AUD-1203)

### ISSUE THREAD

**Issue by timotoots** [espressif/esp-adf#310]
Board: LyraT
Example: Console example

Does not play longer URLs than 123 characters with "play" command. Any way to make the number larger?

**Comment by jason-mao** [comment]
@timotoots There is a size of buffer `CONSOLE_BUFFER_SIZE` at`components/esp_peripherals/periph_console.c`. If  you want to input long URL,please increase the buffer.

**Comment by timotoots** [comment]
@jason-mao This fixed it. Maybe it makes sense to make it changeable in the example as others might find the same problem. Thanks!
