### ISSUE TITLE
How to use "a2dp_stream" in "esp_audio_play()"? (AUD-1207)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-adf#313]
Hi,
In last commit esp-adf, "a2dp_stream" is a good feature.
How to use "a2dp_stream" in "esp_audio_play()"?
(How to set uri?）
Thanks!

**Comment by jason-mao** [comment]
@xiruilin Yes, we plan to use A2DP stream in `esp_audio_play`. The demonstration example is coming.

**Comment by xiruilin** [comment]
@jason-mao 
Thanks!
