### ISSUE TITLE
SIP source files (AUD-1240)

### ISSUE THREAD

**Issue by szucsi23** [espressif/esp-adf#320]
Hi!
I'm working with your SIP libraries, and it would be really helpful, if I could see and add my own additions to the source files.
Is there any way, to make them open source, or some other way to make it accessible for the users?
It would be really great!
Thanks in advance!

**Comment by iscapla** [comment]
Hello @szucsi23, I'd like to take a look on it too because I think that there is a memory leak problem on the sync periodically messages . Have you got any news?

**Comment by szucsi23** [comment]
Sadly no, still waiting.

**Comment by jason-mao** [comment]
Hi guys, I'm sorry that we cannot provide source code.  We will continue to improve the sip design. If you are have any issues, please let me know.
