### ISSUE TITLE
Build issues with simple demo (AUD-1269)

### ISSUE THREAD

**Issue by webtop** [espressif/esp-adf#323]
This might not be the correct place to post this, but I'm getting really frustrated with not being able to build a simple example: play_mp3 without issue.

I don't want to re-post everything here so I'll refer to this thread I just started on ESP32 forums, in the hope that someone can tell me why the build process constantly fails.

See: https://esp32.com/viewtopic.php?f=20&t=13930&p=54514#p54514
The issues I am seeing right now are in the code. It looks like all the build tools are in place.

My latest build gets to 94%, then throws up a bunch of errors relating to ISRs and components.

Attached my sdkconfig in case that matters.
[sdkconfig.txt](https://github.com/espressif/esp-adf/files/4081706/sdkconfig.txt)

I really appreciate any help here. Right now this board is a paperweight!

Paul

**Comment by jason-mao** [comment]
@webtop 
Due to IDF v4.0 and master have some break changes, the ADF have not support that. We are working on this for fix. Please not IDF just support IDF v3.3.1 release now. Please see more with https://esp32.com/viewtopic.php?f=20&t=13930&p=54514#p54514.
