### ISSUE TITLE
"i2c_bus_read_bytes()" parameters can refer to "i2c_bus_write_bytes()"? (AUD-1296)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-adf#333]
@jason-mao 

In commit [b562374](https://github.com/espressif/esp-adf/commit/b562374a2cc6230c362776db55abc7f84d6518d2), i2c_bus modified read bytes function, add ``int reg`` parameter.
Now we can use read_bytes directly without having to call write_bytes first to send "reg",
it's excellent. And we would like to make some suggestions here, can you refer to
``esp_err_t i2c_bus_write_bytes(i2c_bus_handle_t bus, int addr, uint8_t *reg, int regLen, uint8_t *data, int datalen)``,
change
``esp_err_t i2c_bus_read_bytes(i2c_bus_handle_t bus, int addr, int reg, uint8_t *outdata, int len)``
to
``esp_err_t i2c_bus_read_bytes(i2c_bus_handle_t bus, int addr, uint8_t *reg, int regLen, uint8_t *outdata, int datalen)``?
Because some I2C devices have 16 bits reg.

Thanks!

Happy Chinese New Year!

**Comment by jason-mao** [comment]
@xiruilin Thank you for your suggestion.
