### ISSUE TITLE
esp-adf-v2.0-beta2 , voip_app.elf not found (AUD-1299)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#336]
Hi,
I installed the newest esp-adf-v2.0-beta2 version to find out if my registration problem would be solved.

After menuconfig, compilation is OK, but get following error when starting up : 

 c:/users/me/.espressif/tools/xtensa-esp32-elf/1.22.0-80-g6c4433a5-5.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-addr2line -pfiaC -e C:/msys32/home/me/esp-adf-v2.0-beta2/exa
mples/advanced_examples/voip/build/voip_app.elf 0x40078000: [Error 2] Het systeem kan het opgegeven bestand niet vinden (the systems cannot find the given file).
Note : I checked in the given directory, and the file "exists"

Any ideas on this ?
thanks in advance
best regards
Ludo Kustermans

**Comment by jason-mao** [comment]
@Patsjemoe Could you test with latest master?

**Comment by Patsjemoe** [comment]
hi,
where can I download this ?
what is the difference of master vs beta vs standaard release ?
regards

Op wo 12 feb. 2020 06:50 schreef maojianxin <notifications@github.com>:

**Comment by jason-mao** [comment]
@Patsjemoe You can follow the ADF [quick start](https://github.com/espressif/esp-adf#quick-start)clone the latest code and test. We are fix found bugs on master.

**Comment by Patsjemoe** [comment]
Installed v2. 0 final release, problem gone. Still issues with calling android phone, but that is another issue. This one can be closed. 
Thank you
