### ISSUE TITLE
[example] get-started/play_mp3_control - Restart Pipeline not working (AUD-1301)

### ISSUE THREAD

**Issue by oliverjc** [espressif/esp-adf#338]
**Board** LyraT v4.3
**Issue:** Pipeline does not restart when play button is pressed. 

**Fix:**
After line 153 we should add `audio_pipeline_wait_for_stop(pipeline);` to block until we're ready to resume the pipeline.

**Comment by jason-mao** [comment]
@oliverjc Thank you for your report.
