### ISSUE TITLE
some errors on compile player example (AUD-1319)

### ISSUE THREAD

**Issue by pilnikov** [espressif/esp-adf#343]
1.
![raw_stream](https://user-images.githubusercontent.com/25922873/74172881-d69f1300-4c52-11ea-8e3c-3960d79fe603.PNG)
because in esp-adf/components/bluetooth_service/CmakeLists.txt component link missing 
 in original 
set(COMPONENT_REQUIRES bt audio_sal audio_pipeline esp_peripherals)
should be
set(COMPONENT_REQUIRES bt audio_sal audio_pipeline esp_peripherals **audio_stream**)

2.
![dct](https://user-images.githubusercontent.com/25922873/74173138-62b13a80-4c53-11ea-82fa-5138f3c3f51b.PNG)
because ????? 
esp-adf/components/esp-adf-libs/esp_codec/lib/libesp-mp3.a is precompile and not open

**Comment by eclipsevl** [comment]
Tonight I've got same issue with pow, log10 functions, after workaround for these two linker failing on dct_16_opt. Seems like some library is not linked, but I can't find which one.

**Comment by pilnikov** [comment]
https://github.com/pilnikov/adf/tree/master/esp-adf/components/esp-adf-libs/esp_codec/lib
these working - checked

**Comment by eclipsevl** [comment]
> https://github.com/pilnikov/adf/tree/master/esp-adf/components/esp-adf-libs/esp_codec/lib
> these working - checked

Thanks! Indeed, these libs are compilable.
However I still missing log10 and pow functions - had to define it myself, and after that II'm getting following errors after pipeline start:

E (4117) STAGEFRIGHTMP3_DECODER: Encountered error reading when MP3 init
E (4127) AUDIO_ELEMENT: [mp3] AEL_STATUS_ERROR_OPEN
W (4137) AUDIO_ELEMENT: IN-[i2s] AEL_IO_ABORT

Idk if it is connected somehow to this issue.

**Comment by jason-mao** [comment]
@pilnikov Issue 1 is incoming fix. Issue 2,  are you used 5.2.0 toolchain works fine?

**Comment by jason-mao** [comment]
@eclipsevl 
> However I still missing log10 and pow functions - had to define it myself, and after that II'm getting following errors after pipeline start:
> 
> E (4117) STAGEFRIGHTMP3_DECODER: Encountered error reading when MP3 init
> E (4127) AUDIO_ELEMENT: [mp3] AEL_STATUS_ERROR_OPEN
> W (4137) AUDIO_ELEMENT: IN-[i2s] AEL_IO_ABORT
> 
> Idk if it is connected somehow to this issue.

Could you provide your detail logs?

**Comment by pilnikov** [comment]
> @pilnikov Issue 1 is incoming fix. Issue 2, are you used 5.2.0 toolchain works fine?

Yes, everything works except the above. I changed some things for this.

**Comment by eclipsevl** [comment]
> @eclipsevl
> 
> > However I still missing log10 and pow functions - had to define it myself, and after that II'm getting following errors after pipeline start:
> > E (4117) STAGEFRIGHTMP3_DECODER: Encountered error reading when MP3 init
> > E (4127) AUDIO_ELEMENT: [mp3] AEL_STATUS_ERROR_OPEN
> > W (4137) AUDIO_ELEMENT: IN-[i2s] AEL_IO_ABORT
> > Idk if it is connected somehow to this issue.
> 
> Could you provide your detail logs?

Sure.

This is compile log without pow, log10 defined in main.c:
https://pastebin.com/Q5djNzGh

My workaround:
https://pastebin.com/BwT7daMt

App log:
https://pastebin.com/mwEf0L9d

And audio init code. (Board initialization is ommited)
https://pastebin.com/05etDKEr

**Comment by pilnikov** [comment]
![image](https://user-images.githubusercontent.com/25922873/74622749-cfe93200-5163-11ea-932a-c408b8e912fb.png)
decision:
added line
#include "driver/gpio.h"
in file esp_peripherals.c

**Comment by jason-mao** [comment]
@pilnikov 

> ![image](https://user-images.githubusercontent.com/25922873/74622749-cfe93200-5163-11ea-932a-c408b8e912fb.png)
> decision:
> added line
> #include "driver/gpio.h"
> in file esp_peripherals.c

ADF support IDF v3.3 release only. Did you used that?

**Comment by pilnikov** [comment]
But does it really matter which version of IDF to use? Or in the v3.3 links organized differently?  Yes, I use version not 3.3 but 4.1. But someone promised up to version 4  in December.

**Comment by pilnikov** [comment]
Well, if #include "periph_gpio_isr.h"
  it is not right. Then maybe #include "periph_gpio_isr.h" instead? Because
     // TODO: Should we uninstall gpio isr service ??
     // TODO: Because gpio need for sdcard and gpio, then install isr here

**Comment by jason-mao** [comment]
@pilnikov 
> But does it really matter which version of IDF to use? Or in the v3.3 links organized differently? Yes, I use version not 3.3 but 4.1. But someone promised up to version 4 in December.

Sorry for late. It can be support IDF v4.x start 2a95e1f2c603d07f98735518295243cbdb2958ed

**Comment by pilnikov** [comment]
tnx for support

https://github.com/espressif/esp-adf/commit/9c06d63f38cddbef420af3aae78ba15709729b0c#commitcomment-37420385

&& with libesp-mp3.a questions remained

**Comment by jason-mao** [comment]
@pilnikov How to reproduce your mp3 issue?

> tnx for support
> 
> [9c06d63#commitcomment-37420385](https://github.com/espressif/esp-adf/commit/9c06d63f38cddbef420af3aae78ba15709729b0c#commitcomment-37420385)
> 
> && with libesp-mp3.a questions remained
Yes, we will fix that later.

**Comment by pilnikov** [comment]
i check it now - 
https://github.com/espressif/esp-adf-libs/commit/c7c8398e35cbe9949bd427ab42830ff6b6cdb3c1#commitcomment-37420679
