### ISSUE TITLE
Problem make flash monitor -j5 (AUD-1334)

### ISSUE THREAD

**Issue by HoneyPot2020** [espressif/esp-adf#346]
I am doing this on Windows 10 and the make flash monitor -j5  is not recognized.  The menuconfig for the mp3 player example came up fine, however the flash did not.  In the instructions it says to perform the following:
Build, Flash and Monitor
Now you can build, upload and check the application. Run:
make flash monitor -j5
In windows received the error:
'make' is not recognized as an internal or external command,
operable program or batch file.

What is the line I should put instead for windows?

**Comment by HoneyPot2020** [comment]
Fixed Solution: 
Used mingw32 for the make.

**Comment by jason-mao** [comment]
@HoneyPot2020 Thank you for your feedback.
