### ISSUE TITLE
Docker image for building (AUD-1340)

### ISSUE THREAD

**Issue by ftab** [espressif/esp-adf#347]
I am using a Docker image to build a combined IDF & ADF image. As of right now, it successfully builds my favorite example, pipeline_a2dp_sink_and_hfp, with make and cmake, so before it goes out of date I figured I'd contribute it and see if it makes sense to incorporate it into esp-adf.

I don't know where it best fits in your repo, but I'm using a simple GitLab repo to build and deploy to my local registry for quicker downloading on each computer that needs to build/flash/monitor ESP32 stuff.

I've mirrored it to our public GitLab here: https://gitlab.com/radiosound/adf

Let me know if there's a better way to do it. (e.g. do I still need the idf cloned separately as well since esp-adf incorporates it as a submodule?)

If you want, I can submit a PR to include it in tools/docker similar to how it is in esp-idf

**Comment by jason-mao** [comment]
@ftab Well done. Thank you.
