### ISSUE TITLE
Optimal implementation for audio streaming (AUD-1373)

### ISSUE THREAD

**Issue by sosaucily** [espressif/esp-adf#355]
We have a Lyra-T board and are trying to find the highest-quality way to stream audio from SPIFFS to the audio pipelines.

We currently notice a few gaps in the audio playback of 100-200ms, some little glitches that are maybe 20-50ms long, sometimes the audio plays back in slow-motion. 

However we've noticed changes and improvements to this when using various tweaks to our implementation. For example:

1. Loading the entire MP3 from SPIFFS into ram (on the external flash of the chip) made the playback quite a bit smoother. This tells me reading streaming data from SPIFFS is can be slow and can starve the audio playback task.

2. Lowering the task-switching time in sdkconfig from 10ms to 2ms helped, so perhaps we were waiting too long to switch back to this audio playback task.

Unfortunately we could find a way to pull more data from the file into the audio_pipeline buffer at a time. It seems this is set relative to the bitrate of the encoded audio and is not adjustable. Is that true?

Any other ideas? I was thinking to try another file format, perhaps ogg or flac. 

Has anyone else noticed these issues? Thanks!

**Comment by vikramdattu** [comment]
I think there are some issues with your implementation of pipelining?

Few things to check:
1. Set Flash speed to QIO/80MHz.
2. Check if CPU freq is 240MHz.

If this doesn't help, you should increase priority of SPIFFS read task and stream task to greater than decoder. Stream task prio to be highest of three.

ESP32 has 2 cores! Try pinning tasks to different cores. This will help if any CPU congestion.
