### ISSUE TITLE
 play_mp3 example  on LyraT board (AUD-1374)

### ISSUE THREAD

**Issue by embelgit** [espressif/esp-adf#356]
hello, 
i am trying to run the example of play_mp3 while i am doing make menuconfig i got  issue 
esp\esp-adf\examples\get-started\play_mp3>make menuconfig
0: cd: C:UsersHpDesktopespesp-adf: No such file or directory
esp\esp-idf/make/project.mk:114: *** IDF_PATH cannot contain colons. If overridi
ws, use MSYS Unix-style /c/dir instead of C:/dir.  Stop.
please help me out  I am beginner

**Comment by vaderj** [comment]
I was having the same issue and was able to resolve it by updating the ADF_PATH global variable

![image](https://user-images.githubusercontent.com/5408195/76171867-29ce8d80-614d-11ea-8d25-f925ec29d35d.png)

**Comment by vaderj** [comment]
I was able to fix these issues by :

1.) updating both the ADF_PATH and IDF_PATH global variables
2.) make clean

![image](https://user-images.githubusercontent.com/5408195/76171929-c1cc7700-614d-11ea-9830-36519486cbf3.png)
