### ISSUE TITLE
Fail: index is out of range, the min index is 1, the max index is 1 (AUD-1436)

### ISSUE THREAD

**Issue by lance-web** [espressif/esp-adf#363]
我在开发adf的asr时，出现了这个错误，请教大神怎么解决

**Comment by espressif-zhanghu** [comment]
We have fixed a new version of the ADF/ASR,  please test it again. Thank you.

**Comment by mohsenArjmand** [comment]
when in oracle-adf use create_at_range_index and raise "index is out of range" 
you must go to the that page and click on the table and in the binding 
change range index form 25 to null

**Comment by bobo-ba** [comment]
大佬 请问你最终是怎么解决这个问题的
