### ISSUE TITLE
adf框架下的ars语音例程的make menuconfig如何配置才能保证程序的运行 (AUD-1437)

### ISSUE THREAD

**Issue by lance-web** [espressif/esp-adf#364]
出现了检索错误的问题

**Comment by espressif-zhanghu** [comment]
seleck wake up wprd：

- If you want to use "nihaoxiaozhi" as a wakeup word, open menuconfig, go to  “Speech Recognition Configuration” and select: 

“Wake word engine” > WakeNet 5 (quantized)  （or > WakeNet 6 (quantized)）
Wake word name > nihaoxiaozhi

- If you want to use "ni hao xiao zhi" as a wakeup word, open menuconfig, go to Speech Recognition Configuration and select:

Wake word engine > WakeNet 5 (quantized)
Wake word name > hi jeson

- If you want to use "hi lexin" as a wakeup word, The default is "hi lexin".
