### ISSUE TITLE
lyrat_v4_3  Headphone plug problem (AUD-1656)

### ISSUE THREAD

**Issue by zhengjianxing** [espressif/esp-adf#382]
Hi,
in esp-adf\components\audio_hal\driver\es8388\headphone_detect.c
static void IRAM_ATTR headphone_gpio_intr_handler(void *arg)
{
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    xTimerResetFromISR(timer_headphone, &xHigherPriorityTaskWoken);
    if ( xHigherPriorityTaskWoken != pdFALSE ) {
        portYIELD_FROM_ISR();
    }
}

"Headphone_gpio_intr_handler"  triggering the call of "xTimerResetFromISR" by headset plugging and unplugging will cause the touch button to fail.I can't find out why.

**Comment by espressif-zhanghu** [comment]
@zhengjianxing  can I look at you log ?

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
