### ISSUE TITLE
LyraT Mini v1.2 not in menuconfig Audio HAL, buttons not working (AUD-1735)

### ISSUE THREAD

**Issue by rahulgkatre** [espressif/esp-adf#389]
I followed the instructions for pipline_bt_sink found here: https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_bt_sink

I am using the latest version of ESP-ADF and ESP-IDF v3.3.2. 

When asked to select a compatible audio board, I could not find the LyraT Mini v1.2 in menuconfig > Audio HAL. I did find LyraT Mini v1.1, so I used that and the BT audio from my phone was able to play on a connected speaker.

However, none of the buttons (which are supposed to function according to that guide) were functional, which I suspect is because the LyraT Mini v1.2 is not part of the compatible audio board list and the v1.1 does not have the same button pinout. 

Would it be possible to add the v1.2 board to the list of compatible audio boards in menuconfig?

**Comment by espressif-zhanghu** [comment]
thanks.  LyraT Mini v1.2 button attribute is ADC, and Not added before.
