### ISSUE TITLE
Function "audio_element_resume()" may cause block (AUD-1781)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-adf#395]
Hi,

In commit 51f8e6c
File ``esp-adf/components/audio_pipeline/audio_element.c``
Function ``audio_element_process_running()``
Line ``311``
``audio_element_resume(el, 0, 0)`` cause a block of about ``DEFAULT_MAX_WAIT_TIME``
Because ``audio_element_process_running()`` be called in ``audio_element_task()``.

Should be changed to ``audio_element_cmd_send(el, AEL_MSG_CMD_RESUME)``.

Test url: ``http://open.ls.qingting.fm/live/332/64k.m3u8?format=ts``

**Comment by jason-mao** [comment]
@xiruilin Yes.We are found  this issue too. Fix is coming.
