### ISSUE TITLE
ESP32-LyraT-Mini: Blink example doesn't start unless pressing RESET button (AUD-1809)

### ISSUE THREAD

**Issue by menway** [espressif/esp-adf#398]
Hello,
I just bought an ESP32-LyraT-Mini board and flashed the blink example program under esp-idf repository. When the board is connected to the host computer and running by "make flash monitor" command, the blinking function works fine. But when I only connect the power cable, the board is "idle" and doesn't blink. After manually pressing the RESET button, it starts blinking.

video: https://drive.google.com/file/d/1OFcvq2AEqKQzyI-GyT05DoX1OxfXq2OJ/view?usp=sharing

My question is: is this a correct behavior, or did I miss anything? How to make it running as soon as I plug in a power cable? Thanks.

**Comment by espressif-zhanghu** [comment]
@menway  thank you , we will fix it

**Comment by Yohannfra** [comment]
Hello @jason-mao did you fix it ? I still have the exact same issue.
Thanks

**Comment by HengYongChao** [comment]
Hi @Yohannfra 

I'v tried on ESP32-Lyrat-mini v1.2, set blink led GPIO22, then flash the get-started/blink example, it works fine.

IDF V3.3.5 and IDF V4.2.2 both work good. Have you changed the restart behavior in menuconfig?

**Comment by Yohannfra** [comment]
No i didn't change the restard behavior.
When you flash the example if you disconnect the esp32 and close the idf.py monitor then reconnect the esp32 does it start blinking right away? 

Thanks

**Comment by Yohannfra** [comment]
What variables in menuconfig change the restart behavior @HengYongChao ? 
Thanks

**Comment by Yohannfra** [comment]
So the issue is caused by the C9 capacitor on the Lyrat-mini being too small (1uF). 
To fix this issue I had to solder a bigger (I used a 220uF) capacitor in parallel with the C9 capacitor.

**Comment by HengYongChao** [comment]
Hi @Yohannfra 

After replacing a larger capacitor, your board can be reset by the software correctly? If yes, it seems that the capacitor of the reset circuit is aging.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.

**Comment by RuvanMK** [comment]
Update, I can see the C9 cap when zooming in on the schematic PDF https://dl.espressif.com/dl/schematics/Layout_ESP32-LyraT-Mini_V1.2_20220317.pdf

I'm still wondering if this will be fixed in a future board revision and whether the PCB design files are available anywhere. Thanks!

**Comment by RuvanMK** [comment]
Second update, while the larger cap in parallel with C9 does cause the board to run the main program at boot, it stops the board from being able to be put into flashing mode either by the python flasher or by the buttons on the board.

**Comment by EyalSi** [comment]
Just got an ESP32-LyraT-Mini V1.2 with the exact same problem.
For me, it makes the board useless... 
Is there another solution for that other than soldering another capacitor to C9 (it is so tiny!)?

**Comment by jbobrow** [comment]
@espressif-zhanghu, did y'all end up fixing this? If so, what is the solution? I have a number of these boards and would love to be able to have them boot up as expected upon plugging them in.

@Yohannfra I am curious to know if the 220µF capacitor was a reliable solution. I have not had any luck with consistent boot by increasing the C9 capacitor.

**Comment by Yohannfra** [comment]
Hello @jbobrow, it's been a long time but if I remember correctly yes this solution worked for us and the board booted correctly.

**Comment by jbobrow** [comment]
Thanks @Yohannfra! would love to hear from someone at Espressif for the reasoning on this if it is in fact the suggested solution. In the documentation for the boot sequence, it looks like 50µs is the amount of delay needed, which would support the board's original hardware, but in reality it does seem that a much larger capacitor is necessary. Would love to know the failure point so that I can plan for this module in a production device. The question remains, is this a solution that addresses the root cause or a work around?
