### ISSUE TITLE
audio_hal/driver/dac ?

### ISSUE THREAD

**Issue by pcbreflux** [espressif/esp-adf#4]
Is there a plan to build a DAC driver for i.e. the Project Minimum Design  https://esp-adf.readthedocs.io/en/latest/design-guide/project-design.html#project-minimum ? 
Would this added to audio_hal_codecs_default ?

**Comment by jason-mao** [comment]
Hi pcbreflux

Sure,  DAC will be implement a stream soon.

**Comment by pcbreflux** [comment]
Thank you.

**Comment by krzychb** [comment]
Hi @pcbreflux,

DAC support has been implemented with 0311afd31452c4d6ba9b8be57d5f9f8d5fac5fe2
Example is on the way :)
