### ISSUE TITLE
DuerOs

### ISSUE THREAD

**Issue by wenkumk** [espressif/esp-adf#40]
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:5468
load:0x40078000,len:0
load:0x40078000,len:12464
entry 0x40078fbc
[0;32mI (28) boot: ESP-IDF v3.0.1 2nd stage bootloader[0m
[0;32mI (28) boot: compile time 14:53:23[0m
[0;32mI (30) boot: Enabling RNG early entropy source...[0m
[0;32mI (33) boot: SPI Speed      : 80MHz[0m
[0;32mI (37) boot: SPI Mode       : DIO[0m
[0;32mI (41) boot: SPI Flash Size : 4MB[0m
[0;32mI (45) boot: Partition Table:[0m
[0;32mI (48) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (56) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (63) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (71) boot:  2 factory          factory app      00 00 00010000 00100000[0m
[0;32mI (78) boot: End of partition table[0m
[0;32mI (82) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x43f28 (278312) map[0m
[0;32mI (172) esp_image: segment 1: paddr=0x00053f50 vaddr=0x3ffb0000 size=0x03844 ( 14404) load[0m
[0;32mI (177) esp_image: segment 2: paddr=0x0005779c vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (179) esp_image: segment 3: paddr=0x00057ba4 vaddr=0x40080400 size=0x0846c ( 33900) load[0m
[0;32mI (199) esp_image: segment 4: paddr=0x00060018 vaddr=0x400d0018 size=0xfa5a4 (1025444) map[0m
[0;32mI (497) esp_image: segment 5: paddr=0x0015a5c4 vaddr=0x4008886c size=0x09070 ( 36976) load[0m
[0;32mI (510) esp_image: segment 6: paddr=0x0016363c vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;31mE (511) esp_image: Image length 1390176 doesn't fit in partition length 1048576[0m
[0;31mE (516) boot: Factory app partition is not bootable[0m
[0;31mE (522) boot: No bootable app partitions in the partition table[0m
user code done
这是为什么呢，其它的例程都可以，就这个不行。

**Comment by jason-mao** [comment]
@wenkumk 
It's because of  image size out of range. Please increase partition table size to 2M Byte.
`$IDF_PATH/components/partition_table/partitions_singleapp.csv`
```c
# Name,   Type, SubType, Offset,  Size, Flags
# Note: if you change the phy_init or app partition offset, make sure to change the offset in Kconfig.projbuild
nvs,      data, nvs,     0x9000,  0x6000,
phy_init, data, phy,     0xf000,  0x1000,
factory,  app,  factory, 0x10000, 2M,
```
