### ISSUE TITLE
rec_engine_data_read 返回值异常？ (AUD-1826)

### ISSUE THREAD

**Issue by junbowu** [espressif/esp-adf#404]
在通一次语音唤醒，读取数据时，当	rec_engine_data_read 返回值 翻转后(比如之前是连续的1~70)，然后下一次变成了0，此时其实并没有人说话(或者发出声音)rec_engine_data_read 的返回值会一直增加。这是一个异常么？
Line 1: 22:05:20.639] [0;32mI (85264) DUEROS: Recv Que DUER_CMD_START[0m
	Line 2: [22:05:20.648] [0;32mI (85268) DUEROS: index = 1
	Line 4: [22:05:20.648] [0;32mI (85271) DUEROS: index = 2
	Line 6: [22:05:20.659] [0;32mI (85275) DUEROS: index = 3
	Line 8: [22:05:20.659] [0;32mI (85279) DUEROS: index = 4
	Line 10: [22:05:20.659] [0;32mI (85282) DUEROS: index = 5
	Line 12: [22:05:20.669] [0;32mI (85286) DUEROS: index = 6
	Line 14: [22:05:20.669] [0;32mI (85289) DUEROS: index = 1
	Line 16: [22:05:20.669] [0;32mI (85357) DUEROS: index = 2
	Line 18: [22:05:20.726] [0;32mI (85445) DUEROS: index = 3
	Line 20: [22:05:20.815] [0;32mI (85533) DUEROS: index = 4
	Line 22: [22:05:20.903] [0;32mI (85626) DUEROS: index = 5
	Line 24: [22:05:20.995] [0;32mI (85714) DUEROS: index = 6
	Line 27: [22:05:21.176] [0;32mI (85808) DUEROS: index = 7
	Line 29: [22:05:21.176] [0;32mI (85895) DUEROS: index = 8
	Line 31: [22:05:21.264] [0;32mI (85989) DUEROS: index = 9
	Line 33: [22:05:21.357] [0;32mI (86076) DUEROS: index = 10
	Line 35: [22:05:21.445] [0;32mI (86170) DUEROS: index = 11
	Line 37: [22:05:21.539] [0;32mI (86258) DUEROS: index = 12
	Line 40: [22:05:21.708] [0;32mI (86339) DUEROS: index = 13
	Line 42: [22:05:21.708] [0;32mI (86439) DUEROS: index = 14
	Line 44: [22:05:21.808] [0;32mI (86520) DUEROS: index = 15
	Line 46: [22:05:21.889] [0;32mI (86620) DUEROS: index = 16
	Line 48: [22:05:21.989] [0;32mI (86701) DUEROS: index = 17
	Line 51: [22:05:22.180] [0;32mI (86801) DUEROS: rec_engine_cb - REC_EVENT_VAD_STOP, state:4[0m
	Line 52: [22:05:22.180] [0;32mI (86803) DUEROS: index = 0
	Line 54: [22:05:22.187] [0;32mI (86806) DUEROS: Dueros DUER_CMD_STOP[0m
	Line 60: [22:05:27.209] [0;32mI (91834) DUEROS: rec_engine_cb - REC_EVENT_VAD_START[0m
	Line 61: [22:05:27.209] [0;32mI (91834) DUEROS: RECEIVE DUER_CMD_START
	Line 63: [22:05:27.209] [0;32mI (91834) DUEROS: Recv Que DUER_CMD_START[0m
	Line 64: [22:05:27.220] [0;32mI (91838) DUEROS: index = 60
	Line 66: [22:05:27.220] [0;32mI (91841) DUEROS: index = 61
	Line 68: [22:05:27.229] [0;32mI (91845) DUEROS: index = 62
	Line 70: [22:05:27.229] [0;32mI (91849) DUEROS: index = 63
	Line 72: [22:05:27.229] [0;32mI (91852) DUEROS: index = 64
	Line 74: [22:05:27.240] [0;32mI (91856) DUEROS: index = 65
	Line 76: [22:05:27.240] [0;32mI (91860) DUEROS: index = 66
	Line 78: [22:05:27.240] [0;32mI (91864) DUEROS: index = 67
	Line 80: [22:05:27.248] [0;32mI (91867) DUEROS: index = 68
	Line 82: [22:05:27.248] [0;32mI (91871) DUEROS: index = 69
	Line 84: [22:05:27.258] [0;32mI (91875) DUEROS: index = 70
	Line 86: [22:05:27.258] [0;32mI (91879) DUEROS: index = 1
	Line 88: [22:05:27.258] [0;32mI (91933) DUEROS: index = 2
	Line 90: [22:05:27.303] [0;32mI (92014) DUEROS: index = 3
	Line 92: [22:05:27.383] [0;32mI (92102) DUEROS: index = 4
	Line 94: [22:05:27.470] [0;32mI (92195) DUEROS: index = 5
	Line 96: [22:05:27.564] [0;32mI (92283) DUEROS: index = 6
	Line 99: [22:05:27.745] [0;32mI (92376) DUEROS: index = 7
	Line 101: [22:05:27.745] [0;32mI (92464) DUEROS: index = 8
	Line 103: [22:05:27.833] [0;32mI (92558) DUEROS: index = 9
	Line 105: [22:05:27.927] [0;32mI (92645) DUEROS: index = 10
	Line 107: [22:05:28.014] [0;32mI (92733) DUEROS: index = 11
	Line 109: [22:05:28.103] [0;32mI (92826) DUEROS: index = 12
	Line 112: [22:05:28.283] [0;32mI (92914) DUEROS: index = 13
	Line 114: [22:05:28.283] [0;32mI (93008) DUEROS: index = 14
	Line 116: [22:05:28.377] [0;32mI (93095) DUEROS: index = 15
	Line 118: [22:05:28.464] [0;32mI (93189) DUEROS: index = 16
	Line 120: [22:05:28.558] [0;32mI (93277) DUEROS: index = 17
	Line 122: [22:05:28.646] [0;32mI (93370) DUEROS: index = 18
	Line 125: [22:05:28.826] [0;32mI (93458) DUEROS: index = 19
	Line 127: [22:05:28.826] [0;32mI (93539) DUEROS: index = 20
	Line 129: [22:05:28.908] [0;32mI (93639) DUEROS: index = 21
	Line 131: [22:05:29.008] [0;32mI (93720) DUEROS: index = 22
	Line 133: [22:05:29.089] [0;32mI (93820) DUEROS: index = 23
	Line 135: [22:05:29.189] [0;32mI (93902) DUEROS: index = 24
	Line 138: [22:05:29.371] [0;32mI (94001) DUEROS: index = 25
	Line 140: [22:05:29.371] [0;32mI (94083) DUEROS: index = 26
	Line 142: [22:05:29.454] [0;32mI (94170) DUEROS: index = 27
	Line 144: [22:05:29.540] [0;32mI (94264) DUEROS: index = 28
	Line 146: [22:05:29.634] [0;32mI (94352) DUEROS: index = 29
	Line 148: [22:05:29.723] [0;32mI (94445) DUEROS: index = 30
	Line 151: [22:05:29.901] [0;32mI (94533) DUEROS: index = 31
	Line 153: [22:05:29.904] [0;32mI (94626) DUEROS: index = 32
	Line 155: [22:05:29.996] [0;32mI (94714) DUEROS: index = 33
	Line 157: [22:05:30.084] [0;32mI (94808) DUEROS: index = 34
	Line 159: [22:05:30.178] [0;32mI (94895) DUEROS: index = 35
	Line 161: [22:05:30.265] [0;32mI (94983) DUEROS: index = 36
	Line 164: [22:05:30.446] [0;32mI (95076) DUEROS: index = 37
	Line 166: [22:05:30.446] [0;32mI (95164) DUEROS: index = 38
	Line 168: [22:05:30.535] [0;32mI (95258) DUEROS: index = 39
	Line 170: [22:05:30.627] [0;32mI (95345) DUEROS: index = 40
	Line 172: [22:05:30.715] [0;32mI (95439) DUEROS: index = 41
	Line 174: [22:05:30.809] [0;32mI (95527) DUEROS: index = 42
	Line 177: [22:05:30.978] [0;32mI (95608) DUEROS: index = 43
	Line 179: [22:05:30.978] [0;32mI (95708) DUEROS: index = 44
	Line 181: [22:05:31.080] [0;32mI (95795) DUEROS: index = 45
	Line 183: [22:05:31.165] [0;32mI (95889) DUEROS: index = 46
	Line 185: [22:05:31.265] [0;32mI (95976) DUEROS: index = 47
	Line 187: [22:05:31.346] [0;32mI (96070) DUEROS: index = 48
	Line 190: [22:05:31.528] [0;32mI (96158) DUEROS: index = 49
	Line 192: [22:05:31.528] [0;32mI (96251) DUEROS: index = 50
	Line 194: [22:05:31.621] [0;32mI (96340) DUEROS: index = 51
	Line 196: [22:05:31.710] [0;32mI (96420) DUEROS: index = 52
	Line 198: [22:05:31.790] [0;32mI (96520) DUEROS: index = 53
	Line 200: [22:05:31.890] [0;32mI (96602) DUEROS: index = 54
	Line 203: [22:05:32.071] [0;32mI (96701) DUEROS: index = 55
	Line 205: [22:05:32.071] [0;32mI (96783) DUEROS: index = 56
	Line 207: [22:05:32.153] [0;32mI (96883) DUEROS: index = 57
	Line 209: [22:05:32.253] [0;32mI (96964) DUEROS: index = 58
	Line 211: [22:05:32.334] [0;32mI (97052) DUEROS: index = 59
	Line 213: [22:05:32.422] [0;32mI (97145) DUEROS: index = 60
	Line 216: [22:05:32.601] [0;32mI (97233) DUEROS: index = 61
	Line 218: [22:05:32.603] [0;32mI (97326) DUEROS: index = 62
	Line 220: [22:05:32.696] [0;32mI (97414) DUEROS: index = 63
	Line 222: [22:05:32.784] [0;32mI (97508) DUEROS: index = 64
	Line 224: [22:05:32.879] [0;32mI (97595) DUEROS: index = 65
	Line 226: [22:05:32.966] [0;32mI (97689) DUEROS: index = 66
	Line 229: [22:05:33.147] [0;32mI (97777) DUEROS: index = 67
	Line 231: [22:05:33.147] [0;32mI (97864) DUEROS: index = 68
	Line 233: [22:05:33.234] [0;32mI (97958) DUEROS: index = 69
	Line 235: [22:05:33.327] [0;32mI (98045) DUEROS: index = 70
	Line 237: [22:05:33.415] [0;32mI (98139) DUEROS: index = 71
	Line 239: [22:05:33.509] [0;32mI (98226) DUEROS: index = 72
	Line 242: [22:05:33.690] [0;32mI (98320) DUEROS: index = 73
	Line 244: [22:05:33.690] [0;32mI (98408) DUEROS: index = 74
	Line 246: [22:05:33.778] [0;32mI (98490) DUEROS: index = 75
	Line 248: [22:05:33.860] [0;32mI (98589) DUEROS: index = 76
	Line 250: [22:05:33.959] [0;32mI (98670) DUEROS: index = 77
	Line 252: [22:05:34.040] [0;32mI (98770) DUEROS: index = 78
	Line 255: [22:05:34.220] [0;32mI (98852) DUEROS: index = 79
	Line 257: [22:05:34.222] [0;32mI (98951) DUEROS: index = 80
	Line 259: [22:05:34.321] [0;32mI (99033) DUEROS: index = 81
	Line 261: [22:05:34.403] [0;32mI (99133) DUEROS: index = 82
	Line 263: [22:05:34.502] [0;32mI (99214) DUEROS: index = 83
	Line 265: [22:05:34.584] [0;32mI (99302) DUEROS: index = 84
	Line 268: [22:05:34.765] [0;32mI (99395) DUEROS: index = 85
	Line 270: [22:05:34.765] [0;32mI (99483) DUEROS: index = 86
	Line 272: [22:05:34.853] [0;32mI (99576) DUEROS: index = 87
	Line 274: [22:05:34.946] [0;32mI (99664) DUEROS: index = 88
	Line 276: [22:05:35.034] [0;32mI (99758) DUEROS: index = 89
	Line 278: [22:05:35.127] [0;32mI (99845) DUEROS: index = 90
	Line 281: [22:05:35.301] [0;32mI (99933) DUEROS: index = 91
	Line 283: [22:05:35.303] [0;32mI (100027) DUEROS: index = 92
	Line 285: [22:05:35.397] [0;32mI (100114) DUEROS: index = 93
	Line 287: [22:05:35.484] [0;32mI (100208) DUEROS: index = 94
	Line 289: [22:05:35.578] [0;32mI (100295) DUEROS: index = 95
	Line 291: [22:05:35.665] [0;32mI (100389) DUEROS: index = 96
	Line 294: [22:05:35.847] [0;32mI (100476) DUEROS: index = 97
	Line 296: [22:05:35.847] [0;32mI (100570) DUEROS: index = 98
	Line 298: [22:05:35.940] [0;32mI (100658) DUEROS: index = 99
	Line 300: [22:05:36.027] [0;32mI (100739) DUEROS: index = 100
	Line 302: [22:05:36.109] [0;32mI (100839) DUEROS: index = 101
	Line 304: [22:05:36.210] [0;32mI (100920) DUEROS: index = 102
	Line 307: [22:05:36.390] [0;32mI (101020) DUEROS: index = 103
	Line 309: [22:05:36.390] [0;32mI (101101) DUEROS: index = 104
	Line 311: [22:05:36.472] [0;32mI (101201) DUEROS: index = 105
	Line 313: [22:05:36.572] [0;32mI (101283) DUEROS: index = 106
	Line 315: [22:05:36.653] [0;32mI (101370) DUEROS: index = 107
	Line 317: [22:05:36.740] [0;32mI (101464) DUEROS: index = 108
	Line 320: [22:05:36.921] [0;32mI (101551) DUEROS: index = 109
	Line 322: [22:05:36.921] [0;32mI (101645) DUEROS: index = 110
	Line 324: [22:05:37.015] [0;32mI (101733) DUEROS: index = 111
	Line 326: [22:05:37.102] [0;32mI (101826) DUEROS: index = 112
	Line 328: [22:05:37.196] [0;32mI (101914) DUEROS: index = 113
	Line 330: [22:05:37.284] [0;32mI (102008) DUEROS: index = 114
	Line 333: [22:05:37.465] [0;32mI (102095) DUEROS: index = 115

**Comment by espressif-zhanghu** [comment]
唤醒除了语音还有服务器端调用唤醒。需确认是否服务器端唤醒。

**Comment by junbowu** [comment]
测试的时候是把服务器是未连接的(和服务器端应该没什么关系)，只是为了测试唤醒和record，主要是record回来的数据的index看着不太对

**Comment by espressif-zhanghu** [comment]
@junbowu 确认一下，有没有连接 dueros 服务器？因为没有连接服务器，下面的打印确实属于不正常。

**Comment by junbowu** [comment]
没有连接服务器

**Comment by junbowu** [comment]
我本意是想测试record这个模块，实现离线唤醒后，读取录音数据给baidu sr来做在线语音识别，用了dueros这个例子但dueros服务器并没有连接(相关的login和dueros状态修改了下，record返回来的数据大部分时间都是正常的，偶现上面提的问题，感觉是内部的cycle buffer read/write index乱了)

**Comment by espressif-zhanghu** [comment]
@junbowu  如果只想使用 “唤醒”，读取音频数据，可以考虑参考 examples/speech_recognition/asr，因为这个可以看见源码。
从log 没法看出问题出在哪了，还有 index 只有在 唤醒结束 或者 VAD 检测结束会重新初始化。

**Comment by junbowu** [comment]
好的，谢谢！
