### ISSUE TITLE
最近下载了duer的profile文件，而且倒入到dureos的目录下，发现无法链接，现在的profile 文件是不是在百度下面的设备端开发->下载设备配置文件。这个链接? (AUD-1899)

### ISSUE THREAD

**Issue by xpdrycry** [espressif/esp-adf#408]
![Screenshot_2020-06-02 DuerOS开放平台 控制台](https://user-images.githubusercontent.com/55245334/83542303-58ca8480-a52d-11ea-84d9-800fb7ba7835.png)

使用duer文件目录下面的文件，编译到板子里面以后老是出现

I (258735,tid:3ffc5b98) lightduer_engine.c( 220):duer_engine_start, g_handler:3F806D30, length:23992, profile:3F81194C
W (258888) DISPATCHER_DUEROS: duer_callback: type:0, source:0x3f806b90 data:2, data_len:0
E (258740,tid:3ffc5b98) lightduer_ca.c( 645):    create the configuation failed...
I (258754,tid:3ffc5b98) lightduer_ds_log_cache.c(  45):cached tracecode: 0x12010301
I (258762,tid:3ffc5b98) lightduer_connagent.c( 160):=====> event: 1[DUER_EVT_START], status: -18
E (258771,tid:3ffc5b98) lightduer_connagent.c( 207):start fail! status:-18
E (258777,tid:3ffc5b98) lightduer_connagent.c( 286):Action failed: event: 1, status: -18
W (258785,tid:3ffc5b98) lightduer_engine.c( 812):duer_engine_stop has stopped
I (258792,tid:3ffc5b98) lightduer_connagent.c( 160):=====> event: 5[DUER_EVT_STOP], status: -18
I (258800,tid:3ffc5b98) lightduer_connagent.c( 257):connect stopped, status:-18!!
E (258959) DUEROS: event: 1
E (258963) DUEROS: event: DUER_EVENT_STOPPED
W (258968) DISPATCHER_DUEROS: duer_callback: type:0, source:0x3f806b90 data:1, data_len:0
W (258817,tid:3ffc5b98) lightduer_events.c(  80):[lightduer_ca] <== event end = 400FABC8, timespent = 82
W (258980) DISPATCHER_DUEROS: reason:0
E (258990) DISPATCHER_DUEROS: Dueros reconnect failed,time num:128 
提示profile文件有问题，请问，现在的profile 文件是不是在百度下面的设备端开发->下载设备配置文件。这个链接?

**Comment by jason-mao** [comment]
DuerOS  profile 申请入口已关闭，建议使用这个[ESP32-Korvo-Du1906 example](https://github.com/espressif/esp-adf/tree/master/examples/korvo_du1906) 使用百度服务
