### ISSUE TITLE
lyrat 4.3 sd card in 4-bit mode (AUD-1940)

### ISSUE THREAD

**Issue by Maobuff** [espressif/esp-adf#411]
I could not find how to use sdcard in 4bit mode, besides putting dip 1 and 2 in ON possition. Am I missing something?

**Comment by jason-mao** [comment]
@Maobuff Did you change `sdcard_mount`to `SDMMC_HOST_FLAG_4BIT` in  `adf/components/esp_peripherals/lib/sdcard/sdcard.c`?

**Comment by Maobuff** [comment]
@jason-mao Yes, and changed slot_config.width to 4. Didn't get any improvement at read speed.

**Comment by jason-mao** [comment]
@Maobuff You can replace `fopen, fread` in your testing to improve read speed.
