### ISSUE TITLE
Get ESP-ADF working with AWS-RTOS (AUD-2006)

### ISSUE THREAD

**Issue by dev-techshlok** [espressif/esp-adf#414]
Hello,

I am trying to combine ESP-AWS-RTOS and ESP-ADF. To play some audio files from sd-card and use amazon-RTOS services in my application.

But i am facing issues calling components of esp-adf to aws-rtos.

I have also opened an issue on their github https://github.com/aws/amazon-freertos/issues/2039

I am facing this error there https://github.com/aws/amazon-freertos/issues/2039#issuecomment-635919099

**Comment by jason-mao** [comment]
Closed due to this topic has become inactive. Please reopen this if you have any questions or need any further assistance.
