### ISSUE TITLE
error: patch failed: (AUD-2034)

### ISSUE THREAD

**Issue by ZYQ-FEIYUE** [espressif/esp-adf#417]
$ git apply ./idf_v3.3_freertos.patch
error: patch failed: components/freertos/include/freertos/task.h:674
error: components/freertos/include/freertos/task.h: patch does not apply
error: patch failed: components/freertos/tasks.c:756
error: components/freertos/tasks.c: patch does not apply

打补丁失败，我应该怎么打补丁
patch failed, how can I do it

**Comment by jason-mao** [comment]
@ZYQ-FEIYUE 
参考如下命令：
`cd $IDF_PATH`
`git apply $ADF_PATH/idf_patches/idf_v3.3_freertos.patch`

**Comment by alibukharai** [comment]
I am facing the same issue don't know why the patch is not applied. Can you help me to this problem I am new here

Thanks 

![image](https://user-images.githubusercontent.com/60029742/182807398-86c56031-dce4-422e-9853-802a70abab55.png)
