### ISSUE TITLE
amazon/google example (AUD-2038)

### ISSUE THREAD

**Issue by tcpipchip** [espressif/esp-adf#419]
Hi,

Do you intend to import this example to this github ?

https://github.com/espressif/esp-va-sdk

Then will be complete!

**Comment by vikramdattu** [comment]
@tcpipchip there are no immediate plans to move `esp-va-sdk` to ADF.

Do you have specific requirement for this?

**Comment by tcpipchip** [comment]
@vikramdattu 
no more!

**Btw, some more news coming to ESP-VA-SDK ?**

Amazon and Google working assistant working.

Sometimes the GOOGLE crash. But good for tests.

Think about WAKEUP option to GOOGLE.

Thanks to answer, i thought that this esp-va-sdk discussion was dead

**Comment by vikramdattu** [comment]
Cannot say anything concrete, but we do keep updating for features/bug fixes.

Can you please share logs for GVA crash?

You can use `Alexa` WW for Google.
There are no immediate plans to update it with different WW.

**Comment by tcpipchip** [comment]
@vikramdattu 

Good morning!

Nice that there are updates!

Not got more error! Maybe a power supply problem!

Thanks to info about use Alexa WW.

Someday i talked Alexa and the system pop up and i hadnt understand :)

Is it possible use the Alexa/Google to only form the Phrase and not process it ?
For example, i say Turn On the Lamp, but i dont want the Alexa/Google process this order, just back me the text ?

**Comment by tcpipchip** [comment]
ops, got a error
![image](https://user-images.githubusercontent.com/11488460/87036013-8c4d9e00-c1c0-11ea-9d0a-942bcd5ffc1b.png)
But still answer to voice! This good!
