### ISSUE TITLE
pipeline_sdcard_mp3_control example

### ISSUE THREAD

**Issue by RemyEE** [espressif/esp-adf#42]
Anyone have pipeline_sdcard_mp3_control example works properly on latest update?
I tried the example, it worked well (before adding google translate function, I think).
After update the repository, touching SET touch pad just make the pipeline stop. I have to touch SET pad 2 times for playing next song.

Output log:
I (308) SDCARD_MP3_CONTROL_EXAMPLE: [1.0] Initialize peripherals management
I (308) SDCARD_MP3_CONTROL_EXAMPLE: [1.1] Start SD card peripheral
I (318) SDCARD_MP3_CONTROL_EXAMPLE: [1.2] Start SD card peripheral
I (428) SDCARD_MP3_CONTROL_EXAMPLE: [1.3] Initialize Touch peripheral
I (428) SDCARD_MP3_CONTROL_EXAMPLE: [1.4] Start touch peripheral
I (428) SDCARD_MP3_CONTROL_EXAMPLE: [ 2 ] Start codec chip
**E (428) gpio: gpio_install_isr_service(406): GPIO isr service already installed**
I (458) SDCARD_MP3_CONTROL_EXAMPLE: [3.0] Create audio pipeline for playback
I (458) SDCARD_MP3_CONTROL_EXAMPLE: [3.1] Create i2s stream to write data to codec chip
I (468) SDCARD_MP3_CONTROL_EXAMPLE: [3.2] Create mp3 decoder to decode mp3 file
I (478) SDCARD_MP3_CONTROL_EXAMPLE: [3.3] Register all elements to audio pipeline
I (488) SDCARD_MP3_CONTROL_EXAMPLE: [3.4] Link it together [my_sdcard_read_cb]-->mp3_decoder-->i2s_
stream-->[codec_chip]
I (498) SDCARD_MP3_CONTROL_EXAMPLE: [4.0] Setup event listener
I (498) SDCARD_MP3_CONTROL_EXAMPLE: [4.1] Listen for all pipeline events
I (508) SDCARD_MP3_CONTROL_EXAMPLE: [4.2] Listening event from peripherals
W (518) SDCARD_MP3_CONTROL_EXAMPLE: [ 5 ] Tap touch buttons to control music player:
W (528) SDCARD_MP3_CONTROL_EXAMPLE:       [Play] to start, pause and resume, [Set] next song.
W (538) SDCARD_MP3_CONTROL_EXAMPLE:       [Vol-] or [Vol+] to adjust volume.
I (2858) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] [Set] touch tap event
I (2858) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Finishing current song
I (3218) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Received music info from mp3 decoder, sample_rates=44100
, bits=16, ch=2
I (6918) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] [Set] touch tap event
I (6918) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Finishing current song
**E (6948) MP3_DECODER: output aborted 1024**
I (9798) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] [Set] touch tap event
I (9798) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Finishing current song
I (9848) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Received music info from mp3 decoder, sample_rates=44100
, bits=16, ch=2
I (12438) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] [Set] touch tap event
I (12438) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Finishing current song
**E (12468) MP3_DECODER: output aborted 2048**
I (13998) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] [Set] touch tap event
I (13998) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Finishing current song
I (14048) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Received music info from mp3 decoder, sample_rates=4410
0, bits=16, ch=2
I (16518) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] [Set] touch tap event
I (16518) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Finishing current song
**E (16538) MP3_DECODER: output aborted 2560**
I (18258) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] [Set] touch tap event
I (18258) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Finishing current song
I (18318) SDCARD_MP3_CONTROL_EXAMPLE: [ * ] Received music info from mp3 decoder, sample_rates=4410
0, bits=16, ch=2

**Comment by krzychb** [comment]
HI @RemyEE,
Thank you for reporting this issue. I will look into it and resolve.

**Comment by paulsykes** [comment]
Hi @krzychb @tuanpmt,

pipeline_sdcard_mp3_control example is broken by the following commit. Preventing advancing to the next track when pressing the 'Set' button.

I tracked the problem down to this commit https://github.com/espressif/esp-adf/commit/d8a821879f7e591f4b941427513a037043e286d6#diff-ac6e633e7a8d9bb1936675a139649dd1L884

Whilst this commit does add a google translate device example, it also makes some changes to resetting buffers in components/audio_pipeline/audio_pipeline.c

Reverting this file, fixes the above functionality.

**Comment by tuanpmt** [comment]
Hi @paulsykes 

This issue was resolve by @krzychb internally and will be synchronized soon

Thank you for reporting this
