### ISSUE TITLE
https://github.com/espressif/esp-adf/tree/master/examples/cli in this instance ESP32 - Lyrat V4.3 play https://streamingv2.shoutcast.com/oroyawave  is very sticky (AUD-2092)

### ISSUE THREAD

**Issue by snailwft** [espressif/esp-adf#426]
Hi, I use the https://github.com/espressif/esp-adf/tree/master/examples/cli in this instance ESP32 - Lyrat V4.3 play https://streamingv2.shoutcast.com/oroyawave  is very sticky. How can you play it better.

**Comment by jason-mao** [comment]
Closed, please refer  to #297
