### ISSUE TITLE
Com port settings for Lyrat

### ISSUE THREAD

**Issue by carbonadam** [espressif/esp-adf#43]
Ive got my comport setup in menuconfig but always seem to get the following error.  Menu config is COM10 

A fatal error occurred: Failed to connect to ESP32: Invalid head of packet ('\x08')
make: *** [/home/woodtiger/esp/esp-adf/esp-idf/components/esptool_py/Makefile.projbuild:55: flash] Error 2

**Comment by krzychb** [comment]
Hi @carbonadam,

Could you verify if serial communication with the board is [operational](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/establish-serial-connection.html) ?

**Comment by krzychb** [comment]
Good point, thank you. 
I will update the getting started guide.
