### ISSUE TITLE
I wonder what format is needed to play MP3 from the SPIffs partition (AUD-2142)

### ISSUE THREAD

**Issue by snailwft** [espressif/esp-adf#432]
Hi,  I made a SPIFFS file partition that contained XXx.mp3.In my code, I first mount the SPIffs partition and it has succeeded. Then I initialize audio platform. Finally, I call ESP_audio_play (Player, AUDIO_CODEC_TYPE_DECODER, "/spiffs/xxx.mp3", 0).The following error occurred.

log:
/*
E (366) ESP_AUDIO_CTRL: URI part of SCHEMA,PATH,HOST lost

*/
I wonder what format is needed to play MP3 from the SPIffs partition.

**Comment by shootao** [comment]
Hi @snailwft 
We judge the input stream according to the `schme` field, so the format should be `spiffs://spiffs/xxx.mp3`
