### ISSUE TITLE
how to use the esp_audio_seek API in the example (AUD-2162)

### ISSUE THREAD

**Issue by NOA-Vernon** [espressif/esp-adf#436]
Hi,
I have seen the examples under the /esp-adf/example folder, there is no example would have used the audio_err_tesp_audio_seek(esp_audio_handle_thandle, int seek_time_sec) function and how to use this function in the examples. Is it possible to have an example to demonstrate how to use audio_err_tesp_audio_seek(esp_audio_handle_thandle, int seek_time_sec) function.
Thank you so much.

**Comment by jason-mao** [comment]
@NOA-Vernon We will enhance the demo of the `esp-audio_*` interfaces. Please use as follow.
```c
esp_audio_play();
esp_audio_seek();
```
