### ISSUE TITLE
打开wifi时，音频播放有杂音。 (AUD-2197)

### ISSUE THREAD

**Issue by llx4186041** [espressif/esp-adf#442]
用的esp32 lyrat_V4.3 开发板。

开启音频
audio_pipeline_register(recorder, i2s_stream_reader, "i2s");
audio_pipeline_register(recorder, i2s_stream_writer, "i2s_in");
const char *link_tag[2] = {"i2s","i2s_in"};
audio_pipeline_link(recorder, &link_tag[0], 2);	

音量设置为100
audio_hal_set_volume(board_handle->audio_hal, 100);

边录音边播放时，开启wifi ap模式就出现 噗噜噗噜 持续的噪音。 关闭wifi，噪音消失，wifi切换为sta模式，偶现噪音。

**Comment by Gaochenchang** [comment]
@llx4186041 使用的扬声器还是耳机输出？如果使用扬声器，需要将扬声器远离MIC避免出现啸叫；如果使用耳机输出，调整一下耳机接口，可能会有不一样的效果。

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
