### ISSUE TITLE
 When debugging esp32，JTAG print" Too large number of threads 529011891!", please help analyze (AUD-2208)

### ISSUE THREAD

**Issue by feixiang201888** [espressif/esp-adf#443]
hi
 When used eclipse to debug esp32，JTAG print" Too large number of threads 529011891!",
![image](https://user-images.githubusercontent.com/39293932/89769510-d0212380-db2f-11ea-92f8-c470712a1824.png)
run a project(speech_recgnition)The eclipse debug window generates an interrupt, and there is no breakpoint in the whole project
![image](https://user-images.githubusercontent.com/39293932/89770038-c0eea580-db30-11ea-868a-59c8d7aa8026.png)
The development board is ESP32-LyraTD-MSC V2.2
Thank you for your reply！

**Comment by shivi-mangal** [comment]
Hi,
I am facin a similiar error for " Too large number of threads 53608706!".
Is there a solution to solve this?

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
