### ISSUE TITLE
SIP register with domain name, instead of IP address (AUD-2213)

### ISSUE THREAD

**Issue by sosaucily** [espressif/esp-adf#444]
Is it possible to use a domain name (like freeswitch.com, etc) when doing the esp_sip_init, or it must be an IP address?

We get a parsing error when we try to use domain names. But IP address is a bit fragile, relying on DNS would be better I believe.

**Comment by ahhfzhang** [comment]
Yes, use a domain name is better, but we already supported, something like tls://username:passwd@domain:port

If still not working, can you send me a log?

**Comment by sosaucily** [comment]
It seems to be working! Not sure, maybe that was in the old version of adf-2.0 beta 3. Or maybe we just made a mistake. Anyway, all is good, thank you!
