### ISSUE TITLE
How to build esp-adf components tests (AUD-2244)

### ISSUE THREAD

**Issue by zloiia** [espressif/esp-adf#447]
Hello! 
I can not understand how to build and run esp-adf components tests. I read the article https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/unit-tests.html , but I can not found such project in esp-adf path and if I follow the instructions, I can not see ADF components.

**Comment by jason-mao** [comment]
@zloiia The ADF UT tests are not well supported.  If you want to try it. You should modify the IDF `unit-test-app` build file as follow. For makefile example:
```c
$IDF_PATH/tools/unit-test-app/Makefile

-include $(IDF_PATH)/make/project.mk
+include $(ADF_PATH)/project.mk
```
