### ISSUE TITLE
pipeline_bt_sink例程 魅族安卓手机 触摸失败

### ISSUE THREAD

**Issue by fengfeng0328** [espressif/esp-adf#46]
你好！运行pipeline_bt_sink蓝牙播歌例程发现bug：不能通过四个触摸按键控制手机播放、暂停、切换；而在苹果手机上测试并没发现此问题！这是例程bug还是SDK bug？

**Comment by DanielLiMing** [comment]
小米手机同样遇到这样问题！

**Comment by ahhfzhang** [comment]
This issue has been resolved in 8ec973c .
