### ISSUE TITLE
Issue：DLNA Demo在播放一段时间音频流后出现卡顿，不久后重启 (AUD-2323)

### ISSUE THREAD

**Issue by Skylakc** [espressif/esp-adf#461]
Environment：
ESP-IDF 4.1
ESP-ADF 2.1
Ubuntu 20.04
Python 3.8.2

关键log如下
![image](https://user-images.githubusercontent.com/36782643/93011874-181ee480-f5cd-11ea-9a2c-4ad398ce53d2.png)

在正常启动DLNA音频流后一段时间
当出现
![image](https://user-images.githubusercontent.com/36782643/93011881-34228600-f5cd-11ea-9ba1-ab8982112d33.png)
若不刷新重启DLNA流，则会引发崩溃，继而自动重启

请问如何解决

**Comment by jason-mao** [comment]
@Skylakc 这个先分析下HTTP为啥得到了500 的status. Crash的话加些打印，跟踪具体挂在什么位置。

**Comment by kylongmu** [comment]
我的DLNA测试，按官方步骤来，但是Universal Media Center只能看到设备，点播放键后没反应，然后设备变灰色。换网易云音乐能看到设备，并且耳机听到声音，结果是可怕的卡顿，一秒钟一下那种，感觉是MCU上的接收缓存机制有问题，耳机能听到的声音底噪也高Codec_3V3，看到用了LP2985A-33DBVT来做模拟电源应该没问题，不过我考虑另外开个issue描述下。

**Comment by Skylakc** [comment]
> 我的DLNA测试，按官方步骤来，但是Universal Media Center只能看到设备，点播放键后没反应，然后设备变灰色。换网易云音乐能看到设备，并且耳机听到声音，结果是可怕的卡顿，一秒钟一下那种，感觉是MCU上的接收缓存机制有问题，耳机能听到的声音底噪也高Codec_3V3，看到用了LP2985A-33DBVT来做模拟电源应该没问题，不过我考虑另外开个issue描述下。

关于你说的底噪问题我倒是没有遇到过。推荐用Foobar2000+DLNA插件测试，缓冲区可以调大些。不过我在尝试播放96KHz采样率MP3的时候估计遇到处理器性能瓶颈，产生较大卡顿。

**Comment by Skylakc** [comment]
> @Skylakc 这个先分析下HTTP为啥得到了500 的status. Crash的话加些打印，跟踪具体挂在什么位置。

谢谢，明天我回学校了继续调试一下

**Comment by Skylakc** [comment]
![image](https://user-images.githubusercontent.com/36782643/100084654-fde36b80-2e85-11eb-9a59-ddef1e3195be.png)
![image](https://user-images.githubusercontent.com/36782643/100085070-8bbf5680-2e86-11eb-8557-8ddecfa1a3af.png)
![image](https://user-images.githubusercontent.com/36782643/100085098-9679eb80-2e86-11eb-9c9f-9ff585cc9e67.png)
![image](https://user-images.githubusercontent.com/36782643/100085155-a7c2f800-2e86-11eb-8c54-6f0466e1870b.png)
更新：近期我发现espadf和idf都发生了更新，在更新以后 http500的问题没有再发生了，但是发生了Audio_MEM问题

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
