### ISSUE TITLE
Acoustic feedback and echo cancellation problem (Need sound filter) (AUD-2347)

### ISSUE THREAD

**Issue by utkutpcgl** [espressif/esp-adf#464]
I use i2s-stream to read the sound detected by the onboard microphone (esp32 Lyrat board) and play the sound with i2s write with an external speaker connected to the onboard speaker output. Also, I only use one channel to listen and play (channel left).

I have the following pipeline: 
**microphone -> i2s_stream_read -> amr_encoder ->amr_decoder ->i2s_stream_write -> speaker** 
(There is approx. 150 ms delay btw. listening and playing the sound due to read-write delays inside the pipeline.)

The microphone listens to the speaker, hence, it enters a loop and repeats to play the previous sound that it has listened to (this is called acoustic feedback). It can even produce a high-intensity noise due to amplification when the output sound volume is set too high. Otherwise, it repeats the sound it listened once, but it is like an undesired echo that I would like to avoid.

I would like to learn how to overcome this problem. It would be good to use a software filter to filter out the speaker's sound, but I could not find the API for this purpose.  I see that ESP32-LyraTD-MSC V2.2 has acoustic echo cancellation, is there a way to implement it on ESP32-LyraT (my board)?

Thanks for your help!

**Noticed Later**
I noticed that in an issue algorithm_stream.h was suggested for AEC (acoustic echo cancellation). Do you think it will help me? 
Also, why isn't there any documentation related to it? Is it a new API? 

Thanks again.

**Comment by jason-mao** [comment]
@utkutpcgl As your description, I think the `algo_stream_init` could be improve your performance.

**Comment by utkutpcgl** [comment]
Thanks! Can I use it with ESP32-LyraT?

**Comment by jason-mao** [comment]
@utkutpcgl Yes. The algorithm stream ALGORITHM_STREAM_INPUT_TYPE2 can be applied.

**Comment by utkutpcgl** [comment]
Thanks again!

**Comment by frj2a** [comment]
The "algorithm_stream" that uses "esp_aec" is most probably the way to go.
But could not find how to set it up properly.  It needs to be inserted in the "input" pipeline but also needs a reference ring-buffer from the "output" pipeline. This last part is the one I could not find out how to set it up.

**Comment by Patsjemoe** [comment]
Hi,
Thank you for your feedback.
Found esp_aec.h in components\audiostream\algorithm_stream but cannot find
it in the Voip example, despite espressif confirmed it is in it (see
attached pictures).
Any other example using it?
Actually I am not sure how to implement it, so any good suggestion  is
welcome.
Regards
Ludo

Op di 13 okt. 2020 19:48 schreef Francisco J. A. Ares <
notifications@github.com>:

**Comment by jason-mao** [comment]
Similar issue link #476 

We will provide a correlative example for demonstrate how to use algorithm_stream.

**Comment by Patsjemoe** [comment]
Hi,
That would be great.
Thanks
Regards
Ludo

Op do 15 okt. 2020 05:42 schreef maojianxin <notifications@github.com>:

**Comment by Patsjemoe** [comment]
Hi Jason Mao,
Any idea when this would come? Espressif documents show it already exists, so I am wondering why I cannot find any example
Thank you in advance
Regards

**Comment by utkutpcgl** [comment]
Hello and thanks again @jason-mao , I guess I faced a bug.
When I tried to build the project with algo stream added I face the following error:

`[5/7] Generating ld/esp32.project.ld
warning: the default selection ESP32_KORVO_DU1906_CODEC_TAS5805M (undefined) of <choice ESP32_KORVO_DU1906_DAC> (defined at C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/audio_board/Kconfig.projbuild:27) is not contained in the choice
[6/7] Linking CXX executable dinleme_deneme.elf
FAILED: dinleme_deneme.elf
cmd.exe /C "cd . && C:\Users\utkum\.espressif\tools\xtensa-esp32-elf\esp-2020r2-8.2.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-address   @CMakeFiles\dinleme_deneme.elf.rsp  -o dinleme_deneme.elf  && cd ."
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x48): undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x4c): undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x58): undefined reference to `esp_kiss_fftri'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_noisemean_cal':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:123: undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: /home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:131: undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_pro':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:217: undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: /home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:257: undefined reference to `esp_kiss_fftri'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `esp_ns_alloc':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.h:30: undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_init':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:295: undefined reference to `esp_kiss_fftr_alloc'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`

As far as I understand libesp_audio_processor.a has a reference to **esp_kiss_fftr** in _noise suppression related functions_ in the **ns_core** file.

I use:

> Latest adf version
> idf version 4.1
> Windows idf command prompt
> esp32_lyrat board.

Have a nice day.

**Comment by Patsjemoe** [comment]
> The "algorithm_stream" that uses "esp_aec" is most probably the way to go.
> But could not find how to set it up properly. It needs to be inserted in the "input" pipeline but also needs a reference ring-buffer from the "output" pipeline. This last part is the one I could not find out how to set it up.

Hi, 
Could you share already how to define the input part?
Thanks

**Comment by utkutpcgl** [comment]
Hello @Patsjemoe ,
I am not certainly sure but in this pipeline:
**microphone -> i2s_stream_read -> (input_buffer1) ->  amr_encoder ->amr_decoder ->(input_buffer2) ->i2s_stream_write -> speaker**
I expect the record signal input buffer to be input_buffer1 and the reference signal's buffer to be input_buffer2. If I am wrong please correct me @jason-mao . This seemed logical to me by looking at the following diagram: 
![image](https://user-images.githubusercontent.com/18088068/97067973-dfaaf700-15cb-11eb-8511-43e00e2b7d48.png)

Becuase, as far as I know AEC needs an output signal to cancel out the echo, just like @frj2a  said.

**Comment by jason-mao** [comment]
> Hi Jason Mao,
> Any idea when this would come? Espressif documents show it already exists, so I am wondering why I cannot find any example
> Thank you in advance
> Regards

@Patsjemoe It will plan to valid on next week.

**Comment by utkutpcgl** [comment]
Just in case you missed my question above @jason-mao [https://github.com/espressif/esp-adf/issues/464#issuecomment-715164315](url). Thanks.

**Comment by Patsjemoe** [comment]
Hi, did not find any example code yet

**Comment by Patsjemoe** [comment]
> > Hi Jason Mao,
> > Any idea when this would come? Espressif documents show it already exists, so I am wondering why I cannot find any example
> > Thank you in advance
> > Regards
> 
> @Patsjemoe It will plan to valid on next week.

@jason-mao : any progress/idea when it will come?
I am trying to find out myself, but the documentation is not sufficiently complete, so more questions then solution

**Comment by jason-mao** [comment]
@Patsjemoe Yes, we are working on this. There are something need to  modify for process normally case.

**Comment by Patsjemoe** [comment]
OK thank you.

**Comment by jason-mao** [comment]
@Patsjemoe @frj2a  ebb87841016bf0b857a72af119b0d33f6039202b is the algorithm stream example.

**Comment by Patsjemoe** [comment]
Thank you

**Comment by frj2a** [comment]
Thank you

**Comment by utkutpcgl** [comment]
Thanks!

**Comment by Wellan72** [comment]
Hi @utkutpcgl, 

I'm trying to implement a pipeline similar to your example: 

microphone -> i2s_stream_read -> amr_encoder -> amr_decoder -> i2s_stream_write -> speaker

However, I'm having issues when I try to add an AEC filter: it doesn't seem to work. The main problem is that I get strong audio feedback / Larsen when playing the microphone through the speaker. 

Could you give some advice on how to integrate AEC properly to avoid feedback in this kind of pipeline? 

Thanks a lot!
