### ISSUE TITLE
Compile example "pipeline_a2dp_source_stream", get 4 error messages, without any code by myself! (AUD-2359)

### ISSUE THREAD

**Issue by kylongmu** [espressif/esp-adf#466]
ESP-IDF 4.3
ESP-ADF 2.1
--------------------------------------Here is the error message!----------------------------

- -play_bt_source_example.c

1. 'memcpy' forming offset [22, 249] is out of the bounds [0, 21] [-Werror=array-bounds]
2. too few arguments to function 'esp_bt_gap_set_scan_mode'
3. 'ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE' undeclared (first use in this function); did you mean 'ESP_BT_GENERAL_DISCOVERABLE'?

   if (remote_name) {
        memcpy(&remote_bt_device_name, remote_name, strlen(remote_name) + 1);
    } else {
//error 1        memcpy(&remote_bt_device_name, "ESP_SINK_STREAM_DEMO", ESP_BT_GAP_MAX_BDNAME_LEN + 1);
    }

    a2dp_stream_config_t a2dp_config = {
        .type = AUDIO_STREAM_WRITER,
        .user_callback = {0},
    };
    bt_stream_writer = a2dp_stream_init(&a2dp_config);

    esp_bt_gap_start_discovery(ESP_BT_INQ_MODE_GENERAL_INQUIRY, 10, 0);
//error 2,3    esp_bt_gap_set_scan_mode(ESP_BT_SCAN_MODE_CONNECTABLE_DISCOVERABLE);

4. After comment the error code, I get the link error:
FAILED: bt_source_demo.elf
cmd.exe /C "cd . && C:\Users\THINKPAD\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-address -g   @CMakeFiles\bt_source_demo.elf.rsp  -o bt_source_demo.elf  && cd ."
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj):(.literal.es_read_reg+0x4): undefined reference to `i2c_bus_read_bytes'
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj):(.literal.es_write_reg+0x0): undefined reference to `i2c_bus_write_bytes'
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj):(.literal.es8388_deinit+0x0): undefined reference to `i2c_bus_delete'
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj):(.literal.i2c_init+0x8): undefined reference to `i2c_bus_create'
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj): in function `es_read_reg':
D:/Develop/Git_Project/esp-adf/components/audio_hal/driver/es8388/es8388.c:63: undefined reference to `i2c_bus_read_bytes'
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj): in function `es_write_reg':
D:/Develop/Git_Project/esp-adf/components/audio_hal/driver/es8388/es8388.c:58: undefined reference to `i2c_bus_write_bytes'
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj): in function `es8388_deinit':
D:/Develop/Git_Project/esp-adf/components/audio_hal/driver/es8388/es8388.c:235: undefined reference to `i2c_bus_delete'
c:/users/thinkpad/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/audio_hal/libaudio_hal.a(es8388.c.obj): in function `i2c_init':
D:/Develop/Git_Project/esp-adf/components/audio_hal/driver/es8388/es8388.c:76: undefined reference to `i2c_bus_create'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by kylongmu** [comment]
Oh my GOD!
The ADF only support IDF 3.3 version.

**Comment by kylongmu** [comment]
After change the IDF to version 4.1, I can build succesfully, but it's hard.
The 4 errors are still, comment the first 3 error, then I found some info:
"Some Python dependencies must be installed.  Check above message for details."
After a lot of test, I found it's caused by an python option: in this file
idf_tools.py
`line 1185            subprocess.check_call([sys.executable, '-m', 'pip', 'install', '--user', 'virtualenv']`

Remove --user option
Then redo install and export under IDF folder
build success!

**Comment by kylongmu** [comment]
So all the 4 errors, 3 comes from example code, 1 come from IDF install problem.
Please fix these bugs!

**Comment by jason-mao** [comment]
@kylongmu Thanks for you report, the fix is coming.  Please note that ADF can be support IDF released version only,  ESP-IDF 4.3 have not released.

**Comment by kylongmu** [comment]
@jason-mao Thanks for your response, it's nice for the problem to be notified.
