### ISSUE TITLE
Suggestsion: Versions and documentation. (AUD-2362)

### ISSUE THREAD

**Issue by utkutpcgl** [espressif/esp-adf#467]
Sorry if I missed anything in the documents. If not, then it would be nice to consider the points below.

- I guess it would be better if the ESP-ADF versions should be linked to their version (latest, stable or v1.0 documentation, etc.). 
- In the documentation, there should be a git download command for each version uniquely. It would be better to simply download the repo, rather than searching versions.
- And, it would be good if each version associated with the stable or latest version is written. Since it is not easy to understand. 
Now I can see that there is the latest, stable, 2.0, 1.0... I guess the latest one is 2.1 though which one is the stable one?

**Comment by jason-mao** [comment]
@utkutpcgl Thank you for your suggestions. We will make all things easy to understanding and without confusion.

**Comment by utkutpcgl** [comment]
Thanks!
