### ISSUE TITLE
VOIP sleep mode (AUD-2378)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#475]
there is an example of modem sleep in esp-idf/wifi, but not in esp-adf.
Is it possible to implement modem sleep in the VOIP application, taking onto account that there is a need for SIP communication with the sip server.
any suggestions on how to implement this ?

**Comment by jason-mao** [comment]
@Patsjemoe  Please refer to https://github.com/espressif/esp-adf/issues/455
