### ISSUE TITLE
Voip echo (AUD-2379)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#476]
I am using linphone on android with the Voip in esp-adf. Voice is OK on the lyrat or audiokit, but hear everything as echo of what I say. On the esp32 side, there is no echo.
Could it be that microphone of esp is set too sentitive? How can I adapt this setting? 
Anyone a solution for this?

**Comment by Patsjemoe** [comment]
Hi,
I was just wondering if this could be a sort of voice delay instead of echo...? How to attack this?

**Comment by Patsjemoe** [comment]
when using linphone with microsip on my pc, NO ECHO
So it looks as it is related to the esp32

**Comment by Patsjemoe** [comment]
Do I need to use a different codex like speexx?
Can this be used?

**Comment by frj2a** [comment]
There's an "algorithm_stream" that uses "esp_aec" (auto echo cancelation) that probably is the way to go.
But could not find how to set it up propperly.  It needs to be inserted in the "input" pipeline but also needs a reference ring-buffer from the "output" pipeline.

**Comment by Patsjemoe** [comment]
Hi Jason-Mao,
You mentioned : We will provide a correlative example for demonstrate how to use algorithm_stream... Any idea when this will come? 
Thank you in advance
Ludo

**Comment by Patsjemoe** [comment]
@jason-mao : hi, any progress on the algorithm stream example, planned for this week?
Thanks in advance
Ludo

**Comment by Patsjemoe** [comment]
@jason-mao : you had planned the algorithm example two weeks ago. Can you please confirm status?

**Comment by Patsjemoe** [comment]
Example received, thank you
