### ISSUE TITLE
example asr doesn't compiles (AUD-2388)

### ISSUE THREAD

**Issue by Saynok** [espressif/esp-adf#477]
I have tried git submodule update --recurse it doesn't helps
I'm using visual studio code
this is a log:

`[3/4] Linking CXX executable speech_recognition_example.elf
FAILED: speech_recognition_example.elf
cmd.exe /C "cd . && C:\Users\79080\.espressif\tools\xtensa-esp32-elf\esp-2020r2-8.2.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-addre
ss   @CMakeFiles\speech_recognition_example.elf.rsp  -o speech_recognition_example.elf  && cd ."
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.model_destroy+0x8): undefined reference to `dl_matrixq
_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.model_create+0x1c): undefined reference to `dl_matrixq
_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.add_speech_commands+0x14): undefined reference to `get
_id_name'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.lvcsr_model_run_accelerate+0x18): undefined reference 
to `dl_convq_lstm_layer'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.lvcsr_model_run_accelerate+0x1c): undefined reference 
to `dl_relu_convq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.lvcsr_model_run_accelerate+0x20): undefined reference 
to `dl_convq_to_matrix2dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.lvcsr_model_run_accelerate+0x24): undefined reference 
to `dl_matrix2d_from_matrixq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.lvcsr_model_run_accelerate+0x28): undefined reference 
to `dl_matrix_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.lvcsr_model_run_accelerate+0x2c): undefined reference 
to `dl_softmax'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o):(.literal.lvcsr_model_run_accelerate+0x30): undefined reference 
to `dl_matrix_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o): in function `model_destroy':
/home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:257: undefined reference to `dl_matrixq_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:258: undefined reference to `dl_matrixq_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:259: undefined reference to `dl_matrixq_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:272: undefined reference to `dl_convq_queue_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:274: undefined reference to `dl_convq_queue_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:277: undefined reference to `dl_convq_queue_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:278: undefined reference to `dl_convq_queue_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o): in function `model_create':
/home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:339: undefined reference to `dl_convq_queue_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:345: undefined reference to `dl_matrixq_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:347: undefined reference to `dl_matrixq_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:347: undefined reference to `dl_convq_queue_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:350: undefined reference to `dl_matrixq_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:351: undefined reference to `dl_convq_queue_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:352: undefined reference to `dl_convq_queue_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o): in function `add_speech_commands':
/home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:216: undefined reference to `get_id_name'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libmultinet.a(multinet1_quantized_cn.o): in function `lvcsr_model_run_accelerate':
/home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:452: undefined reference to `dl_convq_queue_push_by_qmf'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:456: undefined reference to `dl_dilation_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:461: undefined reference to `dl_dilation_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:466: undefined reference to `dl_dilation_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:471: undefined reference to `dl_dilation_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:483: undefined reference to `dl_convq_lstm_layer'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:487: undefined reference to `dl_atrous_conv1dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:489: undefined reference to `dl_relu_convq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:492: undefined reference to `dl_atrous_conv1dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:495: undefined reference to `dl_relu_convq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:498: undefined reference to `dl_atrous_conv1dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:510: undefined reference to `dl_convq_to_matrix2dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:510: undefined reference to `dl_matrix2d_from_matrixq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:511: undefined reference to `dl_matrix_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:512: undefined reference to `dl_softmax'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:524: undefined reference to `dl_matrix_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/wangwangwang/workspace/AI/esp_sr_lib/components/multinet/multinet1_quantized_cn.c:524: undefined reference to `dl_matrix_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.model_destroy+0x8): undefined reference to `dl_convq_queue_
free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x18): undefined reference to `dl_convq_
queue_push_by_qmf'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x1c): undefined reference to `dl_atrous
_conv1dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x20): undefined reference to `dl_tanh_c
onvq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x24): undefined reference to `dl_dilati
on_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x28): undefined reference to `dl_atrous
_conv1dq_steps'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x2c): undefined reference to `dl_convq_
queue_add'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x30): undefined reference to `dl_softma
x_step'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.wakeNet6_model_run+0x3c): undefined reference to `dl_conv_q
ueue_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o):(.literal.model_create+0xc): undefined reference to `dl_convq_queue_a
lloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o): in function `model_destroy':
/home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:132: undefined reference to `dl_convq_queue_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o): in function `wakeNet6_model_run':
/home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:262: undefined reference to `dl_convq_queue_push_by_qmf'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:266: undefined reference to `dl_atrous_conv1dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:269: undefined reference to `dl_tanh_convq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:272: undefined reference to `dl_dilation_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:276: undefined reference to `dl_dilation_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:280: undefined reference to `dl_dilation_layerq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:285: undefined reference to `dl_atrous_conv1dq_steps'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:288: undefined reference to `dl_atrous_conv1dq'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:291: undefined reference to `dl_convq_queue_add'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:294: undefined reference to `dl_softmax_step'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:370: undefined reference to `dl_conv_queue_free'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(wakenet6_quantized.o): in function `model_create':
/home/sunxiangyu/esp/esp_sr_lib/components/wakenet/wakenet6_quantized.c:179: undefined reference to `dl_convq_queue_alloc'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(mfcc_runner_straight.o):(.literal.run_logfbank+0x4): undefined reference to `csf_preemphasi
s_step'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(mfcc_runner_straight.o):(.literal.run_logfbank+0x8): undefined reference to `csf_logfbank_H
TK_step'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(mfcc_runner_straight.o):(.literal.run+0x0): undefined reference to `csf_mfcc_HTK'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(mfcc_runner_straight.o): in function `run_logfbank':
/home/sunxiangyu/esp/esp_sr_lib/components/wakenet/mfcc_runner_straight.c:70: undefined reference to `csf_preemphasis_step'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 /home/sunxiangyu/esp/esp_sr_lib/components/wakenet/mfcc_runner_straight.c:72: undefined reference to `csf_logfbank_HTK_step'
c:/users/79080/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe:
 C:/Users/79080/.espressif/esp-adf/components/esp-sr/lib\libwakenet.a(mfcc_runner_straight.o): in function `run':
ninja: build stopped: subcommand failed.
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake --build ." terminated with exit code: 1.
`

**Comment by Saynok** [comment]
Is esp-idf version requires?

**Comment by jason-mao** [comment]
Uhm, there is bug on `esp-sr`, the fix is coming.

**Comment by jalakamkiranadspl** [comment]
I am still getting this error any ideas for fix?
