### ISSUE TITLE
DLNA Example: [2/3] Linking CXX executable dlna_example.elf (AUD-2429)

### ISSUE THREAD

**Issue by SeeOneeee** [espressif/esp-adf#486]
So tried to fix this problem for a few hours. No fixes worked for me so far. 
I get this error: [2/3] Linking CXX executable dlna_example.elf
Everything is updated and i reinstalled ESP-IDF and ESP-ADF.  Other example projects (like a2dp_avrcp) are working fine.
I didn't modify anything in the project.
I had problems building other projects in the ADF and I used this fix: https://github.com/espressif/esp-adf/issues/438#issuecomment-667678452
Board: LyraT 4.3

**Comment by jason-mao** [comment]
@SeeOneeee Please provide the error log

**Comment by SeeOneeee** [comment]
@jason-mao Here is the complete Error Log - it is a little bit long.

`Executing action: all (aliases: build)
Running ninja in directory /home/User/esp/esp-adf/examples/advanced_examples/dlna/build
Executing "ninja all"...
[1/5] Performing build step for 'bootloader'
ninja: no work to do.
[2/3] Linking CXX executable dlna_example.elf
FAILED: dlna_example.elf 
: && /home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ -mlongcalls -Wno-frame-address  CMakeFiles/dlna_example.elf.dir/project_elf_src.c.obj CMakeFiles/dlna_example.elf.dir/rootDesc.xml.S.obj CMakeFiles/dlna_example.elf.dir/rootDescLogo.xml.S.obj CMakeFiles/dlna_example.elf.dir/rootDescService.xml.S.obj CMakeFiles/dlna_example.elf.dir/SoapResponseErr.xml.S.obj CMakeFiles/dlna_example.elf.dir/SoapResponseOk.xml.S.obj CMakeFiles/dlna_example.elf.dir/devicelist.xml.S.obj -o dlna_example.elf  esp-idf/xtensa/libxtensa.a  esp-idf/esp_pm/libesp_pm.a  esp-idf/mbedtls/libmbedtls.a  esp-idf/efuse/libefuse.a  esp-idf/bootloader_support/libbootloader_support.a  esp-idf/app_update/libapp_update.a  esp-idf/esp_ipc/libesp_ipc.a  esp-idf/spi_flash/libspi_flash.a  esp-idf/nvs_flash/libnvs_flash.a  esp-idf/pthread/libpthread.a  esp-idf/esp_system/libesp_system.a  esp-idf/esp_rom/libesp_rom.a  esp-idf/hal/libhal.a  esp-idf/soc/libsoc.a  esp-idf/vfs/libvfs.a  esp-idf/esp_eth/libesp_eth.a  esp-idf/tcpip_adapter/libtcpip_adapter.a  esp-idf/esp_netif/libesp_netif.a  esp-idf/esp_event/libesp_event.a  esp-idf/wpa_supplicant/libwpa_supplicant.a  esp-idf/esp_wifi/libesp_wifi.a  esp-idf/lwip/liblwip.a  esp-idf/log/liblog.a  esp-idf/heap/libheap.a  esp-idf/esp_ringbuf/libesp_ringbuf.a  esp-idf/driver/libdriver.a  esp-idf/espcoredump/libespcoredump.a  esp-idf/perfmon/libperfmon.a  esp-idf/esp32/libesp32.a  esp-idf/esp_common/libesp_common.a  esp-idf/esp_timer/libesp_timer.a  esp-idf/freertos/libfreertos.a  esp-idf/newlib/libnewlib.a  esp-idf/cxx/libcxx.a  esp-idf/app_trace/libapp_trace.a  esp-idf/asio/libasio.a  esp-idf/cbor/libcbor.a  esp-idf/unity/libunity.a  esp-idf/cmock/libcmock.a  esp-idf/coap/libcoap.a  esp-idf/console/libconsole.a  esp-idf/nghttp/libnghttp.a  esp-idf/esp-tls/libesp-tls.a  esp-idf/esp_adc_cal/libesp_adc_cal.a  esp-idf/esp_gdbstub/libesp_gdbstub.a  esp-idf/esp_hid/libesp_hid.a  esp-idf/tcp_transport/libtcp_transport.a  esp-idf/esp_http_client/libesp_http_client.a  esp-idf/esp_http_server/libesp_http_server.a  esp-idf/esp_https_ota/libesp_https_ota.a  esp-idf/protobuf-c/libprotobuf-c.a  esp-idf/protocomm/libprotocomm.a  esp-idf/mdns/libmdns.a  esp-idf/esp_local_ctrl/libesp_local_ctrl.a  esp-idf/sdmmc/libsdmmc.a  esp-idf/esp_serial_slave_link/libesp_serial_slave_link.a  esp-idf/esp_websocket_client/libesp_websocket_client.a  esp-idf/expat/libexpat.a  esp-idf/wear_levelling/libwear_levelling.a  esp-idf/fatfs/libfatfs.a  esp-idf/freemodbus/libfreemodbus.a  esp-idf/jsmn/libjsmn.a  esp-idf/json/libjson.a  esp-idf/libsodium/liblibsodium.a  esp-idf/mqtt/libmqtt.a  esp-idf/openssl/libopenssl.a  esp-idf/spiffs/libspiffs.a  esp-idf/ulp/libulp.a  esp-idf/wifi_provisioning/libwifi_provisioning.a  esp-idf/audio_sal/libaudio_sal.a  esp-idf/adf_utils/libadf_utils.a  esp-idf/display_service/libdisplay_service.a  esp-idf/esp_dispatcher/libesp_dispatcher.a  esp-idf/audio_hal/libaudio_hal.a  esp-idf/esp-sr/libesp-sr.a  esp-idf/esp-adf-libs/libesp-adf-libs.a  esp-idf/audio_pipeline/libaudio_pipeline.a  esp-idf/esp_peripherals/libesp_peripherals.a  esp-idf/audio_board/libaudio_board.a  esp-idf/wifi_service/libwifi_service.a  esp-idf/dueros_service/libdueros_service.a  esp-idf/esp_actions/libesp_actions.a  esp-idf/tone_partition/libtone_partition.a  esp-idf/audio_stream/libaudio_stream.a  esp-idf/battery_service/libbattery_service.a  esp-idf/bluetooth_service/libbluetooth_service.a  esp-idf/coredump_upload_service/libcoredump_upload_service.a  esp-idf/esp_event_cast/libesp_event_cast.a  esp-idf/input_key_service/libinput_key_service.a  esp-idf/ota_service/libota_service.a  esp-idf/playlist/libplaylist.a  esp-idf/esp_dlna/libesp_dlna.a  esp-idf/main/libmain.a  -Wl,--cref -Wl,--Map=/home/User/esp/esp-adf/examples/advanced_examples/dlna/build/dlna_example.map  -fno-rtti  -fno-lto  esp-idf/asio/libasio.a  esp-idf/cbor/libcbor.a  esp-idf/cmock/libcmock.a  esp-idf/unity/libunity.a  esp-idf/coap/libcoap.a  esp-idf/esp_gdbstub/libesp_gdbstub.a  esp-idf/esp_hid/libesp_hid.a  esp-idf/esp_local_ctrl/libesp_local_ctrl.a  esp-idf/esp_websocket_client/libesp_websocket_client.a  esp-idf/expat/libexpat.a  esp-idf/freemodbus/libfreemodbus.a  esp-idf/libsodium/liblibsodium.a  esp-idf/mqtt/libmqtt.a  esp-idf/openssl/libopenssl.a  esp-idf/wifi_provisioning/libwifi_provisioning.a  esp-idf/protocomm/libprotocomm.a  esp-idf/protobuf-c/libprotobuf-c.a  esp-idf/mdns/libmdns.a  esp-idf/json/libjson.a  esp-idf/adf_utils/libadf_utils.a  esp-idf/jsmn/libjsmn.a  esp-idf/battery_service/libbattery_service.a  esp-idf/bluetooth_service/libbluetooth_service.a  esp-idf/coredump_upload_service/libcoredump_upload_service.a  esp-idf/esp_event_cast/libesp_event_cast.a  esp-idf/input_key_service/libinput_key_service.a  esp-idf/ota_service/libota_service.a  esp-idf/audio_stream/libaudio_stream.a  esp-idf/tone_partition/libtone_partition.a  esp-idf/wifi_service/libwifi_service.a  esp-idf/esp_actions/libesp_actions.a  esp-idf/wifi_service/libwifi_service.a  esp-idf/esp_actions/libesp_actions.a  -L/home/User/esp/esp-adf/components/wifi_service/airkiss_config  -lairkiss_aes  esp-idf/dueros_service/libdueros_service.a  esp-idf/display_service/libdisplay_service.a  esp-idf/audio_hal/libaudio_hal.a  esp-idf/esp_peripherals/libesp_peripherals.a  esp-idf/audio_board/libaudio_board.a  esp-idf/display_service/libdisplay_service.a  esp-idf/audio_hal/libaudio_hal.a  esp-idf/esp_peripherals/libesp_peripherals.a  esp-idf/audio_board/libaudio_board.a  -L/home/User/esp/esp-adf/components/audio_hal/driver/zl38063/firmware  -lfirmware  esp-idf/console/libconsole.a  esp-idf/esp_adc_cal/libesp_adc_cal.a  esp-idf/fatfs/libfatfs.a  esp-idf/wear_levelling/libwear_levelling.a  esp-idf/spiffs/libspiffs.a  esp-idf/esp_dispatcher/libesp_dispatcher.a  -L/home/User/esp/esp-adf/components/clouds/dueros/lightduer  -lduer-device-v4x  esp-idf/playlist/libplaylist.a  esp-idf/esp_dlna/libesp_dlna.a  esp-idf/esp-adf-libs/libesp-adf-libs.a  esp-idf/audio_pipeline/libaudio_pipeline.a  /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a  esp-idf/esp-adf-libs/libesp-adf-libs.a  esp-idf/audio_pipeline/libaudio_pipeline.a  /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a  esp-idf/esp-sr/libesp-sr.a  /home/User/esp/esp-adf/components/esp-sr/lib/libmultinet.a  esp-idf/esp-sr/libesp-sr.a  /home/User/esp/esp-adf/components/esp-sr/lib/libmultinet.a  -L /home/User/esp/esp-adf/components/esp-sr/lib  -L /home/User/esp/esp-adf/components/esp-sr/wake_word_engine  -L /home/User/esp/esp-adf/components/esp-sr/speech_command_recognition  -L /home/User/esp/esp-adf/components/esp-sr/acoustic_algorithm  -L /home/User/esp/esp-adf/components/esp-sr/esp-tts/esp_tts_chinese  -lwakenet  -ldl_lib  -lc_speech_features  -lhilexin_wn3  -lhilexin_wn4  -lhilexin_wn5  -lhilexin_wn5X2  -lhilexin_wn5X3  -lhijeson_wn5X3  -lnihaoxiaozhi_wn5  -lnihaoxiaozhi_wn5X2  -lnihaoxiaozhi_wn5X3  -lnihaoxiaoxin_wn6  -lnihaoxiaoxin_wn5X3  -lcustomized_word_wn5  -lcustomized_word_wn6  -lmultinet1_ch  -lmultinet1_en  -lesp_tts_chinese  -lvoice_set_xiaole  -lvoice_set_template  -lesp_audio_processor  -Wl,--start-group  -Wl,--end-group  -L /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32  -L /home/User/esp/esp-adf/components/esp-adf-libs/esp_codec/lib/esp32  -L /home/User/esp/esp-adf/components/esp-adf-libs/esp_ssdp/lib/esp32  -L /home/User/esp/esp-adf/components/esp-adf-libs/esp_upnp/lib/esp32  -L /home/User/esp/esp-adf/components/esp-adf-libs/esp_sip/lib/esp32  -L /home/User/esp/esp-adf/components/esp-adf-libs/recorder_engine/lib/esp32  -lesp_processing  -lesp-aac  -lesp-amr  -lesp-amrwbenc  -lesp-flac  -lesp_ssdp-v4x  -lesp-ogg-container  -lesp-opus  -lesp-tremor  -lesp_sip-v4x  -lesp_upnp  -lesp-mp3  -lcodec-utils  -lesp-g711  -lrecorder_engine  esp-idf/audio_sal/libaudio_sal.a  esp-idf/xtensa/libxtensa.a  esp-idf/esp_pm/libesp_pm.a  esp-idf/mbedtls/libmbedtls.a  esp-idf/efuse/libefuse.a  esp-idf/bootloader_support/libbootloader_support.a  esp-idf/app_update/libapp_update.a  esp-idf/esp_ipc/libesp_ipc.a  esp-idf/spi_flash/libspi_flash.a  esp-idf/nvs_flash/libnvs_flash.a  esp-idf/pthread/libpthread.a  esp-idf/esp_system/libesp_system.a  esp-idf/esp_rom/libesp_rom.a  esp-idf/hal/libhal.a  esp-idf/soc/libsoc.a  esp-idf/vfs/libvfs.a  esp-idf/esp_eth/libesp_eth.a  esp-idf/tcpip_adapter/libtcpip_adapter.a  esp-idf/esp_netif/libesp_netif.a  esp-idf/esp_event/libesp_event.a  esp-idf/wpa_supplicant/libwpa_supplicant.a  esp-idf/esp_wifi/libesp_wifi.a  esp-idf/lwip/liblwip.a  esp-idf/log/liblog.a  esp-idf/heap/libheap.a  esp-idf/esp_ringbuf/libesp_ringbuf.a  esp-idf/driver/libdriver.a  esp-idf/espcoredump/libespcoredump.a  esp-idf/perfmon/libperfmon.a  esp-idf/esp32/libesp32.a  esp-idf/esp_common/libesp_common.a  esp-idf/esp_timer/libesp_timer.a  esp-idf/freertos/libfreertos.a  esp-idf/newlib/libnewlib.a  esp-idf/cxx/libcxx.a  esp-idf/app_trace/libapp_trace.a  esp-idf/nghttp/libnghttp.a  esp-idf/esp-tls/libesp-tls.a  esp-idf/tcp_transport/libtcp_transport.a  esp-idf/esp_http_client/libesp_http_client.a  esp-idf/esp_http_server/libesp_http_server.a  esp-idf/esp_https_ota/libesp_https_ota.a  esp-idf/sdmmc/libsdmmc.a  esp-idf/esp_serial_slave_link/libesp_serial_slave_link.a  esp-idf/ulp/libulp.a  esp-idf/mbedtls/mbedtls/library/libmbedtls.a  esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a  esp-idf/mbedtls/mbedtls/library/libmbedx509.a  esp-idf/soc/soc/esp32/libsoc_esp32.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a
  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a  esp-idf/xtensa/libxtensa.a  esp-idf/esp_pm/libesp_pm.a  esp-idf/mbedtls/libmbedtls.a  esp-idf/efuse/libefuse.a  esp-idf/bootloader_support/libbootloader_support.a  esp-idf/app_update/libapp_update.a  esp-idf/esp_ipc/libesp_ipc.a  esp-idf/spi_flash/libspi_flash.a  esp-idf/nvs_flash/libnvs_flash.a  esp-idf/pthread/libpthread.a  esp-idf/esp_system/libesp_system.a  esp-idf/esp_rom/libesp_rom.a  esp-idf/hal/libhal.a  esp-idf/soc/libsoc.a  esp-idf/vfs/libvfs.a  esp-idf/esp_eth/libesp_eth.a  esp-idf/tcpip_adapter/libtcpip_adapter.a  esp-idf/esp_netif/libesp_netif.a  esp-idf/esp_event/libesp_event.a  esp-idf/wpa_supplicant/libwpa_supplicant.a  esp-idf/esp_wifi/libesp_wifi.a  esp-idf/lwip/liblwip.a  esp-idf/log/liblog.a  esp-idf/heap/libheap.a  esp-idf/esp_ringbuf/libesp_ringbuf.a  esp-idf/driver/libdriver.a  esp-idf/espcoredump/libespcoredump.a  esp-idf/perfmon/libperfmon.a  esp-idf/esp32/libesp32.a  esp-idf/esp_common/libesp_common.a  esp-idf/esp_timer/libesp_timer.a  esp-idf/freertos/libfreertos.a  esp-idf/newlib/libnewlib.a  esp-idf/cxx/libcxx.a  esp-idf/app_trace/libapp_trace.a  esp-idf/nghttp/libnghttp.a  esp-idf/esp-tls/libesp-tls.a  esp-idf/tcp_transport/libtcp_transport.a  esp-idf/esp_http_client/libesp_http_client.a  esp-idf/esp_http_server/libesp_http_server.a  esp-idf/esp_https_ota/libesp_https_ota.a  esp-idf/sdmmc/libsdmmc.a  esp-idf/esp_serial_slave_link/libesp_serial_slave_link.a  esp-idf/ulp/libulp.a  esp-idf/mbedtls/mbedtls/library/libmbedtls.a  esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a  esp-idf/mbedtls/mbedtls/library/libmbedx509.a  esp-idf/soc/soc/esp32/libsoc_esp32.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a  esp-idf/xtensa/libxtensa.a  esp-idf/esp_pm/libesp_pm.a  esp-idf/mbedtls/libmbedtls.a  esp-idf/efuse/libefuse.a  esp-idf/bootloader_support/libbootloader_support.a  esp-idf/app_update/libapp_update.a  esp-idf/esp_ipc/libesp_ipc.a  esp-idf/spi_flash/libspi_flash.a  esp-idf/nvs_flash/libnvs_flash.a  esp-idf/pthread/libpthread.a  esp-idf/esp_system/libesp_system.a  esp-idf/esp_rom/libesp_rom.a  esp-idf/hal/libhal.a  esp-idf/soc/libsoc.a  esp-idf/vfs/libvfs.a  esp-idf/esp_eth/libesp_eth.a  esp-idf/tcpip_adapter/libtcpip_adapter.a  esp-idf/esp_netif/libesp_netif.a  esp-idf/esp_event/libesp_event.a  esp-idf/wpa_supplicant/libwpa_supplicant.a  esp-idf/esp_wifi/libesp_wifi.a  esp-idf/lwip/liblwip.a  esp-idf/log/liblog.a  esp-idf/heap/libheap.a  esp-idf/esp_ringbuf/libesp_ringbuf.a  esp-idf/driver/libdriver.a  esp-idf/espcoredump/libespcoredump.a  esp-idf/perfmon/libperfmon.a  esp-idf/esp32/libesp32.a  esp-idf/esp_common/libesp_common.a  esp-idf/esp_timer/libesp_timer.a  esp-idf/freertos/libfreertos.a  esp-idf/newlib/libnewlib.a  esp-idf/cxx/libcxx.a  esp-idf/app_trace/libapp_trace.a  esp-idf/nghttp/libnghttp.a  esp-idf/esp-tls/libesp-tls.a  esp-idf/tcp_transport/libtcp_transport.a  esp-idf/esp_http_client/libesp_http_client.a  esp-idf/esp_http_server/libesp_http_server.a  esp-idf/esp_https_ota/libesp_https_ota.a  esp-idf/sdmmc/libsdmmc.a  esp-idf/esp_serial_slave_link/libesp_serial_slave_link.a  esp-idf/ulp/libulp.a  esp-idf/mbedtls/mbedtls/library/libmbedtls.a  esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a  esp-idf/mbedtls/mbedtls/library/libmbedx509.a  esp-idf/soc/soc/esp32/libsoc_esp32.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a  esp-idf/xtensa/libxtensa.a  esp-idf/esp_pm/libesp_pm.a  esp-idf/mbedtls/libmbedtls.a  esp-idf/efuse/libefuse.a  esp-idf/bootloader_support/libbootloader_support.a  esp-idf/app_update/libapp_update.a  esp-idf/esp_ipc/libesp_ipc.a  esp-idf/spi_flash/libspi_flash.a  esp-idf/nvs_flash/libnvs_flash.a  esp-idf/pthread/libpthread.a  esp-idf/esp_system/libesp_system.a  esp-idf/esp_rom/libesp_rom.a  esp-idf/hal/libhal.a  esp-idf/soc/libsoc.a  esp-idf/vfs/libvfs.a  esp-idf/esp_eth/libesp_eth.a  esp-idf/tcpip_adapter/libtcpip_adapter.a  esp-idf/esp_netif/libesp_netif.a  esp-idf/esp_event/libesp_event.a  esp-idf/wpa_supplicant/libwpa_supplicant.a  esp-idf/esp_wifi/libesp_wifi.a  esp-idf/lwip/liblwip.a  esp-idf/log/liblog.a  esp-idf/heap/libheap.a  esp-idf/esp_ringbuf/libesp_ringbuf.a  esp-idf/driver/libdriver.a  esp-idf/espcoredump/libespcoredump.a  esp-idf/perfmon/libperfmon.a  esp-idf/esp32/libesp32.a  esp-idf/esp_common/libesp_common.a  esp-idf/esp_timer/libesp_timer.a  esp-idf/freertos/libfreertos.a  esp-idf/newlib/libnewlib.a  esp-idf/cxx/libcxx.a  esp-idf/app_trace/libapp_trace.a  esp-idf/nghttp/libnghttp.a  esp-idf/esp-tls/libesp-tls.a  esp-idf/tcp_transport/libtcp_transport.a  esp-idf/esp_http_client/libesp_http_client.a  esp-idf/esp_http_server/libesp_http_server.a  esp-idf/esp_https_ota/libesp_https_ota.a  esp-idf/sdmmc/libsdmmc.a  esp-idf/esp_serial_slave_link/libesp_serial_slave_link.a  esp-idf/ulp/libulp.a  esp-idf/mbedtls/mbedtls/library/libmbedtls.a  esp-idf/mbedtls/mbedtls/library/libmbedcrypto.a  esp-idf/mbedtls/mbedtls/library/libmbedx509.a  esp-idf/soc/soc/esp32/libsoc_esp32.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcoexist.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libcore.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libespnow.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libmesh.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libnet80211.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libpp.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/librtc.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libsmartconfig.a  /home/User/esp/esp-idf/components/esp_wifi/lib/esp32/libphy.a  /home/User/esp/esp-idf/components/xtensa/esp32/libxt_hal.a  -u esp_app_desc  -u pthread_include_pthread_impl  -u pthread_include_pthread_cond_impl  -u pthread_include_pthread_local_storage_impl  -u ld_include_panic_highint_hdl  -u start_app  -u start_app_other_cores  -L /home/User/esp/esp-idf/components/esp_rom/esp32/ld  -T esp32.rom.api.ld  -T esp32.rom.ld  -T esp32.rom.libgcc.ld  -T esp32.rom.newlib-data.ld  -T esp32.rom.syscalls.ld  -u vfs_include_syscalls_impl  -L /home/User/esp/esp-idf/components/esp_wifi/lib/esp32  -L /home/User/esp/esp-adf/examples/advanced_examples/dlna/build/esp-idf/esp32  -T esp32_out.ld  -L /home/User/esp/esp-adf/examples/advanced_examples/dlna/build/esp-idf/esp32/ld  -T esp32.project.ld  -L /home/User/esp/esp-idf/components/esp32/ld  -T esp32.peripherals.ld  -u call_user_start_cpu0  -mfix-esp32-psram-cache-issue  -mfix-esp32-psram-cache-strategy=memw  -Wl,--gc-sections  -Wl,--undefined=uxTopUsedPriority  -u app_main  -lm  esp-idf/newlib/libnewlib.a  -u newlib_include_locks_impl  -u newlib_include_heap_impl  -u newlib_include_syscalls_impl  -u newlib_include_pthread_impl  -lgcc  -u __cxa_guard_dummy  -lstdc++  esp-idf/pthread/libpthread.a  -u __cxx_fatal_exception  esp-idf/app_trace/libapp_trace.a  -lgcov  esp-idf/app_trace/libapp_trace.a  -lgcov  -lc && :
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_codec/lib/esp32/libesp_processing.a(wav_decoder.c.obj): in function `wav_decoder_open':
/home/houhaiyan/esp-audio-adf-projects/esp-adf-libs-source/esp_processing/esp-wrapper/wav_decoder.c:139: multiple definition of `wav_decoder_open'; esp-idf/esp-sr/libesp-sr.a(wav_decoder.c.obj):/home/User/esp/esp-adf/components/esp-sr/esp-tts/esp_tts_wav/wav_decoder.c:64: first defined here
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_codec/lib/esp32/libesp_processing.a(wav_decoder.c.obj): in function `wav_decoder_close':
/home/houhaiyan/esp-audio-adf-projects/esp-adf-libs-source/esp_processing/esp-wrapper/wav_decoder.c:198: multiple definition of `wav_decoder_close'; esp-idf/esp-sr/libesp-sr.a(wav_decoder.c.obj):/home/User/esp/esp-adf/components/esp-sr/esp-tts/esp_tts_wav/wav_decoder.c:130: first defined here
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a(media_ctrl.c.obj):(.literal.media_state_que_clear+0x0): undefined reference to `xQueueGenericReceive'
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a(media_ctrl.c.obj): in function `media_state_que_clear':
/Users/maojianxin/duros/esp-adf-libs-source/esp_audio/src/media_ctrl.c:117: undefined reference to `xQueueGenericReceive'
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a(media_ctrl.c.obj): in function `media_state_sync':
/Users/maojianxin/duros/esp-adf-libs-source/esp_audio/src/media_ctrl.c:57: undefined reference to `xQueueGenericReceive'
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a(media_ctrl.c.obj): in function `media_ctrl_add_in_stream':
/Users/maojianxin/duros/esp-adf-libs-source/esp_audio/src/media_ctrl.c:263: undefined reference to `xQueueGenericReceive'
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a(media_ctrl.c.obj): in function `media_ctrl_add_out_stream':
/Users/maojianxin/duros/esp-adf-libs-source/esp_audio/src/media_ctrl.c:485: undefined reference to `xQueueGenericReceive'
/home/User/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/User/esp/esp-adf/components/esp-adf-libs/esp_audio/lib/esp32/libesp_audio.a(media_ctrl.c.obj):/Users/maojianxin/duros/esp-adf-libs-source/esp_audio/src/media_ctrl.c:507: more undefined references to `xQueueGenericReceive' follow
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`

**Comment by SeeOneeee** [comment]
@jason-mao Thanks for the reply! Here is the Error Log - it is quite long.
[Error_Log.txt](https://github.com/espressif/esp-adf/files/5451897/Error_Log.txt)

**Comment by jason-mao** [comment]
@SeeOneeee Would you please test your problem with latest master ?

**Comment by grewhit25** [comment]
I have tested this against the latest master and it is still failing for me; error log same as @jason-mao

**Comment by jason-mao** [comment]
What IDF version you use?

**Comment by grewhit25** [comment]
@jason-mao my idf.py --version
ESP-IDF v4.3-dev-1901-g178b122c1

**Comment by jason-mao** [comment]
BTW, did you test with other versions, such as v4.2 v4.1.

**Comment by grewhit25** [comment]
Yes, my bad.
I can confirm that I rolled back to v4.1 and v4.2-rc; both compiled the example successfully.
Apologies for time wasting.
