### ISSUE TITLE
The config menu without the selection for "ESP32-LyraT-Mini V1.2" board! Only can choose V1.1 (AUD-2440)

### ISSUE THREAD

**Issue by kylongmu** [espressif/esp-adf#489]
![图片](https://user-images.githubusercontent.com/28899073/97688384-0a69e380-1ad5-11eb-8117-2c21b2273861.png)
I just bought the V1.2 board, but I can't find the board in the config menu, I don't know what's the differnet between them, my code can't works well with V1.1 board, but it works ok on the LyraT board.

**Comment by jason-mao** [comment]
@kylongmu 
There are no  functionality difference between Lyrat Mini v1.1 and Lyrat Mini v1.2. So select the v1.1 can be work with v1.2 board. 
As you said, can't work with v1.2 but ok for LyraT, I think should be other thing caused.
