### ISSUE TITLE
Change sample rate of a2dp source (AUD-2456)

### ISSUE THREAD

**Issue by nikolindima** [espressif/esp-adf#493]
Hello, i want to use bluetooth headphones on 16khz sample rate. How I can change it?
I tried to set it with audio_element_setinfo
tried with audio_element_set_music_info
but not works

I use this pipeline i2s_read-->bt_stream_writer
i2s is set to 16khz with audio_element_setinfo

Please help

**Comment by espressif-zhanghu** [comment]
hello, our a2dp support 44100 and 48000 about sample rate.

**Comment by espressif-zhanghu** [comment]
if set i2s sample rate

**Comment by espressif-zhanghu** [comment]
If set i2s sample rate:
i2s_stream_cfg_t -> i2s_config -> sample_rate
or use "i2s_stream_set_clk(audio_element_handle_t i2s_stream, int rate, int bits, int ch)"
