### ISSUE TITLE
algo_stream error (AUD-2461)

### ISSUE THREAD

**Issue by utkutpcgl** [espressif/esp-adf#494]
I am not certainly sure but in this pipeline:
microphone -> i2s_stream_read -> (input_buffer1) -> amr_encoder ->amr_decoder ->(input_buffer2) ->i2s_stream_write -> speaker
I expect the record signal input buffer to be input_buffer1 and the reference signal's buffer to be input_buffer2. If I am wrong please correct me. This seemed logical to me by looking at the following diagram:
![image](https://user-images.githubusercontent.com/18088068/97067973-dfaaf700-15cb-11eb-8511-43e00e2b7d48.png)

When I tried to build the project with algo stream added I face the following error:

`[5/7] Generating ld/esp32.project.ld
warning: the default selection ESP32_KORVO_DU1906_CODEC_TAS5805M (undefined) of <choice ESP32_KORVO_DU1906_DAC> (defined at C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/audio_board/Kconfig.projbuild:27) is not contained in the choice
[6/7] Linking CXX executable dinleme_deneme.elf
FAILED: dinleme_deneme.elf
cmd.exe /C "cd . && C:\Users\utkum\.espressif\tools\xtensa-esp32-elf\esp-2020r2-8.2.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-address   @CMakeFiles\dinleme_deneme.elf.rsp  -o dinleme_deneme.elf  && cd ."
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x48): undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x4c): undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x58): undefined reference to `esp_kiss_fftri'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_noisemean_cal':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:123: undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: /home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:131: undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_pro':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:217: undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: /home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:257: undefined reference to `esp_kiss_fftri'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `esp_ns_alloc':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.h:30: undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/Documents/esp32_idf4.1_latestADF/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_init':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:295: undefined reference to `esp_kiss_fftr_alloc'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`

As far as I understand libesp_audio_processor.a has a reference to **esp_kiss_fftr** in _noise suppression related functions_ in the **ns_core** file. I guess I faced a bug. I would be glad if you could help.

I use:

> Latest adf version
> idf version 4.1
> Windows idf command prompt
> esp32_lyrat board.

Have a nice day.

_Originally posted by @utkutpcgl in https://github.com/espressif/esp-adf/issues/464#issuecomment-715164315_

**Comment by Patsjemoe** [comment]
Hi,
@utkutpcgl, did you get the example code already? 
Do you combine algorithm stream with pipeline?
Regards

**Comment by utkutpcgl** [comment]
Hi,
I could not find the example yet. Yes, I think we have to combine it with the pipeline as an element.
Best wishes.

**Comment by utkutpcgl** [comment]
The example is available.

**Comment by utkutpcgl** [comment]
I tried to flash LyraT with the structure given in the example code again, however, there is still the same error:

>`c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/OneDrive/Belgeler/esp/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x3c): undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/OneDrive/Belgeler/esp/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x40): undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/OneDrive/Belgeler/esp/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o):(.literal.ns_pro+0x4c): undefined reference to `esp_kiss_fftri'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/OneDrive/Belgeler/esp/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_noisemean_cal':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:123: undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: /home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:131: undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/OneDrive/Belgeler/esp/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_pro':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:217: undefined reference to `esp_kiss_fftr'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: /home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:257: undefined reference to `esp_kiss_fftri'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/OneDrive/Belgeler/esp/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `esp_ns_alloc':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.h:30: undefined reference to `esp_kiss_fftr_alloc'
c:/users/utkum/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:/Users/utkum/OneDrive/Belgeler/esp/esp-adf/components/esp-sr/acoustic_algorithm\libesp_audio_processor.a(ns_core.o): in function `ns_init':
/home/zhaoyang/esp/esp_sr_lib/components/esp_audio_processor/noise_suppression/ns_core.c:295: undefined reference to `esp_kiss_fftr_alloc'`

It has been 20 days since I reported this error, so, it would be nice at least to see a response. 
Thanks in advance.

**Comment by jason-mao** [comment]
@utkutpcgl Sorry for missing, would you please provide your IDF version and ADF commit or version?

**Comment by utkutpcgl** [comment]
I use latest esp-adf and esp-idf 4.1. Thanks @jason-mao , I understand you have not much time.

**Comment by jason-mao** [comment]
@utkutpcgl  There is a quick fixes as follow.
```c
cd $ADF_PATH/components/esp-sr/
git checkout master
git pull
```
Then modify the CMakeLists.txt, Add `add_prebuilt_library(esp_audio_processor "${CMAKE_CURRENT_SOURCE_DIR}/acoustic_algorithm/libesp_audio_processor.a" PRIV_REQUIRES esp-sr)` behind  
https://github.com/espressif/esp-sr/blob/eec128886f882f4bd446eb53588c16858a68acb1/CMakeLists.txt#L23.
,such as 
![image](https://user-images.githubusercontent.com/25599977/100325308-660b8c00-3003-11eb-862b-270e118eb697.png)

**Comment by utkutpcgl** [comment]
Thanks for the fast response, I will share the results.

**Comment by utkutpcgl** [comment]
It works fine as far as I have tested. Thanks!

**Comment by Patsjemoe** [comment]
Hi,
Did you use it as it is, or did you make any changes?
I am trying to implement it in VOIP, but am still struggling due to
unclarities in description of multi input/output ringbuffers
regards
Ludo

Op di 8 dec. 2020 10:32 schreef utkutpcgl <notifications@github.com>:
