### ISSUE TITLE
micropython recorder wav file error (AUD-2467)

### ISSUE THREAD

**Issue by liuyunrui123** [espressif/esp-adf#495]
micropython recorder wav file error. the recorder wav file can not player
micropython录音wav文件，录音文件格式不对无法播放

**Comment by jason-mao** [comment]
@liuyunrui123 请把您录下来的文件提供一下

**Comment by liuyunrui123** [comment]
不好意思，现在测试可以了。因为我之前修改过源码，应该是把mpconfig的&nbsp;MICROPY_STREAMS_POSIX_API配置打开后就可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-adf"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 中午11:30
收件人:&nbsp;"espressif/esp-adf"<esp-adf@noreply.github.com&gt;;
抄送:&nbsp;"林夕"<1753668086@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [espressif/esp-adf] micropython recorder wav file error (AUD-2467) (#495)





 
@liuyunrui123 请把您录下来的文件提供一下
