### ISSUE TITLE
Add an Equalizer to the current ADF

### ISSUE THREAD

**Issue by srinaag** [espressif/esp-adf#5]
Hello,

I would like to add an equalizer on audio output in ADF framework. In short i need access to data or embed equalizer functionality into pipeline as an element. 

How do i do that. I have gone through documentation and the code but is clear as mud.

Thank you.

**Comment by jason-mao** [comment]
Hi Srinaag

The pipeline will be like this`file element`->`mp3 element`->`equalizer  element`->`i2s element`.
`equalizer  element` data input by `audio_element_input`, output data by `audio_element_output`. You can refer to `filter_resample`. If you have any problems, please let me know.
