### ISSUE TITLE
希望能够修改录音wav头文件信息

### ISSUE THREAD

**Issue by donny681** [espressif/esp-adf#50]
现在ｓｄｋ提供录音ｄｅｍｏ只支持44.1ＫＨｚ格式下录音，不开放１６ｋＨｚ录音，我查看了源码，采集数据是可以做到１６ｋ录音，但是ｗａｖ信息头文件还是写到４４．１ＫＨz,导致录音文件播放出错，后来追踪到贵司把该部分代码封装到静态库，这样子无法修改ｗａｖ头文件，１６ＫＨｚ和８ＫＨｚ是非常常用的格式。，希望贵司工程师能够开放支持修改ｗａｖ头文件信息。

**Comment by ahhfzhang** [comment]
Hi @donny681 ,
Thanks for mention, these were supported, you can try like below : 
>--- a/examples/recorder/pipeline_wav_sdcard/main/record_wav_sdcard_example.c
>+++ b/examples/recorder/pipeline_wav_sdcard/main/record_wav_sdcard_example.c
@@ -68,10 +68,17 @@ void app_main(void)
     fatfs_stream_cfg_t fatfs_cfg = FATFS_STREAM_CFG_DEFAULT();
     fatfs_cfg.type = AUDIO_STREAM_WRITER;
     fatfs_stream_writer = fatfs_stream_init(&fatfs_cfg);
> +    audio_element_info_t fatfs_info;
> +    audio_element_getinfo(fatfs_stream_writer, &fatfs_info);
> +    fatfs_info.sample_rates = 16000;
> +    fatfs_info.channels = 1;
> +    audio_element_setinfo(fatfs_stream_writer, &fatfs_info);
>
>    ESP_LOGI(TAG, "[3.2] Create i2s stream to read audio data from codec chip");
>    i2s_stream_cfg_t i2s_cfg = I2S_STREAM_CFG_DEFAULT();
>    i2s_cfg.type = AUDIO_STREAM_READER;
> +    i2s_cfg.i2s_config.sample_rate = 16000;
> +    i2s_cfg.i2s_config.channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT;
>
>i2s_stream_reader = i2s_stream_init(&i2s_cfg);
 
We will be submitted to the examples which facilitate the users to modify.
