### ISSUE TITLE
LyraT Mini V1.2 not available in menuconfig (AUD-2483)

### ISSUE THREAD

**Issue by bs-eng** [espressif/esp-adf#500]
Hi!
I am using ADF V2.1 together with a *LyraT-Mini V1.2*.
When selecting the audio-hal, there is an option for choosing *LyraT-Mini V1.1*. However the *LyraT-Mini V1.2* ist missing.

Is that because they are identical?
Is it still in development pipeline?
What do I need to consider different between the boards?
Electrically I could not find out anything as the schematics of the *LyraT-Mini V1.1* seem to be nowhere available.

Thanks a lot!
![image](https://user-images.githubusercontent.com/48256081/98797358-bc29de00-240c-11eb-8cfb-676337d9bf83.png)

**Comment by jason-mao** [comment]
Same with #489 .

There are no functionality difference between Lyrat Mini v1.1 and Lyrat Mini v1.2. So select the v1.1 can be work with v1.2 board.
