### ISSUE TITLE
pipeline elements order (AUD-2486)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#502]
hi,
when creating a pipeline, and adding elements to it, how do you define the position of each element in the pipeline ?
I assume it is the order of registering the element to the pipeline.....is this correct ?
thanks in advance
regards
ludo

**Comment by jason-mao** [comment]
@Patsjemoe 

> I assume it is the order of registering the element to the pipeline.....is this correct ?
Yes.

**Comment by Patsjemoe** [comment]
Thanks
