### ISSUE TITLE
AMRWB causes watchdog error. (AUD-2503)

### ISSUE THREAD

**Issue by utkutpcgl** [espressif/esp-adf#505]
I use amrwb in my pipeline and when it starts the watchog timer raises an error repeatedly that it was not reset. I use Lyrat, espidf 4.1 and latest adf with esp idf on CMD. Thanks in advance.

**Comment by jason-mao** [comment]
Please use `audio_sys_get_real_time_stats` to make cpu loading in balance.

**Comment by utkutpcgl** [comment]
Thanks, I will share the results later.

**Comment by utkutpcgl** [comment]
I assigned core 0 to the amrwb encoder (works faster this way) and core1 to amrwb decoder as task cores (task_core variable of config) and now it works without the watchdog timer errors. Thanks! I see that audio_sys_get_real_time_stats is new. The library is progressing well. Thanks again.

**Comment by Patsjemoe** [comment]
Hi,
Can you share how you assigned the encoder and decoder to core 0 and 1?
Maybe this will help me to  solve my problem with voip aec algorithm
stream...

Thanks
Ludo

Op wo 25 nov. 2020 09:42 schreef utkutpcgl <notifications@github.com>:

**Comment by utkutpcgl** [comment]
@Patsjemoe I changed the task core of amr decoder by modifying the following struct: 
![image](https://user-images.githubusercontent.com/18088068/100311002-bfea6280-2fbf-11eb-93bc-cb9fd317ebf4.png)
I guess your problem was a little different, but hopefully, it helps. 
Best wishes.

**Comment by Patsjemoe** [comment]
Thanks

Op do 26 nov. 2020 06:18 schreef utkutpcgl <notifications@github.com>:
