### ISSUE TITLE
audio_thread_create() can't get pointer to audio_thread_t handle (AUD-2516)

### ISSUE THREAD

**Issue by liangzhu2008** [espressif/esp-adf#508]
我有一段如下的代码：

```
audio_thread_t      tsk_handle; 
audio_thread_create(&tsk_handle, "wb_player_task", wb_player_manager_task, wb_player, 4*1024, 13, true, 0);
ESP_LOGI(TAG, "tsk_handle=%p", tsk_handle);
```

打印的结果如下：
`I (43094) CONSOLE_EXAMPLE: wb_player_manager_deinit(): wb_player->tsk_handle=0x0`

看起来 `audio_thread_create() ` 并不能直正返回 `tsk_handle` 。

**Comment by jason-mao** [comment]
@liangzhu2008 Thanks for your report. It will be fixed.
