### ISSUE TITLE
Esp32 transmit call voice to blueooth speaker (AUD-2520)

### ISSUE THREAD

**Issue by utya** [espressif/esp-adf#510]
Hello. I want connect my esp32 to car audio system. Transmit voice call from sim800 to car audio system. As far as i know, it's hfp. i see sample, but this sample esp32 as blueooth speaker.
could you help me, whant project shouls i use?

I'm more interested in the transmission of button presses on the stereo system to the esp21

**Comment by jason-mao** [comment]
https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_a2dp_source_stream
https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_a2dp_sink_stream

There are two example can be help you. BTW,  if you want to setup project, suggest use the high level API such as https://github.com/espressif/esp-adf/tree/master/examples/korvo_du1906/components/audio_player
