### ISSUE TITLE
algorithm_stream example ringbuffer  (AUD-2558)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#520]
hi, 
the example you provided shows input _rb=algo_stream_GET_multiple_input_rb(element_algo)
and audio_element_set_multi_output_ringbuf().
I am puzzled, because I do not find a set up for 2 inputs to the AEC , and would expect a "set" function.
Do I need to set multi output in the player section, and multi input in the rec section ?
Is rsp done inside algo ?  
Can you help to better understand ?
If there is a document, possibly with a good block diagram explaining this, it is also welcome.
thanks in advance
best regards
ludo

**Comment by jason-mao** [comment]
@Patsjemoe https://github.com/espressif/esp-adf/blob/73a2ec52436ce30195c010c05c9382bfac09eadc/components/audio_stream/algorithm_stream.c#L601,
this line to set the algo_stream have multi-input ring buffer, the `algo_stream_get_multiple_input_rb ` is available.

https://github.com/espressif/esp-adf/blob/73a2ec52436ce30195c010c05c9382bfac09eadc/examples/advanced_examples/algorithm/main/algorithm_examples.c#L71, to decide how many multiple_input they have.

> Is rsp done inside algo ?

Yes,the AEC ask the input stream  should be 16k rate and signal channel. But most the music is not. The `algo_stream` integrate the resample to downstream the music. So we provide new apis as `algo_stream_set_reference_rate` and `algo_stream_set_record_rate` .

**Comment by Patsjemoe** [comment]
thank you
