### ISSUE TITLE
ESP32_LyraT  vol- canot work? (AUD-2571)

### ISSUE THREAD

**Issue by KISSMonX** [espressif/esp-adf#524]
ESP32-LyraT V4.3

**SD Card Mode set 1_Line**

```c
audio_board_sdcard_init(set, SD_MODE_1_LINE);
```

![image](https://user-images.githubusercontent.com/2876745/100754341-f263e780-3425-11eb-8cbd-6a249344a1ad.png)

![image](https://user-images.githubusercontent.com/2876745/100754515-26d7a380-3426-11eb-90e2-27cc340cff25.png)

**Comment by KISSMonX** [comment]
![image](https://user-images.githubusercontent.com/2876745/100756726-7b7c1e00-3428-11eb-9fed-57588921d65e.png)

**Comment by HengYongChao** [comment]
Hi @KISSMonX 

According to [the schematic diagram of ESP32-Lyrat v4.3](https://docs.espressif.com/projects/esp-adf/en/latest/design-guide/dev-boards/board-esp32-lyrat-v4.3.html), if you need to use the touch button vol- , then you should set the multiplexed key GPIO13 back to the OFF position.
![Selection_331](https://user-images.githubusercontent.com/4134628/153113785-065d0633-941a-48d0-b1e2-3732509d1504.png)

And I've tested, the touch function of VOL- can be used normally.
![Selection_332](https://user-images.githubusercontent.com/4134628/153113946-bbc363b8-1732-46e1-b1bb-efedede27f77.png)

Please try as I mentioned.
