### ISSUE TITLE
DLNA酷狗音乐不能播放，网易音乐可以播放 (AUD-2639)

### ISSUE THREAD

**Issue by 3050311118** [espressif/esp-adf#547]
具体酷狗音乐可以连接上，但是点击播放按键没有反应
W (157732) httpd: httpd_server: error accepting new connection
W (158022) httpd: httpd_accept_conn: error in accept (23)
W (158022) httpd: httpd_server: error accepting new connection
I (176672) DLNA_EXAMPLE: Stop instance=0
W (176672) ESP_AUDIO_CTRL: [media_ctrl_stop]-Already stopped, status is UNKNOWN, phase:0
I (176672) DLNA_EXAMPLE: _avt_get_trans_state STOPPED
E (176682) TRANS_TCP: Error create socket
E (176682) HTTP_CLIENT: Connection failed, sock < 0
E (176682) UPNP_NOTIFY: Unsubscribe=uuid:37521657-2fdb-625e-5020-329b54fbc038
I (184922) DLNA_EXAMPLE: _avt_get_trans_state STOPPED
I (185282) DLNA_EXAMPLE: Stop instance=0
W (185282) ESP_AUDIO_CTRL: [media_ctrl_stop]-Already stopped, status is UNKNOWN, phase:0
I (185282) DLNA_EXAMPLE: _avt_get_trans_state STOPPED
W (188142) httpd: httpd_accept_conn: error in accept (23)
W (188142) httpd: httpd_server: error accepting new connection
W (188162) httpd: httpd_accept_conn: error in accept (23)
W (188162) httpd: httpd_server: error accepting new connection

**Comment by ahhfzhang** [comment]
酷狗音乐 可能有一些私有协议在，目前还没有支持。
