### ISSUE TITLE
esp-adf  ESP32S2还不能用，编译通不过 (AUD-2634)

### ISSUE THREAD

**Issue by 3050311118** [espressif/esp-adf#548]
编译一些简单的范例会出现这种错误
audio hal选择的是esp32s2 kaluga 

error: 'CLK_I2S_MUX_IDX' undeclared (first use in this function)
error: 'GPIO_NUM_46' undeclared (first use in this function)

**Comment by huybk213** [comment]
You should type command in esp-idf
idf.py set-target esp32s2
or you can checkout esp-idf branch release/4.2 instead of 3.3
