### ISSUE TITLE
求提供关于i2s的SCLK和LRCK的时钟频率由外部提供的方法

### ISSUE THREAD

**Issue by gnc1994** [espressif/esp-adf#55]
求提供关于i2s的SCLK和LRCK的时钟频率由外部提供的方法，我们公司准备接上esp32传蓝牙音频，问题是我们的SCLK和LRCK由自己的DSP芯片提供，历程上esp32的音频好像只能选择由esp提供，能否由外部提供i2s时钟信号，如何修改，万分感谢能提供帮助的

**Comment by jason-mao** [comment]
@gnc1994 I2S 工作在slave的模式下就可以接收外部的SCLK和LRCK。
