### ISSUE TITLE
ESP ADF change/set I2S GPIOs (AUD-2660)

### ISSUE THREAD

**Issue by DEMP1993** [espressif/esp-adf#553]
Hello,

is it possible to set the GPIO from the I2S stream ?

In the I2S.h from the IDF is the initialization workflow:

1.  Installing the Driver (_i2s_config_t_)
2. Setting Communication Pins (_i2s_pin_config_t_)
...

In the ADF we configure the I2S Stream [4] over the _i2s_stream_cfg_t_. This includes the _i2s_config_t_ from the I2S.h initialization workflow, but i can not the _i2s_pin_config_t_ in the _i2s_stream_cfg_t_ from the ADF.

Did someone find out how to change the I2S pins?

**Comment by HengYongChao** [comment]
Hi @DEMP1993 , 
In ADF I2s pins are pre-set for support some official development boards, The configuration flow is as follows:
1. Read config by function `get_i2s_pins(I2S_NUM, &i2s_pin_cfg);`, save the pins config in `i2s_pin_cfg` struct.
2.  Set the I2S pins by function `i2s_set_pin(I2S_NUM, &i2s_pin_cfg);`
3. Set mclk output `i2s_mclk_gpio_select(I2S_NUM, GPIO_NUM_0);`

So, if you want change the i2s pins, you may do some steps in the init step of your code like:
1. First initialize the structure  `i2s_pin_config_t i2s_pin_cfg = {....}`
2. Set I2S pins by use function `i2s_set_pin(2S_NUM, &i2s_pin_cfg);`
3. Set mclk output `i2s_mclk_gpio_select(TEST_I2S_NUM, GPIO_NUM_0);`

I hope these answers were helpful to you.

**Comment by DEMP1993** [comment]
Hi HengYongChao,

thanks for the answer. It is very helpfull.

**Comment by ujur007** [comment]
Seems this is very old, for IDF 5.5.1 what is the replacement? could you tell?

I got conflict.

`E (270) i2s(legacy): CONFLICT! The new i2s driver can't work along with the legacy i2s driver`
