### ISSUE TITLE
PERIPH_BUTTON_LONG_PRESSED not triggered when using self soldered button (AUD-2718)

### ISSUE THREAD

**Issue by devax** [espressif/esp-adf#559]
Sorry, if this is a bit off-topic, but I'm not sure where to address this question.
I'm using a Lyra-T V4.3 board and I want to add an external button for the Vol+ touch button. From the schematic I've seen that the button is connected with IO27. So I solderd a push button directly on IO27 and connected it to ground (also tried with 3.3V).
Basically this works, when I push and release and long push the button, I can capture `PERIPH_BUTTON_PRESSED`, `PERIPH_BUTTON_RELEASE` and `PERIPH_BUTTON_LONG_RELEASE` events but for to me unknown reasons, the `PERIPH_BUTTON_LONG_PRESSED` does not show up (unlike when I use the touch button directly).
I also tried with the Play button, but same behavior. I must do something very wrong here, so if anyone can give me a clue or point me to the right direction for my question, this would be much appreciated. Here is my relevant code (snippet):

```
    input_key_service_info_t input_key_info[] = INPUT_KEY_DEFAULT_INFO();
    input_key_service_cfg_t input_cfg = INPUT_KEY_SERVICE_DEFAULT_CONFIG();
    input_cfg.handle = set;
    periph_service_handle_t input_ser = input_key_service_create(&input_cfg);
    input_key_service_add_key(input_ser, input_key_info, INPUT_KEY_NUM);
    periph_service_set_callback(input_ser, input_key_service_cb, NULL);
```

And this is the callback function:
```
static esp_err_t input_key_service_cb(periph_service_handle_t handle, periph_service_event_t *evt, void *ctx)
{
    printf("Type: %d, data: %d, source: %d\n", evt->type, (int)evt->data, (int)evt->source);
    return ESP_OK;
}
```

This is the output for short press/release (as expected):
```
Type: 1, data: 6, source: 1048578
Type: 2, data: 6, source: 1048578
```

And for long press/release (type "3" is missing, this is unexpected):
```
Type: 1, data: 6, source: 1048578
Type: 4, data: 6, source: 1048578
```

And in comparison to what I get when I use the onboard touch button directly (as expected):
```
Type: 1, data: 6, source: 1048578
Type: 3, data: 6, source: 1048578
Type: 4, data: 6, source: 1048578
```

**Comment by HengYongChao** [comment]
Hi, @devax 
PLease try to init long press time value, then try again, code like:
```
    periph_button_cfg_t btn_cfg = {
        .gpio_mask = GPIO_SEL_32,
        .long_press_time_ms = 5000,     /* should be 5000 ,reduce time for debug*/
    };
    esp_periph_handle_t button_handle = periph_button_init(&btn_cfg);
```
Reply here if got any question.
