### ISSUE TITLE
蓝牙音频的i2s传输想改成32位输出到dac上应该改哪里

### ISSUE THREAD

**Issue by gnc1994** [espressif/esp-adf#56]
蓝牙音频的i2s传输想改32位输出到dac上，在历程上改了32位，用示波器测试计算还是16位，bck为1.4m左右，理论应该为2.8m。能提供一下怎么更改吗

**Comment by jason-mao** [comment]
@gnc1994 esp32的DAC 只有8bit.如果只是修改BCK频率，可以修改`bits_per_sample`为32.
