### ISSUE TITLE
ESP  LyraT mini v1.2 megaphone (AUD-2730)

### ISSUE THREAD

**Issue by vrycue** [espressif/esp-adf#561]
is it possible to output mic directly to the speakers? I tried the pipeline that looks like this:       i2s_reader --->  i2swriter, I can only hear noise even when using headphones.

**Comment by HengYongChao** [comment]
Hi, @vrycue 
FYI:  [MIC] --> [CODEC CHIP] --> I2S_READER  --> RINGBUFF --> I2S_WRITER --> [CODEC CHIP] -->[PA] --> [SPEAKER]

**Comment by vrycue** [comment]
I have modified the passthru example here is my code`

#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "audio_pipeline.h"
#include "i2s_stream.h"
#include "raw_stream.h"
#include "board.h"

static const char *TAG = "PASSTHRU";

void app_main(void)
{
    audio_pipeline_handle_t pipeline;
    audio_element_handle_t i2s_stream_writer, i2s_stream_reader, el_raw_write;

    esp_log_level_set("*", ESP_LOG_INFO);
    esp_log_level_set(TAG, ESP_LOG_DEBUG);

    ESP_LOGI(TAG, "[ 1 ] Start codec chip");
    audio_board_handle_t board_handle = audio_board_init();

#ifdef CONFIG_ESP32_S2_KALUGA_1_V1_2_BOARD
    audio_hal_ctrl_codec(board_handle->audio_hal, AUDIO_HAL_CODEC_MODE_BOTH, AUDIO_HAL_CTRL_START);
#else
    audio_hal_ctrl_codec(board_handle->audio_hal, AUDIO_HAL_CODEC_MODE_BOTH, AUDIO_HAL_CTRL_START);
#endif

    audio_hal_set_volume(board_handle-> audio_hal, 100);

    ESP_LOGI(TAG, "[ 2 ] Create audio pipeline for playback");
    audio_pipeline_cfg_t pipeline_cfg = DEFAULT_AUDIO_PIPELINE_CONFIG();
    pipeline = audio_pipeline_init(&pipeline_cfg);

    ESP_LOGI(TAG, "[3.1] Create i2s stream to write data to codec chip");
    i2s_stream_cfg_t i2s_cfg = I2S_STREAM_CFG_DEFAULT();
    i2s_cfg.type = AUDIO_STREAM_WRITER;
    i2s_stream_writer = i2s_stream_init(&i2s_cfg);

    ESP_LOGI(TAG, "[3.2] Create i2s stream to read data from codec chip");
    i2s_stream_cfg_t i2s_cfg_read = I2S_STREAM_CFG_DEFAULT();
    i2s_cfg_read.type = AUDIO_STREAM_READER;
    i2s_cfg.i2s_port = 1;
    i2s_cfg.multi_out_num = 1;
    i2s_stream_reader = i2s_stream_init(&i2s_cfg_read);

    ESP_LOGI(TAG, "[4.2] Create raw stream of base wav to write data");
    raw_stream_cfg_t raw_cfg = RAW_STREAM_CFG_DEFAULT();
    raw_cfg.type = AUDIO_STREAM_WRITER;

    el_raw_write = raw_stream_init(&raw_cfg);

    ESP_LOGI(TAG, "[3.3] Register all elements to audio pipeline");
    audio_pipeline_register(pipeline, i2s_stream_reader, "i2s_read");
    audio_pipeline_register(pipeline, el_raw_write, "raw");
    audio_pipeline_register(pipeline, i2s_stream_writer, "i2s_write");

    ESP_LOGI(TAG, "[3.4] Link it together [codec_chip]-->i2s_stream_reader-->i2s_stream_writer-->[codec_chip]");
    const char *link_tag[3] = {"i2s_read", "raw", "i2s_write"};
    audio_pipeline_link(pipeline, &link_tag[0], 3);

    ringbuf_handle_t rb = audio_element_get_output_ringbuf(el_raw_write);
    audio_element_set_multi_output_ringbuf(i2s_stream_reader, rb, 0);

    ESP_LOGI(TAG, "[ 4 ] Set up  event listener");
    audio_event_iface_cfg_t evt_cfg = AUDIO_EVENT_IFACE_DEFAULT_CFG();
    audio_event_iface_handle_t evt = audio_event_iface_init(&evt_cfg);

    ESP_LOGI(TAG, "[4.1] Listening event from all elements of pipeline");
    audio_pipeline_set_listener(pipeline, evt);

    ESP_LOGI(TAG, "[ 5 ] Start audio_pipeline");
    audio_pipeline_run(pipeline);

    ESP_LOGI(TAG, "[ 6 ] Listen for all pipeline events");
    while (1) {
        audio_event_iface_msg_t msg;
        esp_err_t ret = audio_event_iface_listen(evt, &msg, portMAX_DELAY);
        if (ret != ESP_OK) {
            ESP_LOGE(TAG, "[ * ] Event interface error : %d", ret);
            continue;
        }

        if (msg.cmd == AEL_MSG_CMD_ERROR) {
            ESP_LOGE(TAG, "[ * ] Action command error: src_type:%d, source:%p cmd:%d, data:%p, data_len:%d",
                     msg.source_type, msg.source, msg.cmd, msg.data, msg.data_len);
        }

        /* Stop when the last pipeline element (i2s_stream_writer in this case) receives stop event */
        if (msg.source_type == AUDIO_ELEMENT_TYPE_ELEMENT && msg.source == (void *) i2s_stream_writer
            && msg.cmd == AEL_MSG_CMD_REPORT_STATUS
            && (((int)msg.data == AEL_STATUS_STATE_STOPPED) || ((int)msg.data == AEL_STATUS_STATE_FINISHED))) {
            ESP_LOGW(TAG, "[ * ] Stop event received");
            break;
        }
    }

    ESP_LOGI(TAG, "[ 7 ] Stop audio_pipeline");
    audio_pipeline_stop(pipeline);
    audio_pipeline_wait_for_stop(pipeline);
    audio_pipeline_terminate(pipeline);

    audio_pipeline_unregister(pipeline, i2s_stream_reader);
    audio_pipeline_unregister(pipeline, el_raw_write);
    audio_pipeline_unregister(pipeline, i2s_stream_writer);

    /* Terminate the pipeline before removing the listener */
    audio_pipeline_remove_listener(pipeline);

    /* Make sure audio_pipeline_remove_listener & audio_event_iface_remove_listener are called before destroying event_iface */
    audio_event_iface_destroy(evt);

    /* Release all resources */
    audio_pipeline_deinit(pipeline);
    audio_element_deinit(i2s_stream_reader);
    audio_element_deinit(el_raw_write);    
    audio_element_deinit(i2s_stream_writer);
}
` Still not working here are the logs I (0) cpu_start: App cpu up.
I (250) heap_init: Initializing. RAM available for dynamic allocation:
I (256) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (263) heap_init: At 3FFB2A68 len 0002D598 (181 KiB): DRAM
I (269) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (275) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (282) heap_init: At 4008B934 len 000146CC (81 KiB): IRAM
I (288) cpu_start: Pro cpu start user code
I (306) spi_flash: detected chip: gd
I (306) spi_flash: flash io: dio
I (307) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (314) PASSTHRU: [ 1 ] Start codec chip
I (324) DRV8311: ES8311 in Slave mode
I (344) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
W (344) I2C_BUS: i2c_bus_create:57: I2C bus has been already created, [port:0]
I (344) AUDIO_HAL: Codec mode is 3, Ctrl:1
I (354) PASSTHRU: [ 2 ] Create audio pipeline for playback
I (354) PASSTHRU: [3.1] Create i2s stream to write data to codec chip
I (364) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (374) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (404) I2S: APLL: Req RATE: 44100, real rate: 44099.988, BITS: 16, CLKM: 1, BCK_M: 8, MCLK: 11289597.000, SCLK: 1411199.625000, diva: 1, divb: 0
I (404) LYRAT_MINI_V1_1: I2S0, MCLK output by GPIO0
I (414) PASSTHRU: [3.2] Create i2s stream to read data from codec chip
W (414) I2S: I2S driver already installed
I (424) LYRAT_MINI_V1_1: I2S0, MCLK output by GPIO0
I (424) PASSTHRU: [4.2] Create raw stream of base wav to write data
I (434) PASSTHRU: [3.3] Register all elements to audio pipeline
I (444) PASSTHRU: [3.4] Link it together [codec_chip]-->i2s_stream_reader-->i2s_stream_writer-->[codec_chip]
I (454) AUDIO_PIPELINE: link el->rb, el:0x3ffb8828, tag:i2s_read, rb:0x3ffb8ee8
I (464) AUDIO_PIPELINE: link el->rb, el:0x3ffb8b50, tag:raw, rb:0x3ffbb024
I (464) PASSTHRU: [ 4 ] Set up  event listener
I (474) PASSTHRU: [4.1] Listening event from all elements of pipeline
I (474) PASSTHRU: [ 5 ] Start audio_pipeline
I (484) AUDIO_ELEMENT: [i2s_read-0x3ffb8828] Element task created
I (494) AUDIO_ELEMENT: [raw-0x3ffb8b50] Element task created
I (494) AUDIO_ELEMENT: [i2s_write-0x3ffb8524] Element task created
I (504) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:259200 Bytes

I (514) AUDIO_ELEMENT: [i2s_read] AEL_MSG_CMD_RESUME,state:1
I (514) I2S_STREAM: AUDIO_STREAM_READER,Rate:44100,ch:2
I (544) I2S: APLL: Req RATE: 44100, real rate: 44099.988, BITS: 16, CLKM: 1, BCK_M: 8, MCLK: 11289597.000, SCLK: 1411199.625000, diva: 1, divb: 0
I (554) AUDIO_ELEMENT: [i2s_write] AEL_MSG_CMD_RESUME,state:1
I (554) I2S_STREAM: AUDIO_STREAM_WRITER
I (564) AUDIO_PIPELINE: Pipeline started
I (564) PASSTHRU: [ 6 ] Listen for all pipeline events

**Comment by HengYongChao** [comment]
Hi @vrycue 
I think you should read the example `record_while_play` , It's Similar to your need.
https://github.com/espressif/esp-adf/tree/master/examples/advanced_examples/record_while_play

**Comment by vrycue** [comment]
Hi @HengYongChao, okay ill check it out. Thank you.

**Comment by bulbitron** [comment]
Hello, I join the question, to do something that should be simple I am going crazy, LyraTmini microphone input, and output in real time, some of us are newbies, thanks.

**Comment by HyouinSchoolAcc** [comment]
Is it just me or have I never seen anyone managed to get lyrat mini's 1.2 microphone to work? I have never seen it work anywhere.

**Comment by Bhavesh-Moradiya** [comment]
lyrat mini's 1.2 microphone connected to ADC ES7243 only i guess, is it true?

**Comment by Bhavesh-Moradiya** [comment]
I am trying to get raw PCM data and want to stream on UDP socket but raw data buffer always 0
