### ISSUE TITLE
korvo_du1906 编译问题(ap_manager_event_register) (AUD-2742)

### ISSUE THREAD

**Issue by lindabang** [espressif/esp-adf#566]
编译korvo_du1906时遇到的问题：ap_manager_event_register 的声明在audio_player_manager.c与audio_player_manager.h不一致。
以下是详细的编译日志：

ayer.dir/audio_player_manager.c.obj -c ../components/audio_player/audio_player_manager.c
../components/audio_player/audio_player_manager.c:622:13: error: conflicting types for 'ap_manager_event_register'
 audio_err_t ap_manager_event_register(xQueueHandle que)
             ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../components/audio_player/audio_player_manager.c:40:
../components/audio_player/audio_player_manager.h:208:13: note: previous declaration of 'ap_manager_event_register' was here
 audio_err_t ap_manager_event_register(void *que);
             ^~~~~~~~~~~~~~~~~~~~~~~~~
../components/audio_player/audio_player_manager.c:630:13: error: conflicting types for 'ap_manager_event_unregister'
 audio_err_t ap_manager_event_unregister(xQueueHandle que)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../components/audio_player/audio_player_manager.c:40:
../components/audio_player/audio_player_manager.h:219:13: note: previous declaration of 'ap_manager_event_unregister' was here
 audio_err_t ap_manager_event_unregister(void *que);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by HengYongChao** [comment]
Hi，@lindabang 
 
Does this issue is the same question of #567 ? 

Please use[ audio/stack_on_psram_v3.3 branch](https://github.com/espressif/esp-idf/tree/audio/stack_on_psram_v3.3), and compile again.
