### ISSUE TITLE
ESP32S2 - software serial example (AUD-2771)

### ISSUE THREAD

**Issue by sudheeshsmadhav** [espressif/esp-adf#572]
Hi, I am working with a project where UART0 is log. uart1 is assigned for DAC out. So i cant use uart1. any possibility of software serial? using esp-idf.

**Comment by HengYongChao** [comment]
Hi @sudheeshsmadhav 

What is the software serial port used for? Would you like consider reusing uart1?

**Comment by sudheeshsmadhav** [comment]
I just configured a pin under uart1 and its working. Thank you.

**Comment by sudheeshsmadhav** [comment]
I just configured a pin under uart1 and its working. Thank you.
