### ISSUE TITLE
[google_translation_example] playback wasn't working, link_tag was not properly set (AUD-2787)

### ISSUE THREAD

**Issue by nicocesar** [espressif/esp-adf#574]
https://github.com/espressif/esp-adf/blob/0050cfeaa6b559e2a6ff2fe7bcdd91957095dbd6/examples/cloud_services/google_translate_device/main/google_tts.c#L195

Shouldn't this be `audio_pipeline_link(tts->pipeline, &link_tag[0], 3);`  ?

**Comment by HengYongChao** [comment]
Hi @nicocesar 
Thanks for your report.
