### ISSUE TITLE
mutex_unlock instead of mutex_lock (AUD-2802)

### ISSUE THREAD

**Issue by tq-petri** [espressif/esp-adf#578]
The following line seems to be wrong - it should be mutex_unlock instead of mutex_lock.

https://github.com/espressif/esp-adf/blob/f67fb23b44aba35de2ddab0f7748114669c775b8/components/esp_dispatcher/esp_dispatcher.c#L259

**Comment by jason-mao** [comment]
@tq-petri Thanks for your report.
