### ISSUE TITLE
使用AIRKISS的时候一直返回PERIPH_WIFI_SMARTCONFIG_ERROR (AUD-615)

### ISSUE THREAD

**Issue by bennyhuang007** [espressif/esp-adf#58]
使用AIRKISS的时候一直返回PERIPH_WIFI_SMARTCONFIG_ERROR
但是使用ESPTOUCH的时候能正常返回PERIPH_WIFI_SMARTCONFIG_DONE。
而且IDF的版本AIRKISS和ESPTOUCH都是正常返回PERIPH_WIFI_SMARTCONFIG_DONE的

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
