### ISSUE TITLE
audio_element_set_multi_output_ringbuf  dimensions (AUD-2810)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#580]
Hi,
Where/how can you define the size of the audio_element_set_multi_output_ringbuf ?
It has 2 outputs, can you define one buffer to be double of the other ?
thanks
regards
Ludo

**Comment by HengYongChao** [comment]
Hi, @Patsjemoe 

Q1: Take this piece code for example, first create ringbuf and the same time you need set the ringbuf size.
```
    ringbuf11 = rb_create(RING_BUFFER_SIZE, 1);
    audio_element_set_multi_output_ringbuf(i2s_stream_reader,ringbuf11,0);
    audio_element_set_input_ringbuf(amr_encoder,ringbuf11);
```
Q2: NO, they are separate.

**Comment by Patsjemoe** [comment]
Thank you, will try
