### ISSUE TITLE
Does it work with ESP32-C3 or ESP32-S3? (AUD-2811)

### ISSUE THREAD

**Issue by tapir** [espressif/esp-adf#581]
I know the documentation says ESP32 and ESP32-S2 but just wanted to make sure before committing to buy the wrong module.

**Comment by HengYongChao** [comment]
Hi @tapir 

ESP32-C3 is temporarily not supported, ESP32-S3 will support in release soon.

**Comment by MichaelDu9226** [comment]
@tapir 
Where can you buy ESP32 S3?

**Comment by tapir** [comment]
@MichaelDu9226 it was my mistake. Just looked at the espressif page and assumed it was in production.
