### ISSUE TITLE
Bluetooth service (AUD-614)

### ISSUE THREAD

**Issue by allenddld** [espressif/esp-adf#59]
"The service may also provide polices to allow device operation by specific user or application."
Is there more information about how to limit the user and application? 
bluetooth_service_start would set device name and mode.
bluetooth_service_create_stream and bluetooth_service_create_periph have no arguments
I tried to connect the LyraT with specific app and user. But I cant find how to edit api.

**Comment by ahhfzhang** [comment]
What API do you want to use to implement what?
