### ISSUE TITLE
esp_sip_uac_bye doesn't work (AUD-2907)

### ISSUE THREAD

**Issue by szucsi23** [espressif/esp-adf#593]
Hey!
I'm having an issue with the function esp_sip_uac_bye().
When I'm in a call, and hang up by calling this function, nothing happens on the other side. The logs show, that the function is called, but on the other end there is no sign of the hangup action, the call still goes on.

IDF version: v4.2
ADF version: v2.2

Logs attached.
[hangup_issue_logs.txt](https://github.com/espressif/esp-adf/files/6222502/hangup_issue_logs.txt)

**Comment by ahhfzhang** [comment]
Can you provide a complete log?

**Comment by szucsi23** [comment]
Yes, I'll provide the full logs tomorrow, I don't have the device with me right now.

**Comment by szucsi23** [comment]
Sorry, I got caught up with other things.
So here is the log for a full run.
I used the adf example voip app on a LyraT v4.3, but instead of antisip, I use signalwire, since that's the provider I'm using in my main application as well.

This is how the test goes:
- I flash the example VoIP code to my LyraT v4.3.
- I call my LyraT from the Zoiper VoIP app on Windows (other VoIP apps produce the same issue). The call is detected on line 184 of the log file.
- The call connects, audio is working.
- I press the Set button (for hangup) on the LyraT, and it should hang up the call. (line 364)
- The LyraT hangs up the call, but it's still alive in the Zoiper app on my PC.
- I press hangup on the Zoiper app on the PC (line 443)

Thank you for your help in advance!

[VoIP_example_logs.txt](https://github.com/espressif/esp-adf/files/6264894/VoIP_example_logs.txt)

**Comment by szucsi23** [comment]
Hey!
Just an update, it seems like if the LyraT initiates the call, the hangup works.
But if I call the LyraT from an other device, and hang up on the LyraT, it doesn't work.

Did you have a chance to check te logs?

**Comment by ahhfzhang** [comment]
Hi @szucsi23 ,

I have checked the log, 'BYE' is alerady send to the server, but i don't know why the server responded with a 404 (Not here).
![image](https://user-images.githubusercontent.com/3367837/120581550-970ac480-c45d-11eb-9e41-b974cbbeebe9.png)

Maybe you can try the latest adf, cause we fixed some sip bug, hope you can try again.

BR.

**Comment by szucsi23** [comment]
I'll check tomorrow, and write with an update, thanks!

**Comment by raulrodriguez1** [comment]
It seems I may have a similar problem with BYE. Although slightly different.

I have two ESPs with an Asterisk Server running on Arch. If I call ESP 2 with ESP 1 and hang up the call with ESP 2, then BYE works correctly. However, when I call ESP 2 with ESP 1 and hang up the call with ESP 1, then I get a SIP/2.0 481 Call leg/transaction does not exist and the call continues.

In the attached log, 
[SIP_failed_BYE.txt](https://github.com/espressif/esp-adf/files/6635097/SIP_failed_BYE.txt)

I have seen that when hanging up from the same ESP that made the call causes the TO and FROM fields to switch. Meaning that the TO field contains the extension of the sending ESP and the FROM field contains the extension of the receiving ESP. You can see the difference in the two logs. Below is a successful hangup.
 
[SIP_successful_BYE.txt](https://github.com/espressif/esp-adf/files/6635101/SIP_successful_BYE.txt)

IDF Version: v4.0.2
ADF Version: v2.3-2-g7203f86

**Comment by jason-mao** [comment]
@szucsi23 How is your issue?
