### ISSUE TITLE
AUDIO_HAL_VOL_DEFAULT in VOIP not used (AUD-2912)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#594]
Hi, 
In my audio_hal.h , I have AUDIO_HAL_VOL_DEFAULT 10 
When changing my volume, it starts from 30 and moving up or down, but it should start at the default value.
Is there another place where the volume is defined, I cannot find it ?
thanks in advance
best regards
Ludo

**Comment by ahhfzhang** [comment]
Hi Ludo, 

Yes, you're right, the default volume will be reset by AUDIO_HAL_CTRL_START -> es8311_start
https://github.com/espressif/esp-adf/blob/59e5e02677c7f77f3db8715e4c5ac01d974cccc4/components/audio_hal/driver/es8311/es8311.c#L627

Thanks for your report，we will fix it.
