### ISSUE TITLE
VOIP Example LyraT Mini v1.2 Mic not working (AUD-2917)

### ISSUE THREAD

**Issue by nexstem-siddhant** [espressif/esp-adf#596]
Using the example I am able to register the ESP LyraT Mini v1.2 as a SIP Phone, and am able to make calls as well as accept calls. I am able to hear audio using the earphones jack, but the mic on the LyraT isn't working at all. I tried running other examples to test out the mic, and they worked perfectly.

Can anybody tell me what might be the potential issue here?

**Comment by HengYongChao** [comment]
Hi @nexstem-siddhant 

VOIP example can run on lyrat v4.3 board, except for AEC function cannot be used.

> https://github.com/espressif/esp-adf/tree/master/examples/advanced_examples/voip

Is it correct that the setting of your menuconfig development board? please update log here.

**Comment by nexstem-siddhant** [comment]
I got it to work by just using the example from the master branch for the ADF.

**Comment by fk1000iq** [comment]
> I got it to work by just using the example from the master branch for the ADF.

what is your env? idf version? adf version? I steel get the problem with idf(v5.2.3), adf(v2.7 , currently as master) , board LyraT Mini v1.2.   LinPhone on both PC work well. But Linphone + LyraT Mini, mic not work.
