### ISSUE TITLE
Algorithm Stream AEC (AUD-2977)

### ISSUE THREAD

**Issue by michalber** [espressif/esp-adf#609]
Hi everyone!

Not so much issue but observations about software AEC. I saw a lot of issues about it so I decided to share my results. 

I managed to get AEC work properly but with my program. I spent hours to get available algorithm example to work properly but without any results. Below I add example that work for me. It is based on VOIP example.

Important: It works only with LyraT-mini board due to its construction -> (https://github.com/espressif/esp-adf/issues/570#issuecomment-772334776)

Similarly to algorithm example it plays mp3 file from SD card and saves signal after AEC.

At line 67 you can change reference signal linear amplification factor to value that work best with your setup (I noticed that relative position between speaker and microphones are very important and changing this factor can benefit in AEC performance)
`algo_config.ref_linear_factor = 2;`

Source code:
[algorithm_examples.txt](https://github.com/espressif/esp-adf/files/6397986/algorithm_examples.txt)

**Comment by HengYongChao** [comment]
Hi @michalber 
Thanks for your sharing.
