### ISSUE TITLE
ESP32-LyraTD-MSC with AEC (AUD-2991)

### ISSUE THREAD

**Issue by hoihkj** [espressif/esp-adf#615]
Hi 

If I use ESP32-LyraTD-MSC board, do I have to use algorithm API to enable AEC or jsut use voip example without any configuration with default Hardware AEC?

Thanks in advanced.

**Comment by HengYongChao** [comment]
> Hi
> 
> If I use ESP32-LyraTD-MSC board, do I have to use algorithm API to enable AEC or jsut use voip example without any configuration with default Hardware AEC?
> 
> Thanks in advanced.

Hi @hoihkj 

ESP32-LyraTD-MSC board has a DSP chip, it use Hardware AEC inside.
