### ISSUE TITLE
Is there going to be a Arduino-adf  (AUD-613)

### ISSUE THREAD

**Issue by versamodule** [espressif/esp-adf#62]

**Comment by jason-mao** [comment]
There is no plan to do that.

**Comment by Niek** [comment]
+1, this would be really great

**Comment by jason-mao** [comment]
We're already evaluating it, and the general plan is to release a version in the second half of the year.

Thanks.

**Comment by Romkabouter** [comment]
Is a version still planned for 2019?

**Comment by timotoots** [comment]
+1, this would be great!

**Comment by jason-mao** [comment]
Hi guys, I'm sorry to inform you that the ADF-Arduino will be delayed. We will postpone the first version of arduino  to the first quarter of 2020. I will close this Issue, please refer to #234.
