### ISSUE TITLE
请确认使用LyraT-Mini开发板是否需要指定"i2s_file_cfg.i2s_port = 1;"? (AUD-3017)

### ISSUE THREAD

**Issue by ShaoMingya** [espressif/esp-adf#623]
https://github.com/espressif/esp-adf/blob/3bcca97d39ff5b69d24907f616e91f538ef3eb36/examples/advanced_examples/record_while_play/main/example_record_and_play.c#L157

**Comment by HengYongChao** [comment]
Hi @ShaoMingya 

Lyrat mini v1.2 的 i2s 默认配置的确需要设置为 i2s1。你可以从 [Lyrat mini v1.2 SCH](https://dl.espressif.com/dl/schematics/SCH_ESP32-LYRAT-MINI_V1.2_20190605.pdf) 原理图中获得答案。 

很明显， 默认的  MIC 录入是从 es7243 ADC 这边获取的。 当然，我们也预留了连接 es8311 的位置，但默认是 NC 的。
