### ISSUE TITLE
adf自带idf（3.3.2）menuconfig乱码 (AUD-3076)

### ISSUE THREAD

**Issue by ShaoMingya** [espressif/esp-adf#635]
有没有注意到？

**Comment by HengYongChao** [comment]
Hi @ShaoMingya 

我使用的是 Ubuntu 18.04 lts 版本， 并没有遇到乱码的情形。 并且也没有其他客户报告此类的问题，请问你使用的是什么环境？

如果你的 IDF 是从其他地方 copy 过来的， 那么一般 tools/kconfig/ 下面的一些可执行文件默认权限是不执行的，需要赋权，这个要注意下。
