### ISSUE TITLE
Not able to transfer an audio file from esp32-a1s-audio kit to android mobile phone and esp32 module rebooting itself intermittently (AUD-3096)

### ISSUE THREAD

**Issue by SaiEmbedlover** [espressif/esp-adf#638]
Hi,
I want to transfer an audio file from esp32-a1s-audio kit to an android mobile. For this, i have taken pipeline_a2dp_source_stream example.
I am using the following hardware and software:

ESP32-A1s-Audio kit
Ai-Thinker ESP ADF Frame work and internal IDF within ADF Frame work folder.
Bluetooth Classic
When i run this example using idf command prompt,

1. esp32 module is paired with mobile but no data is transferred and given an error in monitor with btc_a2d_src_connect abort() called presented and BT_BTC: BTA_AV_OPEN_EVT::FAILED status: 2 and module is rebooting....and roams in this loop only.

2. Also , No prompt for PIN displayed on mobile while pairing and mobile itself paired.

3 .From the output monitor , i observed the following:
"btc_av_cb.sm_handle != NULL " failed so that i am suspecting
in the following function call,
static bt_status_t btc_a2d_src_init(void)
{
BTC_TRACE_DEBUG("%s()\n", func);

return btc_av_init(BTA_A2DP_SOURCE_SERVICE_ID);
}

...btc_av_init(); is failed to initialize the handle btc_av_cb.sm_handle.

My question is what are the considerations in mobile side to connect to eps32 and to receive an audio file?
Why system is rebooting if the example was already tested?
Why the above errors are arised?

Please help me! Thank you All!!

**Comment by HengYongChao** [comment]
Hi @SaiEmbedlover 
Not understand your description.
I think if you use CLASSIC BT to transfer files, you shouldn’t use a2dp profile, right?

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
