### ISSUE TITLE
[Korvo_du1906]使用自定义唤醒词 (AUD-3107)

### ISSUE THREAD

**Issue by jayjayhust** [espressif/esp-adf#639]
请问有大神指导korvo_du1906板子的自定义唤醒词如何定制吗？https://ai.baidu.com/tech/speech/wake 这个平台只能导出安卓或者IOS平台的唤醒词bin文件，没有ESP32能用的唤醒词，还望有大神指点，谢谢！

**Comment by HengYongChao** [comment]
@jayjayhust 

你的链接是百度的，如果需要自定义 esp32 唤醒词，[请发邮件给商务](sales@espressif.com)咨询细节。

**Comment by jayjayhust** [comment]
> @jayjayhust
> 
> 你的链接是百度的，如果需要自定义 esp32 唤醒词，[请发邮件给商务](sales@espressif.com)咨询细节。

好的非常感谢
