### ISSUE TITLE
audio Downmix bug (AUD-3111)

### ISSUE THREAD

**Issue by mparker-landt** [espressif/esp-adf#640]
On loading the example Downmix in ADF advanced examples the errors 
"too many arguments to function 'downmix_set_input_rb_timeout'"
appear if you build.

The default example expects only two parameters; audio_element_handle_t self and int ticks_to_wait. How do we pass the index as well?

**Comment by HengYongChao** [comment]
Hi @mparker-landt 

Please update the ADF to latest version.
```
git checkout master
git pull
git submodule update --init --recursive
```

**Comment by mparker-landt** [comment]
Hi @HengYongChao 

My adf is up to date, I keep it and the idf up to date through Github Desktop. I also tried the commands you suggested and it's still the same.

**Comment by mparker-landt** [comment]
Ok, I managed to do it via the commands:
```
cd ~/esp/esp-adf
git pull
git submodule update --init --recursive
```
