### ISSUE TITLE
Cannot compile (AUD-3112)

### ISSUE THREAD

**Issue by orbitcoms** [espressif/esp-adf#641]
I have posted several times without response.
The esp-idf extension and vscode recently updated and my audio projects no longer compile. I get error "Failed to resolve component 'audio_sal'.

Is this because I have updated to latest esp-idf version 4.3?

What is the latest version of esp-idf that this latest version of adf framework will work with?  How do I resolve the error.

PS: I followed the directions for ADF 2.3 and now the code compiles but when I run the project, instead of playing the MP3 file I get this:

CODEC ELEMENT HELPER: The element is 0x3ffd9354. The reserve data 2 is 0x0.

Thanks

**Comment by HengYongChao** [comment]
Hi @orbitcoms 
1. The tested idf version is release/v4.2.
2. please post full log.
