### ISSUE TITLE
用户自定义板级配置 my_board (AUD-3113)

### ISSUE THREAD

**Issue by Kevin-zhongyx** [espressif/esp-adf#642]
Hi 请教一下，我用get-started里的play_mp3，增加了sdkconfig.defaults这个文件，内容是CONFIG_AUDIO_BOARD_CUSTOM=y。 但是编译时会报错找不到board.h。 似乎是编译依赖关系发生了问题，请问这个问题应该怎么解决？
我想用自己的板级配置，发现get-started里的play_mp3是类似的做法，但我参考后发生了和play_mp3这个example一样的问题。找不到我的board.h。

**Comment by HengYongChao** [comment]
Hi @Kevin-zhongyx,
I compile the [play_mp3](https://github.com/espressif/esp-adf/tree/master/examples/get-started/play_mp3) example, it's ok no error, please have a try.
Here is my config [sdkconfig.zip](https://github.com/espressif/esp-adf/files/6702214/sdkconfig.zip)

**Comment by Kevin-zhongyx** [comment]
![image](https://user-images.githubusercontent.com/53296204/123188939-80d9ac80-d4cf-11eb-8454-ff2720d80cf4.png)
我用了你的sdkconfig编译还是一样的错误，我的esp-adf是master最新的版本。commit id :51b6605396b10c4342f0c5389240c7c6643a819f

**Comment by HengYongChao** [comment]
Hi @Kevin-zhongyx  
你使用的 IDF 是 ADF 內建的吗， 还是哪个版本？

**Comment by Kevin-zhongyx** [comment]
是内建的 并没有改动。

**Comment by Kevin-zhongyx** [comment]
你编译时用的ADF是master最新的版本吗？

**Comment by HengYongChao** [comment]
把你的 adf submodule 更新完整
```
git checkout master
git pull
git submodule update --init --recursive
```

**Comment by Kevin-zhongyx** [comment]
![image](https://user-images.githubusercontent.com/53296204/123191716-40c8f880-d4d4-11eb-93e0-d16a00c847a5.png)

**Comment by Kevin-zhongyx** [comment]
![image](https://user-images.githubusercontent.com/53296204/123191804-5dfdc700-d4d4-11eb-80eb-4c01d1dd11f6.png)
有好几个文件报找不到board.h

**Comment by Kevin-zhongyx** [comment]
我检查依赖关系是 编译my_board时是会先编译audio_hal，而编译audio_hal则需要依赖audio_board，而audio_board选了CONFIG_AUDIO_BOARD_CUSTOM是没有编译任何一个文件的， 这样就会造成找不到board.h~~~

**Comment by HengYongChao** [comment]
这个 issue 是修复过的， 我建议你重新克隆一份完整的 adf 再尝试。

**Comment by Kevin-zhongyx** [comment]
我测试不用cmake即不用idf.py build编译  直接用make all可以编译通过。请问一下你编译通过用的cmake 版本是多少呢？
我有两台机器克隆的esp-adf都不能用idf.py build编译play_mp3，我觉得应该跟sdk的完整性关系不大，编译其它项目是正常的。

**Comment by HengYongChao** [comment]
Hi @Kevin-zhongyx 

GNU make 是没有上述问题的。
我使用 cmake 可以复现你的问题，不过 cmake 我建议你使用 IDF release/v4.x 来编译。 
ADF built-in 是 v3.3.2 则使用 GNU make 编译。
