### ISSUE TITLE
Possible Memory Leak in tcp client stream source code (AUD-3126)

### ISSUE THREAD

**Issue by denmuellner** [espressif/esp-adf#644]
https://github.com/espressif/esp-adf/blob/51b6605396b10c4342f0c5389240c7c6643a819f/components/audio_stream/tcp_client_stream.c#L80-L96

Hi all,
in the above referenced section of the local function `_tcp_open()` of the `tcp_client_stream.c` source code, memory is dynamically allocated for a tcp transport object  object by a call to `esp_transport_tcp_init()` in line 93 and a `esp_transport_handle_t` is returned for that object. Then, in line 95 the function will return with `ESP_FAIL` upon an unsuccessful call to `esp_transport_connect()` without freeing the previously allocated memory referenced by the ponter `t` which will subsequently go out of scope. The allocated memory will now remain on the heap without access. I also noticed that in the function `_tcp_close()` referenced below, the tcp socket will get closed by a call to `esp_transport_close()` in line 158 and the flag `is_open` of the transport handle is cleared. However, memory for the transport is not freed. That means that on a subsequent call to `_tcp_open()` after the check of the flag will clear, the call to `esp_transport_tcp_init()` will allocate memory for a new transport instance, whose handle will then be assigned to the dedicated member `t` of the `tcp_stream_t` object handled by the audio element. This will override any reference to previously allocated memory that hasn't been previously freed by a call to `_tcp_destroy()` and therefore can't be accessed anymore.

https://github.com/espressif/esp-adf/blob/51b6605396b10c4342f0c5389240c7c6643a819f/components/audio_stream/tcp_client_stream.c#L148-L167

**Comment by HengYongChao** [comment]
Hi @denmuellner 
Thanks for your report!
