### ISSUE TITLE
Live Audio streaming from ESP32 to Mobile Phone using Bluetooth (AUD-3147)

### ISSUE THREAD

**Issue by shaurya0406** [espressif/esp-adf#649]
I have an ESP32-WROOM module with INMP441 I2S MIC from which I can get the I2S audio stream that I want to live stream on a mobile phone (Android App) via Bluetooth.
So I don't want a recording that gets saved as a .wav file and then send to Android. It has to be live.
Is there any example addressing this?
If not can someone guide me on how to implement that?
Thank you

**Comment by HengYongChao** [comment]
Hi @shaurya0406 

Mic --> INMP4001 --> ESP32 --> Phone,  HF --> AG,  Try HFP ?

**Comment by shaurya0406** [comment]
Thank you for the suggestion.
I will try it out and post my results soon.

**Comment by shaurya0406** [comment]
Are there any docs on how to setup INMP441 MEMS based MIC in ESP-ADF for reading I2S Stream Input?

**Comment by HengYongChao** [comment]
Hi @shaurya0406 

The MIC data currently used by ADF is collected from the codec chip. If you use i2s to connect to MIC directly, you may need to use i2s0's PDM mode.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
