### ISSUE TITLE
When does ADF update its version of IDF?

### ISSUE THREAD

**Issue by hallgrim** [espressif/esp-adf#65]
I think I am hitting [IDF Issue 1736](https://github.com/espressif/esp-idf/issues/1736). It was fixed a while back in [Commit 45f8bcf](https://github.com/espressif/esp-idf/commit/45f8bcf3f8b0062599afd9b538d4c1ddac22de51#diff-316ab610fce940ee568c43ed199cfcbf). 

When does ADF update the version of IDF? Or am I supposed to just pull the latest IDF sub-module?

**Comment by aeklo** [comment]
Following this as well.
Can one update the IDF version manually in the ADF?

**Comment by jason-mao** [comment]
@hallgrim @aeklo  IDF version has been updated to Ver3.1 on commit 35e686dc109e19dc799f62a134be33fa1c9177df
