### ISSUE TITLE
In i2c_bus_read_bytes function why is there a i2c_master_stop byte after writing the chip address and the register? 

### ISSUE THREAD

**Issue by spaceMan00** [espressif/esp-adf#651]
Hello, 

I am on IDF 4.2.1 and ADF master and working with Lyrat board.  
I am trying to interface with IQS316 chip using I2C and I would like to use the driver i2c_bus.c functions of ADF. 
A call to i2c_bus_read_bytes is returning an error because there is an i2c_master_stop on line 138. 
Why is there a stop byte right after writing the chip address and register address? 

All i2c protocol documentation we've read mention the need to send a start byte (restart) after writing the chip address and register address but no documentation mentions sending a stop byte. 

In fact using this variation on the function works on both ES8388 and IQS316. 

```
esp_err_t i2c_bus_read_bytes(i2c_bus_handle_t bus, int addr, uint8_t *reg, int reglen, uint8_t *outdata, int datalen)
{
    I2C_BUS_CHECK(bus != NULL, "Handle error", ESP_FAIL);
    i2c_bus_t *p_bus = (i2c_bus_t *) bus;
    I2C_BUS_CHECK(p_bus->i2c_port < I2C_NUM_MAX, "I2C port error", ESP_FAIL);
    I2C_BUS_CHECK(outdata != NULL, "Not initialized output data buffer pointer", ESP_FAIL);
    esp_err_t ret = ESP_OK;
    mutex_lock(_busLock);
    i2c_cmd_handle_t cmd;
    cmd = i2c_cmd_link_create();
    ret |= i2c_master_start(cmd);
    ret |= i2c_master_write_byte(cmd, addr, I2C_ACK_CHECK_EN);
    ret |= i2c_master_write(cmd, reg, reglen, I2C_ACK_CHECK_EN);
    //ret |= i2c_master_stop(cmd);
    //ret |= i2c_master_cmd_begin(p_bus->i2c_port, cmd, 1000 / portTICK_RATE_MS);
    //i2c_cmd_link_delete(cmd);

    //cmd = i2c_cmd_link_create();
    ret |= i2c_master_start(cmd);
    ret |= i2c_master_write_byte(cmd, addr | 0x01, I2C_ACK_CHECK_EN);

    for (int i = 0; i < datalen - 1; i++) {
        ret |= i2c_master_read_byte(cmd, &outdata[i], 0);
    }
    ret |= i2c_master_read_byte(cmd, &outdata[datalen - 1], 1);

    ret = i2c_master_stop(cmd);
    ret = i2c_master_cmd_begin(p_bus->i2c_port, cmd, 1000 / portTICK_RATE_MS);
    i2c_cmd_link_delete(cmd);

    mutex_unlock(_busLock);
    I2C_BUS_CHECK(ret == 0, "I2C Bus ReadReg Error", ESP_FAIL);
    return ret;
}
```

Can you please let us know if there is any need for this stop byte ?
I really don't like to modify ADF files to make my project work but it seems I have to do that now.

**Comment by HengYongChao** [comment]
Hi @spaceMan00 

To be honest, the i2s bus here is used for initialize several codec(es8388, es8311, es7210 etc.), which may be different from your chip timing.
