### ISSUE TITLE
Example gone missing... espressif/esp-adf/examples/get-started/play_mp3 (AUD-3153)

### ISSUE THREAD

**Issue by RobinE** [espressif/esp-adf#652]
The example espressif/esp-adf/examples/get-started/play_mp3 used in:
https://docs.espressif.com/projects/esp-adf/en/latest/get-started/index.html#get-started-step-by-step
is missing.

**Comment by HengYongChao** [comment]
Hi @RobinE 
The following three examples(`play_mp3`, `play_mp3_control`, `play_mp3_rates`) have been refactor into one example  `play_mp3_control`.

**Comment by RobinE** [comment]
The tutorial documentation needs to be updated to match.  As at (and perhaps elsewhere):
docs.espressif.com/projects/esp-adf/en/latest/get-started/index.html#get-started-step-by-step
