### ISSUE TITLE
偶现I2S recorder噪音。 (AUD-3160)

### ISSUE THREAD

**Issue by llx4186041** [espressif/esp-adf#653]
软件版本：ADF: v2.2-78-g7cf86c9   IDF:   v4.1.1
     硬件版本： ESP32_LyraT V4.3

    问题: 偶现开启recorder后，采集到的声音带很大的底噪，但还是勉强可以听清内容，很像是i2s 采集的数据未对齐，发生了移位。重启系统或者重启recorder恢复正常。出现问题时playback是正常的。
            请问如何避免这个问题，还有出现问题后如何检测出来而不是靠耳朵听？

**Comment by HengYongChao** [comment]
@llx4186041  请问是哪个例子出现的这个问题，如果使用了 sdcard ，可以换一张 sdcard 再尝试。

**Comment by llx4186041** [comment]
没有用到sdcard.
自己写的程序，两个板子通过wifi连接，建立recorder,playback管道。采集到的数据编码后通过tcp发送给对方播放。有时候开机会出现这个问题，确认是录音管道得到的数据有问题。

**Comment by llx4186041** [comment]
问题出现在playbck重新启动时偶尔出现，出现后再关闭playback 重启下就回复正常了。recorder没有操作。

**Comment by HengYongChao** [comment]
如果是这样，我怀疑你的数据传输有问题， 你可构造一致的数据进行传输测试，看看从 A 到 B 数据有无异常
