### ISSUE TITLE
Bluetooth speaker authorization problem (AUD-3165)

### ISSUE THREAD

**Issue by hard-cat** [espressif/esp-adf#654]
hi
I ran into a problem when I set the CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL parameter less than 128 bytes (64 and below), then when the esp_a2d_source_connect function is called, the application hangs and restarts. If it is equal to 128 or more, there is no problem.

The problem arises only in the process of authorizing a new speaker. If you connect to a previously authorized one, then there is no error when CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL = 8

**Comment by jason-mao** [comment]
@hard-cat We do not recommend set CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL too low, the behavior is not predictable.
