### ISSUE TITLE
Lyrat mini VOIP call with register set instead of call key ? (AUD-3207)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#664]
Hi,
I am putting the lyrat mini in deep_sleep, and wake up with a keypress. This workshop fine. Only , the VOIP call should start without additional keypress. Is it possible to simulatie the call keypress by setting certain registers ?
Regards
Ludo

**Comment by HengYongChao** [comment]
Hi @Patsjemoe 

ESP32 has some deepsleep wakeup spurces: timer, touch pad, External wakeup (ext0), External wakeup (ext1), ULP coprocessor wakeup, GPIO wakeup (light sleep only).

For your application, if you want to exclude the use of buttons(GPIOs), it seems you can use ULP processor  to wake up main CPU.

**Comment by Patsjemoe** [comment]
Hi,
Wake up from deep sleep works fine with external wake up by pushing a
button, but that is not the question.
My question is : I wake up by pressing a key, and the program starts up
again. But then, I want the VOIP call to start automatically, instead of
pushing a second button.

I used the sip invite
esp_sip_uac_invite(sip, "101)
but this seems to hang, not make the call.

Is there something to be initiated before the invite?
Regards
Ludo

Op vr 6 aug. 2021 05:24 schreef HengYongChao ***@***.***>:
