### ISSUE TITLE
Can‘t play music from internet, because authorization (AUD-3209)

### ISSUE THREAD

**Issue by new-soul** [espressif/esp-adf#665]
设备已经接入DuerOS，可以识别天气什么的，但是就是播放音乐会提示“该设备未授权接入音乐内容服务，请联系小度音乐申请内容”，请问这个要上哪儿去配置呢，一直没有找到入口。

**Comment by HengYongChao** [comment]
Hi @new-soul,

你说的这个现象是百度是 profile 的授权策略， 音乐服务需要另外授权， 音乐播放需求请联系百度。

**Comment by new-soul** [comment]
好的，我看之前的版本是自带了这个功能。那我再去找一下百度看看。感谢！

**Comment by HengYongChao** [comment]
Hi @new-soul, 如果问题已解决，请主动关闭这个 issue， 谢谢。

**Comment by new-soul** [comment]
最好能加个链接说明一下申请地址，感谢。

**Comment by HengYongChao** [comment]
> 最好能加个链接说明一下申请地址，感谢。

在 README.MD 文档中有这个链接了，[ 度家 AIOT 快速入门 ](https://cloud.baidu.com/doc/SHC/s/wk7bl9g8i)
