### ISSUE TITLE
VOIP call button issue (AUD-3230)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#668]
Hi, 
When pushing the play button in VOIP on lyrat mini, I usually get my call.
Sometimes, it seems to detect another button : 
W (7695) ADC_BTN: Old ID:3, New ID:5
W (10135) ADC_BTN: Old ID:5, New ID:3
I (10375) VOIP_EXAMPLE: [ * ] [Play] input key event
W (10375) SIP: CHANGE STATE FROM 2, TO 64, :func: esp_sip_uac_invite:2065
Only after the second (sometimes more) push, it makes the call.
Is this a matter of voltage level on the button  that is detected in the ADC ?
regards
Ludo

**Comment by eslamsnono** [comment]
could you please tell me which esp-idf version you used to compile? i get error with ESP-IDF v4.4.

**Comment by Patsjemoe** [comment]
Hi,
Use IDF v 3.2.2

Op do 19 aug. 2021 13:52 schreef eslamsnono ***@***.***>:

**Comment by Patsjemoe** [comment]
Hi,
Any feedback?
Regards
Ludo

**Comment by HengYongChao** [comment]
@ahhfzhang Check this issue please.

**Comment by jason-mao** [comment]
@Patsjemoe @eslamsnono  ADF  fix a adc_button bug at https://github.com/espressif/esp-adf/commit/df0be7a62181521f33d09dd18df49c91b0f8ab45, please help check is it solved your problem.
