### ISSUE TITLE
Compilation Error for  esp-adf/examples/get-started/play_mp3_control/ (AUD-3235)

### ISSUE THREAD

**Issue by Vxs14** [espressif/esp-adf#669]
Hy, 

trying to compile this example, without any code modification , just setting Custom audio Board in Audio HAL , there is a compilation error , the report : 

[1078/1084] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/play_mp3_control_example.c.obj
../main/play_mp3_control_example.c: In function 'app_main':
../main/play_mp3_control_example.c:115:5: warning: 'I2S_COMM_FORMAT_I2S' is deprecated [-Wdeprecated-declarations]
     i2s_stream_cfg_t i2s_cfg = I2S_STREAM_CFG_DEFAULT();
     ^~~~~~~~~~~~~~~~
In file included from C:/Users/thier/esp/esp-idf/components/driver/include/driver/i2s.h:16,
                 from C:/Users/thier/esp/esp-adf/components/audio_stream/include/i2s_stream.h:28,
                 from ../main/play_mp3_control_example.c:22:
C:/Users/thier/esp/esp-idf/components/hal/include/hal/i2s_types.h:95:5: note: declared here
     I2S_COMM_FORMAT_I2S       __attribute__((deprecated)) = 0x01, /*!< I2S communication format I2S, correspond to `I2S_COMM_FORMAT_STAND_I2S`*/
     ^~~~~~~~~~~~~~~~~~~
[1082/1084] Linking CXX executable play_mp3_control.elf
FAILED: play_mp3_control.elf 
cmd.exe /C "cd . && C:\Users\thier\.espressif\tools\xtensa-esp32-elf\esp-2021r1-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe -mlongcalls -Wno-frame-address  @CMakeFiles\play_mp3_control.elf.rsp -o play_mp3_control.elf  && cd ."
c:/users/thier/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(play_mp3_control_example.c.obj):(.literal.app_main+0xa8): undefined reference to `get_input_play_id'
c:/users/thier/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(play_mp3_control_example.c.obj):(.literal.app_main+0xac): undefined reference to `get_input_set_id'
c:/users/thier/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(play_mp3_control_example.c.obj):(.literal.app_main+0xb0): undefined reference to `get_input_mode_id'
c:/users/thier/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(play_mp3_control_example.c.obj): in function `app_main':
C:\Users\thier\Documents\ESP32\play_mp3_control\build/../main/play_mp3_control_example.c:150: undefined reference to `get_input_play_id'
c:/users/thier/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\thier\Documents\ESP32\play_mp3_control\build/../main/play_mp3_control_example.c:173: undefined reference to `get_input_set_id'
c:/users/thier/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\thier\Documents\ESP32\play_mp3_control\build/../main/play_mp3_control_example.c:186: undefined reference to `get_input_mode_id'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake --build ." terminated with exit code: 1.

I am really puzzled .... ;-)
Could you help me ! please.

**Comment by HengYongChao** [comment]
Hi @Vxs14 

Thank you for the report, will fix soon.
