### ISSUE TITLE
Dureo用例 怎么获取参考信号？

### ISSUE THREAD

**Issue by xiaoseyihe** [espressif/esp-adf#67]
Dureo用例 怎么获取参考信号？目前只能获取MIC 数据

**Comment by xiaoseyihe** [comment]
喇叭播放的信号，用于回声消除

**Comment by jason-mao** [comment]
@xiaoseyihe 参考信号，建议通过 PA后级通过ADC来回采。当然，通过ESP32内部也可以通过multiple output 接口做数字回采。
