### ISSUE TITLE
Linker Error on ESP-ADF cMake Build (AUD-3246)

### ISSUE THREAD

**Issue by denmuellner** [espressif/esp-adf#672]
Hi,

I'm trying to get ESP-ADF running using the platformIO extension for VS Code, which uses cMake as build system. The build process fails on linking some library files of `esp-adf-libs` and `esp_sr`. Some of the `-Wl,--start-group`/`-Wl,--end-group` lists seem to be out of order. I set up a [repository](https://github.com/denmuellner/ESP-ADF_Components_Test) with a minimal platformio project to reproduce the error and also put the console log output of a verbose build in the attachment. I don't know if this issue also exists with other IDEs or toolchains that use cMake, or if this is something specific to pio. Imo it looks like a general problem with the cMakeList.txt files in the mentioned components. Any hints and tips would be appreciated.

Thanks

[BuldLog.txt](https://github.com/espressif/esp-adf/files/7056184/BuldLog.txt)

**Comment by jason-mao** [comment]
@denmuellner I have not test with platformIO. I don't know if that's what caused it. The `-Wl,--start-group/-Wl,--end-group` can be eliminate the cycle dependency.

**Comment by jason-mao** [comment]
@denmuellner How about your issue?

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
