### ISSUE TITLE
Recording at 44,1 kHz/ 48 kHz (AUD-3248)

### ISSUE THREAD

**Issue by josete89** [espressif/esp-adf#674]
Hi,

Thanks a lot for your great work with the esp-adf library. I was wondering if it's possible to record sound with studio quality something between 44,1 or 48 kHz, since all examples is somewhat recoding some audio and encoding in wav/opus format. I have the lyra-t board and the use case can be using it as a microphone in a call or twitch stream for example. 

Thanks a lot!

**Comment by HengYongChao** [comment]
Hi @josete89 

Are you trying to use a special sampling rate to record audio files? In principle, it is possible, because there is no rule to limit it.

**Comment by josete89** [comment]
Hi @HengYongChao 

It’s more related to the Bluetooth audio examples, they are recording at 16 kHz. Modifying those examples always create a running of memory in the Bluetooth stack. Not sure what is the best way to connect the Lyra-t as microphone with high quality to the computer.

Thanks a lot

**Comment by josete89** [comment]
@HengYongChao thanks a lot for your response. I will give it a try, I'm wondering if it's possible use it as usb microphone since esp-idf can use usb/uart as communication protocol with the laptop.

**Comment by HengYongChao** [comment]
Hi @josete89 

Is the data flow of your project like this?
```
MIC ----> codec ----> ESP32/S2/S3  --> (usb/uart) -->  laptop ?   
```
This seems feasible.

**Comment by mingchau** [comment]
@josete89 Hi Jose, sorry to bother you. Would you please share more of your idea of using it as a microphone? I have a similar purpose, I want to use it as a microphone in Zoom meetings(via Bluetooth or USB).

**Comment by AliRezaBorjigithub** [comment]
I am working on a project in esp-adf in which I need to record as opus. the main problem I am facing is that the frequency of my voice recorded is a bit higher.
also I am using built in ADC of an esp32 to capture the sound data.
-----------------------------------------------------------------------
here is my i2s config:
#define I2S_STREAM_TASK_STACK (3072 + 512)
#define I2S_STREAM_BUF_SIZE (3600)
#define I2S_STREAM_TASK_PRIO (0)
#define I2S_STREAM_TASK_CORE (0)
#define I2S_STREAM_RINGBUFFER_SIZE (8 * 1024)
  {                                                                            \
    .type = AUDIO_STREAM_WRITER,                                               \
    .i2s_config = {.mode =                                                     \
                       (i2s_mode_t)(I2S_MODE_ADC_BUILT_IN | I2S_MODE_MASTER |  \
                                    I2S_MODE_TX | I2S_MODE_RX),                \
                   .sample_rate = 44100,                                       \
                   .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,               \
                   .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,                \
                   .communication_format = I2S_COMM_FORMAT_I2S_MSB,            \
                   .intr_alloc_flags =                                         \
                       ESP_INTR_FLAG_LEVEL2 | ESP_INTR_FLAG_IRAM,              \
                   .dma_buf_count = 10,                                        \
                   .dma_buf_len = 300,                                         \
                   .use_apll = true,                                           \
                   .tx_desc_auto_clear = true,                                 \
                   .fixed_mclk = 0},                                           \
    .i2s_port = I2S_NUM_0, .use_alc = false, .volume = 0,                      \
    .out_rb_size = I2S_STREAM_RINGBUFFER_SIZE,                                 \
    .task_stack = I2S_STREAM_TASK_STACK, .task_core = I2S_STREAM_TASK_CORE,    \
    .task_prio = I2S_STREAM_TASK_PRIO, .stack_in_ext = false,                  \
    .multi_out_num = 0, .uninstall_drv = true, .need_expand = false,           \
    .expand_src_bits = I2S_BITS_PER_SAMPLE_16BIT,                              \
    .buffer_len = I2S_STREAM_BUF_SIZE,                                         \
  }
-----------------------------------------------------------------------
and here is my opus config:
  opus_encoder_cfg_t opus_cfg = DEFAULT_OPUS_ENCODER_CONFIG();
  opus_cfg.sample_rate = SAMPLE_RATE;
  opus_cfg.channel = CHANNEL;
  opus_cfg.bitrate = BIT_RATE;
  opus_cfg.task_prio = 0;
  opus_cfg.task_stack = (40 * 1024);
  opus_cfg.complexity = COMPLEXITY;
#if defined(CONFIG_CHOICE_OPUS_ENCODER)
#define SAMPLE_RATE 44100
#define CHANNEL I2S_CHANNEL_MONO
#define BIT_RATE 16000
#define BIT_PER_SAMPLE                                                         \
  I2S_BITS_PER_SAMPLE_16BIT // other than this the voice get currupted and part
                            // part /*!< data bit-width: 32 */
#define COMPLEXITY 0
-----------------------------------------------------------------------
what is the problem?
