### ISSUE TITLE
Example compile error (AUD-3251)

### ISSUE THREAD

**Issue by DongStop** [espressif/esp-adf#675]
It is very unfortunately of me to compile the example 'play_mp3_control'.
It reminds me that unknow type names ’esp_codec_type_t‘ due to the loss of  audio_type_def.h file
Could you tell me where I can find this file?
The whole error information as below

```
In file included from /esp-adf/components/esp_peripherals/include/esp_peripherals.h:30,
                 from /esp-adf/components/audio_board/lyrat_v4_3/board.h:31,
                 from /esp-adf/components/audio_board/lyrat_v4_3/board.c:26:
/esp-adf/components/esp_peripherals/audio_pipeline/include/audio_common.h:33:10:fatal error:audio_type_def.h:No such file or
directory
#include "audio_type_def.h"
```

**Comment by HengYongChao** [comment]
Hi @DongStop  

Please update the ADF and Submodules, then try again.

1. cd ADF folder, and command `git pull`
2. then  command 'git submodule update --init --recursive'
3. clean the build and compile the example again.
