### ISSUE TITLE
Upgrade IDF to v4.3 (AUD-3264)

### ISSUE THREAD

**Issue by tacrazymage** [espressif/esp-adf#677]
is there any hope that we setup adf to work with new idf v4.3 any soon?

**Comment by HengYongChao** [comment]
Hi @tacrazymage , will update soon.

**Comment by michalber** [comment]
Hi @tacrazymage ! I managed to get this working with one problem with I2S. I posted issue about this and also found solution. Check it out: https://github.com/espressif/esp-adf/issues/663. I am working with ADF v2.3 and IDF v4.3 for over a month.

**Comment by jason-mao** [comment]
IDF v4.3 has supported on 501bb406f1e69e3d3d47b2b3420148578df6b2eb
