### ISSUE TITLE
Chopped audio with example pipeline_a2dp_source_stream (AUD-3274)

### ISSUE THREAD

**Issue by mihovilkolaric** [espressif/esp-adf#678]
Hi,

I'm working on a project based on pipeline_a2dp_source_stream and thus trying to get the example running on a LyraT 4.3 and a Bose QC 35 headset.
The first time after flashing, and connecting the headset in pairing mode the playback works quite OK.

However, after resetting the board, the headphones have troubles in reconnecting, Once they reconnected, the audio is very chopped, and actually unuseable. (Recording:  [after_reset.zip](https://github.com/espressif/esp-adf/files/7147557/after_reset.zip) )
I am using latest ADF from github, and IDF 4.1.2 (which is the latest supported by ADF?).

Attached you can find the logs from first, and a later run of the example:
[first_run.log](https://github.com/espressif/esp-adf/files/7147566/first_run.log)
[after_reset.log](https://github.com/espressif/esp-adf/files/7147567/after_reset.log)

**Comment by jason-mao** [comment]
ADF default IDF version is  v3.3 branch, we recommend use the https://github.com/espressif/esp-idf/tree/audio/stack_on_psram_v3.3 to run A2DP example. Unless ADF change the default version to others.
