### ISSUE TITLE
dueros中怎么录取mic采集到的原始数据并保存到SD卡中，

### ISSUE THREAD

**Issue by xiaoseyihe** [espressif/esp-adf#68]
dueros中怎么录取mic采集到的原始数据并保存到SD卡中？ int ret = rec_engine_data_read(voiceData, ONE_FRAM_SIZE, 110 / portTICK_PERIOD_MS); 录取的voiceData是1录16k的原始数据，这个是处理过的吗？怎么拿的mic的原始数据呢？

**Comment by jason-mao** [comment]
Closed, same with #69.
