### ISSUE TITLE
mk_audio_tone.py如何使用 (AUD-3286)

### ISSUE THREAD

**Issue by ShaoMingya** [espressif/esp-adf#682]
esp-adf\tools\audio_tone\mk_audio_tone.py如何使用？mp3文件在f:\tone_mp3文件夹中，请问如何生成bin文件？我试了半天没有看到任何文件生成。

**Comment by HengYongChao** [comment]
Hi @ShaoMingya 

```
python $ADF_PATH/tools/audio_tone/mk_audio_tone.py -r tone/ -f components/audio_flash_tone -v v1.1.1
```
[Examples/korvo_du1906/README.md](https://github.com/espressif/esp-adf/blob/master/examples/korvo_du1906/README.md) 有说明这个用法，或者使用 ` Python mk_audio_tone.py --help ` 获得帮助，请参考。

**Comment by ShaoMingya** [comment]
谢谢，找到原因了，要用python2才行，python3没任何输出。
