### ISSUE TITLE
Dual I2S outputs (AUD-3304)

### ISSUE THREAD

**Issue by mparker-landt** [espressif/esp-adf#685]
Hi,

Is it possible to get both I2S running as outputs. 

I want both I2S0 and I2S1 playing different tracks at different times but when I set up the I2S with different pins they play equivalent pins are always exactly the same output, even if I only run 1 I2S number.

Any help would be much appreciated.
Thanks

**Comment by jason-mao** [comment]
@mparker-landt What  is exactly means for same output, same sample rate? How is the I2S0 I2S1 configuration?
