### ISSUE TITLE
Couldn't "make flash" in esp-adf (with esp-idf-v3.3.5) (AUD-3338)

### ISSUE THREAD

**Issue by mianqi2016** [espressif/esp-adf#688]
I went to "make menuconfig" in "esp-adf", I used esp-idf-v3.3.5, and could run "make flash", while, it was said:
"cc1: some warnings being treated as errors"

    https://ibb.co/NrPhBHk
    https://ibb.co/rZHRB1S
    https://ibb.co/j6G8tN6

I tried the 2 examples in "get-started" - "play_mp3" and "play_mp3_control", both the same, Are these errors of source code or of compiler?

**Comment by HengYongChao** [comment]
Hi @mianqi2016 

I have not encountered such a compilation error. This error may be related to the compilation environment. 

I suggest you reconfigure the [GNU GCC compilation environment please](https://docs.espressif.com/projects/esp-idf/en/v3.3.5/get-started/index.html#setup-toolchain).
