### ISSUE TITLE
Li Ion battery charger circuit LyraT mini (AUD-3339)

### ISSUE THREAD

**Issue by Patsjemoe** [espressif/esp-adf#689]
Hi,
Is it correct that the battery charger circuit on the LyraT mini includes load sharing (AO3401/SS24), but does not include battery protection, like DW01A/FS8205 ?
Any reason why this is not added to the board ?
If this is correct, it may be good to mention this in the documentation, as it requires batteries with build in protection. 
regards
Ludo

**Comment by Espressif-Kelly** [comment]
Hi,

The Li Ion batteries that we usually use have already been equipped with built-in protective circuit. When the battery that you use doesn't have any built-in protection circuit, external battery protection circuit like DW01A should be better introduced.

Thanks for your reminding and we will add this note in our documentaion later.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
