### ISSUE TITLE
opus encoder memory leak (AUD-3357)

### ISSUE THREAD

**Issue by vetaldudnik** [espressif/esp-adf#693]
I use an ESP-WROOM-32E board (no built-in PSRAM) that takes a few seconds of audio from an I2S microphone, encodes it with an OPUS codec, sends the compressed stream via TCP, and then takes the next few seconds of audio and so on.

Everything works fine, but after a while the board reboots because it can't allocate the next piece of heap.
Debugging the code I found out that opus codec leaks 912 bytes of heap after each  opus_encoder_open() -> opus_encoder_close().

All I managed to find out is that those 912 bytes are allocated with codec_memory_calloc() function and then they are never freed.

Since I don't have source code, I've done this dirty hack in audio_mem.c in audio_calloc() function for now:

```
if((intptr_t)__builtin_return_address(0) == ((intptr_t)codec_memory_calloc + 0x0C) && size == 912)
{
    static uint8_t opus_buffer[912];
    data = opus_buffer;
#ifdef ENABLE_AUDIO_MEM_TRACE
    ESP_LOGW("AUIDO_MEM", "Caught the opus leaking buffer!");
#endif
}
else
{
    data = calloc(nmemb, size);
}
```

Is it possible to fix this?

**Comment by jason-mao** [comment]
@vetaldudnik Thank you for your detail debug and report. We have fixed this bug on master 2177f2450bf820aaf10b1804af87571c970f23ba, please check again, if you are still interested.
