### ISSUE TITLE
ESP32-C3 support? (AUD-3360)

### ISSUE THREAD

**Issue by fgervais** [espressif/esp-adf#696]
Is support for the C3 planned?

**Comment by fgervais** [comment]
Do you know if it will support all features even if it's less powerful?

**Comment by jason-mao** [comment]
Most of them, according to the limited RAM, we will support some lightweight codecs, such as mp3 and wav.

**Comment by jason-mao** [comment]
@fgervais C3 has been support on 7a729dd6acbbafdbab256799ecc95d4cf8baaf11.
