### ISSUE TITLE
ESP32-LaryT MINI v1.2 VOIP Issues！ (AUD-3372)

### ISSUE THREAD

**Issue by zx568073531** [espressif/esp-adf#698]
Please forgive my poor English .

Hi , Everyone. 

I try to exam voip on my ESP32-LaryT MINI v1.2 board.
I set up the Sip server and it running find.

then I build the voip example , download in the board . 
It can connceted the Sip Server and i call the board . it ringing ...
then i press the "play key", the Communication has been established .

Computer side cannot hear voice , but board can hear voice send from Computer side .

I try to save file from i2s stream , algo stream etc. 
then i found the NOT VOICE FROM

aec_process(algo->aec_handle, record->aec_buff, reference->aec_buff, algo->aec_buff);

algo->aec_buff not data in ..  it silence 。

But i found press RST key，rst the system，aec_process it work！！！

哈喽，各位，最近调试ESP32-LyraT Mini 1.2的板子在voip例程下不能正常工作的问题。
实验详情：
1.用一块ESP32-LyraT Mini 1.2，使用ESP-ADF自带的ESP-IDF编译，并且下载了“铃声.bin”， Sip服务器搭建好并且2台电脑之间测试完成。
2.在ESP32下载软件之后，可以正常连接WiFi，连接服务器，并且提示连接成功。
3.ESP32在服务器上可以看到已经登陆，注册成功。
4.在电脑端使用Sip客户端呼叫ESP32，能够正常振铃(有振铃提示音)。

5.按键Play按下，能够正常进入语音通信，但是只有喇叭有声音，电脑客户端没有声音。

6.按下RST按键，重新连接服务器之后，能够链接服务器，这时在进行呼叫，双方都正常，有声音。

经过，排查，通过文件存储的形式，最后定位到，注意：在algorithm_stream.c中的 AEC 初始化虽然成功，但是在执行 aec_process(algo->aec_handle, record->aec_buff, reference->aec_buff, algo->aec_buff);无输出到algo->aec_buff。

通过文件将record->aec_buff，reference->aec_buff, algo->aec_buff 存储。

只有 record->aec_buff，reference->aec_buff 均有输出音频。
algo->aec_buf 是静音的。

最后通过手动复位之后，以上错误没有，尝试使用esp_restart(); 软件复位，也不可以。因此必须手动复位一次。

idf branch
* (HEAD detached at 722043f734)
* 
esp-adf>git branch -a
* master

**Comment by HengYongChao** [comment]
请按照上述更新 AEC 库，并且删除 build 目录后，再次编译测试，如有问题请再次反馈到这里，谢谢！
