### ISSUE TITLE
ESP32 ADF ASR无法唤醒 (AUD-3376)

### ISSUE THREAD

**Issue by bobo-ba** [espressif/esp-adf#701]
PS D:\ESP32\ESP-ADF\esp-adf\examples\speech_recognition\asr> idf.py -p  COM4 monitor
Executing action: monitor
Running idf_monitor in directory d:\esp32\esp-adf\esp-adf\examples\speech_recognition\asr
Executing "D:\ESP32\ESP-IDF-TOOL\.espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:\ESP32\ESP-IDF\tools/idf_monitor.py -p COM4 -b 115200 --toolchain-prefix xtensa-esp32-elf- d:\esp32\esp-adf\esp-adf\examples\speech_recognition\asr\build\speech_recognition_example.elf -m 'D:\ESP32\ESP-IDF-TOOL\.espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe' 'D:\ESP32\ESP-IDF\tools\idf.py' '-p' 'COM4'"...
[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM4 instead...[0m
--- idf_monitor on \\.\COM4 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:7288
load:0x40078000,len:15000
load:0x40080400,len:4416
0x40080400: _init at ??:?

entry 0x400806a0
I (27) boot: ESP-IDF v4.3.1 2nd stage bootloader
I (27) boot: compile time 16:30:43
I (27) boot: chip revision: 1
I (30) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (37) qio_mode: Enabling default flash chip QIO
I (42) boot.esp32: SPI Speed      : 80MHz
I (47) boot.esp32: SPI Mode       : QIO
I (51) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (61) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (72) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  2 factory          factory app      00 00 00010000 00260000
I (95) boot:  3 flash_tone       Unknown data     01 ff 00270000 00004000
I (102) boot: End of partition table
I (106) boot_comm: chip revision: 1, min. application chip revision: 0
I (114) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=202834h (2107444) map
I (702) esp_image: segment 1: paddr=0021285c vaddr=3ffb0000 size=02bc0h ( 11200) load
I (706) esp_image: segment 2: paddr=00215424 vaddr=40080000 size=0abf4h ( 44020) load
I (723) esp_image: segment 3: paddr=00220020 vaddr=400d0020 size=48c64h (298084) map
I (805) esp_image: segment 4: paddr=00268c8c vaddr=4008abf4 size=049a4h ( 18852) load
I (811) esp_image: segment 5: paddr=0026d638 vaddr=50000000 size=00010h (    16) load
I (819) boot: Loaded app from partition at offset 0x10000
I (819) boot: Disabling RNG early entropy source...
I (833) cpu_start: Pro cpu up.
I (833) cpu_start: Starting app cpu, entry point is 0x400813fc
0x400813fc: call_start_cpu1 at D:/ESP32/ESP-IDF/components/esp_system/port/cpu_start.c:141

I (0) cpu_start: App cpu up.
I (848) cpu_start: Pro cpu start user code
I (848) cpu_start: cpu freq: 240000000
I (848) cpu_start: Application information:
I (852) cpu_start: Project name:     speech_recognition_example
I (859) cpu_start: App version:      v2.3-61-g6fa0292-dirty
I (865) cpu_start: Compile time:     Oct 15 2021 17:13:35
I (871) cpu_start: ELF file SHA256:  971b3a999d2b6f95...
I (877) cpu_start: ESP-IDF:          v4.3.1
I (882) heap_init: Initializing. RAM available for dynamic allocation:
I (889) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (895) heap_init: At 3FFB3718 len 0002C8E8 (178 KiB): DRAM
I (902) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (908) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (914) heap_init: At 4008F598 len 00010A68 (66 KiB): IRAM
I (921) spi_flash: detected chip: gd
I (925) spi_flash: flash io: qio
W (929) spi_flash: Detected size(8192k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (942) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (958) example_asr_keywords: Initialize SR wn handle
Quantized wakeNet5: wakeNet5X3_v5_hilexin_5_0.97_0.90, mode:0 (Oct 14 2020 16:26:17)
I (971) example_asr_keywords: keywords: hilexin (index = 1)
Fail: index is out of range, the min index is 1, the max index is 1I (977) example_asr_keywords: keywords_num = 1, threshold = 0.000000, sample_rate = 16000, chunksize = 480, sizeof_uint16 = 2
WARNING: Sample length must less than 5000ms in the SINGLE_RECOGNITION mode
SINGLE_RECOGNITION: 2_0 MN1_4; core: 0; (May 15 2020 14:50:27)
SHIFT: 8, 12, 17, 17, 19, 17, 6, 16, 15, 14,
I (1020) example_asr_keywords: keywords_num = 166 , sample_rate = 16000, chunksize = 480, sizeof_uint16 = 2
I (1022) example_asr_keywords: [ 1 ] Start codec chip
I (1528) example_asr_keywords: [ 2.0 ] Create audio pipeline for recording
I (1528) example_asr_keywords: [ 2.1 ] Create i2s stream to read audio data from codec chip
I (1551) example_asr_keywords: [ 2.3 ] Create raw to receive data
I (1551) example_asr_keywords: [ 3 ] Register all elements to audio pipeline
I (1554) example_asr_keywords: [ 4 ] Link elements together [codec_chip]-->i2s_stream-->raw-->[SR]
W (1624) I2C_BUS: i2c_bus_create:57: I2C bus has been already created, [port:0]

----------------------------- ESP Audio Platform -----------------------------
|                                                                            |
|                 ESP_AUDIO-v1.7.0-20-ga07d753-14f5826-09be8fe               |
|                     Compile date: Aug 23 2021-03:25:55                     |
------------------------------------------------------------------------------
I (1679) example_asr_keywords: esp_audio instance is:0x3ffd2cdc

I (1680) example_asr_keywords: [ 5 ] Start audio_pipeline

**Fail: index is out of range, the min index is 1, the max index is 1I (977) example_asr_keywords: keywords_num = 1, threshold = 0.000000, sample_rate = 16000, chunksize = 480, sizeof_uint16 = 2
WARNING: Sample length must less than 5000ms in the SINGLE_RECOGNITION mode**

看见有朋友也出现了同样的问题，可是没有给出解决方法。经过麦没问题，配置中开发板选择没问题没问题，不知道应该怎么解决这个问题了

**Comment by jason-mao** [comment]
建议最新的使用 wwe  example 进行测试。
