### ISSUE TITLE
Compile errors for a2dp_sink with esp32-c3 (AUD-3378)

### ISSUE THREAD

**Issue by pschatzmann** [espressif/esp-adf#702]
The documentation for the ESP32-c3 is indicating that A2DP should be working:
see https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/bluetooth/classic_bt.html

Compiling your a2dp_sink example gives the following compile errors

 ```
/Users/pschatzmann/esp/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'hci_layer_init_env':
/Users/pschatzmann/esp/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:184:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_init'; did you mean 'btsnd_hcic_ble_set_phy'? [-Werror=implicit-function-declaration]
    btsnd_hcic_ble_sync_sem_init();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    btsnd_hcic_ble_set_phy
/Users/pschatzmann/esp/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'hci_layer_deinit_env':
/Users/pschatzmann/esp/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:207:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_deinit'; did you mean 'btsnd_hcic_ble_clear_adv_set'? [-Werror=implicit-function-declaration]
    btsnd_hcic_ble_sync_sem_deinit();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    btsnd_hcic_ble_clear_adv_set
/Users/pschatzmann/esp/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'filter_incoming_event':
/Users/pschatzmann/esp/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:443:36: error: implicit declaration of function 'btsnd_hcic_ble_get_sync_info'; did you mean 'btsnd_hcic_ble_ext_scan_enable'? [-Werror=implicit-function-declaration]
            BlE_SYNC *sync_info =  btsnd_hcic_ble_get_sync_info();
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   btsnd_hcic_ble_ext_scan_enable
/Users/pschatzmann/esp/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:443:36: warning: initialization of 'BlE_SYNC *' {aka 'struct <anonymous> *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
cc1: some warnings being treated as errors
 ```

**Comment by pschatzmann** [comment]
Can we use this issue to have the documentation corrected ?

**Comment by KonssnoK** [comment]
same is happening on ESP32-S3
`C:/src/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'hci_layer_init_env':
C:/src/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:184:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_init'; did you mean 'btsnd_hcic_ble_set_phy'? [-Werror=implicit-function-declaration]
     btsnd_hcic_ble_sync_sem_init();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     btsnd_hcic_ble_set_phy
C:/src/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'hci_layer_deinit_env':
C:/src/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:207:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_deinit'; did you mean 'btsnd_hcic_ble_clear_adv_set'? [-Werror=implicit-function-declaration]
     btsnd_hcic_ble_sync_sem_deinit();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     btsnd_hcic_ble_clear_adv_set
C:/src/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'filter_incoming_event':
C:/src/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:443:36: error: implicit declaration of function 'btsnd_hcic_ble_get_sync_info'; did you mean 'btsnd_hcic_ble_ext_scan_enable'? [-Werror=implicit-function-declaration]
             BlE_SYNC *sync_info =  btsnd_hcic_ble_get_sync_info();
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    btsnd_hcic_ble_ext_scan_enable`

**Comment by jason-mao** [comment]
Please refer follow table to query the supported chip for example, https://github.com/espressif/esp-adf/tree/master/examples#compatibility-of-examples-with-espressif-audio-boards
