### ISSUE TITLE
Voip - Authentication error with FreePBX (AUD-3392)

### ISSUE THREAD

**Issue by liugyer** [espressif/esp-adf#705]
Hi guys

I'm sure that my freepbx server works fine, because I use microSIP to connect it successfully in two different computers.
And then when I run voip example in this repo, my board (lyrat-mini-v1.2) can't connect to my freepbx, and the log in freepbx shows that "Failed to authenticate"
Please help to fix this issue.
I have captured the log of my board, and freepbx, and the log of freepbx connected with MicroSIP.
The log is in my repo: [https://github.com/liugyer/esp32_log](url)

**Comment by Bruce213** [comment]
Hi，
i met the same problem with myvoip sip server，
have you ever solved it？
wish you give me some help，thank you
