### ISSUE TITLE
get-start in [README.md] document could be 'error'

### ISSUE THREAD

**Issue by InfiniteYuan1** [espressif/esp-adf#71]
Follow the steps below from `esp-adf` README.md [get-start](https://github.com/espressif/esp-adf#quick-start) will get an error.

```
git clone --recursive https://github.com/espressif/esp-adf.git 
cd esp-adf/examples/get-started 
make menuconfig
make flash monitor
```

I think there should be `cd esp-adf/examples/get-started/play_mp3 ` .

I hope you check it kindly.

**Comment by krzychb** [comment]
Hi @InfiniteYuan1,
Good point. Thank you for reporting!
I will get it fixed.
