### ISSUE TITLE
speech_recognition asr speech command detection issue (AUD-3400)

### ISSUE THREAD

**Issue by SAIXHardikHarpal** [espressif/esp-adf#710]
Using default example on Lyra T dev kit and esp-adf/examples/speech_recognition/asr/ English wake word detects 95% times but speech commands are hardly working like 2-5% times, what can be reason how to debug and resolve the issue.

**Comment by HengYongChao** [comment]
Hi @SAIXHardikHarpal 

![image](https://user-images.githubusercontent.com/4134628/140473896-6bb910f9-c177-4f1a-8cee-5b1edcb0b25c.png)

What is your `sdkconfig` configuration?  The speech commands shouldn't only respond 2- 5 times. Please try it with my sdkconfig and reply, thanks!

**Comment by SAIXHardikHarpal** [comment]
Hi @HengYongChao 

Yes it is same but still not working. Wakeword is working fine, so no issue in hardware. You can find code here:
https://singaix-my.sharepoint.com/:u:/g/personal/hardik_harpal_singularityaix_com/EcT805zPMCNHtehn9oEp3AMBD8CfR1o-q3zeHNScxgWaVw?e=p4Fi8C

**Comment by SAIXHardikHarpal** [comment]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/90772293/140698825-68a81918-54b4-4eb8-8743-b0f7dd0ba80d.png)

**Comment by SAIXHardikHarpal** [comment]
@HengYongChao 

Anything you find from code or suggestion, we need this to work. Can you help us?

**Comment by SAIXHardikHarpal** [comment]
@HengYongChao Any update? How to get support on this issue?

**Comment by feizi** [comment]
@SAIXHardikHarpal , You can try English speech commands recognition in esp-skainet: https://github.com/espressif/esp-skainet/tree/master/examples/en_speech_commands_recognition.
The performance of ESP32-S3 English speech commands model is much better than ESP32.

**Comment by HengYongChao** [comment]
Hi @SAIXHardikHarpal

I am very sorry for the speech commands were not recognized caused by submodule changes.

We will update the asr example and esp-sr submodule to support the new command recognition soon.

Please pay attention to ADF.

**Comment by jason-mao** [comment]
@SAIXHardikHarpal So appreciate any progress update from your side.
