### ISSUE TITLE
esp32 lyrat v4.3 音频输入 (AUD-3402)

### ISSUE THREAD

**Issue by DongStop** [espressif/esp-adf#711]
在ESP-ADF components/audio_board/lyrat_v4_3/board_def.h下修改codec芯片的默认配置
adc_input为AUDIO_HAL_ADC_INPUT_LINE2,重新构建工程,插入麦克风无声音,但是插入的过程中扬声器有砰砰的声音.想问一下,esp32 lyrat v4.3板不支持通用麦克风吗?看原理图AUX_IN是支持3段式接口,是不是接入4段式导致的问题?

**Comment by HengYongChao** [comment]
Hi  @DongStop 


![image](https://user-images.githubusercontent.com/4134628/140479626-aa4b7b96-6377-4d0d-9d6a-da577563b56c.png)


录音输入应该使用 AUX_IN，请注意 PHONE_JACK 是输出。

**Comment by jason-mao** [comment]
关闭这个不活跃问题，如有需要，请重新打开或者创建新 issue。
