### ISSUE TITLE
ESP32-LyraT 4.3 Playback and record simultaneously does not work (AUD-3413)

### ISSUE THREAD

**Issue by vovan888** [espressif/esp-adf#713]
i2s_stream_init() fails when registering AUDIO_STREAM_READER after AUDIO_STREAM_WRITER was successfully registered with the following message: "I2S: register I2S object to platform failed"

This happens because i2s_priv_register_object() checks if I2S port is already registered for other audio stream.

**Comment by HengYongChao** [comment]
Hi @vovan888 

I think this example([record_while_play](https://github.com/espressif/esp-adf/tree/master/examples/advanced_examples/record_while_play)) will helps you. It demonstrates how to record and play at the same time.

**Comment by vovan888** [comment]
It does not work too.

**Comment by vovan888** [comment]
Fixed with switching to esp-idf 4.3.1
