### ISSUE TITLE
esp-adf still not support esp32-lyrat-mini v1.2 in menuconfig (AUD-3438)

### ISSUE THREAD

**Issue by changjian-k2k** [espressif/esp-adf#719]
If there any plan in menuconfig for audio hal -> audio board supporting lyrat-mini v1.2, in which I only found lyrat-mini v1.1?

**Comment by HengYongChao** [comment]
Hi @changjian-k2k 

You can still choose lyrat-mini v1.1 in the menuconfig.

The difference between those development boards is that some PCB traces are optimized.

We plan to add the audio board changes history pages for customer inquiries.

**Comment by dandandan1983** [comment]
Hi, @HengYongChao . 
Audio codec device configuration doesn't has ES8311 installed into esp32-lyrat-mini v1.2 . Is it possible to use it when i choose lyrat-mini v1.1 in the menuconfig.?
![изображение](https://github.com/espressif/esp-adf/assets/1750383/22139bef-060a-492f-8c86-192060529771)
