### ISSUE TITLE
#play_sdcard_control FILE RESUME timeout  (AUD-3445)

### ISSUE THREAD

**Issue by DongStop** [espressif/esp-adf#722]
![image](https://user-images.githubusercontent.com/66958826/141993400-b6a8a7a2-a1e4-4e05-b565-7bbc738e2454.png)

![Ubuntu OS-2021-11-16-20-50-55](https://user-images.githubusercontent.com/66958826/141992470-1d33b665-2a15-45b9-b5f8-409526eef13f.png)

**Comment by HengYongChao** [comment]
Hi @DongStop 

可否简要说明操作？ 看 log 似乎是上一首结束了，开始播放下一首的时候出错，此错误是偶先还是必现？

**Comment by DongStop** [comment]
此问题我已解决，我认为存在的问题有可能存在于贵公司的解码库，从log信息很显然说明，当i2s steam发出AEL_STATE_FINISHED信号时，fatfs stream element 未执行close()调用。经过我单独添加了一个fatfs stream 的reset函数，添加在audio_pipeline_reset_elements()前，问题得到解决。并且，我认为贵公司该例程的写法完全是有问题的，这部分代码会导致很严重的内存泄露，每次播放下一首时，都将调用audio_pipeline_run()，请仔细查看该函数，注意该函数的行为，为每个element重新动态创建线程，但是在播放下一首时，并未退出原来element的线程，即未被destroy，在切歌的时候我添加了一段代码，查看系统的memory，切一次歌，少一段内存。

**Comment by DongStop** [comment]
正确的做法是调用audio_pipeline_resume()恢复原先的线程。具体的编程细节我就不多说了。

**Comment by DongStop** [comment]
该问题存在于我用来测试的部分flac歌曲，每次播放完该歌曲时，就会出现该问题。例如我所提供的log信息中，《告白气球》播放完正常播放下一首歌曲，而《蒲公英的约定》播放完无法正常播放下一首，这个时候按下reset键，重新开始，当播放到《蒲公英的约定》时，该问题重新出现，这几首歌文件信息是完整的，我使用读卡器检查了SD卡的文件数据。

**Comment by DongStop** [comment]
所以我推测是flac解码的问题。

**Comment by DongStop** [comment]
@HengYongChao

**Comment by DongStop** [comment]
还有吐槽贵公司的校园招聘。本人应聘嵌入式开发岗位，两道编程题全例通过，结果提示被打入人才库。连一次技术交流的机会都没给。本来想借此面试机会交流IDF SDK开发时遇到问题，恐怖如斯，连面试机会都没得。

**Comment by HengYongChao** [comment]
Hi @DongStop  



> 此问题我已解决，我认为存在的问题有可能存在于贵公司的解码库，从log信息很显然说明，当i2s steam发出AEL_STATE_FINISHED信号时，fatfs stream element 未执行close()调用。经过我单独添加了一个fatfs stream 的reset函数，添加在audio_pipeline_reset_elements()前，问题得到解决。并且，我认为贵公司该例程的写法完全是有问题的，这部分代码会导致很严重的内存泄露，每次播放下一首时，都将调用audio_pipeline_run()，请仔细查看该函数，注意该函数的行为，为每个element重新动态创建线程，但是在播放下一首时，并未退出原来element的线程，即未被destroy，在切歌的时候我添加了一段代码，查看系统的memory，切一次歌，少一段内存。

你好，有具体的代码实现吗，我需要去复现你说的现象。 当前我使用 [pipeline_play_sdcard_music](https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_play_sdcard_music) 这个例程播放 flac 格式的音乐，未复现您提及的内存泄露问题。

**Comment by HengYongChao** [comment]
@DongStop  此问题在最新 ADF 版本中无法复现，如果有需求，你可以再次更新此问题。
