### ISSUE TITLE
wifi_bt_ble_coex_example blufi issue (AUD-3450)

### ISSUE THREAD

**Issue by spaceMan00** [espressif/esp-adf#724]
I am trying to run the wifi_bt_ble_coex_example. 
Board: Lyrat V4.3 using ESP32-WROVER-E
ESP-ADF: master 59a716f
ESP-IDF: v4.2.1
EspBlufi app running on iOS 14.8.1

I follow the instructions as specified and everything builds and runs smoothly. I didn't change anything in menuconfig or the code. 
I am using the EspBlufi app, I can see the BLUFI_DEVICE however as soon as press "Connect" the app displays "Discover service failed" 
 
And the log throws
`W (232234) BT_APPL: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0013`

You can see the log file [here](https://github.com/espressif/esp-adf/files/7566182/log.txt).

Is this a bug or am I missing something?

**Comment by HengYongChao** [comment]
Hi @spaceMan00 

Does this problem still existed in your side? I am not able to reproduct this issue.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
