### ISSUE TITLE
incorrect gpio allocation for one-line mode sdcard (AUD-3463)

### ISSUE THREAD

**Issue by nezen** [espressif/esp-adf#729]
I was testing my Lyrat4.3 board and found vol- touch button could not work even one-line mode was in use.
I investigated it a little bit and believe #line106 is in the wrong position.

https://github.com/espressif/esp-adf/blob/dcf4e356aaeb7f3869ec41ef7a030b905b020731/components/esp_peripherals/lib/sdcard/sdcard.c#L104-L111

I believe it is supposed to be like this:
```
gpio_set_pull_mode(GPIO_NUM_15, GPIO_PULLUP_ONLY);
gpio_set_pull_mode(GPIO_NUM_2,  GPIO_PULLUP_ONLY);
//gpio_set_pull_mode(GPIO_NUM_13, GPIO_PULLUP_ONLY);

if (mode == SD_MODE_4_LINE) {
    gpio_set_pull_mode(GPIO_NUM_13, GPIO_PULLUP_ONLY);
    gpio_set_pull_mode(GPIO_NUM_4,  GPIO_PULLUP_ONLY);
    gpio_set_pull_mode(GPIO_NUM_12, GPIO_PULLUP_ONLY);
}
```

**Comment by HengYongChao** [comment]
Hi @nezen 

This problem does exist here, we will submit a bugfix for it, thanks for your report.
