### ISSUE TITLE
adf里面recorder不能在mini_V1.2运行 (AUD-3464)

### ISSUE THREAD

**Issue by MikeWellC** [espressif/esp-adf#730]
当选择mini_v1.1开发板的时候，程序在
`i2s_stream_reader = i2s_stream_init(&i2s_cfg);`里面出现问题，串口终端里面出现乱码。进一步排查发现是
`i2s_cfg.i2s_port = 1;`选择了I2S端口为1就会出现这个问题。

I (10) boot: ESP-IDF v5.0-dev-489-gef98a363e3 2nd stage bootloader
I (10) boot: compile time 14:00:24
I (10) boot: chip revision: 1
I (13) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (21) qio_mode: Enabling default flash chip QIO
I (26) boot.esp32: SPI Speed      : 80MHz
I (30) boot.esp32: SPI Mode       : QIO
I (35) boot.esp32: SPI Flash Size : 4MB
I (40) boot: Enabling RNG early entropy source...
I (45) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (56) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (63) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (71) boot:  2 factory          factory app      00 00 00010000 00100000
I (78) boot: End of partition table
I (82) boot_comm: chip revision: 1, min. application chip revision: 0
I (90) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=40820h (264224) map
I (171) esp_image: segment 1: paddr=00050848 vaddr=3ffb0000 size=02794h ( 10132) load
I (174) esp_image: segment 2: paddr=00052fe4 vaddr=40080000 size=0d034h ( 53300) load
I (194) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=3766ch (226924) map
I (257) esp_image: segment 4: paddr=00097694 vaddr=4008d034 size=07ffch ( 32764) load
I (268) esp_image: segment 5: paddr=0009f698 vaddr=50000000 size=00010h (    16) load
I (278) boot: Loaded app from partition at offset 0x10000
I (278) boot: Disabling RNG early entropy source...
I (290) psram: This chip is ESP32-D0WD
I (291) spiram: Found 64MBit SPI RAM device
I (291) spiram: SPI RAM mode: flash 80m sram 80m
I (293) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (301) cpu_start: Pro cpu up.
I (304) cpu_start: Starting app cpu, entry point is 0x40081710
I (0) cpu_start: App cpu up.
I (804) spiram: SPI SRAM memory test OK
I (812) cpu_start: Pro cpu start user code
I (812) cpu_start: cpu freq: 240000000 Hz
I (812) cpu_start: Application information:
I (815) cpu_start: Project name:     recording_to_sdcard
I (821) cpu_start: App version:      1
I (825) cpu_start: Compile time:     Nov 29 2021 14:46:35
I (831) cpu_start: ELF file SHA256:  0891f93fb4e694d2...
I (837) cpu_start: ESP-IDF:          v5.0-dev-489-gef98a363e3
I (844) heap_init: Initializing. RAM available for dynamic allocation:
I (851) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (857) heap_init: At 3FFB3360 len 0002CCA0 (179 KiB): DRAM
I (863) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (870) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (876) heap_init: At 40095030 len 0000AFD0 (43 KiB): IRAM
I (882) spiram: Adding pool of 4095K of external SPI memory to heap allocator
I (891) spi_flash: detected chip: gd
I (894) spi_flash: flash io: qio
W (898) spi_flash: Detected size(8192k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (912) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (927) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (935) RECORD_TO_SDCARD: [ 1 ] Mount sdcard
I (1441) RECORD_TO_SDCARD: [ 2 ] Start codec chip
W (1502) I2C_BUS: i2c_bus_create:57: I2C bus has been already created, [port:0]
I (1510) RECORD_TO_SDCARD: [3.0] Create audio pipeline for recording
I (1511) RECORD_TO_SDCARD: [3.1] Create fatfs stream to write data to sdcard
I (1516) RECORD_TO_SDCARD: [3.2] Create i2s str痧囵sg3bfssfggcfffccgfg3sgcc3sgs鎟fg鎌srf3ssfsg3c起续痧痧鹄噼鵂瘘萬gfffscfffg鎓gfccgcsff痧痧痧瘌鹦痧痧痧禳类桊痿噜疣瘘瘘帏瘌瘌瘌续续恤痧瘌瘌瘘叙痧麴瘌囵噜鹦疣桫疣瘘痧鹄鹄_痧疣麴餱gc痧鹦瘌囵痧痧桊痿栲痧鹦瘌瘘痧痧噜噼噼类嗬嗬噜纮豇悬疣痧痧鹄痧痧鵂痧痧续痧鲤痧瘘瘘痧鹄豇餻囵麴痧囵痧痧狆续疣续瘌痧痧痧瘌帏瘘麴痿疣痧痧痧瘌痧疣瘘痧瘘痧痧疣鹦痧痧痧续痧�囵嗬黎黎鲤囵需噼噜�类枥枞饊览帏佬嗬览枥览嗳类噜噜廊噜类览噜鄁淅噜黎嗬痂嗬鄝类类嗬帼噜嗬嘈�类览噼噜览嗬枥览愷梃鄝嘈疣嘈鹄瘌囵栲览览览览枥噼疣枥噼励枥疣栲瘌梃栲桫噜栲噜痧鲤嗬痂栲壤噼览黎嘈览嗬嗬帏囵黎黎嗬鹄�览览噼嘈痧痧瘘痧瘌叙悬叙痧痧痧豇瘘瘌痧瘌痧囵瘘�3gff鎔cbf3sggggggf33#sg7cg鎐fff�3gf3333gcfffs2黟痧瘌痧痿瘌痧瘌桊麴鹦瘌鹦痧叙帱叙瘌酄叙麴瘌帏鹦痧瘘痧痧瘌痧痧痧痧srgff#vgfwgfsbfffgggss鎓fffffwggf3c痧瘘鄐2s3ssbfffcf瘘痧鹄瘌7gfg#ss#cfgggfsfgs33#cc骛痿瘘痧痿瘌痧囵麴痧瘘痧痧嗬疣酄痧痿鹄励痧痧悬帱麴帱瘌痧瘌痧�痿续痧痧圄帱嗬痧疣疣fsgggbfgcgf7ggfgfgfgfbfsc#sscfscg33rsggfgfgf3ffffgfffffgff#gfg3cgs#cb#sfcgfcfgfff#scfcgf3ssgfgfgfffffffff33sgg3337cf3#2cscggfgfgfgg3s2bbffgffffsbggscg悬痧叙瘌痧瘌瘌瘘续续续囵瘘痧鲤瘌瘘鲤疣悬痿瘌囵鴢痧痧痧痿痿类馉H---璱I-m-韘gsgfgc3sgfcfffcfg3sgg泺痧帱饜gf鎔fgffcggsfcssfsscvg3c3ssffscg3g瘘鲤鵂噜痧帏瘘噜帱悬痧痧痂悬瘘瘌瘘瘌瘘瘌悬��揉鑰噼类壤类嗳噜鲤鹦帏噼桫噼嘈鲤噜黎嗳疣噼痂疣囵览栲冷嗬�览愢览�览噜噼噼噜嗬类愢噜类栲朽类览栲览嗬鲤鑰嗬栲�枥类枥噜�枥览噜�缾鄝黎嗬类��类�类朽嗳噜类梃桊疣梃需噼噜桊噜枥痂枥枥鹄类类鲤览廊鄝��鲤览噼嗬览纮鄝佬类嗬类噜枥鹄黎噜疣噜梃嗬噼叙疣桊梃噜嘈噜栲鹄噜鑠桊鲤励鹄类噜鹄疣梃桊枥噼嘈嗬囵噼噼噜枥�噜噼嗬疣桊枥类痧鲤类枥噜揉揉鲤黎嗬嗬噼鲤佬栲揉览疣嗬纮类�嗬栲痧黎噜鹄��类类类嗬鄝嗬鹄嗬嗬鹄类黎栲嗬囵黎噼噜栲栲栲囵噼噜欣嗬噜嗬桊类黎噜嗬类鲤噼囵噼痂桊类黎嗬噜需揉欣类嗬类梃鲤�鹑噼类噜疣佬嘈桊励类欣囵噜壤嗬鲤鹑嗬览噜噜枥栲鲤类噼嗬欣类类疣疣类噜嗬黎帏鲤嗬嗬嗬鹑嗬佬噜类噜鹄栲栲黎噜枞欣瑞嗬噼鲤噜�黎纮噜壤嗬嗬览噜噜佬枥���嗬览览噜噜嗬噜枥梃佬嗬噜囵朽痂疣栲佬类类鲤栲噼噼噜黎鲤览鲤鲤桊枥�黎囵囵噜噜囵揉类类类嗳嗬pfff箴瘌痧囵酎痧悬瘘酎瘌瘌痧痧痧瘌帱囵瘘痧瘌瘘痧痧痧瘌痧痧豇躥cfggsgffffg##cbfgffbg琰痧痧嘈桊瘘痧痧瘌痧瘘鹦痧痧瘌痧瘌痧痧痧瘘瘌痧帏叙鹦鵂傈痧瘌帏嘈瘌瘘�览纮囵爛�枥衻�览噜览类嘈览鄝�鲤类�类鲤欣噜揉类嗬痧枥愷鹄噜类欣嗬黎类览类痧鲤瑞栲览桊桊鹄囵��噼疣嗬瑞痂类噜瑞嗬嗬栲噜类痂枥类羿嗬类嗬痧噼嗳囵鲤愢类�枥类廊噜囵嗬噼梃类梃栲嗬囵腥痧栲励�嗬黎惾桫栲壤嗬类梃栊枥痧励览欣嗳鹄纮类揉览鲤惱类惱疣囵噼噜枥嗬鹄嗬栲纮帏噜囵疣噼囵嗬类廊噜桎嗬嗬噜噜欣瘌览噜嗬壤黎帱鹦瘘鹦痧悬瘌瘌瘌瘌痿瘘览囵�类桫噜噜栲览噜佬栲帏疣枞栲囵栊pf疣辱噜栲嘈噼痧类鲤枥欣鲤鲤鹄噼噜佬噼囵枥类嘈嗬嗬噜壤嘈类鲤嗳嗬纮类类佬佬揉鲤类鲤噜噼鲤噜嗬需朽噜梃噜栊噜栲帏帏噜噼噼桫噼疣帏梃欣鲤噜桊类ffsssg3#bfbfffcfsswcs#sbfggg33s3ssbfgffgg3sbffbsc琊疣痧瘌鹛gffcffffggfs33cssc#3ss3rggggcggg3gcscf3ssgc#cgfffggfg鎤ggff33rfffcfg簏痧瘘痧瘌瘘鹦痿痧痿瘌痧悬瘘痧痧帏狆馉痧鲤傈瘘麴鹄鹦鹦瘌瘌x#3gfffgfg鎓#sgfbfffggcgffff3bfffff3rss3s2bfgff3cscfcfbg3cbcggf333#7cf帏鹦�7bfsgssww#cggggfffffgsffbbf3cgf3c7ccff3332bbfggss3#333##3sfffgf333bbfgsf3c3#3cscff瘌瘌瘌03sccf33223g33##2bcwgss37rggfgcs33#ss33##2scgfgg悬瘌痧痧囵麴痧ggsccffsgfwgffggf33ssfcgrcfffgffg鎔g鎣f3rfgcb3ffgcfgffgff3sfffffffffbfbfcc7wggfcgfcfffsccffgsc3#cbcf'gffgg33s#rbffgccfcfffgffff#cfbfff3fggfffcssfgg#7cfg鎔gffffffcs3gc7s3##bgcfgfffffff3#痧馉瘘悬叙鹄疣梃类噼噜栲桫栲噜帏疣类览鹄梃类鄲噜栲噼囵疣栊栲噜栲噼枞囵枥类帏嗬嗬噼噜鄝壤嗬噼痂嗬览类桊栲痧噼痧类嗬噜梃鹄嗬噼疣梃囵噜鲤类需噜辱黎�类热嗬噼类梃噼鹄鑰类噜佬噼黎嗬嗬嗬览鄝�览噜类噜嗬类噜类览纮类壤类览栲览疣类�噼噼痂噼鹄黎囵囵噼嗳噜疣类览嗬鄝噜栲噜囵嗳类类梃类鹄�栲枥囵嗬鄝惱类佬类嘈梃类嗬枥帏览类囵壤噜�����疣噜鲤类��览腥类���览嘈览桊�廊览噼嗬�嗬枥欣疣�嗬鄝鲤栲黎类pfff嗬鹄欣嘈类鹑�类揉鲤枥朽噼鹄栲桊噼类桫枥栲类朽黎朽枥类嗬栲枥类佬栲栲鲤鲤嗬览嗬嗬览欣类黎类枞览鹄朽噼廊噜嗬噜噼pg�栲桊鄝�栲噜类类类枥枥噜痂鹄欣览噼枥噼鹄噼鲤桊类佬噜噜噜揉��览纮佬嗬噼鄝鲤类嗬鄝噜鹦览噼鹄黎鄝餻f�览览栲览���欣纮览嗬览类览��栊廊���览廊噼噜噜览嗬噼痧惱览���嗬览廊类痂桫栲嘈噜疣桊梃嗬疣梃疣噼揉枥枥枥疣桊廊鹄嗬揉览枞嗳鹄饦ffgf噜黎佬揉类噜黎揉类噜黎噜嗬囵��嗬廊栲纮鲤鄻ffff鹄枥纮葊览枞嘈噜类嗬噜壤类朽纮�纮鄝纮览览黎鲤鹄疣鲤鲤桊欣噜痂噼痂嘈嘈鲤壤枥鲤壤囵噜噼嗬鄝类噜枥痂览栲f3c333s2bfbbf悬瘘瘘痧痧痧痧�333bfffgff3s琰痧鹦麴瘌桊痧瘌痧痧痧悬瘘痧痧痧痧览览噜噜类嗬愯类嗬类览鹑鄝类类览�衻类惱噼类嗬欣�衻嗬类览�佬揉囵壤噜噼嗬览��嗬栲纮揉囵佬览嗬嗳嗬枥览��览览愢鄲览类枥噜噜类鄝览噜犘类��类嗬噜纮繞���览览览览黎览�惱噜类��览览类�览衻���黎览嗬�鲤朽类嗬���览�鲤类览览类枥佬类嗬噜噜栲噜类f3ssbfff2sgffgs333#ccfcgf33#c37cfggffgfgf3c3fffgssgg3#32sswggfffbssv#33cc37wsscbfc3#桊痧瘌桫桊痧帏痧瘘痧痧痧瘘瘌瘘痧瘘瘘瘌痧723cccgfwwffgfgff3#f瀋ffcccs7s33#3cs2s3333#33sw733333233s773#33ss32333w73ss33#33cffggv3333g3333cccsgbfffcgf7s3ffffg33s瘌桊痧瘘酎瘘酎酎麴痧痧瘌痧瘘酎酤桫瘌痧瘌痧瘘瘌痧囵痧瘘瘌�?瘌*獣*キ暕┆***ァオ�**暘�*�)璉)-iIff2cgwcff3s3sgg3s333f337b3ssffffggffgffgfsggg3bfscfccg3ggfgf鎠vfcf鎋瘘疣瘘痿鹦瘘黿3rccccgff3fc痧痧酎瘘0fgwss3322sc3s3s3#23ss7c#3#2scffgggcfffffg3723scgcgw333#cbf3瑛续痧痧瘘疣帏瘘桊瘌悬瘘椟痧瘌痧痧瘌瘌痧痧瘘痧疣痧麴瘘酎痧鲤嗬饊瘌栲鄲瑞览痧嗳嗬噜纮�览类欣嗬览览嗳鄝枥纮览纮�噼嘈廊鲤栲噜类览噜览鹦黎�嗬痂览鹑嗬类鹄鹄噼噜纮类嗳嗬痧类噼嗬嗬辱嘈欣类噜廊嗬噜览续噜栲噼痧瘘麴桊瘌酎�鲤鹄噼噜嗬痂痧励枥枥噜噜览鄝噼鑰类��愯噜览类噜嗬噜疣览�嘈爛��愢览噜噜嗳嗬瘌枥鹄噜类愢噜桊梃嗬帏鹄噜枥疣噼噜噜揉栲栲疣嗬类鄝疣桊噜鲤嗬疣噼吏疣囵壤佬嗬嗬类类�栲痧黎囵栲栲惱栲枥嗬噜噜栲噜圄痂嗬需噼栲枥桊噜囵梃疣噼嗬瘌桫痂桊噜桊噜栲疣桊鹄帏疣嘈栲揉栲类嗳痧痧噜疣瑞揉惱噜栲辱黎鹄桊痂栊囵梃噜枥欣黎励嗬栲噜枥欣嗬枥囵栲痂噜噼览噼囵�枥览览噼噜鄝噜纮览嗳囵类览疣噼嗬袗�囵噜腥噼类疣噼嗬黎览类桊嗬廊类桊嗬类览噜衻类嘈壤疣栲类揉饊览廊类叙噜鲤�览览�纮惱噜痧囵鲤噜梃览鹄噜�黎噜囵疣噜类类渇类桊鹄嗳览佬鲤噼嗬噜嗬类瘌gs333#32cfffgc23sss3bfffgggfgffss3s2r3g33333#3#cgggcss322cccfcbggfffgfgfcswgggf33#3c33fbfcs322c333s33ss333c抢类鄍

**Comment by HengYongChao** [comment]
Hi @MikeWellC 

请更新 ADF 到最新版本， 这个问题已经在 [bugfix: correct i2s stream mclk ouput issue](https://github.com/espressif/esp-adf/commit/91dfe6ef98124507ffbc65b4ebd8fcb4b7f3a067) 这个提交中被修复了。
