### ISSUE TITLE
录制声音播放时是杂音 (AUD-3467)

### ISSUE THREAD

**Issue by 547176052** [espressif/esp-adf#731]
使用例子
https://github.com/espressif/esp-adf/tree/master/examples/recorder/pipeline_recording_to_sdcard
开发板使用
ESP32-LyraTD-MSC V2.2
录制得到的文件
[rec.zip](https://github.com/espressif/esp-adf/files/7625948/rec.zip)
杂音

**Comment by HengYongChao** [comment]
Hi @547176052 

我测试使用 MSC v2.2 这个块板子， 测试例程为 [pipeline_recording_to_sdcard](https://github.com/espressif/esp-adf/tree/master/examples/recorder/pipeline_recording_to_sdcard), IDF 选择 [release/v4.4](https://github.com/espressif/esp-idf/tree/release/v4.4) , menuconfig 选择 WAV 录制 来编译，烧录后， 录音正常。
[rec.zip](https://github.com/espressif/esp-adf/files/7647257/rec.zip)

**Comment by 547176052** [comment]
好的,谢谢你
