### ISSUE TITLE
I hope you have a chance to give this great repo an update. (AUD-3494)

### ISSUE THREAD

**Issue by aguaviva** [espressif/esp-adf#734]
This repo is still using esp-idf from 2 years ago, and the last release is from May 21.  An update would be more than welcome!

Cheers!

**Comment by HengYongChao** [comment]
Hi @aguaviva 

Thanks for your suggestion first!

Regarding the built-in IDF version of ADF, we will be updated soon.  And actually, IDF v3.3 is still within the [support periods](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/versions.html#support-periods)

About built-in esp-idf version too old problem, you can specify $IDF_PATH to external other IDF versions, using command  `export IDF_PATH=/workshop/esp-idfs/esp-idf-release-v4.2` to export the IDF version to release v4.2, then You can build ADF example with IDF release v4.2 now.
