### ISSUE TITLE
ADF环境安装完成后编译出现问题 (AUD-3555)

### ISSUE THREAD

**Issue by CYCHEN97** [espressif/esp-adf#747]
![](https://user-images.githubusercontent.com/61934856/149056885-00e1ae59-c4b8-4de7-b036-48fd55842fa0.png)
ADF安装好后进行编译自动语音识别demo时，提示python版本问题，还没安装ADF之前linux中只有python3，安装好ADF后多了几个python版本
![](https://user-images.githubusercontent.com/61934856/149057182-2fd014f2-298e-4521-b1b9-61fcd5891306.png)

![](https://user-images.githubusercontent.com/61934856/149058986-6c97c3a9-296f-4ab4-8d85-a21e72aeb307.png)
ADF安装成功可以在VSCODE显示example

![](https://user-images.githubusercontent.com/61934856/149058894-2d70b668-bd9c-48dd-84a5-a1229714a07b.png)
但是点这个配置后提示错误

**Comment by CYCHEN97** [comment]
@HengYongChao
麻烦帮忙看一下

**Comment by CYCHEN97** [comment]
@HengYongChao
@jason-mao 
@binartech
@espressif-zhanghu
@krzychb
@ahhfzhang
你好，我用装好的这个环境编译了MP3的example是没问题的，也可以正常播放音乐，但是编译配置ASR语音识别这个example时就出现问题了，麻烦帮我看一下这是怎么回事，谢谢
![图片](https://user-images.githubusercontent.com/61934856/149250857-ac15f5d5-0465-4a1f-93ca-823fceaf71b5.png)

**Comment by jason-mao** [comment]
@CYCHEN97 建议你先把 IDF 升级到 release/4.4，同时使用最新ADF master里面的wwe example 体验ASR 的功能。

**Comment by CYCHEN97** [comment]
@jason-mao
IDF不需要使用ADF下的那个吗？

**Comment by jason-mao** [comment]
> @jason-mao
> IDF不需要使用ADF下的那个吗？
ADF下IDF 只是指定了版本，可以在里面切换到其他分支。参考example README, 
https://github.com/espressif/esp-adf/blob/master/examples/speech_recognition/wwe/README_CN.md#编译和下载

**Comment by CYCHEN97** [comment]
@jason-mao
ADF用master版本吗？

**Comment by CYCHEN97** [comment]
![图片](https://user-images.githubusercontent.com/61934856/149264786-54b10d7c-a47b-4c99-91cf-3ded4c1cb1f3.png)

**Comment by CYCHEN97** [comment]
@jason-mao
ADF更新到master，ADF下的IDF更新到4.4版本后，编译那个wee例程成功了，但是跑到开发板上出问题了，开发板用的是ESP32-LyraTD-MSC_A V2.2
![图片](https://user-images.githubusercontent.com/61934856/149273728-01957b6e-b6a2-4d92-b2f3-fca1bd528f51.png)
还有就是默认分区太小了，生成的.bin文件有3.2M，但是那个分区表默认只给了0x300000，我增大了那个程序分区后才能烧写程序到板子上
![图片](https://user-images.githubusercontent.com/61934856/149274391-106f05a8-d385-4a3a-9938-8e455b958a50.png)

**Comment by jason-mao** [comment]
@CYCHEN97 你板子的批次比较久远，内存使用上有些限制，建议只开wakenet，不要开multi net了。另外建议你使用的S3开发板体验效果会更佳。

**Comment by CYCHEN97** [comment]
@jason-mao 
关闭wakenet，只开启wakenet
![图片](https://user-images.githubusercontent.com/61934856/149276953-dbd21d81-45c2-48e6-bc54-7e2923f34ebc.png)
然后还是一样的问题
![图片](https://user-images.githubusercontent.com/61934856/149277193-3c090a45-8417-4bbc-9aaf-3c81de66386e.png)

**Comment by CYCHEN97** [comment]
@jason-mao

**Comment by CYCHEN97** [comment]
@jason-mao
跑ASR的例程就一直在复位
![图片](https://user-images.githubusercontent.com/61934856/149284625-45b3d64e-e660-4777-8c91-e17d34753968.png)

**Comment by CYCHEN97** [comment]
@ jason-mao
支持了就跟我说一下哈

**Comment by jason-mao** [comment]
@CYCHEN97 请基于这个ID测试 34af12428ea6fa691e9b2cf9259cd86b1c62c0c2,
