### ISSUE TITLE
ESP32 S3是否会支持蓝牙音频，如A2DP或BLE Audio？ (AUD-3578)

### ISSUE THREAD

**Issue by MichaelDu9226** [espressif/esp-adf#752]
如果使用ESP32 S3实现蓝牙音频功能，请问有合适的建议吗？
简单查了一下，ESP32支持A2DP
ESP32 S3因为没有经典蓝牙所以不支持A2DP，请问S3是否会支持BLE Audio，不知道官方是否有此计划？

**Comment by HengYongChao** [comment]
Hi @MichaelDu9226 

ESP32-S3 是一款集成 2.4 GHz Wi-Fi 和 Bluetooth 5 (LE) 的 MCU 芯片，不支持经典蓝牙的，同样 LE audio 是 5.2 的内容， S3 也不支持。 

乐鑫后面会推新的芯片支持上面的 feature 的，请持续关注乐鑫，谢谢！
