### ISSUE TITLE
VOIP:注册失败 (AUD-3595)

### ISSUE THREAD

**Issue by davidHuW** [espressif/esp-adf#756]
IDF:v4.2及以上/v3.3
ADF:Master
SIP 服务器：Yate

I (689) wifi:new:<1,1>, old:<1,0>, ap:<255,255>, sta:<1,1>, prof:1
I (1369) wifi:state: init -> auth (b0)
I (1389) wifi:state: auth -> assoc (0)
I (1399) wifi:state: assoc -> run (10)
I (1409) wifi:connected with 1308, aid = 7, channel 1, 40U, bssid = f4:a5:9d:26:0e:1c
I (1409) wifi:security type: 3, phy: bgn, rssi: -58
I (1419) wifi:pm start, type: 1

I (1609) wifi:AP's beacon interval = 102400 us, DTIM period = 1
[0;32mI (2169) event: sta ip: 192.168.3.124, mask: 255.255.255.0, gw: 192.168.3.1[0m
[0;32mI (2169) WIFI_SERV: Got ip:192.168.3.124[0m
[0;33mW (2169) WIFI_SERV: STATE type:2, pdata:0x0, len:0[0m
[0;32mI (2189) VOIP_EXAMPLE: PERIPH_WIFI_CONNECTED [323][0m
[0;32mI (2189) VOIP_EXAMPLE: [ 5 ] Create SIP Service[0m
[0;32mI (2189) SIP: esp_sip ver : '1.0.1' Compile date: Dec 23 2021-14:09:23
[0m
[0;32mI (2199) SIP: Conecting...[0m
[0;33mW (2199) SIP: CHANGE STATE FROM 0, TO 1, :func: sip_connect:1684[0m
[0;32mI (2209) SIP: [1970-01-01/00:00:01]=======WRITE 0578 bytes>>[0m
[0;32mI (2209) SIP: 

REGISTER sip:100@192.168.3.93:5060 SIP/2.0

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK-805801336;rport

From: <sip:100@192.168.3.93:5060>;tag=730510460

To: <sip:100@192.168.3.93:5060>

Contact: <sip:100@192.168.3.124:19149>

Max-Forwards: 70

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 1 REGISTER

Expires: 3600

User-Agent: ESP32 SIP/2.0

Content-Length: 0

Allow: INVITE, ACK, CANCEL, BYE, UPDATE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE

Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri

Allow-Events: presence, kpml

[0m
[0;32mI (2269) SIP: [1970-01-01/00:00:01]=======================>>[0m
[0;32mI (2339) SIP: [1970-01-01/00:00:01]<<=====READ 0314 bytes==[0m
[0;32mI (2339) SIP: 

SIP/2.0 100 Trying

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK-805801336;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=730510460

To: <sip:100@192.168.3.93:5060>

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 1 REGISTER

Server: YATE/6.1.0

Content-Length: 0

[0m
[0;32mI (2359) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (2369) SIP: [1970-01-01/00:00:01]<<=====READ 0519 bytes==[0m
[0;32mI (2379) SIP: 

SIP/2.0 401 Unauthorized

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK-805801336;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=730510460

To: <sip:100@192.168.3.93:5060>;tag=967731643

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 1 REGISTER

WWW-Authenticate: Digest realm="Yate", nonce="f8d1003feca404243e0945d41757eaba.1643462364", stale=FALSE, algorithm=MD5

Server: YATE/6.1.0

Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO

Content-Length: 0

[0m
[0;32mI (2419) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (2429) SIP: Required authentication[0m
[0;32mI (2439) SIP: [1970-01-01/00:00:01]=======WRITE 0815 bytes>>[0m
[0;32mI (2439) SIP: 

REGISTER sip:100@192.168.3.93:5060 SIP/2.0

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1982092730;rport

From: <sip:100@192.168.3.93:5060>;tag=-283863032

To: <sip:100@192.168.3.93:5060>

Contact: <sip:100@192.168.3.124:19149>

Max-Forwards: 70

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 2 REGISTER

Expires: 3600

User-Agent: ESP32 SIP/2.0

Content-Length: 0

Allow: INVITE, ACK, CANCEL, BYE, UPDATE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE

Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri

Allow-Events: presence, kpml

Authorization: Digest username="100", realm="Yate", nonce="f8d1003feca404243e0945d41757eaba.1643462364", uri="sip:192.168.3.93:5060", response="f5a8a7ce1831181bc49d6c52775b0128", algorithm=md5, nc=00000001, cnonce="f76faf67abfe24ae"

[0m
[0;32mI (2519) SIP: [1970-01-01/00:00:01]=======================>>[0m
[0;32mI (2539) SIP: [1970-01-01/00:00:01]<<=====READ 0317 bytes==[0m
[0;32mI (2539) SIP: 

SIP/2.0 100 Trying

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1982092730;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=-283863032

To: <sip:100@192.168.3.93:5060>

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 2 REGISTER

Server: YATE/6.1.0

Content-Length: 0

[0m
[0;32mI (2569) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (2579) SIP: [1970-01-01/00:00:01]<<=====READ 0523 bytes==[0m
[0;32mI (2579) SIP: 

SIP/2.0 401 Unauthorized

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1982092730;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=-283863032

To: <sip:100@192.168.3.93:5060>;tag=1020068012

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 2 REGISTER

WWW-Authenticate: Digest realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", stale=FALSE, algorithm=MD5

Server: YATE/6.1.0

Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO

Content-Length: 0

[0m
[0;32mI (2629) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (2639) SIP: Required authentication[0m
[0;32mI (2639) SIP: [1970-01-01/00:00:01]=======WRITE 0814 bytes>>[0m
[0;32mI (2649) SIP: 

REGISTER sip:100@192.168.3.93:5060 SIP/2.0

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1974865940;rport

From: <sip:100@192.168.3.93:5060>;tag=720657929

To: <sip:100@192.168.3.93:5060>

Contact: <sip:100@192.168.3.124:19149>

Max-Forwards: 70

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 3 REGISTER

Expires: 3600

User-Agent: ESP32 SIP/2.0

Content-Length: 0

Allow: INVITE, ACK, CANCEL, BYE, UPDATE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE

Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri

Allow-Events: presence, kpml

Authorization: Digest username="100", realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", uri="sip:192.168.3.93:5060", response="d62e2a1fa45f862348402e6fefc64779", algorithm=md5, nc=00000001, cnonce="aa46b5f5a7a11098"

[0m
[0;32mI (2719) SIP: [1970-01-01/00:00:01]=======================>>[0m
[0;32mI (2749) SIP: [1970-01-01/00:00:01]<<=====READ 0316 bytes==[0m
[0;32mI (2749) SIP: 

SIP/2.0 100 Trying

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1974865940;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=720657929

To: <sip:100@192.168.3.93:5060>

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 3 REGISTER

Server: YATE/6.1.0

Content-Length: 0

[0m
[0;32mI (2779) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (2789) SIP: [1970-01-01/00:00:01]<<=====READ 0522 bytes==[0m
[0;32mI (2789) SIP: 

SIP/2.0 401 Unauthorized

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1974865940;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=720657929

To: <sip:100@192.168.3.93:5060>;tag=1371682657

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 3 REGISTER

WWW-Authenticate: Digest realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", stale=FALSE, algorithm=MD5

Server: YATE/6.1.0

Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO

Content-Length: 0

[0m
[0;32mI (2839) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (2849) SIP: Required authentication[0m
[0;32mI (2849) SIP: [1970-01-01/00:00:01]=======WRITE 0814 bytes>>[0m
[0;32mI (2859) SIP: 

REGISTER sip:100@192.168.3.93:5060 SIP/2.0

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1525884008;rport

From: <sip:100@192.168.3.93:5060>;tag=401535613

To: <sip:100@192.168.3.93:5060>

Contact: <sip:100@192.168.3.124:19149>

Max-Forwards: 70

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 4 REGISTER

Expires: 3600

User-Agent: ESP32 SIP/2.0

Content-Length: 0

Allow: INVITE, ACK, CANCEL, BYE, UPDATE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE

Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri

Allow-Events: presence, kpml

Authorization: Digest username="100", realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", uri="sip:192.168.3.93:5060", response="d62e2a1fa45f862348402e6fefc64779", algorithm=md5, nc=00000001, cnonce="dd225d4b68334de9"

[0m
[0;32mI (2929) SIP: [1970-01-01/00:00:01]=======================>>[0m
[0;32mI (2959) SIP: [1970-01-01/00:00:01]<<=====READ 0316 bytes==[0m
[0;32mI (2959) SIP: 

SIP/2.0 100 Trying

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1525884008;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=401535613

To: <sip:100@192.168.3.93:5060>

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 4 REGISTER

Server: YATE/6.1.0

Content-Length: 0

[0m
[0;32mI (2979) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (2989) SIP: [1970-01-01/00:00:01]<<=====READ 0521 bytes==[0m
[0;32mI (2999) SIP: 

SIP/2.0 401 Unauthorized

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1525884008;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=401535613

To: <sip:100@192.168.3.93:5060>;tag=141139179

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 4 REGISTER

WWW-Authenticate: Digest realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", stale=FALSE, algorithm=MD5

Server: YATE/6.1.0

Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO

Content-Length: 0

[0m
[0;32mI (3049) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (3049) SIP: Required authentication[0m
[0;32mI (3059) SIP: [1970-01-01/00:00:01]=======WRITE 0814 bytes>>[0m
[0;32mI (3059) SIP: 

REGISTER sip:100@192.168.3.93:5060 SIP/2.0

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--2028851935;rport

From: <sip:100@192.168.3.93:5060>;tag=645989708

To: <sip:100@192.168.3.93:5060>

Contact: <sip:100@192.168.3.124:19149>

Max-Forwards: 70

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 5 REGISTER

Expires: 3600

User-Agent: ESP32 SIP/2.0

Content-Length: 0

Allow: INVITE, ACK, CANCEL, BYE, UPDATE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE

Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri

Allow-Events: presence, kpml

Authorization: Digest username="100", realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", uri="sip:192.168.3.93:5060", response="d62e2a1fa45f862348402e6fefc64779", algorithm=md5, nc=00000001, cnonce="0ae7cf4d86a911a1"

[0m
[0;32mI (3139) SIP: [1970-01-01/00:00:01]=======================>>[0m
[0;32mI (3169) SIP: [1970-01-01/00:00:01]<<=====READ 0316 bytes==[0m
[0;32mI (3169) SIP: 

SIP/2.0 100 Trying

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--2028851935;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=645989708

To: <sip:100@192.168.3.93:5060>

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 5 REGISTER

Server: YATE/6.1.0

Content-Length: 0

[0m
[0;32mI (3189) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (3199) SIP: [1970-01-01/00:00:01]<<=====READ 0522 bytes==[0m
[0;32mI (3209) SIP: 

SIP/2.0 401 Unauthorized

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--2028851935;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=645989708

To: <sip:100@192.168.3.93:5060>;tag=1582382231

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 5 REGISTER

WWW-Authenticate: Digest realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", stale=FALSE, algorithm=MD5

Server: YATE/6.1.0

Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO

Content-Length: 0

[0m
[0;32mI (3249) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (3259) SIP: Required authentication[0m
[0;32mI (3269) SIP: [1970-01-01/00:00:01]=======WRITE 0814 bytes>>[0m
[0;32mI (3269) SIP: 

REGISTER sip:100@192.168.3.93:5060 SIP/2.0

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK-2066197906;rport

From: <sip:100@192.168.3.93:5060>;tag=-230881210

To: <sip:100@192.168.3.93:5060>

Contact: <sip:100@192.168.3.124:19149>

Max-Forwards: 70

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 6 REGISTER

Expires: 3600

User-Agent: ESP32 SIP/2.0

Content-Length: 0

Allow: INVITE, ACK, CANCEL, BYE, UPDATE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE

Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri

Allow-Events: presence, kpml

Authorization: Digest username="100", realm="Yate", nonce="dcf598bc8d8e23553d0e38d2ae3346cd.1643462365", uri="sip:192.168.3.93:5060", response="d62e2a1fa45f862348402e6fefc64779", algorithm=md5, nc=00000001, cnonce="a646ba9e34b7b43a"

[0m
[0;32mI (3349) SIP: [1970-01-01/00:00:01]=======================>>[0m
[0;32mI (3369) SIP: [1970-01-01/00:00:01]<<=====READ 0316 bytes==[0m
[0;32mI (3369) SIP: 

SIP/2.0 100 Trying

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK-2066197906;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=-230881210

To: <sip:100@192.168.3.93:5060>

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 6 REGISTER

Server: YATE/6.1.0

Content-Length: 0

[0m
[0;32mI (3399) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (3399) SIP: [1970-01-01/00:00:01]<<=====READ 0522 bytes==[0m
[0;32mI (3409) SIP: 

SIP/2.0 401 Unauthorized

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK-2066197906;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=-230881210

To: <sip:100@192.168.3.93:5060>;tag=1603571448

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 6 REGISTER

WWW-Authenticate: Digest realm="Yate", nonce="d01b21bf210f5ddd15503f14dc054233.1643462366", stale=FALSE, algorithm=MD5

Server: YATE/6.1.0

Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO

Content-Length: 0

[0m
[0;32mI (3459) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (3469) SIP: Required authentication[0m
[0;32mI (3469) SIP: [1970-01-01/00:00:01]=======WRITE 0815 bytes>>[0m
[0;32mI (3479) SIP: 

REGISTER sip:100@192.168.3.93:5060 SIP/2.0

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1317130060;rport

From: <sip:100@192.168.3.93:5060>;tag=1248911934

To: <sip:100@192.168.3.93:5060>

Contact: <sip:100@192.168.3.124:19149>

Max-Forwards: 70

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 7 REGISTER

Expires: 3600

User-Agent: ESP32 SIP/2.0

Content-Length: 0

Allow: INVITE, ACK, CANCEL, BYE, UPDATE, REFER, MESSAGE, OPTIONS, INFO, SUBSCRIBE

Supported: replaces, norefersub, extended-refer, timer, X-cisco-serviceuri

Allow-Events: presence, kpml

Authorization: Digest username="100", realm="Yate", nonce="d01b21bf210f5ddd15503f14dc054233.1643462366", uri="sip:192.168.3.93:5060", response="33d892ebafa30d93eb88d6cfe15dc328", algorithm=md5, nc=00000001, cnonce="39b17467df00fd6c"

[0m
[0;32mI (3549) SIP: [1970-01-01/00:00:01]=======================>>[0m
[0;32mI (3579) SIP: [1970-01-01/00:00:01]<<=====READ 0317 bytes==[0m
[0;32mI (3579) SIP: 

SIP/2.0 100 Trying

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1317130060;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=1248911934

To: <sip:100@192.168.3.93:5060>

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 7 REGISTER

Server: YATE/6.1.0

Content-Length: 0

[0m
[0;32mI (3609) SIP: [1970-01-01/00:00:01]<<======================[0m
[0;32mI (3609) SIP: [1970-01-01/00:00:01]<<=====READ 0522 bytes==[0m
[0;32mI (3619) SIP: 

SIP/2.0 401 Unauthorized

Via: SIP/2.0/UDP 192.168.3.124:19149;branch=z9hG4bK--1317130060;rport=19149;received=192.168.3.124

From: <sip:100@192.168.3.93:5060>;tag=1248911934

To: <sip:100@192.168.3.93:5060>;tag=929509086

Call-ID: 42E3BCE9F2E33D63A9B524A3B3E67AE63E9D2B0075EA

CSeq: 7 REGISTER

WWW-Authenticate: Digest realm="Yate", nonce="d01b21bf210f5ddd15503f14dc054233.1643462366", stale=FALSE, algorithm=MD5

Server: YATE/6.1.0

Allow: ACK, INVITE, BYE, CANCEL, REGISTER, REFER, OPTIONS, INFO

Content-Length: 0

**Comment by ahhfzhang** [comment]
Hi davidHuW,

Thanks for your report!

We will fix it ASAP.

br.
