### ISSUE TITLE
pipeline_http_mp3 播放速度异常

### ISSUE THREAD

**Issue by zxxxd** [espressif/esp-adf#76]
您好，我在使用pipeline_http_mp3播放一些音频时发现前1秒的播放速度异常，它在1秒内播放了至少3秒的内容，使得实际听起来像快放一样。后续过程中还有停顿。
我注意到这一行：D (41885) ADF_BIT_STREAM: length = 2106, bytenum = 0, bread = 2106，它似乎读取了过多的流并播放了出来。不知道怎么解决这个问题。
我用的音频文件的比特率为90kbps。
下面是一些播放的log：
I (41687) HTTP_MP3_EXAMPLE: [2.0] Create audio pipeline for playback
I (41688) socket: send mp3_url queue success.
I (41695) HTTP_MP3_EXAMPLE: [2.1] Create http stream to read data
no print.
I (41707) HTTP_MP3_EXAMPLE: [2.2] Create i2s stream to write data to codec chip
no OTA_URL.
W (41716) I2S: I2S driver already installed
no OTA_port.
I (41722) HTTP_MP3_EXAMPLE: [2.3] Create mp3 decoder to decode mp3 file
no OTA_filename.
I (41730) MP3_DECODER: MP3 init
message send success.D (41735) MP3_DECODER: mp3_decoder_init
I (41740) HTTP_MP3_EXAMPLE: [2.4] Register all elements to audio pipeline
I (41748) HTTP_MP3_EXAMPLE: [2.5] Link it together http_stream-->mp3_decoder-->i2s_stream-->[codec_chip]
I (41758) HTTP_MP3_EXAMPLE: [2.6] Setup uri (http as http_stream, mp3 as mp3 decoder, and default output is i2s)
I (41769) HTTP_MP3_EXAMPLE: [ 3 ] Start and wait for Wi-Fi network
I (41776) HTTP_MP3_EXAMPLE: [ 4 ] Setup event listener
I (41781) HTTP_MP3_EXAMPLE: [4.1] Listening event from all elements of pipeline
I (41790) HTTP_MP3_EXAMPLE: [4.2] Listening event from peripherals
I (41806) HTTP_MP3_EXAMPLE: [ 5 ] Start audio_pipeline
I (41806) AUDIO_ELEMENT: [http] Element task created
I (41808) AUDIO_ELEMENT: [mp3] Element task created
I (41813) AUDIO_ELEMENT: [i2s] Element task created
I (41819) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:260, MEM Total:65908 Bytes

I (41827) AUDIO_ELEMENT: [http] AEL_MSG_CMD_RESUME,state:1
I (41836) AUDIO_ELEMENT: [mp3] AEL_MSG_CMD_RESUME,state:1
D (41840) MP3_DECODER: _mp3_decoder_open
I (41844) MP3_DECODER: MP3 opened
I (41848) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (41854) I2S_STREAM: AUDIO_STREAM_WRITER
I (41860) AUDIO_PIPELINE: Pipeline started
D (41885) ADF_BIT_STREAM: length = 2106, bytenum = 0, bread = 2106
D (41886) ADF_BIT_STREAM: length = 2106, bytenum = 2106
D (41887) MP3_DECODER: _mp3_decoder_process
D (41892) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (41896) ADF_BIT_STREAM: length = 72, bytenum = 72
I (41901) MP3_DECODER: I2S setup: sample_rate = 16000 : channels = 1
D (41908) MP3_DECODER: _mp3_decoder_process
D (41914) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (41918) ADF_BIT_STREAM: length = 72, bytenum = 72
D (41923) MP3_DECODER: _mp3_decoder_process
D (41929) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (41933) ADF_BIT_STREAM: length = 72, bytenum = 72
D (41938) MP3_DECODER: _mp3_decoder_process
D (41944) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (41948) ADF_BIT_STREAM: length = 72, bytenum = 72
D (41953) MP3_DECODER: _mp3_decoder_process
D (41959) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (41964) ADF_BIT_STREAM: length = 72, bytenum = 72
D (41969) MP3_DECODER: _mp3_decoder_process
D (41974) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (41979) ADF_BIT_STREAM: length = 72, bytenum = 72
D (41984) MP3_DECODER: _mp3_decoder_process
D (41989) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (41994) ADF_BIT_STREAM: length = 72, bytenum = 72
D (41999) MP3_DECODER: _mp3_decoder_process
D (42004) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42009) ADF_BIT_STREAM: length = 72, bytenum = 72
W (42014) HTTP_STREAM: No more data,errno:0
I (42019) AUDIO_ELEMENT: IN-[http] AEL_IO_DONE,0
I (42029) I2S: APLL: Req RATE: 16000, real rate: 15999.022, BITS: 16, CLKM: 1, BCK: 8, MCLK: 4096000.000, SCLK: 511968.718750, diva: 1, divb: 0
I (42038) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:3
I (42044) I2S_STREAM: AUDIO_STREAM_WRITER
D (42049) MP3_DECODER: _mp3_decoder_process
D (42054) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42058) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42063) MP3_DECODER: _mp3_decoder_process
D (42069) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42074) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42078) MP3_DECODER: _mp3_decoder_process
D (42084) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42089) ADF_BIT_STREAM: length = 72, bytenum = 72
i2s_stream_set_clk:0
I (42096) HTTP_MP3_EXAMPLE: [ * ] Receive music info from mp3 decoder, sample_rates=16000, bits=16, ch=1
I (42225) I2S: APLL: Req RATE: 16000, real rate: 15999.022, BITS: 16, CLKM: 1, BCK: 8, MCLK: 4096000.000, SCLK: 511968.718750, diva: 1, divb: 0
I (42228) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:3
I (42234) I2S_STREAM: AUDIO_STREAM_WRITER
D (42239) MP3_DECODER: _mp3_decoder_process
D (42244) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42249) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42254) MP3_DECODER: _mp3_decoder_process
D (42259) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42264) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42269) MP3_DECODER: _mp3_decoder_process
D (42274) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42279) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42284) MP3_DECODER: _mp3_decoder_process
D (42289) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42294) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42338) MP3_DECODER: _mp3_decoder_process
D (42340) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42340) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42342) MP3_DECODER: _mp3_decoder_process
D (42348) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42352) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42413) MP3_DECODER: _mp3_decoder_process
D (42415) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42415) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42451) MP3_DECODER: _mp3_decoder_process
D (42452) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 72
D (42452) ADF_BIT_STREAM: length = 72, bytenum = 72
D (42455) MP3_DECODER: _mp3_decoder_process
D (42461) ADF_BIT_STREAM: length = 72, bytenum = 0, bread = 54
I (42465) AUDIO_ELEMENT: IN-[mp3] AEL_IO_DONE,-2
D (42470) ADF_BIT_STREAM: length = 72, bytenum = 54
D (42526) MP3_DECODER: _mp3_decoder_process
D (42528) MP3_DECODER: _mp3_decoder_process
D (42601) MP3_DECODER: _mp3_decoder_process
D (42603) MP3_DECODER: _mp3_decoder_process
D (42676) MP3_DECODER: _mp3_decoder_process
D (42713) MP3_DECODER: _mp3_decoder_process
D (42715) MP3_DECODER: _mp3_decoder_process
D (42788) MP3_DECODER: _mp3_decoder_process
D (42790) MP3_DECODER: _mp3_decoder_process
D (42863) MP3_DECODER: _mp3_decoder_process
D (42865) MP3_DECODER: _mp3_decoder_process
D (42901) MP3_DECODER: _mp3_decoder_process
D (42903) MP3_DECODER: _mp3_decoder_process
D (42976) MP3_DECODER: _mp3_decoder_process
D (43051) MP3_DECODER: _mp3_decoder_process
D (43052) MP3_DECODER: _mp3_decoder_process
D (43126) MP3_DECODER: _mp3_decoder_process
D (43128) MP3_DECODER: _mp3_decoder_process
D (43163) MP3_DECODER: _mp3_decoder_process
D (43165) MP3_DECODER: _mp3_decoder_process
D (43238) MP3_DECODER: _mp3_decoder_process
D (43313) MP3_DECODER: _mp3_decoder_process
D (43315) MP3_DECODER: _mp3_decoder_process
D (43351) MP3_DECODER: _mp3_decoder_process
D (43352) MP3_DECODER: _mp3_decoder_process
D (43426) MP3_DECODER: _mp3_decoder_process
D (43428) MP3_DECODER: _mp3_decoder_process
D (43501) MP3_DECODER: _mp3_decoder_process
D (43502) MP3_DECODER: _mp3_decoder_process
D (43538) MP3_DECODER: _mp3_decoder_process
I (43538) MP3_DECODER: MP3 decodig done
D (43539) MP3_DECODER: _mp3_decoder_close
I (43540) MP3_DECODER: Closed
I (43838) AUDIO_ELEMENT: IN-[i2s] AEL_IO_DONE,-2
W (44063) HTTP_MP3_EXAMPLE: [ * ] Stop event received
I (44063) HTTP_MP3_EXAMPLE: [ 6 ] Stop audio_pipeline
W (44064) AUDIO_PIPELINE: There are no listener registered
I (44070) AUDIO_PIPELINE: audio_pipeline_unlinked

**Comment by jason-mao** [comment]
@zxxxd 理论上这个是存在的，因为默认I2S配置为44100Hz，而音乐是16KHz的采样率。在收到`I (42096) HTTP_MP3_EXAMPLE: [ * ] Receive music info from mp3 decoder, sample_rates=16000, bits=16, ch=1`这个的时候，才修改采样率为16k。所以你可能会听到前面声音快。
