### ISSUE TITLE
idfv4.4 and latest adf compile error (AUD-3605)

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-adf#760]
D:/project/esp32/esp-adf/components/audio_stream/pwm_stream.c: In function 'timer_group_isr':
D:/project/esp32/esp-adf/components/audio_stream/pwm_stream.c:230:25: error: 'timg_dev_t' {aka 'volatile struct timg_dev_s'} has no member named 'int_st_timers'
     if (handle->timg_dev->int_st_timers.val & BIT(handle->config.timer_num)) {
                         ^~
D:/project/esp32/esp-adf/components/audio_stream/pwm_stream.c:231:27: error: 'timg_dev_t' {aka 'volatile struct timg_dev_s'} has no member named 'int_clr_timers'; did you mean 'int_clr'?
         handle->timg_dev->int_clr_timers.val |= (1UL << handle->config.timer_num);
                           ^~~~~~~~~~~~~~
                           int_clr
D:/project/esp32/esp-adf/components/audio_stream/pwm_stream.c:234:65: error: 'volatile union <anonymous>' has no member named 'tx_alarm_en'; did you mean 'alarm_en'?
     handle->timg_dev->hw_timer[handle->config.timer_num].config.tx_alarm_en = TIMER_ALARM_EN;
                                                                 ^~~~~~~~~~~
                                                                 alarm_en
D:/project/esp32/esp-adf/components/audio_stream/pwm_stream.c: In function 'audio_pwm_set_sample_rate':
D:/project/esp32/esp-adf/components/audio_stream/pwm_stream.c:440:81: error: 'volatile union <anonymous>' has no member named 'tx_divider'; did you mean 'divider'?
     div = (uint16_t)handle->timg_dev->hw_timer[handle->config.timer_num].config.tx_divider;

**Comment by achao1104** [comment]
audio board:esp32-s2-kaluga-1 v1.2

**Comment by jason-mao** [comment]
@achao1104 Thanks for your report, please provide full log for us, thanks.

**Comment by jason-mao** [comment]
Closed, successfully build esp32-s2-kaluga board on v4.4.
