### ISSUE TITLE
如何在不用唤醒词的情况下跑wwe例子进行语音识别 (AUD-3621)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-adf#765]

**Comment by fzboffice** [comment]
也不需要按键触发 就是直接说命令

**Comment by HengYongChao** [comment]
Hi @fzboffice 

事实上，最新版本的 [esp-sr](https://github.com/espressif/esp-sr/tree/dev/2.0) 已经有这个功能了，但目前不推荐，因为通道选择不准确（双麦克会有有个通道的数据，会使用唤醒选择其中一路），后继会迭代更新。

目前实现是，使用能量选择不使用唤醒，会在 [dev/2.0](https://github.com/espressif/esp-sr/tree/dev/2.0) 上更新，准确率较唤醒会稍差一点。
