### ISSUE TITLE
idf_v3.3_freertos.patch  failed for idfv4.3.2 (AUD-3640)

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-adf#770]
Hello,

I am using adf master ad idfv4.3.2 and according to the log, I am trying to apply the patch.
if I apply idf_v3.3_freertos.patch, it reports:
error: patch failed: components/freertos/include/freertos/task.h:674
error: components/freertos/include/freertos/task.h: patch does not apply

if I apply idf_v4.4_freertos.patch,it reports:
error: patch failed: components/freertos/include/freertos/task.h:701
error: components/freertos/include/freertos/task.h: patch does not apply
error: patch failed: components/freertos/tasks.c:812
error: components/freertos/tasks.c: patch does not apply

**Comment by CAIJUN111** [comment]
I have the same problem,=====
