### ISSUE TITLE
a2dp stream destory error (AUD-3655)

### ISSUE THREAD

**Issue by Novice2Engineer** [espressif/esp-adf#773]
W (29741) AUDIO_ELEMENT: IN-[i2s_writer] AEL_IO_ABORT
I (29829) AUDIO_PIPELINE: audio_pipeline_unlinked
W (29830) AUDIO_ELEMENT: [bt_stream] Element has not create when AUDIO_ELEMENT_TERMINATE
I (29833) A2DP_STREAM: a2dp_sink_destory
E (29838) A2DP_STREAM: a2dp_queue aredy delete
W (29843) AUDIO_ELEMENT: [i2s_writer] Element has not create when AUDIO_ELEMENT_TERMINATE
E:/ESP/esp-idf/components/freertos/queue.c:1462 (xQueueGenericReceive)- assert failed!

abort() was called at PC 0x400989f5 on core 0

Backtrace:0x400951be:0x3f8209f0 0x400958b5:0x3f820a10 0x40099bde:0x3f820a30 0x400989f5:0x3f820aa0 0x400e3db5:0x3f820ae0 0x400958bd:0x3f820b10

ELF file SHA256: fc366f7b0d48b838

Rebooting...

a2dp_sink_destory()有时会出现上述问题，原因是audio_a2dp_stream_thread()还未delete，s_aadp_handler.a2dp_queue就已经被delete了。

a2dp_stream.c

line 89
        if ( pdTRUE ==  xQueueReceive (s_aadp_handler.a2dp_queue, &recv_msg, portMAX_DELAY) ) 

line 256
    if ( xQueueSend( s_aadp_handler.a2dp_queue, &destory_msg, 0 )  != pdPASS ) {
        ESP_LOGE(TAG, "Destory audio_a2dp_stream_thread failed");
        return ESP_FAIL;
    }
    s_aadp_handler.sink_stream = NULL;
    vQueueDelete(s_aadp_handler.a2dp_queue);
    ESP_LOGE(TAG, "a2dp_queue aredy delete");
    s_aadp_handler.a2dp_queue = NULL;

**Comment by HengYongChao** [comment]
Hi @Novice2Engineer 

Thanks for your report!  I will submit the bugfix as soon as possible if I confirm the issue.
