### ISSUE TITLE
Restore support for 32b audio in I2S stream (AUD-3670)

### ISSUE THREAD

**Issue by TVD-Contributor** [espressif/esp-adf#775]
Commit 6223a362f4127f2c8ac4237ba72df21b7af4255b removed support for 2-channel 32b audio. The change committed in i2s_stream.c instead forces the sample resolution back to 16b and pads with zeros. Why not retain the full 32 bits of audio? My application relied on being able to transfer all 64 bits in the I2S frame to a codec that utilises all 64 bits of data. But this change breaks my application. I do not understand the justification for this change.

**Comment by jason-mao** [comment]
@TVD-Contributor Thanks for your report,it will be fixed ASAP.
