### ISSUE TITLE
s3box、s3box_lite关于SD卡引脚(PMOD2)定义是错的 (AUD-3683)

### ISSUE THREAD

**Issue by Beanv587** [espressif/esp-adf#779]
/master/components/audio_board/esp32_s3_box_lite/board_def.h
/master/components/audio_board/esp32_s3_box/board_def.h

![11](https://user-images.githubusercontent.com/30143806/156953644-b14baf21-4dab-4176-82ef-473878fe2c04.png)
![12](https://user-images.githubusercontent.com/30143806/156953646-8ac06570-45db-496a-83da-324ff81f331d.png)

比如spi时钟引脚是GPIO12,而不是13.是不是看串了:smiley:

**Comment by jason-mao** [comment]
@Beanv587 硬件上的定义是预定义，客户自行设计的可以随意定义。我们设计的SD卡子板是按board_def.h进行定义的。

**Comment by Beanv587** [comment]
@jason-mao 嗯嗯 晓得嘞
