### ISSUE TITLE
idf v4.2.2 adf patch failed

### ISSUE THREAD

**Issue by CAIJUN111** [espressif/esp-adf#781]
![1646805291(1)](https://user-images.githubusercontent.com/96687945/157381214-8ff9e699-15e4-4d40-8ebb-1bc5ec2434b6.jpg)
![1646805268(1)](https://user-images.githubusercontent.com/96687945/157381235-725a8b8e-3057-4768-a484-b73794f80c8f.jpg)
hi/ everyone! When I run voip routines using IDF v4.2.2, patching failed. The patch I used is  idf_v4.4_freertos.patch.
I saw that  IDF v4.2.2 can patch successfully on the forum,but  I did fail .
I would be grateful if anyone could help me.

_Administrator@USER-20211223CY MINGW64 /f/CJ/Espressif/frameworks/esp-idf-v4.2.2 ((v4.2.2))
$ git apply ./idf_v4.4_freertos.patch
error: patch failed: components/freertos/include/freertos/task.h:701
error: components/freertos/include/freertos/task.h: patch does not apply
error: patch failed: components/freertos/tasks.c:812
error: components/freertos/tasks.c: patch does not apply_

**Comment by HengYongChao** [comment]
Hi @CAIJUN111 

The new MR coming soon  to fix the above situation. You can temporarily use the following patches. 

[idf_v4.2_patches.zip](https://github.com/espressif/esp-adf/files/8220000/idf_v4.2_patches.zip)

**Comment by CAIJUN111** [comment]
thanks,but&nbsp;I&nbsp;have&nbsp;uninstalled IDF V4.&nbsp;2.2.Will this patch be available in 4.3.1?








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 中午11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [espressif/esp-adf] idf v4.2.2 adf patch failed (Issue #781)





 
Hi @CAIJUN111
 
The new MR coming soon  to fix the above situation. You can temporarily use the following patches.
 
idf_v4.2_patches.zip
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CAIJUN111** [comment]
Can you give me a patch that can be installed in 4.3.1? Thank you very much
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-adf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-adf] idf v4.2.2 adf patch failed (Issue #781)





 
Hi @CAIJUN111
 
The new MR coming soon  to fix the above situation. You can temporarily use the following patches.
 
idf_v4.2_patches.zip
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HengYongChao** [comment]
Hi @CAIJUN111 ,

Try IDF V4.3 patches please, as I mentioned above, there will be an MR commit to the ADF master branch, until then, you can use the patch I sent you currently.

[idf_v4.3_patches.zip](https://github.com/espressif/esp-adf/files/8220881/idf_v4.3_patches.zip)

**Comment by CAIJUN111** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 下午2:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [espressif/esp-adf] idf v4.2.2 adf patch failed (Issue #781)





 
Hi @CAIJUN111 ,
 
Try IDF V4.3 patches please, as I mentioned above, there will be an MR commit to the ADF master branch, until then, you can use the patch I sent you currently.
 
idf_v4.3_patches.zip
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
