### ISSUE TITLE
How to use UART in ADF   (AUD-3704)

### ISSUE THREAD

**Issue by CAIJUN111** [espressif/esp-adf#785]
After reading the related ADF routines, I found that there is no UART in the audio element. How can I output the audio through the serial port?  
I am working on a project about using the SERIAL port of 4G module to output SIP audio.How can I use the serial port?

**Comment by HengYongChao** [comment]
Hi @CAIJUN111 

Sorry, there is no implementation of uart stream in ADF current.

You can imitate the i2s writer stream to write a uart stream, the behavior of these two peripherals is similar.

FYI: https://github.com/espressif/esp-adf/tree/master/components/audio_stream
