### ISSUE TITLE
What types of chips can run voip routines, except ESP32？

### ISSUE THREAD

**Issue by CAIJUN111** [espressif/esp-adf#793]
![image](https://user-images.githubusercontent.com/96687945/160227522-9984b6e0-97c0-45c9-adb8-23b04fb40b87.png)
![image](https://user-images.githubusercontent.com/96687945/160227550-8c460ab6-688f-4e86-9fac-0b94c83090ce.png)

None of the chips shown above can successfully compile routines ，except  ESP32.

**Comment by CAIJUN111** [comment]
If I use ESP32S2 or another chip to connect to ES8388, can it replace ESP32?

**Comment by HengYongChao** [comment]
Hi @CAIJUN111 

VIOP use esp-sr submodule, and esp-sr currently only supports esp32 and esp32s3 chip.

**Comment by CAIJUN111** [comment]
> Hi @CAIJUN111
> 
> VIOP use esp-sr submodule, and esp-sr currently only supports esp32 and esp32s3 chip.
> 
> So, in addition to esp32, only esps3 supports this routine.

Thanks @HengYongChao, I select chip s3 to compile the routine,it won't be sucessful
..
