### ISSUE TITLE
has delay when playing music (AUD-3747)

### ISSUE THREAD

**Issue by Bruce213** [espressif/esp-adf#797]
hi
i use adf play music demo as a network player，the pipeline as follow：
RAW_WRITE --> DECODER--> I2S_STREAM_WRITE
Some audio files have great playback delay, but the log shows that the i2S_write interface is called at the beginning, but after writing a lot of data to the i2S, the sound starts, but some audio files can play very quickly。

pls give me some help
thanks in advance.

【log】
[0;32mI (1383) AUDIO PIPELINE: audio player has been created[0m
[0;32mI (1383) AUDIO_ELEMENT: [raw-0x3f801578] Element task created[0m
[0;32mI (1393) AUDIO_THREAD: The audio_dec task allocate stack on external memory[0m
[0;32mI (1403) AUDIO_ELEMENT: [audio_dec-0x3f8016f4] Element task created[0m
[0;32mI (1403) AUDIO_ELEMENT: [i2s-0x3f801884] Element task created[0m
[0;32mI (1413) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:4307683 Bytes, Inter:329051 Bytes, Dram:269323 Bytes
[0m
[0;32mI (1423) AUDIO_ELEMENT: [audio_dec] AEL_MSG_CMD_RESUME,state:1[0m
[0;32mI (1433) MP3_DECODER: MP3 opened[0m
[0;32mI (1433) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1[0m
[0;32mI (1443) I2S_STREAM: AUDIO_STREAM_WRITER[0m
[0;32mI (1443) AUDIO_PIPELINE: Pipeline started[0m
[0;32mI (1453) BC VOIP: Raw writing...[0m
[0;32mI (1473) BC VOIP: Raw write: 1000[0m
[0;32mI (1493) BC VOIP: Raw write: 1000[0m
[0;32mI (1513) BC VOIP: Raw write: 1000[0m
[0;32mI (1533) BC VOIP: Raw write: 1000[0m
[0;32mI (1553) BC VOIP: Raw write: 1000[0m
[0;32mI (1573) BC VOIP: Raw write: 1000[0m
[0;32mI (1593) BC VOIP: Raw write: 1000[0m
[0;32mI (1613) BC VOIP: Raw write: 1000[0m
[0;32mI (1633) BC VOIP: Raw write: 1000[0m
[0;32mI (1653) BC VOIP: Raw write: 1000[0m
[0;32mI (1673) BC VOIP: Raw write: 1000[0m
[0;32mI (1693) BC VOIP: Raw write: 1000[0m
[0;32mI (1713) BC VOIP: Raw write: 1000[0m
[0;32mI (1733) BC VOIP: Raw write: 1000[0m
[0;32mI (1753) BC VOIP: Raw write: 1000[0m
[0;32mI (1773) BC VOIP: Raw write: 1000[0m
[0;32mI (1793) BC VOIP: Raw write: 1000[0m
[0;32mI (1813) BC VOIP: Raw write: 1000[0m
[0;32mI (1833) BC VOIP: Raw write: 1000[0m
[0;32mI (1853) BC VOIP: Raw write: 1000[0m
[0;32mI (1873) BC VOIP: Raw write: 1000[0m
[0;32mI (1893) BC VOIP: Raw write: 1000[0m
[0;32mI (1913) BC VOIP: Raw write: 1000[0m
[0;32mI (1933) BC VOIP: Raw write: 1000[0m
[0;32mI (1953) BC VOIP: Raw write: 1000[0m
[0;32mI (1973) BC VOIP: Raw write: 1000[0m
【from here，just have sound】

**Comment by HengYongChao** [comment]
Hi @Bruce213 

Generally speaking, after the audio data is written to i2s, there will be sound. 

Could you check whether the audio data written is muted data?

**Comment by jason-mao** [comment]
@Bruce213 So appreciate any progress from your issue.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
