### ISSUE TITLE
Audio Player delay too long (AUD-3748)

### ISSUE THREAD

**Issue by lonelyjesse** [espressif/esp-adf#798]
Hi, 
Our project is based on one of ADF demo projects, which is get-started/play_mp3_control. 
It's OK when we use the mp3 file from your project, but when it comes to our own mp3 file, which is 128kbps or 320kbps,
there is a delay. In worse situation, the delay reaches 10 seconds.
Would you please help me get out of this? It's an emergency.
I am really hope to receive your reply.

[delay_4S.txt](https://github.com/espressif/esp-adf/files/8456500/delay_4S.txt)

[music-16b-2c-44100hz.zip](https://github.com/espressif/esp-adf/files/8456503/music-16b-2c-44100hz.zip)

**Comment by lonelyjesse** [comment]
PS:
It's OK when it runs in second round.
[source_code.txt](https://github.com/espressif/esp-adf/files/8456509/source_code.txt)

**Comment by HengYongChao** [comment]
Hi @lonelyjesse 

![image](https://user-images.githubusercontent.com/4134628/163523473-06ee4505-b2f2-46b7-970a-8c3ecdd9cc4b.png)

This song has almost 2 seconds of silence data at the beginning, I still recommend you to test with different audio in #797 .
