### ISSUE TITLE
Example:wifi_bt_ble_coex issue(AUD-3751)

### ISSUE THREAD

**Issue by AdonisXie** [espressif/esp-adf#800]
Hi,
I am trying to run the routine wifi_bt_ble_coex , but there is a problem which is strange.
ESP-IDF: v4.4-329-g3c9657fa4e
OS : ubuntu 20

**The log is shown below：**

```
             ESP Audio Platform
ESP_AUDIO-v1.7.0-63-g2b9ee8e-bec4a56-4d51bc8
Compile date: Feb 23 2022-02:43:28


w(1870)BT_BTC: A2DP Enable with AVRC
I(1870) cOEX_EXAMPLE:A2DP sink user cb
I(1870) COEX_EXAMPLE: User cb A2DP event: 4
(1870) COEX_EXAWIPLE:Func:setup_player, Line:294，NEN Total:4158063 Bytes，Inter:104979 Bytes，Dran:83955BytesI
(1890)COEX_EXAMPLE: esp_audio instance is:0x3f81cad8
I(1890) COEX_EXAMPLE:[ 5 ] create audio pipeline for playback
I(1900) COEX_EXAMPLE: [5.1] Create i2s strean to read data fron codec chipE(1910)I2S:register I2s object to platforn failed

> **E(1910)I2S: register I2s object to platforn failed**
( the right log shoule be : W (2824) I2S: I2S driver already installed )

I(1910) COEX_EXAMPLE:[5.2] create hfp strean
I(1920) COEX_EXAINPLE:[5.3] Register i2s reader and hfp outgoing to audio pipeline
1(1930)COEX_EXANPLE: [5.4]Link it together [codec_chip]-->i2s_ strean_reader -->filter ->hfp_out strean--[Bluetooth]


```

The log " register I2s object to platform failed " is written in the **i2s.c**  ,  the function is : **esp_err_t i2s_driver_install** ,so it means the i2s driver doesn`t initialize in the right way.

AAAAAAnd,I am using the EspBlufi app, I can see the BLUFI_DEVICE however as soon as press "Connect" the app displays "Discover service failed"

And , I test the routine "pipeline_http_mp3"，it`s work properly, I check the code between two routines,

Here are the codes in "wifi_bt_ble_coex":
```
    ESP_LOGI(TAG, "[5.1] Create i2s stream to read data from codec chip");
    i2s_stream_cfg_t i2s_cfg = I2S_STREAM_CFG_DEFAULT();
    i2s_cfg.type = AUDIO_STREAM_READER;
#if defined CONFIG_ESP_LYRAT_MINI_V1_1_BOARD
    i2s_cfg.i2s_config.use_apll = false;
    i2s_cfg.i2s_port = 1;
#endif
    audio_element_handle_t i2s_stream_reader = i2s_stream_init(&i2s_cfg);
    
    rsp_filter_cfg_t rsp_cfg = DEFAULT_RESAMPLE_FILTER_CONFIG();
    rsp_cfg.src_rate = 44100;
    rsp_cfg.src_ch = 2;
    rsp_cfg.dest_rate = HFP_RESAMPLE_RATE;
    rsp_cfg.dest_ch = 1;
    audio_element_handle_t filter = rsp_filter_init(&rsp_cfg);
```

in "pipeline_http_mp3"

```
    ESP_LOGI(TAG, "[2.2] Create i2s stream to write data to codec chip");
    i2s_stream_cfg_t i2s_cfg = I2S_STREAM_CFG_DEFAULT();
    i2s_cfg.type = AUDIO_STREAM_WRITER;
    i2s_stream_writer = i2s_stream_init(&i2s_cfg);
```

The only difference is :
in "wifi_bt_ble_coex "  i2s_cfg.type = **AUDIO_STREAM_READER**;
in " pipeline_http_mp3 " i2s_cfg.type = **AUDIO_STREAM_WRITER**;

The initial of the i2s is almost same , but the ending is so different.

Please guide me , thanks.

**Comment by HengYongChao** [comment]
Hi @AdonisXie 

The README.MD document mentions:
>
> This example involves the coexistence of Wi-Fi, A2DP, HFP, and Bluetooth LE, so the IDF branch that optimizes coexistence is used - [audio/stack_on_psram_v3.3](https://github.com/espressif/esp-idf/tree/audio/stack_on_psram_v3.3).

Please use the stack_on_psram_v3.3 branch to compile the coex example, and try again.
