### ISSUE TITLE
 Task watchdog got triggered (AUD-3766)

### ISSUE THREAD

**Issue by Bruce213** [espressif/esp-adf#801]
Hi，
我使用VOIP Demo拨打电话，出现一下错误，声音也无法正常播放，
log如下，请帮忙分析一下，谢谢：
【LOG】
W (34895634) SIP: CHANGE STATE FROM 2, TO 16, :func: _sip_uas_process_req_invite:873
I (34896734) HW VOIP: ringing... RemotePhoneNum 200
W (34896754) SIP: CHANGE STATE FROM 16, TO 32, :func: sip_uas_process_req:942
I (34896754) HW VOIP: SIP_EVENT_AUDIO_SESSION_BEGIN
W (34896754) I2S: I2S driver already installed
I (34896754) MY_BOARD_V1_0: I2S0, MCLK output by GPIO0
I (34896764) AUDIO_PIPELINE: link el->rb, el:0x3f81d384, tag:i2s, rb:0x3f8104d8
I (34896774) AUDIO_PIPELINE: link el->rb, el:0x3f81d460, tag:filter_r, rb:0x3f810514
I (34896784) AUDIO_PIPELINE: link el->rb, el:0x3f81d5b0, tag:algo, rb:0x3f810550
I (34896784) AUDIO_PIPELINE: link el->rb, el:0x3f810118, tag:filter, rb:0x3f81058c
I (34896794) AUDIO_PIPELINE: link el->rb, el:0x3f810238, tag:sip_enc, rb:0x3f8105c8
I (34896804) AUDIO PIPELINE:  SIP recorder has been created
W (34896814) I2S: I2S driver already installed
I (34896814) MY_BOARD_V1_0: I2S0, MCLK output by GPIO0
I (34896824) AUDIO_PIPELINE: link el->rb, el:0x3f810624, tag:raw, rb:0x3f818a28
I (34896834) AUDIO_PIPELINE: link el->rb, el:0x3f810754, tag:sip_dec, rb:0x3f81aaac
I (34896834) AUDIO_PIPELINE: link el->rb, el:0x3f8108c4, tag:filter, rb:0x3f81b2ec
I (34896854) AUDIO PIPELINE: SIP player has been created
I (34896854) AUDIO_ELEMENT: [raw-0x3f810624] Element task created
I (34896864) AUDIO_THREAD: The sip_dec task allocate stack on external memory
I (34896864) AUDIO_ELEMENT: [sip_dec-0x3f810754] Element task created
I (34896874) AUDIO_THREAD: The filter task allocate stack on external memory
I (34896884) AUDIO_ELEMENT: [filter-0x3f8108c4] Element task created
I (34896894) AUDIO_ELEMENT: [i2s-0x3f818894] Element task created
I (34896894) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:4062275 Bytes, Inter:242111 Bytes, Dram:203471 Bytes

I (34896904) AUDIO_ELEMENT: [sip_dec] AEL_MSG_CMD_RESUME,state:1
I (34896914) CODEC_ELEMENT_HELPER: The element is 0x3f810754. The reserve data 2 is 0x0.
I (34896924) AUDIO_ELEMENT: [filter] AEL_MSG_CMD_RESUME,state:1
I (34896934) RSP_FILTER: sample rate of source data : 8000, channel of source data : 1, sample rate of destination data : 16000, channel of destination data : 2
I (34896944) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (34896954) I2S_STREAM: AUDIO_STREAM_WRITER
I (34896954) AUDIO_PIPELINE: Pipeline started
I (34896964) AUDIO_ELEMENT: [i2s-0x3f81d384] Element task created
I (34896964) AUDIO_THREAD: The filter_r task allocate stack on external memory
I (34896974) AUDIO_ELEMENT: [filter_r-0x3f81d460] Element task created
I (34896984) AUDIO_ELEMENT: [algo-0x3f81d5b0] Element task created
I (34896994) AUDIO_THREAD: The filter task allocate stack on external memory
I (34896994) AUDIO_ELEMENT: [filter-0x3f810118] Element task created
I (34897004) AUDIO_THREAD: The sip_enc task allocate stack on external memory
I (34897014) AUDIO_ELEMENT: [sip_enc-0x3f810238] Element task created
I (34897024) AUDIO_ELEMENT: [raw-0x3f810368] Element task created
I (34897024) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:4022075 Bytes, Inter:220143 Bytes, Dram:181503 Bytes

I (34897034) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (34897044) AUDIO_ELEMENT: [filter_r] AEL_MSG_CMD_RESUME,state:1
I (34897054) RSP_FILTER: sample rate of source data : 16000, channel of source data : 2, sample rate of destination data : 16000, channel of destination data : 1
I (34897054) AUDIO_ELEMENT: [algo] AEL_MSG_CMD_RESUME,state:1
I (34897074) AUDIO_ELEMENT: [filter] AEL_MSG_CMD_RESUME,state:1
I (34897084) RSP_FILTER: sample rate of source data : 16000, channel of source data : 1, sample rate of destination data : 8000, channel of destination data : 1
I (34897084) AUDIO_ELEMENT: [sip_enc] AEL_MSG_CMD_RESUME,state:1
I (34897104) AUDIO_PIPELINE: Pipeline started
I (34897104) SIP_RTP: receive task, local addr=192.168.2.9:31987
:1006697114) SIP_RTP: send task, remote addr=192.168.2.218
Initial ONE-MIC auido front-end for speech recognition, mode:1, (Dec 10 2021 20:29:24)
E (34902224) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (34902224) task_wdt:  - IDLE (CPU 1)
E (34902224) task_wdt: Tasks currently running:
E (34902224) task_wdt: CPU 0: IDLE
E (34902224) task_wdt: CPU 1: algo
E (34902224) task_wdt: Print CPU 0 (current core) backtrace

Backtrace:0x4013F71E:0x3FFB0850 0x4008418D:0x3FFB0870 0x401A931B:0x3FFB9A70 0x400D7BD9:0x3FFB9A90 0x40090E90:0x3FFB9AB0

E (34902224) task_wdt: Print CPU 1 backtrace

Backtrace:0x40087465:0x3FFB0E50 0x4008418D:0x3FFB0E70 0x4008B68C:0x3FFD1110 0x401210D1:0x3FFD1120 0x400DA820:0x3FFD1140 0x400DDACA:0x3FFD1160

E (34907224) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (34907224) task_wdt:  - IDLE (CPU 1)
E (34907224) task_wdt: Tasks currently running:
E (34907224) task_wdt: CPU 0: IDLE
E (34907224) task_wdt: CPU 1: afe_mase
E (34907224) task_wdt: Print CPU 0 (current core) backtrace

Backtrace:0x4013F71E:0x3FFB0850 0x4008418D:0x3FFB0870 0x401A931B:0x3FFB9A70 0x400D7BD9:0x3FFB9A90 0x40090E90:0x3FFB9AB0

E (34907224) task_wdt: Print CPU 1 backtrace

Backtrace:0x40087465:0x3FFB0E50 0x4008418D:0x3FFB0E70 0x400DA857:0x3FFD1140 0x400DDACA:0x3FFD1160

E (34912224) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (34912224) task_wdt:  - IDLE (CPU 1)
E (34912224) task_wdt: Tasks currently running:
E (34912224) task_wdt: CPU 0: IDLE
E (34912224) task_wdt: CPU 1: afe_mase
E (34912224) task_wdt: Print CPU 0 (current core) backtrace

Backtrace:0x4013F71E:0x3FFB0850 0x4008418D:0x3FFB0870 0x401A931B:0x3FFB9A70 0x400D7BD9:0x3FFB9A90 0x40090E90:0x3FFB9AB0

E (34912224) task_wdt: Print CPU 1 backtrace

Backtrace:0x40087465:0x3FFB0E50 0x4008418D:0x3FFB0E70 0x401098FB:0x3FFD10D0 0x40108DF9:0x3FFD1120 0x400DA8AA:0x3FFD1140 0x400DDACA:0x3FFD1160

I (34915554) SIP_RTP: send task stopped
I (34915584) HW VOIP: SIP_EVENT_AUDIO_SESSION_END
W (34915584) AUDIO_ELEMENT: IN-[sip_dec] AEL_IO_ABORT
W (34915584) AUDIO_ELEMENT: IN-[filter] AEL_IO_ABORT
W (34915604) AUDIO_PIPELINE: There are no listener registered
I (34915604) AUDIO_PIPELINE: audio_pipeline_unlinked
W (34915604) AUDIO_ELEMENT: [raw] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915614) AUDIO_ELEMENT: [sip_dec] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915624) AUDIO_ELEMENT: [filter] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915634) AUDIO_ELEMENT: [i2s] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915644) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (34915654) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (34915654) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (34915664) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (34915664) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (34915674) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
W (34915674) AUDIO_ELEMENT: OUT-[i2s] AEL_IO_ABORT
I (34915694) ALGORITHM_STREAM: _algo_fetch_task is stopped
afe_se_task quit
afe task destroy finished
W (34915714) AUDIO_PIPELINE: There are no listener registered
I (34915714) AUDIO_PIPELINE: audio_pipeline_unlinked
W (34915714) AUDIO_ELEMENT: [i2s] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915724) AUDIO_ELEMENT: [filter_r] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915734) AUDIO_ELEMENT: [algo] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915744) AUDIO_ELEMENT: [filter] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915754) AUDIO_ELEMENT: [sip_enc] Element has not create when AUDIO_ELEMENT_TERMINATE
W (34915764) AUDIO_ELEMENT: [raw] Element has not create when AUDIO_ELEMENT_TERMINATE
I (34915774) SIP_RTP: receive task stopped
I (34915774) SIP_RTP: RTP stopped
I (34915784) HW VOIP: SIP_EVENT_HANGUP
W (34915784) SIP: CHANGE STATE FROM 32, TO 2, :func: sip_uas_process_req:912
W (35666194) SIP: CHANGE STATE FROM 2, TO 0, :func: sip_reconnect:355
W (35667394) SIP: CHANGE STATE FROM 0, TO 1, :func: sip_connect:1674
I (35667424) HW VOIP: SIP_EVENT_REGISTERED
W (35667424) SIP: CHANGE STATE FROM 1, TO 2, :func: sip_register:1702

**Comment by HengYongChao** [comment]
Hi @Bruce213 

一般 AEC task 占用 CPU 不超过10% 除非有它的其它 task 占满 CPU 了，建议你捋顺下 系统的 task 占用情况，合理分配 CPU 任务使用。
