### ISSUE TITLE
Query: Does this ADF framework only support selected board? (AUD-3784)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-adf#806]
This is a question:

Just want to double-confirm if this ADF only support those borards released by espressif (those ones listed on home page)? Is there a chance for it to support other boards using ESP32 chip?

On the other word, does ADF rely on features/functions on board, instead of on chip? (I found function audio_board_init() is only implemented for specific board.)

**Comment by jitenshap** [comment]
https://github.com/espressif/esp-adf/issues/327

**Comment by mike-2020** [comment]
Thanks, Simple anwser, but useful.

**Comment by mike-2020** [comment]
Issue resolved.
