### ISSUE TITLE
Shortage of I2S in my use case (AUD-3786)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-adf#808]
I already have a camera which uses I2S for DMA.

I also need both audio input and output. 

Direct DAC output is not an option as the required two Pins are not exported on by board. So, I have to use the other I2S port for audio output.

It looks like this leaves me no option but have to choose audio input with ADC without I2S (without DMA).

Please share your recommendation. And question is: does ADF support ADC input without I2S?

**Comment by HengYongChao** [comment]
Hi @mike-2020 

You can refer to the official development board hardware interface design, https://docs.espressif.com/projects/esp-adf/en/latest/design-guide/dev-boards/user-guide-esp32-s3-korvo-2.html

**Comment by jason-mao** [comment]
@mike-2020 ADF does not support ADC without I2S.  Recommend use es8311 for you project. It's full-duplex for ADC and DAC with one I2S.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
