### ISSUE TITLE
Add SIP user-agent library for VoIP (AUD-607)

### ISSUE THREAD

**Issue by renne** [espressif/esp-adf#81]
The ESP32 is a great SoC for [wireless VoIP phones](https://hackaday.io/project/159811-esp32-wiphone). Please add a [IETF RFC 3261](https://tools.ietf.org/html/rfc3261)-compliant SIP user-agent library for audio handling.

**Comment by jason-mao** [comment]
@renne Cool. We are already have a  SIP demo  for internal test. 
We plan to  integrate SIP to ADF next release.

**Comment by bwannduke** [comment]
Is the SIP demo still close to release?

**Comment by tommichaud** [comment]
Jason - Any update on the SIP supported release?

**Comment by ahhfzhang** [comment]
SIP user-agent library and VoIP demo has been released.

**Comment by Niek** [comment]
Reference: https://github.com/espressif/esp-adf/tree/master/examples/advanced_examples/voip
