### ISSUE TITLE
dueros无法连接 (AUD-606)

### ISSUE THREAD

**Issue by cc1227858751** [espressif/esp-adf#82]
rst:0x1 (POWERON_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)

flash read err, 1000

ets_main.c 371 

ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)

configsip: 0, SPIWP:0xee

clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00

mode:DIO, clock div:1

load:0x3fff0018,len:4

load:0x3fff001c,len:5964

load:0x40078000,len:7892

load:0x40080000,len:5808

entry 0x40080314

[0;32mI (29) boot: ESP-IDF v3.1.1-6-g2aa9a2118-dirty 2nd stage bootloader[0m

[0;32mI (29) boot: compile time 13:16:41[0m

[0;32mI (31) boot: Enabling RNG early entropy source...[0m

[0;32mI (35) boot: SPI Speed      : 80MHz[0m

[0;32mI (39) boot: SPI Mode       : DIO[0m

[0;32mI (43) boot: SPI Flash Size : 4MB[0m

[0;32mI (47) boot: Partition Table:[0m

[0;32mI (51) boot: ## Label            Usage          Type ST Offset   Length[0m

[0;32mI (58) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m

[0;32mI (66) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m

[0;32mI (73) boot:  2 factory          factory app      00 00 00010000 00200000[0m

[0;32mI (81) boot: End of partition table[0m

[0;32mI (85) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x8fbe8 (588776) map[0m

[0;32mI (263) esp_image: segment 1: paddr=0x0009fc10 vaddr=0x3ffb0000 size=0x00400 (  1024) load[0m

[0;32mI (263) esp_image: segment 2: paddr=0x000a0018 vaddr=0x400d0018 size=0x1269b4 (1206708) map[0m

[0;32mI (616) esp_image: segment 3: paddr=0x001c69d4 vaddr=0x3ffb0400 size=0x035e8 ( 13800) load[0m

[0;32mI (621) esp_image: segment 4: paddr=0x001c9fc4 vaddr=0x3ffb39e8 size=0x00000 (     0) load[0m

[0;32mI (623) esp_image: segment 5: paddr=0x001c9fcc vaddr=0x40080000 size=0x00400 (  1024) load[0m

[0;32mI (632) esp_image: segment 6: paddr=0x001ca3d4 vaddr=0x40080400 size=0x11c28 ( 72744) load[0m

[0;32mI (665) esp_image: segment 7: paddr=0x001dc004 vaddr=0x400c0000 size=0x00000 (     0) load[0m

[0;32mI (665) esp_image: segment 8: paddr=0x001dc00c vaddr=0x50000000 size=0x00000 (     0) load[0m

[0;32mI (682) boot: Loaded app from partition at offset 0x10000[0m

[0;32mI (682) boot: Disabling RNG early entropy source...[0m

[0;32mI (683) cpu_start: Pro cpu up.[0m

[0;32mI (687) cpu_start: Starting app cpu, entry point is 0x40081174[0m

[0;32mI (0) cpu_start: App cpu up.[0m

[0;32mI (697) heap_init: Initializing. RAM available for dynamic allocation:[0m

[0;32mI (704) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m

[0;32mI (710) heap_init: At 3FFBAF90 len 00025070 (148 KiB): DRAM[0m

[0;32mI (717) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m

[0;32mI (723) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m

[0;32mI (729) heap_init: At 40092028 len 0000DFD8 (55 KiB): IRAM[0m

[0;32mI (735) cpu_start: Pro cpu start user code[0m

[0;32mI (82) cpu_start: Starting scheduler on PRO CPU.[0m

[0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m

[0;32mI (122) DUEROS: ADF version is v1.0-beta1-49-g5d73886-dirty[0m

[0;33mW (122) ESP_PERIPH: Peripherals have been initialized already[0m

[0;32mI (124) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 [0m

[0;32mI (133) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 [0m

[0;33mW (168) PERIPH_TOUCH: _touch_init[0m

[0;32mI (168) SDCARD: Trying to mount with base path=/sdcard[0m

[0;32mI (214) SDCARD: CID name SD   !

[0m

E (0,tid:3ffc9cd0) lightduer_events.c( 131):[lightduer_socket] Alloc the events resource failed!

E (340,tid:3ffc9cd0) lightduer_timers.c(  67):Memory Overflow!!!

E (343,tid:3ffc9cd0) lightduer_statistics.c( 100):Start timer failed

E (349,tid:3ffc9cd0) lightduer_ds_report.c(  55):memory overflow

I (453) wifi: wifi driver task: 3ffcb4e4, prio:23, stack:3584, core=0

E (356,tid:3ffc9cd0) lightduer_system_info.c( 731):Sys Info: Register report system dynamic function failed ret: -17

I (464) wifi: wifi firmware version: b2c9a19

I (478) wifi: config NVS flash: enabled

I (481) wifi: config nano formating: disabled

[0;32mI (485) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m

[0;32mI (495) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m

I (519) wifi: Init dynamic tx buffer num: 32

I (519) wifi: Init data frame dynamic rx buffer num: 32

I (519) wifi: Init management frame dynamic rx buffer num: 32

I (522) wifi: Init static rx buffer size: 1600

I (526) wifi: Init static rx buffer num: 10

I (530) wifi: Init dynamic rx buffer num: 32

E (433,tid:3ffc9cd0) lightduer_ds_report.c(  55):memory overflow

E (439,tid:3ffc9cd0) lightdu[0;32mI (604) phy: phy_version: 4000, b6198fa, Sep  3 2018, 15:11:06, 0, 0[0m

er_system_info.c( 736):Sys Info: Register report memory function failed ret: -17

I (605) wifi: mode : sta (24:0a:c4:9c:aa:48)

E (510,tid:3ffc9cd0) lightduer_ds_report.c(  55):memory overflow

E (514,tid:3ffc9cd0) lightduer_system_info.c( 741):Sys Info: Register report network function failed ret: -17

E (524,tid:3ffc9cd0) lightduer_ds_report.c(  55):memory overflow

E (530,tid:3ffc9cd0) lightduer_system_info.c( 746):Sys Info: Register report disk function failed ret: -17

E (539,tid:3ffc9cd0) lightduer_statistics.c( 315):Sys Info: Init system info failed ret: -17

E (548,tid:3ffc9cd0) lightduer_events.c( 131):[lightduer_ca] Alloc the events resource failed!

E (556,tid:3ffc9cd0) lightduer_connagent.c( 301):duer_initialize fail! res:-1

E (562,tid:3ffc9cd0) lightduer_ds_report.c(  55):memory overflow

E (568,tid:3ffc9cd0) lightduer_connagent.c( 306):report ca status register failed ret: -17

[0;32mI (679) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 [0m

[0;31mE (687) gpio: gpio_install_isr_service(394): GPIO isr service already installed[0m

[0;32mI (708) gpio: GPIO[21]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 [0m

[0;32mI (709) ES8388_DRIVER: init,out:02, in:00[0m

[0;32mI (718) AUDIO_HAL: Codec mode is 1, Ctrl:1[0m

[0;32mI (721) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3[0m

[0;32mI (724) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3[0m

[0;32mI (733) I2S: APLL: Req RATE: 44100, real rate: 43945.238, BITS: 16, CLKM: 1, BCK_M: 8, MCLK: 11249981.000, SCLK: 1406247.625000, diva: 1, divb: 0[0m

[0;32mI (745) AUDIO_ELEMENT: [i2s] Element task created[0m

[0;32mI (751) AUDIO_ELEMENT: [filter] Element task created[0m

[0;32mI (755) AUDIO_ELEMENT: [raw] Element task created[0m

[0;32mI (761) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:260, MEM Total:147388 Bytes

[0m

[0;32mI (769) AUDIO_PIPELINE: Pipeline started[0m

[0;32mI (769) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1[0m

[0;32mI (774) DUEROS: Recorder has been created[0m

[0;32mI (780) I2S_STREAM: AUDIO_STREAM_READER,Rate:48000,ch:2[0m

[0;33mW (785) REC_ENG: open rec_eng_2.wav failed,[293][0m

[0;32mI (793) I2S: APLL: Req RATE: 48000, real rate: 47999.961, BITS: 16, CLKM: 1, BCK_M: 8, MCLK: 12287990.000, SCLK: 1535998.750000, diva: 1, divb: 0[0m

[0;32mI (796) REC_ENG: ESP SR Engine, chunksize is 480锛?FRAME_SIZE:960, frequency:16000[0m

[0;31mE (818) REC_ENG: Recorder Engine Running ..., vad_window=9, wakeup=10000 ms, vad_off=800 ms, threshold=90 ms, sensitivity=0[0m

[0;32mI (769) AUDIO_ELEMENT: [filter] AEL_MSG_CMD_RESUME,state:1[0m

[0;32mI (829) REC_ENG: state idle[0m

[0;32mI (836) RSP_FILTER: rsp_filter_open, encoder, src:48000,2,dest:16000,1,buf_sz:6200, in_pcm:6192[0m

I (1699) wifi: n:9 0, o:1 0, ap:255 255, sta:9 0, prof:1

I (2544) wifi: state: init -> auth (b0)

I (2579) wifi: state: auth -> assoc (0)

I (2623) wifi: state: assoc -> run (10)

I (2749) wifi: connected with QJ_YJS, channel 9

I (2749) wifi: pm start, type: 1

[0;32mI (4125) event: sta ip: 192.168.31.211, mask: 255.255.255.0, gw: 192.168.31.1[0m

[0;32mI (4126) DUEROS: PERIPH_WIFI_CONNECTED [452][0m

[0;31mE (4127) DUEROS: Recv Que DUER_CMD_LOGIN[0m

[0;32mI (4132) DUEROS: duer_start, len:1470

{"configures":"{}","bindToken":"1240bb8c6921f4ec546cebbcd17cace0","coapPort":443,"token":"CdAqAuKYUuR2vHrsGNJXzu7Rmf9CYfET","serverAddr":"device.iot.baidu.com","lwm2mPort":443,"uuid":"18ec0000000001","rsaCaCrt":"-----BEGIN CERTIFICATE-----\nMIIDUDCCAjgCCQCmVPUErMYmCjANBgkqhkiG9w0BAQUFADBqMQswCQYDVQQGEwJD\nTjETMBEGA1UECAwKU29tZS1TdGF0ZTEOMAwGA1UECgwFYmFpZHUxGDAWBgNVBAMM\nDyouaW90LmJhaWR1LmNvbTEcMBoGCSqGSIb3DQEJARYNaW90QGJhaWR1LmNvbTAe\nFw0xNjAzMTEwMzMwNDlaFw0yNjAzMDkwMzMwNDlaMGoxCzAJBgNVBAYTAkNOMRMw\nEQYDVQQIDApTb21lLVN0YXRlMQ4wDAYDVQQKDAViYWlkdTEYMBYGA1UEAwwPKi5p\nb3QuYmFpZHUuY29tMRwwGgYJKoZIhvcNAQkBFg1pb3RAYmFpZHUuY29tMIIBIjAN\nBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtbhIeiN7pznzuMwsLKQj2xB02+51\nOvCJ5d116ZFLjecp9qtllqOfN7bm+AJa5N2aAHJtsetcTHMitY4dtGmOpw4dlGqx\nluoz50kWJWQjVR+z6DLPnGE4uELOS8vbKHUoYPPQTT80eNVnl9S9h/l7DcjEAJYC\nIYJbf6+K9x+Ti9VRChvWcvgZQHMRym9j1g/7CKGMCIwkC+6ihkGD/XG40r7KRCyH\nbD53KnBjBO9FH4IL3rGlZWKWzMw3zC6RTS2ekfEsgAtYDvROKd4rNs+uDU9xaBLO\ndXTl5uxgudH2VnVzWtj09OUbBtXcQFD2IhmOl20BrckYul+HEIMR0oDibwIDAQAB\nMA0GCSqGSIb3DQEBBQUAA4IBAQCzTTH91jNh/uYBEFekSVNg1h1kPSujlwEDDf/W\npjqPJPqrZvW0w0cmYsYibNDy985JB87MJMfJVESG/v0Y/YbvcnRoi5gAenWXQNL4\nh2hf08A5wEQfLO/EaD1GTH3OIierKYZ6GItGrz4uFKHV5fTMiflABCdu37ALGjrA\nrIjwjxQG6WwLr9468hkKrWNG3dMBHKvmqO8x42sZOFRJMkqBbKzaBd1uW4xY5XwM\nS1QX56tVrgO0A3S+4dEg5uiLVN4YVP/Vqh4SMtYkL7ZZiZAxD9GtNnhRyFsWlC2r\nOVSdXs1ttZxEaEBGUl7tgsBte556BIvufZX+BXGyycVJdBu3\n-----END CERTIFICATE-----\n","macId":"","version":11662}[0m

E (4162,tid:3ffc9cd0) lightduer_connagent.c( 331):memory alloc fail!

I (4169,tid:3ffc9cd0) lightduer_ds_log_cache.c(  45):cached tracecode: 0x12010400

**Comment by cc1227858751** [comment]
不止我一个人出现这问题吧，求助啊

**Comment by jason-mao** [comment]
@cc1227858751 请参考dueros 下的sdkconfig.defaults.

```c
CONFIG_SPIRAM_BOOT_INIT=y
CONFIG_SPIRAM_USE_MALLOC=y
CONFIG_SPIRAM_TYPE_ESPPSRAM32=y
CONFIG_SPIRAM_SIZE=4194304
CONFIG_SPIRAM_SPEED_80M=y
CONFIG_SPIRAM_MEMTEST=y
CONFIG_SPIRAM_CACHE_WORKAROUND=y
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
```

> E (4162,tid:3ffc9cd0) lightduer_connagent.c( 331):memory alloc fail!

是由于你没有打开PSRAM导致申请内存失败。

**Comment by cc1227858751** [comment]
> @cc1227858751 请参考dueros 下的sdkconfig.defaults.
> 
> ```c
> CONFIG_SPIRAM_BOOT_INIT=y
> CONFIG_SPIRAM_USE_MALLOC=y
> CONFIG_SPIRAM_TYPE_ESPPSRAM32=y
> CONFIG_SPIRAM_SIZE=4194304
> CONFIG_SPIRAM_SPEED_80M=y
> CONFIG_SPIRAM_MEMTEST=y
> CONFIG_SPIRAM_CACHE_WORKAROUND=y
> CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
> ```
> 
> > E (4162,tid:3ffc9cd0) lightduer_connagent.c( 331):memory alloc fail!
> 
> 是由于你没有打开PSRAM导致申请内存失败。

不好意思，如何打开PSRAM呢，在munuconfig中吗？

**Comment by jason-mao** [comment]
run command: `make menuconfig`, select item like follow:`Component config`-> `ESP32-specific`->`Support for external, SPI-connected RAM`.

**Comment by cc1227858751** [comment]
> run command: `make menuconfig`, select item like follow:`Component config`-> `ESP32-specific`->`Support for external, SPI-connected RAM`.

已解决，多谢！
