### ISSUE TITLE
当我在运行spiffs_amr_resample_example例程的时候发现播放的音频声音几乎听不见 (AUD-3820)

### ISSUE THREAD

**Issue by geekheart** [espressif/esp-adf#820]
![image](https://user-images.githubusercontent.com/68679210/168421735-ff4dd0de-cff6-42f5-ab31-557391ec176b.png)
运行都很正常，我在lyrat 4.3上运行该例程，编译都没问题，录音下来后播放声音特别小，耳朵趴在喇叭上才听得见。我此前运行过play_mp3_example我确认我的喇叭部分可以正常工作

**Comment by HengYongChao** [comment]
HI @geekheart 

你可以使用相同的硬件和软件环境，测试下 [example/recorder](https://github.com/espressif/esp-adf/tree/master/examples/recorder) 下面的其他录音例程， 看看是否音响仍然很小呢？ 做对比测试验证下。

**Comment by jason-mao** [comment]
@geekheart 你这个问题怎么样了？如果有需要进一步的帮助敬请联系我们。

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
