### ISSUE TITLE
关于pipeline_aws_polly产生的错误 (AUD-3836)

### ISSUE THREAD

**Issue by HongYan12345** [espressif/esp-adf#827]
<img width="581" alt="01" src="https://user-images.githubusercontent.com/106100576/169860911-0edd5e9e-f265-4198-87e4-12dd18eaadeb.png">
<img width="571" alt="02" src="https://user-images.githubusercontent.com/106100576/169860926-2f2d4ac4-950b-4100-838f-86dc80c24f9b.png">
我在运行examples里面的examples/cloud_services/pipeline_aws_polly_mp3出现错误
我没有修改例子代码里面的任何东西，我在menuconfig里面设置了wifi密码和aws账号和密码，最后运行卡在了这里，这个错误是因为什么引起的呢？代码里面有哪些地方还需要改的吗？

**Comment by HengYongChao** [comment]
Hi @HongYan12345 

HTTP 返回的错误码是 403（禁止访问），检查下你的 aws账号和密码是否正确。

第二张图是退出当前例程，WiFi 资源被 destroy 掉了。

**Comment by HongYan12345** [comment]
> Hi @HongYan12345
> 
> HTTP 返回的错误码是 403（禁止访问），检查下你的 aws账号和密码是否正确。
> 
> 第二张图是退出当前例程，WiFi 资源被 destroy 掉了。

我是第一次使用aws，昨天刚创建出来，我不知道是不是直接用我注册的邮箱和密码放到代码里面，还是说要在aws网站里重新申请个密钥什么的吗？

**Comment by HengYongChao** [comment]
> > Hi @HongYan12345
> > HTTP 返回的错误码是 403（禁止访问），检查下你的 aws账号和密码是否正确。
> > 第二张图是退出当前例程，WiFi 资源被 destroy 掉了。
> 
> 我是第一次使用aws，昨天刚创建出来，我不知道是不是直接用我注册的邮箱和密码放到代码里面，还是说要在aws网站里重新申请个密钥什么的吗？

把申请的密钥放在 `menuconfig` 配置里， [README.md](https://github.com/espressif/esp-adf/blob/master/examples/cloud_services/pipeline_aws_polly_mp3/README_CN.md) 文档已经提供了步骤，照着操作。

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
