### ISSUE TITLE
Latest version of sip.h doesn't have SIP_EVENT_BUSY (AUD-3838)

### ISSUE THREAD

**Issue by Hasaken** [espressif/esp-adf#828]
Hi ESP-ADF Team.

The latest version of sip.h doesn't have SIP_EVENT_BUSY in sip_event_t struct. It was in previous versions and is useful event.
Please add it there.

**Comment by ahhfzhang** [comment]
Hi @Hasaken,

It has been replaced by SIP_EVENT_ERROR.
