### ISSUE TITLE
关于边录边播的问题

### ISSUE THREAD

**Issue by constcharp** [espressif/esp-adf#84]
我的做法是：
I2S_NUM_0：负责从sd卡中读取MP3数据并播放。
I2S_NUM_1：负责采集收录的音频并保存到SD卡中。
流程：先进行配置初始化，随后启用播放线程进程播放，播放一段时间后开启录音线程。
现象：开启录音后播放有明显卡顿，最终的录音文件为尖锐的噪音。去掉扬声器，收录的同样是纯噪音。
请问我的做法是否正确，软硬件能够支持吗？

**Comment by jason-mao** [comment]
@constcharp 你的做法是支持的。你独立的录音，放音都正常吗？多路操作SDcard的时候，注意提高SDCARD的总线频率。
