### ISSUE TITLE
esp32  A1S kit pipeline_a2dp_sink_stream 有声音但是不正常只有突突声 (AUD-3932)

### ISSUE THREAD

**Issue by myzhang001** [espressif/esp-adf#845]
硬件：AIthinker esp32  A1S 开发板

问题：pipeline_a2dp_sink_stream 有声音但是不正常只有突突声

当前状态：
按照安信可的修改指引当前使用  pipeline_http_select_decoder  例程 可以正常使用声音也正常，说明驱动修改正确

**Comment by HengYongChao** [comment]
Hi @myzhang001 

测试的手机型号是安卓吗？ 有没有使用 IOS 手机对比测试下？ 歌曲音源是正常的吗

**Comment by myzhang001** [comment]
1.测试使用的是小米11pro 手机

**Comment by jason-mao** [comment]
@myzhang001 这个问题怎么样了？

**Comment by myzhang001** [comment]
没有解决

**Comment by jason-mao** [comment]
> 没有解决

我们用你说的手机，Lyrat v4.3开发板，测试这个example，没有复现到你的情况。你可以做以下验证：
- AIthinker esp32 A1S 板子把蓝牙传过来音频数据存为文件，在电脑上看是否能播放。
- 如果数据正常则检查I2S 配置以及AIthinker esp32 A1S DAC 配置。否则需要检查蓝牙接收侧的情况。

**Comment by myzhang001** [comment]
感谢解答
