### ISSUE TITLE
语音识别和语音合成模型存放在U盘读取 (AUD-3971)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-adf#855]
你好，我使用的是esp32_s3_korvo2_v3板子，通过使用外部PARAM将flash映射成U盘。
我希望通过U盘读写语音识别和语音合成的模型，请问语音识别和语音合成的模型是否支持通过U盘读取。
如果可以的话，请问如何操作呢

**Comment by jason-mao** [comment]
@Zhengqinze05 暂时还不支持从U盘读取。
