### ISSUE TITLE
ESP-ADF getting started project build error   (AUD-3981)

### ISSUE THREAD

**Issue by alibukharai** [espressif/esp-adf#859]
----------------------------- Delete above -----------------------------

## Environment

- Audio development kit:      ESP32-LyraT 4.3
- Operating system:     Windows 10

## Problem Description

I am new to LyraT board. I am trying to run the getting started commands from documents, it gives me a strange error related to cmake. I have attached a screenshot.  
![image](https://user-images.githubusercontent.com/60029742/182044511-32371c6c-5252-4d9a-aef4-16a96e1ce7bf.png)

### Code to Reproduce This Issue

in Cmd 

cd C:\esp
git clone --recursive https://github.com/espressif/esp-adf.git   or 
git clone --recursive https://gitee.com/EspressifSystems/esp-adf.git 
set ADF_PATH=C:\esp\esp-adf
echo %ADF_PATH%

in idfcmd 

C:\esp\esp-idf\export.bat
cd C:\esp
xcopy /e /i C:\esp\esp-adf\examples\get-started\play_mp3_control

cd C:\esp\play_mp3_control
idf.py set-target esp32
idf.py menuconfig

**Comment by jason-mao** [comment]
@alibukharai I not have found any problems as your commands, did you saw right path with `echo %ADF_PATH%`and `echo %IDF_PATH%` before `idf.py set-target esp32`?

**Comment by alibukharai** [comment]
> @alibukharai I not have found any problems as your commands, did you saw right path with `echo %ADF_PATH%`and `echo %IDF_PATH%` before `idf.py set-target esp32`?

after restarting the system this problem is solved

**Comment by jason-mao** [comment]
@alibukharai Thanks for your reply.
