### ISSUE TITLE
ESP32-LyraTD-MSC这块板子有接dueros的SDK或者例程吗？

### ISSUE THREAD

**Issue by cc1227858751** [espressif/esp-adf#86]
如题

**Comment by Chenzejun-Dummkopf** [comment]
那块圆形的黑色板子吗？

**Comment by cc1227858751** [comment]
> 那块圆形的黑色板子吗？

是的

**Comment by Chenzejun-Dummkopf** [comment]
不过我木有额，那个圆板挺贵的

**Comment by cc1227858751** [comment]
> 不过我木有额，那个圆板挺贵的

299，确实有点贵。

**Comment by Chenzejun-Dummkopf** [comment]
淘宝买的话，应该是有SDK给的吧，你可以问问客服

**Comment by jason-mao** [comment]
https://github.com/espressif/esp-adf/tree/master/examples/asr, 可以先看下这个例子程序，LyraTD-MSC的DuerOS版本会在下个release 版本发布。

**Comment by Chenzejun-Dummkopf** [comment]
@jason-mao 请问下个release版本什么时候发布？ 是针对 LyraTD-MSC 平台的吗？

**Comment by jason-mao** [comment]
@Chenzejun-Dummkopf 预计会在3月中旬，是的，会支持LyraTD-MSC.

**Comment by Chenzejun-Dummkopf** [comment]
@jason-mao  好的，了解，多谢 👍

**Comment by cc1227858751** [comment]
> @Chenzejun-Dummkopf 预计会在3月中旬，是的，会支持LyraTD-MSC.

多谢！
