### ISSUE TITLE
Error in cloning ESP-ADF (AUD-3982)

### ISSUE THREAD

**Issue by alibukharai** [espressif/esp-adf#860]
## Environment

- Audio development kit:      [ESP32-LyraT|
- Operating system:     Windows10

## Problem Description

during the installation and cloning process of ADF, there shows an error. I have attached a screenshot.

### Steps to Reproduce

1. git clone --recursive https://github.com/espressif/esp-adf.git

![image](https://user-images.githubusercontent.com/60029742/182045721-9a6b5fda-6cc8-439c-a55e-0f460f9cca37.png)

**Comment by jason-mao** [comment]
@alibukharai It's looks like can't connect to GitHub server. Can you open GitHub in your browser？

**Comment by alibukharai** [comment]
> 

yes I resolved the issue by setting IP address

**Comment by jason-mao** [comment]
@alibukharai Thanks for your update.
