### ISSUE TITLE
wwe工程不用唤醒词不能进行英文语音识别吗 (AUD-4000)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-adf#864]
你好，我使用的是esp32_s3_korvo2_v3的板子，IDF的版本是idf4.4
我想使用英文语音识别，并且不使用唤醒词，但是我在menuconfig中发现关闭了唤醒词。并且选择了英文语音识别，它没有英文的关键词模型选择
![image](https://user-images.githubusercontent.com/92145359/183885637-ef3c5277-9f6c-4c34-886e-84db65a56406.png)

**Comment by jason-mao** [comment]
@Zhengqinze05 你说的情况可以在 1mic 的情况下使用。但不推荐。

**Comment by Zhengqinze05** [comment]
我目前是使用1mic的，请问如何开启呢，有什么风险吗

**Comment by jason-mao** [comment]
参考[esp_afe_config.h](https://github.com/espressif/esp-sr/blob/98900ad8ef5c24f95a31fca22e331634627c7338/include/esp32s3/esp_afe_config.h#L77)。识别效果不理想。

**Comment by Zhengqinze05** [comment]
具体如何操作呢，我是使用的adf版本里面的esp-sr库，没有esp_afe_config.h这个文件，在adf版本里，我使用menuconfig关闭了唤醒词，在wwe工程中#define WAKENET_ENABLE      (false) ，然而提示我
wakenet is NULL, please use set_wakenet function to set wakenet.并且说出关键词也没有反应
![image](https://user-images.githubusercontent.com/92145359/185336510-89a77391-3a3d-4f5a-b15d-380a9a8d7e26.png)
请问还需要修改什么地方吗
