### ISSUE TITLE
PLAY MUTIPLE FILE MP3

### ISSUE THREAD

**Issue by quoctrung99** [espressif/esp-adf#866]
I have a problem with run mutiple file mp3 esp adf. 
please help me

**Comment by jason-mao** [comment]
@quoctrung99 Please add more information for your issue, such as what is file? how to play?

**Comment by quoctrung99** [comment]
For example i have 3 mp3 files,  I need to read each file in turn.

**Comment by jason-mao** [comment]
@quoctrung99 What kind of behavior do you expect？

**Comment by quoctrung99** [comment]
i'm following the example play_mp3_control_example.c

**Comment by quoctrung99** [comment]
i need to concatenate all mp3 files to play. For example I have a number as input: 101. I need play file1 ->file0->file1

**Comment by jason-mao** [comment]
Can there be silence between file1 and file0?

**Comment by quoctrung99** [comment]
yes it is possible

**Comment by and-elf** [comment]
Use a playlist?

**Comment by quoctrung99** [comment]
yes, please help me

**Comment by and-elf** [comment]
Have you looked at this example: https://github.com/espressif/esp-adf/blob/master/examples/player/pipeline_sdcard_mp3_control/main/play_sdcard_mp3_control_example.c You'll also have to learn how to use the playlist API. Basically create a playlist and then add paths to it based on command/user input. Have you written the parser (code that handles input)? Split a string into characters and then use sprintf () to turn them into file names should be easy enough
