### ISSUE TITLE
请问播放多个MP3文件并输出到BT？ (AUD-4014)

### ISSUE THREAD

**Issue by monets** [espressif/esp-adf#867]
你好，我这边的板子是eso32_lyraT v4.3,有个项目需求是播放Sd卡内MP3文件，并不是全部，是指定几个文件，我这边参考了例程play_a2dp_source_stream。但无法做到播放完一个MP3文件后，接着播放下一个文件，总是会报一个[ * ] Bluetooth disconnected or suspended cmd，直接断开了。
请问怎么才能做到，SD卡内指定多个MP3文件，并不断开蓝牙，直到收到指定命令才断开？

**Comment by jason-mao** [comment]
@monets pipeline_a2dp_source_stream 在结束的时候会audio_pipeline_terminate 断开bt stream。你的应用，建议file->mp3 一 个pipeline，bt stream 已element 的形式控制。两者之间的数据连接添加 mp3 decoder 的 write callback实现。
