### ISSUE TITLE
语音识别内存可不可以放在外部内存 (AUD-4016)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-adf#868]
你好，我使用的是esp32_s3_korvo2_v3板子，使用语音识别时，会有内存不足的问题，语音识别模型加载时，好像会占用100k的内部内存，请问这部分可以放在外部内存吗，因为我用了蓝牙wifi以及其他一些占用内存的线程，这100k的内部内存会导致我内部内存不足，请问有什么方法可以避免或者可以直接使用外部内存加载模型吗

**Comment by jason-mao** [comment]
不能放在外部，你要尽可能的将其他应用层代码放置在psram，将`CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=2048`先试试。
