### ISSUE TITLE
如何利用ESP32 lyrat下载dueros返回的url中的mp3文件？

### ISSUE THREAD

**Issue by Chenzejun-Dummkopf** [espressif/esp-adf#87]
大家好，我在esp32外接了自己的codec解码器，想请问下如何利用esp32下载dueros返回的url中的mp3文件，以便我播放使用。
核心问题就是：如何利用esp32下载mp3文件？
谢谢大家

**Comment by jason-mao** [comment]
@Chenzejun-Dummkopf 请参考这个示例https://github.com/espressif/esp-adf/tree/master/examples/advanced_examples/http_play_and_save_to_file
