### ISSUE TITLE
VoIP Integrate AT Module get “ERROR! rb_in slow!” (AUD-4020)

### ISSUE THREAD

**Issue by wenxiao11** [espressif/esp-adf#870]
## Environment

- Audio development kit: ESP32-LyraT
- Audio kit version: v4.3
- Module or chip used:  ESP32-WROVER-E
- IDF version: v4.4 (The version inside ADF folder)
- ADF version: v2.4 Released
- Build system: idf.py
- Operating system: Windows
- Environment type: PowerShell
- Power supply: USB

## Problem Description

I try to combine VoIP example with ESP AT Commands, and there are some conflicts. The voip code is the sample code in ADF. I add the `esp_at_module_init()` at the beginning of main. It will cause the ringbuffer problem after the audio pipeline is created. If I comment the code related to `player_pipeline_open()`, the audio pipeline works correctly without speaker. The original VoIP code works correctly.

### Expected Behavior

Making calls correctly

### Actual Behavior

Ring buffer errors

### Code to Reproduce This Issue

```cpp

void app_main()
{
#ifdef CONFIG_IDF_TARGET_ESP32
    at_disable_rtc_wdt();
#endif
    esp_at_module_init(CONFIG_AT_SOCKET_MAX_CONN_NUM, 0);  // reserved one for server
    esp_log_level_set("*", ESP_LOG_INFO);
    media_lib_add_default_adapter();
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES) {
        // NVS partition was truncated and needs to be erased
        // Retry nvs_flash_init
        ESP_ERROR_CHECK(nvs_flash_erase());
        err = nvs_flash_init();
    }
    ESP_ERROR_CHECK(err);
#if (ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(4, 1, 0))
    ESP_ERROR_CHECK(esp_netif_init());
#else
    tcpip_adapter_init();
#endif

    ESP_LOGI(TAG, "[1.0] Initialize peripherals management");
    esp_periph_config_t periph_cfg = DEFAULT_ESP_PERIPH_SET_CONFIG();
    esp_periph_set_handle_t set = esp_periph_set_init(&periph_cfg);

    ESP_LOGI(TAG, "[1.1] Initialize and start peripherals");
    audio_board_key_init(set);
#ifdef DEBUG_AEC_INPUT
    audio_board_sdcard_init(set, SD_MODE_1_LINE);
#endif

    ESP_LOGI(TAG, "[1.2] Create and start input key service");
    input_key_service_info_t input_key_info[] = INPUT_KEY_DEFAULT_INFO();
    input_key_service_cfg_t input_cfg = INPUT_KEY_SERVICE_DEFAULT_CONFIG();
    input_cfg.handle = set;
    input_cfg.based_cfg.task_stack = 4 * 1024;
    periph_service_handle_t input_ser = input_key_service_create(&input_cfg);

#ifdef FUNC_SYS_LEN_EN
    ESP_LOGI(TAG, "[ 1.3 ] Create display service instance");
    disp = audio_board_led_init();
#endif

    ESP_LOGI(TAG, "[ 2 ] Start codec chip");
    audio_board_handle_t board_handle = audio_board_init();
    audio_hal_ctrl_codec(board_handle->audio_hal, AUDIO_HAL_CODEC_MODE_BOTH, AUDIO_HAL_CTRL_START);
    audio_hal_set_volume(board_handle->audio_hal, 55);

    input_key_service_add_key(input_ser, input_key_info, INPUT_KEY_NUM);
    periph_service_set_callback(input_ser, input_key_service_cb, (void *)board_handle);
	
    ESP_LOGI(TAG, "[ 3 ] Initialize tone player");
    //audio_player_int_tone_init();

    ESP_LOGI(TAG, "[ 4 ] Create Wi-Fi service instance");
    setup_wifi();
}

```

## Debug Logs

<Pre>
I (33298) VOIP_EXAMPLE: SIP_EVENT_AUDIO_SESSION_BEGIN
I (33298) I2S: APLL expected frequency is 8192000 Hz, real frequency is 8191999 Hz
I (33308) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (33318) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (33328) I2S: I2S0, MCLK output by GPIO0
I (33328) LYRAT_V4_3: I2S0, MCLK output by GPIO0
I (33338) AUDIO_PIPELINE: link el->rb, el:0x3f818174, tag:i2s, rb:0x3f819dd4
I (33348) AUDIO_PIPELINE: link el->rb, el:0x3f8182e8, tag:filter_r, rb:0x3f81be14
I (33348) AUDIO_PIPELINE: link el->rb, el:0x3f818438, tag:algo, rb:0x3f81e654
I (33358) AUDIO_PIPELINE: link el->rb, el:0x3f819a04, tag:filter, rb:0x3f820694
I (33368) AUDIO_PIPELINE: link el->rb, el:0x3f819b34, tag:sip_enc, rb:0x3f820ed4
I (33378) VOIP_EXAMPLE:  SIP recorder has been created
E (33378) I2S: register I2S object to platform failed
I (33388) I2S: I2S0, MCLK output by GPIO0
I (33388) LYRAT_V4_3: I2S0, MCLK output by GPIO0
I (33398) AUDIO_PIPELINE: link el->rb, el:0x3f821734, tag:raw, rb:0x3f821d04
I (33408) AUDIO_PIPELINE: link el->rb, el:0x3f821864, tag:sip_dec, rb:0x3f823d44
I (33408) AUDIO_PIPELINE: link el->rb, el:0x3f8219d8, tag:filter, rb:0x3f824584
I (33428) VOIP_EXAMPLE: SIP player has been created
I (33428) AUDIO_PIPELINE: start el[             raw], linked:1, state:1,[0x3f821734],
I (33438) AUDIO_ELEMENT: [raw-0x3f821734] Element task created
I (33438) AUDIO_PIPELINE: start el[         sip_dec], linked:1, state:1,[0x3f821864],
I (33448) AUDIO_THREAD: The sip_dec task allocate stack on external memory
I (33458) AUDIO_ELEMENT: [sip_dec-0x3f821864] Element task created
I (33468) AUDIO_PIPELINE: start el[          filter], linked:1, state:1,[0x3f8219d8],
I (33468) AUDIO_THREAD: The filter task allocate stack on external memory
I (33478) AUDIO_ELEMENT: [filter-0x3f8219d8] Element task created
I (33488) AUDIO_PIPELINE: start el[             i2s], linked:1, state:1,[0x3f821b70],
I (33498) AUDIO_ELEMENT: [i2s-0x3f821b70] Element task created
I (33498) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:4101267 Bytes, Inter:155639 Bytes, Dram:121399 Bytes

I (33518) AUDIO_ELEMENT: [sip_dec] AEL_MSG_CMD_RESUME,state:1
I (33518) CODEC_ELEMENT_HELPER: The element is 0x3f821864. The reserve data 2 is 0x0.
I (33528) AUDIO_ELEMENT: [filter] AEL_MSG_CMD_RESUME,state:1
I (33548) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (33548) I2S_STREAM: AUDIO_STREAM_WRITER
I (33548) AUDIO_PIPELINE: Pipeline started
I (33548) AUDIO_PIPELINE: start el[             i2s], linked:1, state:1,[0x3f818174],
I (33558) AUDIO_ELEMENT: [i2s-0x3f818174] Element task created
I (33568) AUDIO_PIPELINE: start el[        filter_r], linked:1, state:1,[0x3f8182e8],
I (33578) AUDIO_THREAD: The filter_r task allocate stack on external memory
I (33578) AUDIO_ELEMENT: [filter_r-0x3f8182e8] Element task created
I (33588) AUDIO_PIPELINE: start el[            algo], linked:1, state:1,[0x3f818438],
I (33598) AUDIO_THREAD: The algo task allocate stack on external memory
I (33608) AUDIO_ELEMENT: [algo-0x3f818438] Element task created
I (33608) AUDIO_PIPELINE: start el[          filter], linked:1, state:1,[0x3f819a04],
I (33618) AUDIO_THREAD: The filter task allocate stack on external memory
I (33628) AUDIO_ELEMENT: [filter-0x3f819a04] Element task created
I (33638) AUDIO_PIPELINE: start el[         sip_enc], linked:1, state:1,[0x3f819b34],
I (33638) AUDIO_THREAD: The sip_enc task allocate stack on external memory
I (33648) AUDIO_ELEMENT: [sip_enc-0x3f819b34] Element task created
I (33658) AUDIO_PIPELINE: start el[             raw], linked:1, state:1,[0x3f819c64],
I (33668) AUDIO_ELEMENT: [raw-0x3f819c64] Element task created
I (33668) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:3815911 Bytes, Inter:149463 Bytes, Dram:115223 Bytes

I (33688) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (33688) AUDIO_ELEMENT: [filter_r] AEL_MSG_CMD_RESUME,state:1[0m
I (33698) RSP_FILTER: sample rate of source data : 8000, channel of source data : 1, sample rate of destination data : 16000, channel of destination data : 2
 (33698)RSP_FLTER: sample rate ofsource data : 16000, channel ofsouce data : 2, sampe rae f estination data : 6000, channl of dstinatio data : 1
I (33698) AUDIO_ELEMENT: [algo] AEL_MSG_CMD_RESUME,state:1
I (33738) AUDIO_ELEMENT: [filter] AEL_MSG_CMD_RESUME,state:1
I (33738) RSP_FILTER: sample rate of source data : 16000, channel of source data : 1, sample rate of destination data : 8000, channel of destination data : 1
I (33758) AUDIO_ELEMENT: [sip_enc] AEL_MSG_CMD_RESUME,ste:1
I (33768) AUDIO_PIPELINE: Pipeline started
I (33768) SIP_RTP: receive task, local addr=10.0.28.110:35728
:1357868) SIP_RTP: send task, remote addr=34.203.251.129
Initial ONE-MIC auido front-end for speech recognition, mode:1, (Dec 10 2021 20:29:24)
I (33898) AUDIO_THREAD: The algo_fetchtask allocate stack on external memory
ERROR! rb_in slow!!!
ERROR! rb_in slow!!!
ERROR! rb_in slow!!!
ERROR! rb_in slow!!!
</Pre>

**Comment by jason-mao** [comment]
@wenxiao11  `ERROR! rb_in slow!!!` is your ringbuffer problem?
If yes, there is some misunderstanding. `ERROR! rb_in slow!!!` is come from AFE module, it means that CPU is busy. I suggest you checked two core CPU loading and make them balance running.
