### ISSUE TITLE
Add context option to SIP Event Handler  (AUD-4070)

### ISSUE THREAD

**Issue by sidwarkd** [espressif/esp-adf#871]
With almost all of the built-in services in ESP-IDF the callback event handlers have a concept of being able to pass a context object to the event handler in the form of a void*. The `sip_config_t` allows you to specify the event_handler but there is no way to pass a context object to be passed into that handler. This would be incredibly useful while also following the pattern of most other event handlers in the Espressif ecosystem.

**Comment by jason-mao** [comment]
Thanks for your suggestion, let me check it.
