### ISSUE TITLE
voip通话工程中，mic不能正常工作 (AUD-4046)

### ISSUE THREAD

**Issue by hnhkj** [espressif/esp-adf#876]
https://github.com/espressif/esp-adf/issues/872
根据这个bug，我对esp-sr进行了更新，编译可以顺利通过。但是通话的时候，mic功能不正常，不能正常通话。

**Comment by jason-mao** [comment]
@hnhkj 感谢您反馈的问题。新的 esp-sr 与 VoIP 的适配工作还有部分正在进行中，我们会尽快提交。

**Comment by jason-mao** [comment]
@hnhkj Please test with 619a9055b153ba037052c01802defbba66c03c0a

**Comment by hnhkj** [comment]
> @hnhkj Please test with [619a905](https://github.com/espressif/esp-adf/commit/619a9055b153ba037052c01802defbba66c03c0a)

success, thanks
