### ISSUE TITLE
Allow option to change OPTIONS ping interval to PBX server (AUD-4060)

### ISSUE THREAD

**Issue by sidwarkd** [espressif/esp-adf#878]
In testing the SIP client included in the ADF I have found that the client sends an OPTIONS packet to the PBX every 32 seconds. For performance reasons on the PBX-side it would be very useful to be able to specify a different interval.

## Request
Allow a different OPTIONS ping interval to be passed to the SIP client via the `sip_config_t` struct.

**Comment by jason-mao** [comment]
Thanks for your suggestion, we will handle it.
