### ISSUE TITLE
"algorithm_mono_fix" function not found (AUD-4068)

### ISSUE THREAD

**Issue by Hasaken** [espressif/esp-adf#880]
VOIP example in the latest version of ADF has "algorithm_mono_fix" function calls and it causes "implicit declaration of function" error.

Could you please re-check it?

**Comment by jason-mao** [comment]
@Hasaken I have not reproduced your issue on latest version of ADF with target esp32 and esp32s3. Please double check your environment .

**Comment by Hasaken** [comment]
Yes, it works.
Thank you.
