### ISSUE TITLE
components/esp_peripherals/lib/blufi/blufi_security.c:45:10: fatal error: esp32s2beta/rom/crc.h: No such file or directory  #include "esp32s2beta/rom/crc.h" (AUD-4069)

### ISSUE THREAD

**Issue by jiafeng-1** [espressif/esp-adf#881]
我在在下载的adf与idf包中并没有找到Esp32s2Beta/room/crc.h
但是编译时候却需要这个头文件。是否是提供的adf库问题？
更详细请看#879问题 
 @projectgus @justintconroy @pedrominatel @kedars @mahavirj 
```c
#ifdef CONFIG_IDF_TARGET_ESP32
#include "esp32/rom/crc.h"
#else
#include "esp32s2beta/rom/crc.h"
#endif // CONFIG_IDF_TARGET_ESP32
```

**Comment by jason-mao** [comment]
@jiafeng-1 这个问题在4月份的提交 d44e7418ba8e52a8822723f6d593d32a9977f8ec ，已经修复了。建议你是用最新的代码验证。另外一个问题尽量只建一个Issue，这个会关闭。
