### ISSUE TITLE
单MIC出现 AFE_SR: ERROR! rb_out slow!!! (AUD-4076)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-adf#882]
我使用的esp32s3的芯片，音频只用了es8311，然后在工程中使用了单麦语音识别，但是出现了AFE_SR: ERROR! rb_out slow!!!问题。我把其他所有功能关闭之后，只剩下单麦语音识别，是没有问题的，但是加上其他功能，就会出现AFE_SR: ERROR! rb_out slow!!!问题。
![image](https://user-images.githubusercontent.com/92145359/189025867-51ab895f-31fc-4f82-9124-e73bca64cf97.png)
这是我用audio_sys_get_real_time_stats();打印的线程信息
![image](https://user-images.githubusercontent.com/92145359/189026351-360ae847-8142-4fe8-8112-6d420ed38ab9.png)

**Comment by jason-mao** [comment]
Duplicate issue is #873
