### ISSUE TITLE
停止语音识别可以释放内存吗 (AUD-4078)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-adf#884]
我使用了esp32s3的板子，开启语音识别功能。但是语音识别太消耗资源了，在不用语音识别的时候，我想把资源回收，我使用了recorder_sr_enable()接口，语音识别是停止了，但是内存却没有减少，请问这是怎么回事呢，在不使用的时候可以暂停，并把线程内存释放掉吗，除了模型之类的初始化不释放，因为语音识别的初始化还需要一定的时间，但是初始化之后，开启语音识别还需要25k左右的内存，当我暂时不使用时，可以将内存回收吗

**Comment by jason-mao** [comment]
Fixed by fe4d59aa604b7146723d870ec9a1181c6846542a
