### ISSUE TITLE
VOIP与公网部署的SIP服务器通话，出现esp-s3能听到公网服务器对话，对端无法听到esp-s3设备说话 (AUD-4105)

### ISSUE THREAD

**Issue by jiafeng-1** [espressif/esp-adf#890]
板卡：ESP-RTC以ESP32-S3-Korvo-2

根据调研，可能需要使用NAT服务，我准备使用STUN服务器做透传，不知道设备能否支持。

我偶然看到“乐鑫推出 ESP-RTC 实时音视频通信方案”[https://www.espressif.com.cn/zh-hans/news/ESP-RTC](url)。

> ESP-RTC 方案基于乐鑫自研的 SIP（Session Initialization Protocol，会话初始协议）协议栈，实现了实时的音视频通信。协议栈包含传输层、事务层和会话层，其信令交互模块支持 UDP、TCP 和 TLS 三种方式，媒体传输模块支持 RTP (UDP)、RTCP、SRTP、TURN 等 NAT 透传协议。值得一提的是，ESP-RTC 方案还在传输模块中增加了弱网对抗算法，如 Jitter Buffer 和 PLC，有效解决了丢包、抖动、拥塞、延时等问题，能够充分保证音视频通信的流畅性与实时性。

上面提支持NAT透传协议，但是我不知道从哪获取。请帮帮我。

**Comment by jason-mao** [comment]
@jiafeng-1 这部分的支持，请联系我们 sales@espressif.com
