### ISSUE TITLE
how to make the bt_sink print some music massage  (AUD-4116)

### ISSUE THREAD

**Issue by Kingwulin** [espressif/esp-adf#891]
Hi, I am using the  [pipeline_bt_sink ](https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_bt_sink)example
I want to achive the function that printing the music singger , lyric and title in the console
I had found the callback function here the same as [idf example ](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/a2dp_sink)did 
But in the adf demo pipeline_bt_sink  always run into [here](https://github.com/espressif/esp-adf/blob/master/components/bluetooth_service/bluetooth_service.c#L331)

how would I do in pipeline_bt_sink exampe

**Comment by jason-mao** [comment]
Duplicate #905
