### ISSUE TITLE
VOIP setting (AUD-4129)

### ISSUE THREAD

**Issue by salviador** [espressif/esp-adf#896]
I am using VOIP example

The problem is how to set the parameters with the same settings I have in the "microsip" application for windows
SIP URI (Transport://user:password@server:port)

[microsip setting](https://ibb.co/GkhbNcq)

I have formatted uri sip in the following way

udp://**username**:**password**@**domain**:5060

but I need setting "SIP server" and "SIP proxy" for my network

**Comment by ahhfzhang** [comment]
Hi @salviador 

Microsip also supports that the sip server and domain are the same address, and the proxy can be left blank.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
