### ISSUE TITLE
VOIP Outbound Proxy (AUD-4130)

### ISSUE THREAD

**Issue by salviador** [espressif/esp-adf#897]
How setting example "VOIP" with "Outbound Proxy" ?

**Comment by ahhfzhang** [comment]
Hi @salviador 

We use the same server which set in your SIP URI as an outbound proxy server.

Thnaks.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
