### ISSUE TITLE
ESP-ADF的例程如何搬到ESP-IDF里面编译，将esp-adf里的相关部分功能集成到esp-idf里？ (AUD-4143)

### ISSUE THREAD

**Issue by mengjiqing** [espressif/esp-adf#900]
ESP-ADF的例程如何搬到ESP-IDF里面编译，将esp-adf里的相关部分功能集成到esp-idf里？

**Comment by jason-mao** [comment]
@mengjiqing 不建议这样做。 ADF 例程依赖ADF的组件，ADF 组件使用了 `EXTRA_COMPONENT_DIRS`来扩展IDF的组件范围。
