### ISSUE TITLE
esp-adf pipeline_bt_sink demo 无法通过AVRCP CT 获取音乐的歌名/作曲者/歌词 (AUD-4162)

### ISSUE THREAD

**Issue by Kingwulin** [espressif/esp-adf#905]
你好，我使用这个 [demo](https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_bt_sink)，但是发现无法获取到歌曲的相关信息，只有歌声
而在 idf中的 [demo](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/a2dp_sink) 是可以获取到音频和歌词信息的

**Comment by jason-mao** [comment]
@Kingwulin 谢谢您的反馈，我们来检查修复。

**Comment by Kingwulin** [comment]
> @Kingwulin 谢谢您的反馈，我们来检查修复。

期待更新！

**Comment by Kingwulin** [comment]
> @Kingwulin 谢谢您的反馈，我们来检查修复。

你好，有解决方法吗

**Comment by jason-mao** [comment]
我们修改 example 会支持这个功能。
