### ISSUE TITLE
esp32_s3_korvo2_v3的板子可以使用korvo_du1906例程吗？ (AUD-4176)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-adf#906]
我使用的是esp32_s3_korvo2_v3板子，dueros能使用起来，能识别的短语太少了，而且好像百度对这个例程和profile的支持很少。想问一下esp32_s3_korvo2_v3可以使用korvo_du1906例程吗？需要做什么修改呢?

**Comment by jason-mao** [comment]
@Zhengqinze05 目前不行，korvo_du1906 的库有部分在新的IDF上编译不过。
