### ISSUE TITLE
I2S: APLL not supported on current chip, use I2S_CLK_D2CLK as default clock source (AUD-4177)

### ISSUE THREAD

**Issue by adrianpi** [espressif/esp-adf#907]
I'm getting the following on the monitor when running **play_mp3_control** on a ESP32-S3-Korvo-2 v3.1

`I2S: APLL not supported on current chip, use I2S_CLK_D2CLK as default clock source`

## Environment

- Audio development kit:  ESP32-S3-Korvo-2
- Audio kit version: v3.1
- Module or chip used:  ESP32-S3-WROOM-1
- IDF version v4.4.2
- ADF v2.4-138-g1d0a049
- Build system:  idf.py
- Running log:

```
I (25) boot: ESP-IDF v4.4.2-dirty 2nd stage bootloader
I (25) boot: compile time 11:44:38
I (25) boot: chip revision: 0
I (27) boot.esp32s3: Boot SPI Speed : 80MHz
I (32) boot.esp32s3: SPI Mode       : DIO
I (36) boot.esp32s3: SPI Flash Size : 2MB
I (41) boot: Enabling RNG early entropy source...
I (47) boot: Partition Table:
I (50) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (65) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (72) boot:  2 factory          factory app      00 00 00010000 00100000
I (80) boot: End of partition table
I (84) esp_image: segment 0: paddr=00010020 vaddr=3c030020 size=89c38h (564280) map
I (194) esp_image: segment 1: paddr=00099c60 vaddr=3fc930b0 size=02828h ( 10280) load
I (196) esp_image: segment 2: paddr=0009c490 vaddr=40374000 size=03b88h ( 15240) load
I (203) esp_image: segment 3: paddr=000a0020 vaddr=42000020 size=2dbc4h (187332) map
I (241) esp_image: segment 4: paddr=000cdbec vaddr=40377b88 size=0b520h ( 46368) load
I (252) esp_image: segment 5: paddr=000d9114 vaddr=50000000 size=00010h (    16) load
I (258) boot: Loaded app from partition at offset 0x10000
I (258) boot: Disabling RNG early entropy source...
I (272) cpu_start: Pro cpu up.
I (272) cpu_start: Starting app cpu, entry point is 0x40375294
0x40375294: call_start_cpu1 at C:/Espressif/frameworks/esp-idf-v4.4.2/components/esp_system/port/cpu_start.c:160

I (0) cpu_start: App cpu up.
I (286) cpu_start: Pro cpu start user code
I (286) cpu_start: cpu freq: 160000000
I (286) cpu_start: Application information:
I (289) cpu_start: Project name:     play_mp3_control
I (295) cpu_start: App version:      v2.4-138-g1d0a049-dirty
I (301) cpu_start: Compile time:     Oct 25 2022 11:44:10
I (307) cpu_start: ELF file SHA256:  e33971dcf6784de7...
I (313) cpu_start: ESP-IDF:          v4.4.2-dirty
I (319) heap_init: Initializing. RAM available for dynamic allocation:
I (326) heap_init: At 3FC96460 len 00049BA0 (294 KiB): D/IRAM
I (332) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (339) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (345) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (352) spi_flash: detected chip: gd
I (356) spi_flash: flash io: dio
W (360) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (373) sleep: Configure to isolate all GPIO pins in sleep state
I (380) sleep: Enable automatic switching of GPIO sleep configuration
I (387) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (407) PLAY_FLASH_MP3_CONTROL: [ 1 ] Start audio codec chip
W (427) I2C_BUS: i2c_bus_create:58: I2C bus has been already created, [port:0]
W (457) ES7210: Enable TDM mode. ES7210_SDP_INTERFACE2_REG12: 2
I (467) PLAY_FLASH_MP3_CONTROL: [ 2 ] Create audio pipeline, add all elements to pipeline, and subscribe pipeline event
I (467) PLAY_FLASH_MP3_CONTROL: [2.1] Create mp3 decoder to decode mp3 file and set custom read callback
I (477) PLAY_FLASH_MP3_CONTROL: [2.2] Create i2s stream to write data to codec chip
W (487) I2S: APLL not supported on current chip, use I2S_CLK_D2CLK as default clock source
```
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` in your project folder to find it): 8.4.0
- Operating system:     Windows
- (Windows only) Environment type: ESP Command Prompt
- Using an IDE?: No
- Power supply:  USB

## Problem Description

Followed step by step guide with no inconvenient

https://espressif-docs.readthedocs-hosted.com/projects/esp-adf/en/latest/get-started/index.html#get-started-step-by-step

When running the example I get no sound output and the mentioned clock source error

Compiled the example application

### Expected Behavior

Sound should be heard

### Actual Behavior

No sound heard and APLL clock source warning

### Steps to Reproduce

1. Compile ***play_mp3_control*** example
2. Flash it
3. Run

// If possible, attach a picture of your setup/wiring here.

Just a speaker onto SPK connector

### Code to Reproduce This Issue

***play_mp3_control*** example "as is"

## Debug Logs

Already provided

## Other Items If Possible

[sdkconfig.txt](https://github.com/espressif/esp-adf/files/9861453/sdkconfig.txt)

**Comment by jason-mao** [comment]
@adrianpi `W (419) I2S: APLL not supported on current chip, use I2S_CLK_D2CLK as default clock source` is not error. Even got this the sound should be heard. I have check example sound is fine.  Did you check your speaker is it ok?

**Comment by HappyJoeJoe** [comment]
> 

I hava got the same problem, I can't heard the sound

**Comment by adrian-piccioli-mk** [comment]
Honestly, I forgot about the issue as the two included DACs are mono and I do need stereo for my application:

https://youtu.be/SZelCfDm-FU

 I managed to hook a CS-4344 on the test points and I'm currently using Korvo just to check out ESP32 S3 performance compared to ESP32. And yes, using plain I2S and setting useApll to false works great.

Nota bene, I'm currently not using ESP-ADF as I had my own wrapper for I2S that is cross-platform over PortAudio, so bulk of coding, debugging and running is actually done on the desktop computer 

ESP32 kinda performs better so far, but maybe is something freeRTOS related: Two pinned tasks one on each core are synthesizing sound and the main task is just getting and dispatching MIDI messages but somehow this little guy seem to struggle to get a chance to work. Was not the case with the ESP32 Anyway too soon to tell, just got everything up and running today and indeed is not related to this.

Was hopping PERI_POWER_ON on the GPIO expander to turn off the included DACS but just do so on SD card, LCD and Camera, right?

I'll check tomorrow about the ADF example and let you know.  Thanks for your time 👍🏻

**Comment by adrianpi** [comment]
Honestly, I forgot about the issue as the two included DACs are mono and I do need stereo for my application:

https://youtu.be/SZelCfDm-FU

 I managed to hook a CS-4344 on the test points and I'm currently using Korvo just to check out ESP32 S3 performance compared to ESP32. And yes, using plain I2S and setting useApll to false works great.

Nota bene, I'm currently not using ESP-ADF as I had my own wrapper for I2S that is cross-platform over PortAudio, so bulk of coding, debugging and tunning is actually done on the desktop computer 

ESP32 kinda performs better so far, but maybe is something freeRTOS related: Two pinned tasks one on each core are synthesizing sound and the main task is just getting and dispatching MIDI messages but somehow this little guy seem to struggle to get a chance to work. Was not the case with the ESP32 Anyway too soon to tell, just got everything up and running today and indeed is not related to this.

Was hopping PERI_POWER_ON on the GPIO expander to turn off the included DACS but just do so on SD card, LCD and Camera, right?

I'll check tomorrow about the ADF example and let you know.  Thanks for your time 👍🏻

**Comment by adrianpi** [comment]
Giving a second look at the log, it appears to not be loading the sound at all
```

(In326) heap_init: At 3FC96460 len 00049BA0 (294 KiB): D/IRAM
I (332) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (339) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (345) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (352) spi_flash: detected chip: gd
I (356) spi_flash: flash io: dio
W (360) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header
```

**Comment by adrianpi** [comment]
Sorry for the delay.
Not sure what changed, but now when building I'm getting this:

`_NUM_45' undeclared (first use in this function); did you mean 'GPIO_NUM_35'?
         i2s_config->ws_io_num = GPIO_NUM_45;
                                 ^~~~~~~~~~~
                                 GPIO_NUM_35
F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c:54:33: note: each undeclared identifier is reported only once for each function it appears in
In file included from F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board.h:29,
                 from F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c:28:
F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c: In function 'get_pa_enable_gpio':
F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_def.h:116:37: error: 'GPIO_NUM_48' undeclared (first use in this function); did you mean 'GPIO_NUM_38'?
 #define PA_ENABLE_GPIO              GPIO_NUM_48
                                     ^~~~~~~~~~~
F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c:126:12: note: in expansion of macro 'PA_ENABLE_GPIO'
     return PA_ENABLE_GPIO;
            ^~~~~~~~~~~~~~`

At some point I installed Visual Code extensions and it broke the whole building system so I reinstalled everything, so hard to tell what's wrong

**Comment by jason-mao** [comment]
> Sorry for the delay. Not sure what changed, but now when building I'm getting this:
> 
> `_NUM_45' undeclared (first use in this function); did you mean 'GPIO_NUM_35'? i2s_config->ws_io_num = GPIO_NUM_45; ^~~~~~~~~~~ GPIO_NUM_35 F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c:54:33: note: each undeclared identifier is reported only once for each function it appears in In file included from F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board.h:29, from F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c:28: F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c: In function 'get_pa_enable_gpio': F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_def.h:116:37: error: 'GPIO_NUM_48' undeclared (first use in this function); did you mean 'GPIO_NUM_38'? #define PA_ENABLE_GPIO GPIO_NUM_48 ^~~~~~~~~~~ F:/Espressif/frameworks/esp-adf-v2.4.1/components/audio_board/esp32_s3_korvo2_v3/board_pins_config.c:126:12: note: in expansion of macro 'PA_ENABLE_GPIO' return PA_ENABLE_GPIO; ^~~~~~~~~~~~~~`
> 
> At some point I installed Visual Code extensions and it broke the whole building system so I reinstalled everything, so hard to tell what's wrong

It's looks like not set chip target for esp32s3, try it with `idf.py set-target esp32s3`

**Comment by adrianpi** [comment]
Yup, that did the trick, after an idf.py clean. Thank you.
I'm getting something that looks like music on the oscilloscope, lasting 12 seconds or so, but yet nothing on the speaker.
Checked continuity and everything is fine. It is an 8 Ohms 4' speaker.  Nothing elaborate, something like this:

https://www.arcadeworlduk.com/products/budget-4-inch-speaker-8-ohms-5-watt.html

Can it drive it? Found no specs about output impedance nowhere.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
