### ISSUE TITLE
WWE例程无法运行，报错和重启 (AUD-4208)

### ISSUE THREAD

**Issue by Ouyangtengfang** [espressif/esp-adf#913]
您好！

按照指导文档（https://github.com/espressif/esp-adf/blob/ba18b938297c4a0faaded7508a9fedb29d0277c8/examples/speech_recognition/wwe/README_CN.md）编译WWE例程，开发板是（ESP32-S3-Korvo-2 v3.0），但是运行后，说“HI，Lexin”就会报错和重启，日志如下，请指导，谢谢！

Setting PYTHONNOUSERSITE, was not set
Using Python in C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\
Python 3.8.7
Using Git in C:\Espressif\tools\idf-git\2.34.2\cmd\
git version 2.34.1.windows.1
Setting IDF_PATH: C:\Espressif\frameworks\esp-idf-v4.4.2

Adding ESP-IDF tools to PATH...
    C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin
    C:\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin
    C:\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin
    C:\Espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin
    C:\Espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin
    C:\Espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin
    C:\Espressif\tools\cmake\3.23.1\bin
    C:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20220411\openocd-esp32\bin
    C:\Espressif\tools\ninja\1.10.2\
    C:\Espressif\tools\idf-exe\1.0.3\
    C:\Espressif\tools\ccache\4.3\ccache-4.3-windows-64
    C:\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
    C:\Espressif\frameworks\esp-idf-v4.4.2\tools

Checking if Python packages are up to date...
Python requirements from C:\Espressif\frameworks\esp-idf-v4.4.2\requirements.txt are satisfied.

Done! You can now compile ESP-IDF projects.
Go to the project directory and run:

  idf.py build

C:\Espressif\frameworks\esp-idf-v4.4.2>cd c:\Espressif\esp\wwe

c:\Espressif\esp\wwe>idf.py -p COM4 monitor
Executing action: monitor
Running idf_monitor in directory c:\espressif\esp\wwe
Executing "C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:\Espressif\frameworks\esp-idf-v4.4.2\tools/idf_monitor.py -p COM4 -b 115200 --toolchain-prefix xtensa-esp32s3-elf- --target esp32s3 c:\espressif\esp\wwe\build\example_wwe.elf -m 'C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe' 'C:\Espressif\frameworks\esp-idf-v4.4.2\tools\idf.py' '-p' 'COM4'"...
[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM4 instead...[0m
[0;33m--- idf_monitor on \\.\COM4 115200 ---[0m
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x17b0
load:0x403c9700,len:0xe64
load:0x403cc700,len:0x30e8
entry 0x403c9980
I (25) boot: ESP-IDF v4.4.2-dirty 2nd stage bootloader
I (25) boot: compile time 17:07:52
I (25) boot: chip revision: 0
I (27) qio_mode: Enabling default flash chip QIO
I (32) boot.esp32s3: Boot SPI Speed : 80MHz
I (37) boot.esp32s3: SPI Mode       : QIO
I (42) boot.esp32s3: SPI Flash Size : 8MB
I (46) boot: Enabling RNG early entropy source...
I (52) boot: Partition Table:
I (55) boot: ## Label            Usage          Type ST Offset   Length
I (63) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (70) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (78) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (85) boot:  3 ota_0            OTA app          00 10 00010000 00290000
I (93) boot:  4 model            Unknown data     01 82 002a0000 0040e000
I (100) boot:  5 flash_tone       Unknown data     01 27 006ae000 00032000
I (108) boot: End of partition table
I (112) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=3b550h (243024) map
I (157) esp_image: segment 1: paddr=0004b578 vaddr=3fca21b0 size=04aa0h ( 19104) load
I (161) esp_image: segment 2: paddr=00050020 vaddr=42000020 size=9530ch (611084) map
I (256) esp_image: segment 3: paddr=000e5334 vaddr=3fca6c50 size=00738h (  1848) load
I (256) esp_image: segment 4: paddr=000e5a74 vaddr=40378000 size=1a1b0h (106928) load
I (282) esp_image: segment 5: paddr=000ffc2c vaddr=50000000 size=00010h (    16) load
I (292) boot: Loaded app from partition at offset 0x10000
I (292) boot: Disabling RNG early entropy source...
I (304) opi psram: vendor id : 0x0d (AP)
I (304) opi psram: dev id    : 0x02 (generation 3)
I (304) opi psram: density   : 0x03 (64 Mbit)
I (308) opi psram: good-die  : 0x01 (Pass)
I (313) opi psram: Latency   : 0x01 (Fixed)
I (318) opi psram: VCC       : 0x01 (3V)
I (322) opi psram: SRF       : 0x01 (Fast Refresh)
I (328) opi psram: BurstType : 0x01 (Hybrid Wrap)
I (333) opi psram: BurstLen  : 0x01 (32 Byte)
I (338) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (344) opi psram: DriveStrength: 0x00 (1/1)
W (349) PSRAM: DO NOT USE FOR MASS PRODUCTION! Timing parameters will be updated in future IDF version.
I (360) spiram: Found 64MBit SPI RAM device
I (364) spiram: SPI RAM mode: sram 80m
I (368) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (375) cpu_start: Pro cpu up.
I (379) cpu_start: Starting app cpu, entry point is 0x4037955c
0x4037955c: call_start_cpu1 at C:/Espressif/frameworks/esp-idf-v4.4.2/components/esp_system/port/cpu_start.c:160

I (0) cpu_start: App cpu up.
I (671) spiram: SPI SRAM memory test OK
I (679) cpu_start: Pro cpu start user code
I (679) cpu_start: cpu freq: 240000000
I (679) cpu_start: Application information:
I (682) cpu_start: Project name:     example_wwe
I (687) cpu_start: App version:      1
I (692) cpu_start: Compile time:     Nov  7 2022 17:07:28
I (698) cpu_start: ELF file SHA256:  e2162020b3cc135f...
I (704) cpu_start: ESP-IDF:          v4.4.2-dirty
I (709) heap_init: Initializing. RAM available for dynamic allocation:
I (716) heap_init: At 3FCA9548 len 00036AB8 (218 KiB): D/IRAM
I (723) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (730) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (736) spiram: Adding pool of 8192K of external SPI memory to heap allocator
I (744) spi_flash: detected chip: gd
I (748) spi_flash: flash io: qio
W (752) spi_flash: Detected size(16384k) larger than the size in the binary image header(8192k). Using the size in the binary image header.
I (765) sleep: Configure to isolate all GPIO pins in sleep state
I (772) sleep: Enable automatic switching of GPIO sleep configuration
I (779) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (799) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (809) DRV8311: ES8311 in Slave mode
I (819) gpio: GPIO[48]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (829) ES7210: ES7210 in Slave mode
I (839) ES7210: Enable ES7210_INPUT_MIC1
I (839) ES7210: Enable ES7210_INPUT_MIC2
I (839) ES7210: Enable ES7210_INPUT_MIC3
W (839) ES7210: Enable TDM mode. ES7210_SDP_INTERFACE2_REG12: 2
I (849) ES7210: config fmt 60
W (849) AUDIO_BOARD: The board has already been initialized!

----------------------------- ESP Audio Platform -----------------------------
|                                                                            |
|                       ESP_AUDIO-v1.7.1-4717e99-42c05f5                     |
|                     Compile date: Aug 24 2022-06:32:45                     |
------------------------------------------------------------------------------
I (899) ESP32_S3_KORVO_2: I2S0, MCLK output by GPIO0
I (899) wwe_example: Func:setup_player, Line:146, MEM Total:8601815 Bytes, Inter:238351 Bytes, Dram:238351 Bytes

I (909) wwe_example: esp_audio instance is:0x3d801b88

I (909) wwe_example: CODEC_ADC_BITS_PER_SAMPLE
I (919) wwe_example: i2s_stream_init start
E (919) I2S: register I2S object to platform failed
I (929) ESP32_S3_KORVO_2: I2S0, MCLK output by GPIO0
I (929) wwe_example: i2s_stream_init end
I (939) wwe_example: Recorder has been created
I (939) MODEL_LOADER:
Initializing models from SPIFFS, partition label: model

I (1199) MODEL_LOADER: Partition size: total: 3900791, used: 2085308

I (1409) AFE_SR: afe interface for speech recognition

I (1409) AFE_SR: AFE version: SR_V220727

I (1409) AFE_SR: Initial auido front-end, total channel: 3, mic num: 2, ref num: 1

I (1419) AFE_SR: aec_init: 1, se_init: 1, vad_init: 1

I (1429) AFE_SR: wakenet_init: 1

model_name: wn9_hilexin model_data: /srmodel/wn9_hilexin/wn9_data
MC Quantized wakenet9: wakenet9_v1h24_hilexin_3_0.608_0.615, tigger:v3, mode:2, p:0, (Oct  9 2022 17:21:08)
I (2179) AFE_SR: wake num: 3, mode: 0, (Oct  9 2022 17:21:16)

I (2179) MN: model_name: mn4_cn model_data: /srmodel/mn4_cn/mn4_cn_data
I (3419) MN: SINGLE_RECOGNITION: V4.5 CN; core: 0; (Oct  9 2022 17:21:10)

esp_mn_commands_update_from_sdkconfig
I (3419) MN_COMMAND: ---------------------SPEECH COMMANDS---------------------
I (3429) MN_COMMAND: Command ID0, phrase ID0: da kai kong tiao
I (3439) MN_COMMAND: Command ID1, phrase ID1: guan bi kong tiao
I (3449) MN_COMMAND: Command ID2, phrase ID2: zeng da feng su
I (3449) MN_COMMAND: Command ID3, phrase ID3: jian xiao feng su
I (3459) MN_COMMAND: Command ID4, phrase ID4: sheng gao yi du
I (3459) MN_COMMAND: Command ID5, phrase ID5: jiang di yi du
I (3469) MN_COMMAND: Command ID6, phrase ID6: zhi re mo shi
I (3479) MN_COMMAND: Command ID7, phrase ID7: zhi leng mo shi
I (3479) MN_COMMAND: Command ID8, phrase ID8: song feng mo shi
I (3489) MN_COMMAND: Command ID9, phrase ID9: jie neng mo shi
I (3499) MN_COMMAND: Command ID10, phrase ID10: chu shi mo shi
I (3499) MN_COMMAND: Command ID11, phrase ID11: jian kang mo shi
I (3509) MN_COMMAND: Command ID12, phrase ID12: shui mian mo shi
I (3519) MN_COMMAND: Command ID13, phrase ID13: da kai lan ya
I (3519) MN_COMMAND: Command ID14, phrase ID14: guan bi lan ya
I (3529) MN_COMMAND: Command ID15, phrase ID15: kai shi bo fang
I (3539) MN_COMMAND: Command ID16, phrase ID16: zan ting bo fang
I (3539) MN_COMMAND: Command ID17, phrase ID17: ding shi yi xiao shi
I (3549) MN_COMMAND: Command ID18, phrase ID18: da kai dian deng
I (3559) MN_COMMAND: Command ID19, phrase ID19: guan bi dian deng
I (3559) MN_COMMAND: ---------------------------------------------------------

I (5849) wwe_example: rec_engine_cb - REC_EVENT_WAKEUP_START
E (5849) wwe_example: voice_reading is false

assert failed: dl_matrixq_slice dl_lib_matrixq.c:483 (in->flags & DL_MF_FOREIGNDATA)

Backtrace:0x40379fbe:0x3d955c00 |<-CORRUPTED
0x40379fbe: panic_abort at C:/Espressif/frameworks/esp-idf-v4.4.2/components/esp_system/panic.c:402

ELF file SHA256: e2162020b3cc135f

Rebooting...
��ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x42092592
0x42092592: esp_pm_impl_waiti at C:/Espressif/frameworks/esp-idf-v4.4.2/components/esp_pm/pm_impl.c:839

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x17b0
load:0x403c9700,len:0xe64
load:0x403cc700,len:0x30e8
entry 0x403c9980
I (29) boot: ESP-IDF v4.4.2-dirty 2nd stage bootloader
I (29) boot: compile time 17:07:52
I (29) boot: chip revision: 0
I (31) qio_mode: Enabling default flash chip QIO
I (37) boot.esp32s3: Boot SPI Speed : 80MHz
I (41) boot.esp32s3: SPI Mode       : QIO
I (46) boot.esp32s3: SPI Flash Size : 8MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (75) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (82) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (89) boot:  3 ota_0            OTA app          00 10 00010000 00290000
I (97) boot:  4 model            Unknown data     01 82 002a0000 0040e000
I (104) boot:  5 flash_tone       Unknown data     01 27 006ae000 00032000
I (112) boot: End of partition table
I (116) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=3b550h (243024) map
I (162) esp_image: segment 1: paddr=0004b578 vaddr=3fca21b0 size=04aa0h ( 19104) load
I (165) esp_image: segment 2: paddr=00050020 vaddr=42000020 size=9530ch (611084) map
I (260) esp_image: segment 3: paddr=000e5334 vaddr=3fca6c50 size=00738h (  1848) load
I (261) esp_image: segment 4: paddr=000e5a74 vaddr=40378000 size=1a1b0h (106928) load
I (286) esp_image: segment 5: paddr=000ffc2c vaddr=50000000 size=00010h (    16) load
I (297) boot: Loaded app from partition at offset 0x10000
I (297) boot: Disabling RNG early entropy source...
I (308) opi psram: vendor id : 0x0d (AP)
I (308) opi psram: dev id    : 0x02 (generation 3)
I (309) opi psram: density   : 0x03 (64 Mbit)
I (312) opi psram: good-die  : 0x01 (Pass)
I (317) opi psram: Latency   : 0x01 (Fixed)
I (322) opi psram: VCC       : 0x01 (3V)
I (326) opi psram: SRF       : 0x01 (Fast Refresh)
I (332) opi psram: BurstType : 0x01 (Hybrid Wrap)
I (337) opi psram: BurstLen  : 0x01 (32 Byte)
I (342) opi psram: Readlatency  : 0x02 (10 cycles@Fixed)
I (348) opi psram: DriveStrength: 0x00 (1/1)
W (353) PSRAM: DO NOT USE FOR MASS PRODUCTION! Timing parameters will be updated in future IDF version.
I (364) spiram: Found 64MBit SPI RAM device
I (368) spiram: SPI RAM mode: sram 80m
I (373) spiram: PSRAM initialized, cache is in normal (1-core) mode.
I (380) cpu_start: Pro cpu up.
I (383) cpu_start: Starting app cpu, entry point is 0x4037955c
0x4037955c: call_start_cpu1 at C:/Espressif/frameworks/esp-idf-v4.4.2/components/esp_system/port/cpu_start.c:160

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x10 (RTCWDT_RTC_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x17b0
load:0x403c9700,len:0xe64
load:0x403cc700,len:0x30e8
entry 0x403c9980
I (25) boot: ESP-IDF v4.4.2-dirty 2nd stage bootloader
I (25) boot: compile time 17:07:52
I (25) boot: chip revision: 0
I (27) qio_mode: Enabling default flash chip QIO
I (33) boot.esp32s3: Boot SPI Speed : 80MHz
I (38) boot.esp32s3: SPI Mode       : QIO
I (42) boot.esp32s3: SPI Flash Size : 8MB
I (47) boot: Enabling RNG early entropy source...
I (52) boot: Partition Table:
I (56) boot: ## Label            Usage          Type ST Offset   Length
I (63) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (71) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (78) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (86) boot:  3 ota_0            OTA app          00 10 00010000 00290000
I (93) boot:  4 model            Unknown data     01 82 002a0000 0040e000
I (101) boot:  5 flash_tone       Unknown data     01 27 006ae000 00032000
I (108) boot: End of partition table
I (113) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=3b550h (243024) map
I (158) esp_image: segment 1: paddr=0004b578 vaddr=3fca21b0 size=04aa0h ( 19104) load

**Comment by jason-mao** [comment]
@Ouyangtengfang 上面问题的ADF版本是多少？另外你帮用最新的master 试一下

**Comment by jason-mao** [comment]
我们在0cbeef7f6d34b0db1ecd813876781be2ad279e22分支上check 该问题，没有复现。该问题先行关闭，如还有问题请重新打开或者新建Issue。
