### ISSUE TITLE
d0wd chip 32bit 1CH output not correct (AUD-4261)

### ISSUE THREAD

**Issue by powerpun** [espressif/esp-adf#924]
chip: d0wd-v3
idf: 4.3
adf: master

method:
use pcm_decode and set call back function to refill data from memory.

![f4f283c0156f4b91b87b36faa2e56c2](https://user-images.githubusercontent.com/13483251/205040574-d5fb60ea-8288-4ac8-9160-2e72be1d0a3c.jpg)

while use 2CH, then output correct.
data is the same but while 2 channels just send one data twice.

**Comment by jason-mao** [comment]
ESP32 have a bug on one channel, please refer to https://github.com/espressif/esp-adf/blob/6a977ad9d252738ecf672b154450d450b5e01a70/components/audio_stream/i2s_stream.c#L66 swap the byte order.

**Comment by powerpun** [comment]
tested work...
