### ISSUE TITLE
BT-"ESP_AVRC_RN_PLAY_POS_CHANGED" event not work with apple ios device. (AUD-4269)

### ISSUE THREAD

**Issue by DevSong-Dio** [espressif/esp-adf#926]
hello i am noobie programmer.
I am currently developing a bluetooth audio speaker.

i tested ESP_AVRC_RN_PLAY_POS_CHANGED event with android smart phone.
bt_av_new_track,bt_av_playback_changed,bt_av_play_pos_changed function is ok.

no problem to get all dataa and event. (music information, play play/stop event, play position change event)

but, ios devices (ios16 iphone, ipad pro) is not work "ESP_AVRC_RN_PLAY_POS_CHANGED".

esp_avrc_ct_send_metadata_cmd(APP_RC_CT_TL_GET_META_DATA, attr_mask) and APP_RC_CT_TL_RN_TRACK_CHANGE,APP_RC_CT_TL_RN_PLAYBACK_CHANGE is all ok with ios device.

So I can't check the current position time of the music being played.

my question is,
1. I want to know if others have the same issue as me.
2. Is there any other way to check current position time of playing audio?

I found the logs when the phone connects esp32.

run esp_avrc_ct_send_get_rn_capabilities_cmd(APP_RC_CT_TL_GET_CAPS) function and..

android phone`s log-> remote rn_cap: count 7, bitmask 0xf26

ios device`s log ->        remote rn_cap: count 7, bitmask 0x1f06

![image](https://user-images.githubusercontent.com/111501926/205474620-fadae40d-2327-46d8-9b51-e1d5114d5140.png)

=========
device : esp32-wrover-e custom board
ESP-IDF:          v4.4.1-dirty 
ESP-ADF: maybe May version?
program is bluetooth audio player.
=========

**Comment by jason-mao** [comment]
@DevSong-Dio Looks like the IOS is not support ESP_AVRC_RN_PLAY_POS_CHANGED, `remote rn_cap` bit5 is ESP_AVRC_RN_PLAY_POS_CHANGED.
