### ISSUE TITLE
Problem to start VOIP example on ESP32-LyraTD-MSC_A V2.2 (AUD-4300)

### ISSUE THREAD

**Issue by CiochinaVitalie** [espressif/esp-adf#931]
**Enviroment**:
ESP-IDF Version: 4.4.3
ESP-ADF Version: Master

SIP Codec: G711 PCMA
Audio Hal: ESP32-LyraTD-MSC_A V2.2 (ESP32-WROVER-B)

**Issue**:
Can't run voip example on ESP32-Lyra_A TD-MSC V2.2

**Steps taken**:
Configured the WiFi ssid, WiFi password, audio hal and VoIP url, as directed by the example's instructions. Flashed and monitor Voip example.

![screen_2](https://user-images.githubusercontent.com/24220355/209296037-b1763ecf-2bbc-48ed-8168-635a62ca33bd.png)
![screen_1](https://user-images.githubusercontent.com/24220355/209295963-3d5d739f-dd3f-499a-b114-e70b43d0e7aa.png)
[log.txt](https://github.com/espressif/esp-adf/files/10293406/log.txt)

**Comment by jason-mao** [comment]
@CiochinaVitalie  I saw `W (2794) AUIDO_MEM: Can't support stack on external memory due to ESP32 chip is 1`, your chip is eco1, it's too old. You may test without PSRAM or found eco3 new chip.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
