### ISSUE TITLE
A Talking Clock in Chinese (AUD-4325)

### ISSUE THREAD

**Issue by babadue** [espressif/esp-adf#938]
While going through those examples for the Box, I manage to copy and paste my way through a talking clock in Chinese.

[A Talking Clock in Chinese](https://github.com/babadue/talking_clock_chinese_esp32_s3_box)

Updated: 

01-22-2023 Ported over to IDF v5.0.
02-02-2023 Enable http server to upload mp3 files directly to the sd card.

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
