### ISSUE TITLE
Lyrat-Mini 使用google-translate例子按键没反应 (AUD-4327)

### ISSUE THREAD

**Issue by HongYan12345** [espressif/esp-adf#939]
我使用的Lyrat-Mini 板子，在google-translate例子按下rec键按钮没有任何反应

**Comment by shootao** [comment]
Hi @HongYan12345 
Please try again using the patch below
[0001-example-support-google_translate_device-example-supp.patch](https://github.com/espressif/esp-adf/files/12523244/0001-example-support-google_translate_device-example-supp.patch)

**Comment by shootao** [comment]
Hi @HongYan12345 
上面的  `patch `可以解决你的问题嘛?

**Comment by PrathamG** [comment]
See my solution here (https://github.com/espressif/esp-adf/issues/934#issuecomment-1923532342)

**Comment by jason-mao** [comment]
Related issue #934, closed.
