### ISSUE TITLE
E (30647) WAV_HEAD: This is not wav stream (AUD-4329)

### ISSUE THREAD

**Issue by Bruce213** [espressif/esp-adf#940]
Hi ,
i use ADF  in my custom board as a network music player, ADF Version is V2.4, IDF Version is V4.4.

i send a wav file by udp communication ,first frame len is 1400+,  esp board recv and open the pipeline, 
but the wav decoder print "E (30647) WAV_HEAD: This is not wav stream. E (30657) AUDIO_ELEMENT: [audio_dec] AEL_STATUS_ERROR_OPEN,-1" ,  audio_element_getinfo return correct sample rate ,sample bit and so on.

i want to know is my sending data have some errors or the esp board handler the data not correctly?
thanks.

**Comment by jason-mao** [comment]
@Bruce213 Please place this wav file to sdcard and test, is it get same error?
