### ISSUE TITLE
ADF支持使用蓝牙5.0了吗? (AUD-4343)

### ISSUE THREAD

**Issue by dawnlike** [espressif/esp-adf#942]
目前的bluetooth_service.h当中只有:
/**
 * brief      Bluetooth service working mode
 */
typedef enum {
    BLUETOOTH_A2DP_SINK,    /*!< A2DP Bluetooth sink audio, ESP32 will receive audio data from other bluetooth devices */
    BLUETOOTH_A2DP_SOURCE,   /*!< A2DP Bluetooth source audio, ESP32 can send audio data to other bluetooth devices */
} bluetooth_service_mode_t;
只支持A2DP, ESP32-S3-KORVO-2-V3这样的板子的蓝牙就没有任何语音的能力呀.
请问ADF什么时候支持蓝牙5.0?

**Comment by jason-mao** [comment]
@dawnlike ESP32-S3的芯片不支持经典蓝牙，但是支持BLE5.0。如果您一定需要A2DP的话，请选择ESP32。
