### ISSUE TITLE
[help]在adf框架下使用蓝牙播放音频同时提供额外的特征控制硬件 (AUD-4394)

### ISSUE THREAD

**Issue by robbietree8** [espressif/esp-adf#951]
请教一下，如何在adf框架下做到以下两点：

1. 作为蓝牙接收端接收手机传过来的蓝牙音频播放(这个我理解参考这个例程就行， [pipeline_bt_sink](https://github.com/espressif/esp-adf/tree/master/examples/player/pipeline_bt_sink))
2. 同时能提供一些特征，手机可以通过这些特征控制硬件(包括ota等等)

**Comment by jason-mao** [comment]
@robbietree8  对于您提出的第二问题，通用的做法是，ESP32芯片支持BLE、蓝牙、WiFi共存，可以通过BLE或者WiFi和手机进行数据通信，您可以参考 IDF 的 BLE example 和 esp-idf/examples/protocols/sockets 。

**Comment by robbietree8** [comment]
@jason-mao 感谢回复。

如果是BLE的话，那就意味着手机需要连接两次蓝牙？ 一次用来连接经典蓝牙，一次用来连接BLE

**Comment by jason-mao** [comment]
> 如果是BLE的话，那就意味着手机需要连接两次蓝牙？ 一次用来连接经典蓝牙，一次用来连接BLE

这个是一次。

**Comment by liuliuu-112** [comment]
目前也遇到这个问题了，需要蓝牙配网，也需要经典蓝牙播放，想问下怎么解决的
