### ISSUE TITLE
A panic error occurs when more than 16 MP3 files are saved and played in the FAT file system of the ESP32's internal memory. (AUD-4401)

### ISSUE THREAD

**Issue by charon22** [espressif/esp-adf#954]
## Environment
Development Kit: ESP32-LyraT V4.3
Chip used: ESP32-WROVER-B
IDF version: v4.4.1
Build System: idf.py
Operating System: Windows 10
Power Supply: USB / 5v

## Problem Description
After creating a fat fs in the fat file system inside the ep32 internal flash memory, mp3 files are stored in the fat file system of the internal memory of the esp32 and play is being tested. 
However, if more than 16 mp3 files are saved in the folder root, a panic error occurs every time.

We are currently testing using the audio_player_mp3_play function.

## Analyize
* There is no problem when getting a list of 16 or more files.
  - If there are more than 16 stored files, a panic error occurs when playing one of the mp3 files.
* Only mp3 files stored in the current root can be played.
* The mp3 file size is not the problem. A 1.5Mbyte mp3 file works normally if there are less than 16 files.  

## Question

How can I store and play more than 16 mp3 files?
[mp3play_error.txt](https://github.com/espressif/esp-adf/files/10809388/mp3play_error.txt)

**Comment by jason-mao** [comment]
@charon22 I have see A2 register value is 0xf33af07c, this is invalid. I think some memory problem on there, such as memory override, wild pointer.  Would you  test with latest ADF  and feedback?

**Comment by jason-mao** [comment]
This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
