### ISSUE TITLE
ESP32-LyraTD-MSC V2.1 与 ESP32-LyraTD-MSC V2.2 有什么区别？ (AUD-4419)

### ISSUE THREAD

**Issue by yinwhm12** [espressif/esp-adf#959]
你好！我们开发目前使用的是贵司ESP32-LyraTD-MSC V2.1 产品，但是找不到相关 V2.1介绍。仅仅可查V2.2，请问V2.1与V2.2有什么区别？能提供该方面的文档？非常感谢！

**Comment by jason-mao** [comment]
v2.2 相对 v2.1 有以下改动内容：
- 为了改善DSP输出的音质，PA改为差分输入的形式，而且改使用两颗PA芯片；
- PA芯片输入电源默认接DCDC（ETA1093）的输出，但预留接VCC_For_Audio的电阻（用以验证是否
  可以删除这颗DCDC）;
- 为了配合PA的差分输入，耳机增加插入时的信号检测，以确保插入耳机后，PA被关掉喇叭无输出;
- 原本配置给Battery ADC检测的GPIO36（SENSOR_VP），现挪给耳机插入信号的检测使用;
