### ISSUE TITLE
ESP32S3 TOUCH TT21100触摸屏无法工作 (AUD-4426)

### ISSUE THREAD

**Issue by IotSHCJC** [espressif/esp-adf#960]
我用了example的display的music_player的例子，烧录完成之后,触摸屏无法工作
发现一直报错i2c: i2c_master_read(1255): i2c data read length error
通过对比该例子下面的tt21100的驱动和[最新的tt21100驱动](https://components.espressif.com/components/espressif/esp_lcd_touch_tt21100)
需要修改tt2100的驱动,第一次读取的数据长度大于0才能继续读取
`   static uint16_t data_len;
    static uint8_t data[256];
    esp_err_t ret_val = ESP_OK;

    /* Get report data length */
    ret_val |= tt21100_read((uint8_t *)&data_len, sizeof(data_len));
    ESP_LOGD(TAG, "Data len : %u", data_len);

    /* Read report data if length */
    if (data_len > 0 && data_len < sizeof(data)) {`

**Comment by jason-mao** [comment]
@IotSHCJC 谢谢，已在 2859ec2693be3ceae80f2c209394c83b4d532617 修复
