### ISSUE TITLE
Resample - sample rate is out of range (AUD-4437)

### ISSUE THREAD

**Issue by ribeirojaque** [espressif/esp-adf#964]
The bug is in source rate and destiny rate. I have a signal that is an array, but when I put other values in these variables the code "works" (I don't know that the resample is right, but the code doesn't present bugs).

For example, if I put:
src_rate = 44100 and dest_rate = 48000. 

don't know what happened.

the code
![code](https://user-images.githubusercontent.com/29240997/223754044-08fea1b8-642d-4acf-a6ea-65e1dbdb08bb.png)

the variables
![variables](https://user-images.githubusercontent.com/29240997/223754115-79f4aa30-f0c7-40d4-882a-f45130f6fa0f.png)

the erro
![erro](https://user-images.githubusercontent.com/29240997/223754146-736880a2-6b65-488a-afa4-26a25357fb72.png)

**Comment by jason-mao** [comment]
@ribeirojaque I think there is confusing error information. The resample support rate is 8000Hz,11025Hz,16000Hz, 22050Hz,24000Hz,32000Hz,44100Hz,48000Hz and 96000Hz. We will change the docs more clearly. Thanks.
