### ISSUE TITLE
Wider band codecs (SPEEX, opus, ...) support in VoIP example (AUD-4443)

### ISSUE THREAD

**Issue by gabriel-f-o** [espressif/esp-adf#965]
Hello to all,

I would like to ask (if it does not exist already) a wider band codec support in the VoIP example.

In the menuconfig, the only choices are G711 PCMU and G711PCMA. It works fine but the audio quality could be better, specially when using a speaker.

It would be very helpful to have the OPUS codec in the dropdown list.

I have tried to change the av_stream_config.acodec_type = AV_ACODEC_OPUS, but this only results in more issues.

If this feature already exists, do you have a tutorial on how to implement it ? I could not find something similar.

Thank you for your time,

**Comment by ahhfzhang** [comment]
Hi @gabriel-f-o 

We will support OPUS in the next release version.

**Comment by gabriel-f-o** [comment]
Hello @ahhfzhang 

Thank you for your response.

That is good news ! Do you have an approximate release date for the next version?

**Comment by chris-genone** [comment]
Also super curious about this! Also if there is a workaround in the meantime. @ahhfzhang

**Comment by chris-genone** [comment]
Any updates on this?

**Comment by chris-genone** [comment]
I noticed this commit on esp-adf-libs. Looks like a good sign

https://github.com/espressif/esp-adf-libs/commit/b0e908b0252d94025fb82274e5d23910bedf0d7c
