### ISSUE TITLE
Severe issue in the AAC+ decoder introduced above esp-adf-v1.0 version (AUD-4444)

### ISSUE THREAD

**Issue by grantrismo** [espressif/esp-adf#966]
There is a sever issue in the AAC+ decoder all versions above esp-adf-v1.0 version. Too much bass boost overdrive resulting into audio glitches and distortions.

To reproduce listen to http://lounge-aacp.rautemusik.fm

use adf-idf-v1.0 no overdrive 
use adf-idf latest release produces audio glitches and distortions.

simply compare the decoder output, they are different. I think there is a bug in the optimized assembly code introduced after v.1.0

**Comment by houhaiyan** [comment]
@grantrismo please make `pluse_enable` in `aac_decoder_cfg_t` equal to true, the audio quality will improve
