### ISSUE TITLE
如果将ADF作为IDF的一个组件 (AUD-4476)

### ISSUE THREAD

**Issue by Spring641** [espressif/esp-adf#969]
我想知道怎么才能把adf作为idf的一个组件，这样方便我将adf移植到micropython的最新版本

**Comment by jason-mao** [comment]
可以将ADF 的components 目录以 EXTRA_COMPONENT_DIRS 的形式配置你的IDF 工程下

**Comment by Ming-XF** [comment]
大哥，你的micropython可以使用ADF吗？怎么做的？我搞了一星期了，都没搞定，真诚的求助～
