### ISSUE TITLE
VOIP example DMTF events are missing (AUD-4490)

### ISSUE THREAD

**Issue by sylvainleris** [espressif/esp-adf#973]
## Environment

- Audio development kit: ESP32-LyraT
- Audio kit version: v4.3
- Module or chip used: ESP32-S2-WROVER
- IDF version: v4.4.4
- ADF version: v2.5
- Build system: idf.py

## Problem Description

In v2.5 release and master, DTMF events are missing. Do you plan to support them again ?

**Comment by ahhfzhang** [comment]
@sylvainleris 

Thanks for your report, we will add this feature.
