### ISSUE TITLE
中文文本转语音 (TTS) 中mac 怎么烧入esp_tts_voice_data_xiaole.dat？ (AUD-4499)

### ISSUE THREAD

**Issue by yinwhm12** [espressif/esp-adf#976]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/25929417/228898739-43ca6810-6112-447b-a9fb-2228d40c40f7.png">

你好！
本人学者，看文档到这里懵了。希望能得到指点，谢谢！
环境基本上搭建完成，也跑出了一些demo，但是关于 中文文本转语音 (TTS)，是在搞不懂，不耻下问。
跑起来，是这样的：
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/25929417/228899699-214ec0ab-1647-41ec-b75d-41852e20235a.png">
flash是这样的：
<img width="742" alt="image" src="https://user-images.githubusercontent.com/25929417/228901150-a9d87656-3d24-4acc-99b6-847479fb8884.png">
可以看出确实少了   

0x100000 | components/esp-sr/esp-tts/esp_tts_chinese/esp_tts_voice_data_xiaole.dat
-- | --

关于 esp_tts_voice_data_xiaole.dat 文件，确实可以从官网找到，但是，我怎么编译到开发盘呢？
本人初学者，请谅解。
环境：
macOS Monterey(12.4)
esp-idf release4.4
esp-adf master

🙏🙏🙏

**Comment by yinwhm12** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/25929417/228904813-447e7961-3274-49b1-aaca-999a3772a672.png">

**Comment by feizi** [comment]
@yinwhm12 
你可以用相同方法, 换一个voice烧写 `esp_tts_chinese/esp_tts_voice_data_xiaoxin_small.dat`,看看是否可以正常运行

**Comment by yinwhm12** [comment]
@feizi 非常感谢你的回答！我的疑问是，怎么将.dat文件烧写进去，因为readme介绍，是写入固定的地址。仅仅提了一下，也没给出步骤，麻烦指点我一下呀，非常感谢！

**Comment by feizi** [comment]
你可以参考这个脚本 https://github.com/espressif/esp-skainet/blob/master/examples/chinese_tts/flash_voicedata.sh
