### ISSUE TITLE
ESP-ADF Compatible with IDF 5.0.1?  (AUD-4509)

### ISSUE THREAD

**Issue by DerPicknicker** [espressif/esp-adf#978]
Hello, 

I use the ESP32-S3 for an Project with the newest IDF Version. But as you mentioned in the Github the Espressif Audio Development Framework is currently not usable with the newest IDF Version. Do you already have an Timeframe when the Audio Development Frame is compatible with the ESP IDF V5? 

Or is it already compatible but the Github Documentation is not updated yet? 

Best regards

**Comment by DerPicknicker** [comment]
@jason-mao … Push … any updates regarding compatibility ?

**Comment by Builty** [comment]
I also want to know this. I am doing a project with 5.0.1 and need the audio support. I don't want to roll back to old IDF if the new ADF is close. 

Please give a release timeline.

**Comment by DerPicknicker** [comment]
Yeah I feel you. Here was mentioned in a couple of weeks. But this was in feb 2023... But still no updates on the ADF side..... 

https://github.com/espressif/esp-adf/issues/952#issuecomment-1445903783

**Comment by jason-mao** [comment]
Hi guys, Thank you for your patience. We are still working on this, the latest status is that the modificaitons final review is on going, it will take one or two weeks.

**Comment by DerPicknicker** [comment]
Thank you for your updates.

**Comment by zafeer-birde** [comment]
@jason-mao Is this activity now complete ? What timelines are we looking at now ?

**Comment by MoritzSchwoerer** [comment]
Any news about this topic?

**Comment by DerPicknicker** [comment]
@jason-mao … any updates..?

**Comment by jason-mao** [comment]
Hi guys, thank you for being so patient. This feature support on c1e884871872bc748a0248746fcba4980170356f
