### ISSUE TITLE
Issue in playing 128kbps mp3 https streams (AUD-602)

### ISSUE THREAD

**Issue by jerinjacobk** [espressif/esp-adf#98]
Looks like lot packets drops while playing 128kps streams, Not sure it is in network layer or decoder level?

It can be reproduced with pipeline_http_mp3 example application by changing mp3 streaming URL.

Working 64kbps URL:
http://198.178.123.2:9484

Nonworking (audio drops frequently) URL:
http://167.114.64.181:8554/stream
details: MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, Stereo

Any thoughts?

**Comment by jerinjacobk** [comment]
Some more observation. 

Actually, 128kbps example file provided in esp-adf resources website does not look like 128kbps file.

$ wget https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.mp3 
$ file ff-16b-2c-44100hz.mp3 
ff-16b-2c-44100hz.mp3: Audio file with ID3 version 2.4.0, contains:MPEG ADTS, layer III, v1,  64 kbps, 44.1 kHz, Stereo

Is 128kbps known to work? or some configuration missing?

**Comment by krzychb** [comment]
Hi @jerinjacobk,

Thank you for reporting the issue with packet drops. We will look into it.

In the meantime I would like verify the bitrate of the example file:

> Actually, 128kbps example file provided in esp-adf resources website does not look like 128kbps file.

I have the same result of `$ file ff-16b-2c-44100hz.mp3` command as you provided . 

However, when using `spek` program the result is as follows:

![image](https://user-images.githubusercontent.com/12953787/50653346-79358e80-0f89-11e9-94b0-201983e6454a.png)
Both information above the spectrogram and a [cut off frequency](https://www.reddit.com/r/hiphopheads/comments/2t88ne/a_quick_guide_to_checking_the_real_bitrate_of/) indicate 128 kbps.

I see the same 128 kbps when checking properties of this example:

![image](https://user-images.githubusercontent.com/12953787/50654019-bf8bed00-0f8b-11e9-96e3-3b207288e0f1.png)

I guess the `file` command provides incorrect bitrate.

**Comment by jerinjacobk** [comment]
Capturing the stream from http://167.114.64.181:8554/stream and store in MMC card avoids audio drop issue so it is not mp3 decoder problem, some issue in the input side either in WIFI or http?

**Comment by Gatlarf** [comment]
I had similar issues with my lyrat board.  Increasing the ring-buffer made thing slightly better but I still experienced some drops. Have you tried playing with the RX & TX buffers for the wifi-connection as described [here](https://docs.espressif.com/projects/esp-adf/en/latest/design-guide/design-considerations.html)?  I'm not in the possibility to test it myself right now because a power-surge fried my development board last weekend...

**Comment by jason-mao** [comment]
Suggest check with #297.
