### ISSUE TITLE
ESP-ADF版本分支确认 (AUD-4518)

### ISSUE THREAD

**Issue by MrYanLK** [espressif/esp-adf#982]
麻烦帮忙确认个事情，ADF的版本，是使用release的版本，还是可以使用master的版本，直接使用git下载下来的代码，用master分支有没有什么问题？ 现在ADF release的版本是2.4，用2.4的tag对应的代码，我一样的项目代码，IRAM就剩很少，但用master分支的代码，IRAM就会多一点

**Comment by MrYanLK** [comment]
请问谁能帮忙确认下？

**Comment by jason-mao** [comment]
@MrYanLK 您跟着master 分支走。

**Comment by MrYanLK** [comment]
好的，感谢
