### ISSUE TITLE
Integrate the ADF components as parts of MicroPython: ERROR! (AUD-4526)

### ISSUE THREAD

**Issue by Ming-XF** [espressif/esp-adf#986]
I try to Integrate the ADF components as parts of MicroPython with micropython_adf's README.
我尝试跟着README在micropython集成ADF
but I got this error
但我得到了这个错误

liyongheng@liyonghengdeMacBook-Pro esp32 % make deploy -j8 BOARD=GENERIC_SPIRAM BAUD=921600 PORT=/dev/cu.usbserial-1130
idf.py -D MICROPY_BOARD=GENERIC_SPIRAM -D MICROPY_BOARD_DIR=/Users/liyongheng/esp/micro/esp-adf/micropython_adf/micropython/ports/esp32/boards/GENERIC_SPIRAM -B build-GENERIC_SPIRAM  -p /dev/cu.usbserial-1130 -b 921600 flash
Executing action: flash
Running cmake in directory /Users/liyongheng/esp/micro/esp-adf/micropython_adf/micropython/ports/esp32/build-GENERIC_SPIRAM
Executing "cmake -G 'Unix Makefiles' -DPYTHON_DEPS_CHECKED=1 -DPYTHON=/Users/liyongheng/.espressif/python_env/idf5.1_py3.8_env/bin/python -DESP_PLATFORM=1 -DMICROPY_BOARD=GENERIC_SPIRAM -DMICROPY_BOARD_DIR=/Users/liyongheng/esp/micro/esp-adf/micropython_adf/micropython/ports/esp32/boards/GENERIC_SPIRAM -DCCACHE_ENABLE=0 /Users/liyongheng/esp/micro/esp-adf/micropython_adf/micropython/ports/esp32"...
-- IDF_TARGET not set, using default target: esp32
-- Found Git: /usr/bin/git (found version "2.32.0 (Apple Git-132)") 
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /Users/liyongheng/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Users/liyongheng/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Users/liyongheng/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
Processing 1 dependencies:
[1/1] idf (5.1.0)
CMake Error at /Users/liyongheng/esp/micro/esp-idf/tools/cmake/build.cmake:265 (message):
  Failed to resolve component 'esp_adc_cal'.
Call Stack (most recent call first):
  /Users/liyongheng/esp/micro/esp-idf/tools/cmake/build.cmake:301 (__build_resolve_and_add_req)
  /Users/liyongheng/esp/micro/esp-idf/tools/cmake/build.cmake:594 (__build_expand_requirements)
  /Users/liyongheng/esp/micro/esp-idf/tools/cmake/project.cmake:464 (idf_build_process)
  CMakeLists.txt:58 (project)

Is there anyone who can help me?
有谁可以帮我一下吗？

**Comment by jason-mao** [comment]
ADF has been fixed and updated mciropython version on 8f96346eb1a2dbdafee30f8a8a642f8e89655f8f
