### ISSUE TITLE
examples/asr里的语音识别关键词可以修改吗？

### ISSUE THREAD

**Issue by bigiot** [espressif/esp-adf#99]
本地语音识别的关键词，可以通过修改代码改变吗？如果能，在哪里修改？谢谢！

**Comment by bigiot** [comment]
是的，可以自定义关键词吗？

**Comment by jason-mao** [comment]
@bigiot 支持的，目前有需要的话只能先联系我们的商务。后续我们会开放服务器接口，让用户自己来定义。

**Comment by bigiot** [comment]
好的，先了解一下，心里有个数。
