### ISSUE TITLE
build error (AUD-4591)

### ISSUE THREAD

**Issue by brilliantWorks** [espressif/esp-adf#995]
hi there~

Audio development kit: Custom board
Module or chip used: ESP32
ADF version : v2.5

examples/get-started/play_mp3_control 
When I build, I get an error like below.
I just selected "customboard" in menuconfig.
If you do not select "customboard" in menuconfig, no issues will occur.

----------------------------------------------------------------------------------------------------------

Audio HAL
CONFIG_AUDIO_BOARD_CUSTOM=y
CONFIG_ESP_LYRAT_V4_3_BOARD is not set
CONFIG_ESP_LYRAT_V4_2_BOARD is not set
CONFIG_ESP_LYRATD_MSC_V2_1_BOARD is not set
CONFIG_ESP_LYRATD_MSC_V2_2_BOARD is not set
CONFIG_ESP_LYRAT_MINI_V1_1_BOARD is not set
CONFIG_ESP32_KORVO_DU1906_BOARD is not set
CONFIG_ESP32_S2_KALUGA_1_V1_2_BOARD is not set
CONFIG_ESP32_S3_KORVO2_V3_BOARD is not set
CONFIG_ESP32_S3_KORVO2L_V1_BOARD is not set
CONFIG_ESP32_S3_BOX_LITE_BOARD is not set
CONFIG_ESP32_S3_BOX_BOARD is not set
CONFIG_ESP32_C3_LYRA_V2_BOARD is not set
end of Audio HAL

My Audio Board

CONFIG_MY_BOARD_V1_0=y
end of My Audio Board

----------------------------------------------------------------------------------------------------------
.obj   -c /opt/Espressif/ESP32/esp-adf-v2.5/components/audio_hal/driver/es8388/es8388.c
/opt/Espressif/ESP32/esp-adf-v2.5/components/audio_hal/driver/es8388/es8388.c: In function 'es8388_init':
/opt/Espressif/ESP32/esp-adf-v2.5/components/audio_hal/driver/es8388/es8388.c:43:22: error: 'BOARD_PA_GAIN' undeclared (first use in this function)
     .board_pa_gain = BOARD_PA_GAIN,                         \
                      ^~~~~~~~~~~~~
/opt/Espressif/ESP32/esp-adf-v2.5/components/audio_hal/driver/es8388/es8388.c:340:41: note: in expansion of macro 'ES8388_DAC_VOL_CFG_DEFAULT'
     codec_dac_volume_config_t vol_cfg = ES8388_DAC_VOL_CFG_DEFAULT();
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/Espressif/ESP32/esp-adf-v2.5/components/audio_hal/driver/es8388/es8388.c:43:22: note: each undeclared identifier is reported only once for each function it appears in
     .board_pa_gain = BOARD_PA_GAIN,                         \
                      ^~~~~~~~~~~~~
/opt/Espressif/ESP32/esp-adf-v2.5/components/audio_hal/driver/es8388/es8388.c:340:41: note: in expansion of macro 'ES8388_DAC_VOL_CFG_DEFAULT'
     codec_dac_volume_config_t vol_cfg = ES8388_DAC_VOL_CFG_DEFAULT();
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
[1142/1228] Building C object esp-idf/audio_hal/CMakeFiles/__idf_audio_hal.dir/driver/es7210/es7210.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by texruska** [comment]
Your custom board is missing some definitions that seem to be required (for now). My minimal working example looks like this:

```
#ifndef _AUDIO_BOARD_DEFINITION_H_
#define _AUDIO_BOARD_DEFINITION_H_

extern audio_hal_func_t AUDIO_NEW_CODEC_DEFAULT_HANDLE;

#define AUDIO_CODEC_DEFAULT_CONFIG(){                   \
        .adc_input  = AUDIO_HAL_ADC_INPUT_LINE1,        \
        .dac_output = AUDIO_HAL_DAC_OUTPUT_ALL,         \
        .codec_mode = AUDIO_HAL_CODEC_MODE_BOTH,        \
        .i2s_iface = {                                  \
            .mode = AUDIO_HAL_MODE_SLAVE,               \
            .fmt = AUDIO_HAL_I2S_NORMAL,                \
            .samples = AUDIO_HAL_48K_SAMPLES,           \
            .bits = AUDIO_HAL_BIT_LENGTH_16BITS,        \
        },                                              \
};

#endif
```

**Comment by texruska** [comment]
This is related to https://github.com/espressif/esp-adf/pull/1008

For now you can solve this problem by having your `board_def.h` to contain this following definition:

```#ifndef _AUDIO_BOARD_DEFINITION_H_
#define _AUDIO_BOARD_DEFINITION_H_

#define BOARD_PA_GAIN 0

#endif
```
