### ISSUE TITLE
afe_perferred typo in esp_afe_config.h and algorithm_stream.c  (AUD-4603)

### ISSUE THREAD

**Issue by Gaai** [espressif/esp-adf#999]
Declared in esp_afe_config.h
```
typedef struct {
...<cut>
    int afe_perferred_core;
    int afe_perferred_priority;
...<cut>
} afe_config_t;
```

and used in algorithm_stream.c:
```
    afe_config.afe_perferred_core = 1;
    afe_config.afe_perferred_priority = 21;
```

Solution:
Replace "perferred" with "preferred"

If that's all the references to this variable I can do a pull request.

**Comment by Gaai** [comment]
Another mistake, this time in audio-element.c: line 1297
`The index of ringbuffer is gather than and equal to ringbuffer maximum (...)`
Not sure what that was meant to mean. Greater than and equal to ringbuffer maximum (...)? But that can't be right. Maybe: greater than or equal to ringbuffer maximum?

**Comment by jason-mao** [comment]
@Gaai Thank you for your report. We will fix that.

**Comment by feizi** [comment]
> Replace "perferred" with "preferred"

Thanks, I will fix it.

**Comment by jason-mao** [comment]
This topic will be fixed on ESP-SR repo.
